-- Run in a transaction after the migration; ALWAYS ROLLBACK. No durable fixtures.
create temp table hr_test_ids(kind text primary key,id uuid default gen_random_uuid());
insert into hr_test_ids(kind) values('admin'),('hr'),('manager'),('employee'),('other'),('client');
insert into auth.users(id,email) select id,'hr-test-'||id::text||'@example.invalid' from hr_test_ids;
insert into public.profiles(id,full_name,role,active) select id,'HR test '||kind,case when kind='admin' then 'administrador' when kind='client' then 'cliente' when kind='hr' then 'rrhh' else 'almacenero' end,true from hr_test_ids on conflict(id) do update set role=excluded.role,active=true;
create temp table hr_test_employees(kind text primary key,id uuid);
insert into public.hr_employees(full_name,profile_id) select 'HR test '||kind,id from hr_test_ids where kind in ('employee','other','manager');
insert into hr_test_employees select t.kind,e.id from public.hr_employees e join hr_test_ids t on t.id=e.profile_id;
-- El N+1 del empleado es la ficha del responsable: de ahí salen sus derechos de equipo.
update public.hr_employees set manager_id=(select id from hr_test_employees where kind='manager') where id=(select id from hr_test_employees where kind='employee');
grant select on hr_test_ids,hr_test_employees to authenticated;
create function pg_temp.assert_true(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'ASSERT FAILED: %',label;end if;end$$;
create function pg_temp.expect_error(q text) returns void language plpgsql as $$begin begin execute q;exception when others then return;end;raise exception 'EXPECTED ERROR: %',q;end$$;
select set_config('request.jwt.claim.sub',(select id::text from hr_test_ids where kind='admin'),true);
set local role authenticated;
insert into public.hr_employee_private(employee_id,salary,annual_leave_days) select id,1500,15 from hr_test_employees;
insert into public.hr_work_patterns(employee_id,effective_from,weekdays,daily_hours) select id,'2026-01-01','{1,2,3,4,5}',8 from hr_test_employees;
insert into public.hr_holidays values('2027-01-01','HR test holiday');
insert into public.hr_leave_accounts(employee_id,year,entitlement,reason) select id,y,15,'Test allocation' from hr_test_employees cross join generate_series(2026,2027) y;
insert into storage.objects(bucket_id,name) select 'hr-documents',id::text||'/test.pdf' from hr_test_employees where kind='employee';
insert into public.hr_documents(employee_id,kind,title,effective_date,storage_path,filename) select id,'contract','Test contract','2026-01-01',id::text||'/test.pdf','test.pdf' from hr_test_employees where kind='employee';
select pg_temp.assert_true((select count(*)=3 from public.hr_employee_private where employee_id in(select id from hr_test_employees)),'admin sees private salaries');
select set_config('request.jwt.claim.sub',(select id::text from hr_test_ids where kind='employee'),true);
select pg_temp.assert_true((select count(*)=1 from public.hr_employee_private where employee_id in(select id from hr_test_employees)),'employee only own salary');
select pg_temp.assert_true((select count(*)=1 from public.hr_documents where employee_id in(select id from hr_test_employees)),'employee reads own document');
select pg_temp.expect_error('select public.gama_assign_access_profile(auth.uid(),''rrhh'')');
select pg_temp.expect_error(format('insert into public.hr_absences(employee_id,start_date,end_date,status) values(%L,''2026-12-30'',''2027-01-04'',''aprobada'')',(select id from hr_test_employees where kind='employee')));
insert into public.hr_absences(employee_id,start_date,end_date,start_fraction) select id,'2026-12-30','2027-01-04',0.5 from hr_test_employees where kind='employee';
select pg_temp.expect_error(format('insert into public.hr_absences(employee_id,start_date,end_date) values(%L,''2026-12-30'',''2026-12-31'')',(select id from hr_test_employees where kind='other')));
select pg_temp.expect_error('select private.hr_leave_available(gen_random_uuid(),2026,current_date)');
-- Real clock RPC, unique open session, no self approval through direct API.
select public.gama_hr_clock('in');
select pg_temp.expect_error('select public.gama_hr_clock(''in'')');
select public.gama_hr_clock('break');
select public.gama_hr_clock('resume');
select public.gama_hr_clock('out');
update public.hr_attendance set status='approved' where employee_id=(select id from hr_test_employees where kind='employee');
select pg_temp.assert_true((select bool_and(status='pending') from public.hr_attendance where employee_id=(select id from hr_test_employees where kind='employee')),'employee cannot approve clock');
select set_config('request.jwt.claim.sub',(select id::text from hr_test_ids where kind='manager'),true);
select pg_temp.assert_true((select count(*)=1 from public.hr_employee_private where employee_id in(select id from hr_test_employees)),'manager cannot see team salaries');
select pg_temp.assert_true((select count(*)=0 from public.hr_documents where employee_id in(select id from hr_test_employees)),'manager cannot read team documents');
select pg_temp.expect_error(format('insert into public.hr_shifts(employee_id,starts_at,ends_at) values(%L,''2026-12-01 09:00Z'',''2026-12-01 17:00Z'')',(select id from hr_test_employees where kind='other')));
update public.hr_absences set status='aprobada' where employee_id=(select id from hr_test_employees where kind='employee');
select pg_temp.assert_true((select bool_and(status='aprobada') from public.hr_absences where employee_id=(select id from hr_test_employees where kind='employee')),'manager approves team');
update public.hr_attendance set status='approved' where employee_id=(select id from hr_test_employees where kind='employee');
select pg_temp.assert_true((select bool_and(status='approved' and reviewed_by=auth.uid()) from public.hr_attendance where employee_id=(select id from hr_test_employees where kind='employee')),'manager approves hours server stamp');
select pg_temp.expect_error(format('insert into public.hr_absences(employee_id,start_date,end_date,status) values(%L,''2026-12-01'',''2026-12-02'',''aprobada'')',(select id from hr_test_employees where kind='manager')));
insert into public.hr_shifts(employee_id,starts_at,ends_at) select id,'2026-12-01 08:00Z','2026-12-01 16:00Z' from hr_test_employees where kind='employee';
select pg_temp.expect_error(format('insert into public.hr_shifts(employee_id,starts_at,ends_at) values(%L,''2026-12-01 09:00Z'',''2026-12-01 17:00Z'')',(select id from hr_test_employees where kind='employee')));
select set_config('request.jwt.claim.sub',(select id::text from hr_test_ids where kind='hr'),true);
select pg_temp.assert_true((select count(*)=3 from public.hr_employee_private where employee_id in(select id from hr_test_employees)),'HR sees private salaries');
select pg_temp.expect_error(format('insert into public.hr_payroll(employee_id,period,source_ref,gross,net,employer_cost) values(%L,''2026-09-01'',''hr-test-bad'',1000,800,500)',(select id from hr_test_employees where kind='employee')));
insert into public.hr_payroll(employee_id,period,source_ref,gross,net,employer_cost) select id,'2026-09-01','hr-test-'||id,1000,800,1200 from hr_test_employees where kind='employee';
select pg_temp.expect_error(format('insert into public.hr_payroll(employee_id,period,source_ref,gross,net,employer_cost) values(%L,''2026-09-01'',''hr-test-duplicate'',1000,800,1200)',(select id from hr_test_employees where kind='employee')));
update public.hr_payroll set status='validated' where employee_id=(select id from hr_test_employees where kind='employee');
select pg_temp.expect_error(format('update public.hr_payroll set gross=500 where employee_id=%L',(select id from hr_test_employees where kind='employee')));
insert into public.hr_payroll_payments(payroll_id,paid_on,amount,reference) select id,'2026-09-30',300,'hr-test-payment-'||id from public.hr_payroll where employee_id=(select id from hr_test_employees where kind='employee');
select pg_temp.expect_error(format('insert into public.hr_payroll_payments(payroll_id,paid_on,amount,reference) values(%L,''2026-09-30'',501,''hr-test-excess'')',(select id from public.hr_payroll where employee_id=(select id from hr_test_employees where kind='employee'))));
select pg_temp.expect_error(format('update public.hr_payroll set status=''cancelled'' where employee_id=%L',(select id from hr_test_employees where kind='employee')));
select pg_temp.assert_true((select count(*)>0 from public.hr_audit where actor_id in(select id from hr_test_ids)),'audit writes retained');
select set_config('request.jwt.claim.sub',(select id::text from hr_test_ids where kind='client'),true);
select pg_temp.assert_true((select count(*)=0 from public.hr_payroll),'client no payroll');
select pg_temp.assert_true((select count(*)=0 from public.hr_documents),'client no documents');
select pg_temp.assert_true((select count(*)=0 from public.hr_audit),'client no audit');
select pg_temp.expect_error('select public.gama_hr_clock(''in'')');
reset role;
-- Internal computation, only as database owner (not exposed to callers).
select pg_temp.assert_true(private.hr_leave_days((select id from hr_test_employees where kind='employee'),'2026-12-30','2026-12-31',0.5,1)=1.5,'half day in first year');
select pg_temp.assert_true(private.hr_leave_days((select id from hr_test_employees where kind='employee'),'2027-01-01','2027-01-04',1,1)=1,'holiday excluded next year');
select set_config('request.jwt.claim.sub',(select id::text from hr_test_ids where kind='employee'),true);
set local role authenticated;
insert into public.hr_absences(employee_id,start_date,end_date) select id,'2026-10-01','2026-10-01' from hr_test_employees where kind='employee';
update public.hr_absences set status='cancelada',decision_reason='Confidential cancellation' where employee_id=(select id from hr_test_employees where kind='employee') and status='pendiente';
select pg_temp.assert_true((select bool_and(decision_reason is null) from public.hr_absences where employee_id in(select id from hr_test_employees)),'free text absent from team calendar');
select pg_temp.assert_true((select count(*)=1 from public.hr_absence_decisions where employee_id=(select id from hr_test_employees where kind='employee')),'owner reads cancellation reason');
select set_config('request.jwt.claim.sub',(select id::text from hr_test_ids where kind='other'),true);
select pg_temp.assert_true((select count(*)=0 from public.hr_absence_decisions),'colleague cannot read decision reasons');
reset role;
select 'HR P1 database checks passed' as result;
