-- Transactional test fixtures: no business rows persist after ROLLBACK.
begin;
create temp table pm_test_users(kind text primary key,id uuid default gen_random_uuid());
insert into pm_test_users(kind) values('admin'),('manager'),('member'),('outsider'),('viewer'),('client'),('inactive');
insert into auth.users(id,email) select id,'pm-qa-'||id||'@example.invalid' from pm_test_users;
insert into public.profiles(id,full_name,role,active) select id,'PM QA '||kind,case when kind in ('admin','inactive') then 'administrador' when kind='client' then 'cliente' else 'comercial' end,kind<>'inactive' from pm_test_users on conflict(id) do update set role=excluded.role,active=excluded.active;
create temp table pm_test_ids(k text primary key,id uuid,v integer);
grant select,insert,update on pm_test_ids to authenticated;grant select on pm_test_users to authenticated;
create function pg_temp.pm_assert(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'PM ASSERT FAILED: %',label;end if;end$$;
create function pg_temp.pm_fail(q text,needle text default null) returns void language plpgsql as $$begin begin execute q;exception when others then if needle is not null and position(needle in sqlerrm)=0 then raise exception 'WRONG FAILURE: % expected %',sqlerrm,needle;end if;return;end;raise exception 'EXPECTED FAILURE: %',q;end$$;
create function pg_temp.pm_call(a text,d jsonb default '{}') returns jsonb language sql as $$ select public.gama_projects_action(a,d||jsonb_build_object('request_key',gen_random_uuid())) $$;
create function pg_temp.pm_id(k text) returns uuid language sql as $$select id from pm_test_ids where pm_test_ids.k=pm_id.k$$;
create function pg_temp.pm_user(k text) returns uuid language sql as $$select id from pm_test_users where kind=k$$;
select set_config('request.jwt.claim.sub',pg_temp.pm_user('manager')::text,true);
set local role authenticated;
insert into pm_test_ids(k,id) select 'project',(pg_temp.pm_call('create_project',jsonb_build_object('name','Project QA <script>','manager_id',pg_temp.pm_user('manager'),'start_date',current_date,'due_date',current_date+90,'budget',1000,'currency','USD'))->>'project_id')::uuid;
select pg_temp.pm_assert((select reference ~ '^PRJ-[0-9]{6,}$' and mode='simple' from public.pm_projects where id=pg_temp.pm_id('project')),'reference and default mode');
select pg_temp.pm_fail($q$insert into public.pm_projects(name,manager_id,start_date,due_date,created_by) values('Forbidden',pg_temp.pm_user('manager'),current_date,current_date,pg_temp.pm_user('manager'))$q$,'permission denied');
select pg_temp.pm_call('member',jsonb_build_object('project_id',pg_temp.pm_id('project'),'version',1,'profile_id',pg_temp.pm_user('member'),'role','member'));
select pg_temp.pm_call('member',jsonb_build_object('project_id',pg_temp.pm_id('project'),'version',2,'profile_id',pg_temp.pm_user('viewer'),'role','viewer'));
insert into pm_test_ids(k,id) select 'phase',(pg_temp.pm_call('save_item',jsonb_build_object('project_id',pg_temp.pm_id('project'),'kind','phase','title','Phase 1','owner_id',pg_temp.pm_user('manager')))->>'id')::uuid;
insert into pm_test_ids(k,id) select 'task1',(pg_temp.pm_call('save_item',jsonb_build_object('project_id',pg_temp.pm_id('project'),'kind','task','title','Task 1','phase_id',pg_temp.pm_id('phase'),'owner_id',pg_temp.pm_user('member'),'due_date',current_date-1,'data',jsonb_build_object('estimated_hours',10,'checklist',jsonb_build_array(jsonb_build_object('text','Review','done',false)))))->>'id')::uuid;
insert into pm_test_ids(k,id) select 'task2',(pg_temp.pm_call('save_item',jsonb_build_object('project_id',pg_temp.pm_id('project'),'kind','task','title','Task 2','phase_id',pg_temp.pm_id('phase'),'owner_id',pg_temp.pm_user('manager'),'data',jsonb_build_object('dependencies',jsonb_build_array(pg_temp.pm_id('task1')))))->>'id')::uuid;
select pg_temp.pm_fail($q$select pg_temp.pm_call('save_item',jsonb_build_object('project_id',pg_temp.pm_id('project'),'id',pg_temp.pm_id('task2'),'version',1,'status','in_progress'))$q$,'PM_DEPENDENCY_PENDING');
select pg_temp.pm_fail($q$select pg_temp.pm_call('save_item',jsonb_build_object('project_id',pg_temp.pm_id('project'),'id',pg_temp.pm_id('task1'),'version',1,'data',jsonb_build_object('dependencies',jsonb_build_array(pg_temp.pm_id('task2')))))$q$,'PM_DEPENDENCY_CYCLE');
select pg_temp.pm_fail($q$select pg_temp.pm_call('save_item',jsonb_build_object('project_id',pg_temp.pm_id('project'),'id',pg_temp.pm_id('task1'),'version',1,'status','done'))$q$,'PM_CHECKLIST_PENDING');
select pg_temp.pm_call('save_item',jsonb_build_object('project_id',pg_temp.pm_id('project'),'id',pg_temp.pm_id('task1'),'version',1,'status','done','data',jsonb_build_object('checklist',jsonb_build_array(jsonb_build_object('text','Review','done',true)))));
select pg_temp.pm_assert((select progress=50 from public.pm_items where id=pg_temp.pm_id('phase')),'phase rollup 50');
select pg_temp.pm_assert((public.gama_projects_action('detail',jsonb_build_object('project_id',pg_temp.pm_id('project')))->'metrics'->>'progress')::numeric=50,'project rollup 50');
select pg_temp.pm_fail($q$select pg_temp.pm_call('save_item',jsonb_build_object('project_id',pg_temp.pm_id('project'),'id',pg_temp.pm_id('task1'),'version',1,'title','Stale'))$q$,'PM_CONFLICT');
select pg_temp.pm_call('save_item',jsonb_build_object('project_id',pg_temp.pm_id('project'),'id',pg_temp.pm_id('task2'),'version',1,'status','done'));
select pg_temp.pm_fail($q$select pg_temp.pm_call('save_item',jsonb_build_object('project_id',pg_temp.pm_id('project'),'kind','risk','title','Bad risk','data',jsonb_build_object('probability',6,'impact',5)))$q$,'PM_INVALID_RISK');
insert into pm_test_ids(k,id) select 'risk',(pg_temp.pm_call('save_item',jsonb_build_object('project_id',pg_temp.pm_id('project'),'kind','risk','title','Critical risk','data',jsonb_build_object('probability',5,'impact',5)))->>'id')::uuid;
select pg_temp.pm_assert((public.gama_projects_action('detail',jsonb_build_object('project_id',pg_temp.pm_id('project')))->'metrics'->>'health')::int=2,'critical risk health');
select pg_temp.pm_assert(jsonb_array_length(public.gama_projects_action('alerts'))>0,'actionable alerts');
select pg_temp.pm_fail($q$select pg_temp.pm_call('close',jsonb_build_object('project_id',pg_temp.pm_id('project'),'version',3))$q$,'PM_CLOSE_BLOCKED');
select pg_temp.pm_call('save_item',jsonb_build_object('project_id',pg_temp.pm_id('project'),'id',pg_temp.pm_id('risk'),'version',1,'status','closed'));
select pg_temp.pm_call('update_project',jsonb_build_object('project_id',pg_temp.pm_id('project'),'version',3,'mode','advanced','status','active'));
insert into pm_test_ids(k,id) select 'wp',(pg_temp.pm_call('save_item',jsonb_build_object('project_id',pg_temp.pm_id('project'),'kind','work_package','title','Package','phase_id',pg_temp.pm_id('phase')))->>'id')::uuid;
insert into pm_test_ids(k,id) select 'deliverable',(pg_temp.pm_call('save_item',jsonb_build_object('project_id',pg_temp.pm_id('project'),'kind','deliverable','title','Result','phase_id',pg_temp.pm_id('phase'),'work_package_id',pg_temp.pm_id('wp'),'approver_id',pg_temp.pm_user('member')))->>'id')::uuid;
select pg_temp.pm_fail($q$select pg_temp.pm_call('save_item',jsonb_build_object('project_id',pg_temp.pm_id('project'),'id',pg_temp.pm_id('deliverable'),'version',1,'status','approved'))$q$,'PM_USE_WORKFLOW');
select pg_temp.pm_fail($q$select pg_temp.pm_call('submit',jsonb_build_object('project_id',pg_temp.pm_id('project'),'id',pg_temp.pm_id('deliverable'),'version',1))$q$,'PM_DOCUMENT_REQUIRED');
select pg_temp.pm_call('file',jsonb_build_object('project_id',pg_temp.pm_id('project'),'id',pg_temp.pm_id('deliverable'),'filename','Acceptance','url','https://example.invalid/acceptance.pdf'));
select pg_temp.pm_call('submit',jsonb_build_object('project_id',pg_temp.pm_id('project'),'id',pg_temp.pm_id('deliverable'),'version',1));
select pg_temp.pm_fail($q$select pg_temp.pm_call('approve',jsonb_build_object('project_id',pg_temp.pm_id('project'),'id',pg_temp.pm_id('deliverable'),'version',2))$q$,'PM_APPROVER_REQUIRED');
select set_config('request.jwt.claim.sub',pg_temp.pm_user('member')::text,true);
select pg_temp.pm_call('approve',jsonb_build_object('project_id',pg_temp.pm_id('project'),'id',pg_temp.pm_id('deliverable'),'version',2));
select pg_temp.pm_fail($q$select pg_temp.pm_call('update_project',jsonb_build_object('project_id',pg_temp.pm_id('project'),'version',4,'budget',9999))$q$,'PM_FORBIDDEN');
select set_config('request.jwt.claim.sub',pg_temp.pm_user('manager')::text,true);
insert into pm_test_ids(k,id) select 'change',(pg_temp.pm_call('save_item',jsonb_build_object('project_id',pg_temp.pm_id('project'),'kind','change','title','Approved scope','approver_id',pg_temp.pm_user('member'),'data',jsonb_build_object('budget_impact',200,'schedule_impact',3,'scope_impact','Added scope')))->>'id')::uuid;
select pg_temp.pm_call('submit',jsonb_build_object('project_id',pg_temp.pm_id('project'),'id',pg_temp.pm_id('change'),'version',1));
select pg_temp.pm_fail($q$select pg_temp.pm_call('save_item',jsonb_build_object('project_id',pg_temp.pm_id('project'),'id',pg_temp.pm_id('change'),'version',2,'data',jsonb_build_object('budget_impact',9999)))$q$,'PM_ITEM_LOCKED');
select set_config('request.jwt.claim.sub',pg_temp.pm_user('member')::text,true);
select pg_temp.pm_call('approve',jsonb_build_object('project_id',pg_temp.pm_id('project'),'id',pg_temp.pm_id('change'),'version',2));
select set_config('request.jwt.claim.sub',pg_temp.pm_user('manager')::text,true);
insert into pm_test_ids(k,id) values('apply-key',gen_random_uuid());
select public.gama_projects_action('apply_change',jsonb_build_object('project_id',pg_temp.pm_id('project'),'id',pg_temp.pm_id('change'),'version',3,'request_key',pg_temp.pm_id('apply-key')));
select public.gama_projects_action('apply_change',jsonb_build_object('project_id',pg_temp.pm_id('project'),'id',pg_temp.pm_id('change'),'version',3,'request_key',pg_temp.pm_id('apply-key')));
select pg_temp.pm_assert((select budget=1200 and due_date=current_date+93 from public.pm_projects where id=pg_temp.pm_id('project')),'change applied once');
select pg_temp.pm_fail($q$select pg_temp.pm_call('apply_change',jsonb_build_object('project_id',pg_temp.pm_id('project'),'id',pg_temp.pm_id('change'),'version',4))$q$,'PM_INVALID_TRANSITION');
select pg_temp.pm_call('close_change',jsonb_build_object('project_id',pg_temp.pm_id('project'),'id',pg_temp.pm_id('change'),'version',4));
insert into pm_test_ids(k,id) select 'lesson',(pg_temp.pm_call('save_item',jsonb_build_object('project_id',pg_temp.pm_id('project'),'kind','lesson','title','Reusable lesson','description','Keep it simple','data',jsonb_build_object('recommendation','Reuse modules')))->>'id')::uuid;
-- Purchase creation, commitment and receipt valuation use the existing records.
reset role;
insert into pm_test_ids(k,id) values('supplier',gen_random_uuid()),('product',gen_random_uuid());
insert into public.suppliers(id,name) values(pg_temp.pm_id('supplier'),'PM QA supplier');
insert into public.products(id,name,reference) values(pg_temp.pm_id('product'),'PM QA product '||pg_temp.pm_id('product'),'PMQA-'||pg_temp.pm_id('product'));
set local role authenticated;
insert into pm_test_ids(k,id) select 'purchase',(pg_temp.pm_call('create_purchase',jsonb_build_object('project_id',pg_temp.pm_id('project'),'id',pg_temp.pm_id('phase'),'supplier_id',pg_temp.pm_id('supplier'),'currency','USD','exchange_rate',1,'lines',jsonb_build_array(jsonb_build_object('product_id',pg_temp.pm_id('product'),'quantity',10,'unit_cost',20))))->>'purchase_id')::uuid;
select pg_temp.pm_assert((public.gama_projects_action('detail',jsonb_build_object('project_id',pg_temp.pm_id('project')))->'metrics'->>'committed')::numeric=200,'purchase commitment');
select pg_temp.pm_fail($q$select pg_temp.pm_call('link',jsonb_build_object('project_id',pg_temp.pm_id('project'),'kind','purchase','target_id',pg_temp.pm_id('purchase'),'currency','USD','exchange_rate',1))$q$,'duplicate key');
reset role;
update public.purchase_order_lines set received_quantity=3 where purchase_order_id=pg_temp.pm_id('purchase');
update public.purchase_orders set status='partial' where id=pg_temp.pm_id('purchase');
set local role authenticated;
select pg_temp.pm_assert((public.gama_projects_action('detail',jsonb_build_object('project_id',pg_temp.pm_id('project')))->'metrics'->>'actual')::numeric=60,'received actual cost');
select pg_temp.pm_assert((public.gama_projects_action('detail',jsonb_build_object('project_id',pg_temp.pm_id('project')))->'metrics'->>'committed')::numeric=140,'commitment excludes receipts');
select pg_temp.pm_assert((public.gama_projects_action('detail',jsonb_build_object('project_id',pg_temp.pm_id('project')))->'metrics'->>'remaining')::numeric=1140,'remaining budget minus actual');
select pg_temp.pm_fail($q$select pg_temp.pm_call('close',jsonb_build_object('project_id',pg_temp.pm_id('project'),'version',5,'went_well','a','went_wrong','b','do_differently','c','costs_confirmed',true))$q$,'PM_CLOSE_BLOCKED');
reset role;
update public.purchase_order_lines set received_quantity=10 where purchase_order_id=pg_temp.pm_id('purchase');
update public.purchase_orders set status='received' where id=pg_temp.pm_id('purchase');
set local role authenticated;

-- Row and RPC boundaries: an unrelated colleague, client and inactive admin cannot see the project.
select set_config('request.jwt.claim.sub',pg_temp.pm_user('outsider')::text,true);
select pg_temp.pm_assert((select count(*)=0 from public.pm_projects where id=pg_temp.pm_id('project')),'outsider RLS');
select pg_temp.pm_fail($q$select public.gama_projects_action('detail',jsonb_build_object('project_id',pg_temp.pm_id('project')))$q$,'PM_FORBIDDEN');
select set_config('request.jwt.claim.sub',pg_temp.pm_user('viewer')::text,true);
select pg_temp.pm_assert((select count(*)=1 from public.pm_projects where id=pg_temp.pm_id('project')),'viewer read');
select pg_temp.pm_fail($q$select pg_temp.pm_call('comment',jsonb_build_object('project_id',pg_temp.pm_id('project'),'body','No write'))$q$,'PM_FORBIDDEN');
select set_config('request.jwt.claim.sub',pg_temp.pm_user('client')::text,true);
select pg_temp.pm_assert((select count(*)=0 from public.pm_projects),'client RLS');
select pg_temp.pm_fail($q$select public.gama_projects_action('lookups')$q$,'PM_FORBIDDEN');
select set_config('request.jwt.claim.sub',pg_temp.pm_user('inactive')::text,true);
select pg_temp.pm_fail($q$select public.gama_projects_action('portfolio')$q$,'PM_FORBIDDEN');
select set_config('request.jwt.claim.sub',pg_temp.pm_user('manager')::text,true);
select pg_temp.pm_call('close',jsonb_build_object('project_id',pg_temp.pm_id('project'),'version',5,'went_well','Team','went_wrong','Delays','do_differently','Plan','costs_confirmed',true));
select pg_temp.pm_fail($q$select pg_temp.pm_call('comment',jsonb_build_object('project_id',pg_temp.pm_id('project'),'body','Closed edit'))$q$,'PM_PROJECT_CLOSED');
select pg_temp.pm_fail($q$select pg_temp.pm_call('reopen',jsonb_build_object('project_id',pg_temp.pm_id('project'),'version',6,'reason','Try'))$q$,'PM_FORBIDDEN');
reset role;
select pg_temp.pm_fail($q$update public.purchase_order_lines set unit_cost=999 where purchase_order_id=pg_temp.pm_id('purchase')$q$,'PM_PROJECT_CLOSED');
set local role authenticated;
select set_config('request.jwt.claim.sub',pg_temp.pm_user('admin')::text,true);
select pg_temp.pm_call('reopen',jsonb_build_object('project_id',pg_temp.pm_id('project'),'version',6,'reason','Authorised restart'));
select pg_temp.pm_call('lesson_knowledge',jsonb_build_object('project_id',pg_temp.pm_id('project'),'id',pg_temp.pm_id('lesson')));
select pg_temp.pm_call('lesson_knowledge',jsonb_build_object('project_id',pg_temp.pm_id('project'),'id',pg_temp.pm_id('lesson')));
select pg_temp.pm_assert((select count(*)=1 from public.pm_links where project_id=pg_temp.pm_id('project') and kind='knowledge'),'lesson conversion idempotent');
select pg_temp.pm_call('save_template',jsonb_build_object('project_id',pg_temp.pm_id('project'),'name','QA custom template'));
reset role;
select pg_temp.pm_assert((select count(*)>10 from public.gama_audit where table_name like 'pm_%' and (row_id=pg_temp.pm_id('project')::text or new_data->>'project_id'=pg_temp.pm_id('project')::text)),'existing GAMA audit populated');
select pg_temp.pm_assert((select count(*)=1 from public.gama_audit where table_name='pm_projects' and row_id=pg_temp.pm_id('project')::text and old_data->>'status'='completed' and new_data->>'status'='active'),'reopen audited');
rollback;
select 'Project management: workflow, idempotency, approval, audit and access tests passed' result;
