/* Durable work is executed on the server, including when this screen is closed. */
(function(){'use strict';
const U=window.ArcUI,E=U.esc,F=U.field;
const t=(es,fr,en)=>({es,fr,en}[window.GamaI18n?.language||'es']||es);
const rpc=(action,data={})=>window.ArcData.rpc('gama_automation',{p_action:action,p_data:data});
let epoch=0;const hosts=new Set();
const states={queued:['En espera','En attente','Queued'],running:['En curso','En cours','Running'],retry:['Reintento previsto','Nouvelle tentative prévue','Retry scheduled'],blocked:['Revisión necesaria','À vérifier','Review needed'],succeeded:['Finalizado','Terminé','Completed'],cancelled:['Cancelado','Annulé','Cancelled'],dead:['Error definitivo','Échec','Failed']};
const label=s=>states[s]?t(...states[s]):s;
const date=s=>s?new Date(s).toLocaleString(window.GamaI18n?.locale||'es-EC'):'—';
function fail(host,e){if(host?.isConnected)U.render(host,`<p role="alert">${E(window.ArcErrors?.message(e)||e.message)}</p><button class="arcButton secondary" data-auto-refresh>${t('Reintentar','Réessayer','Retry')}</button>`);host?.querySelector('[data-auto-refresh]')?.addEventListener('click',()=>mount(host))}
async function mount(host,options={}){
 if(!host)return;hosts.add(host);const session=epoch,revision=(Number(host.dataset.autoRevision)||0)+1;host.dataset.autoRevision=String(revision);
 U.render(host,`<p role="status">${t('Cargando tratamientos…','Chargement des traitements…','Loading jobs…')}</p>`);
 try{const d=await rpc('snapshot',options);if(session!==epoch||!host.isConnected||Number(host.dataset.autoRevision)!==revision)return;
 const action=(name,attrs='')=>`<button type="button" class="arcButton secondary" ${attrs}>${E(name)}</button>`;
 U.render(host,`<div class="arcPanel card"><h3>${t('Automatizaciones y excepciones','Automatisations et exceptions','Automation and exceptions')}</h3><p>${t('Los tratamientos continúan sin abrir la aplicación. Los controles físicos, aprobaciones y documentos fiscales conservan sus validaciones.','Les traitements continuent lorsque l’application est fermée. Les contrôles physiques, approbations et documents fiscaux conservent leurs validations.','Jobs continue when the application is closed. Physical checks, approvals and fiscal documents retain their validations.')}</p><p>${E(date(d.as_of))} · ${E(d.pending)} ${t('pendientes','en attente','pending')}</p><div class="arcFormGrid"><label>${t('Estado','État','Status')}<select data-auto-state><option value="">${t('Todos','Tous','All')}</option>${Object.keys(states).map(s=>`<option value="${s}" ${options.state===s?'selected':''}>${E(label(s))}</option>`).join('')}</select></label>${action(t('Actualizar','Actualiser','Refresh'),'data-auto-refresh')}</div></div>
 <div class="arcPanel card"><h3>${t('Excepciones a tratar','Exceptions à traiter','Exceptions to handle')}</h3>${U.table({columns:[{key:'reference',label:t('Dossier','Dossier','Case')},{key:'reason',label:t('Motivo','Motif','Reason')},{key:'assigned_name',label:t('Responsable','Responsable','Owner')},{key:'next_action',label:t('Próxima acción','Prochaine action','Next action')},{key:'due_at',label:t('Plazo','Échéance','Due'),html:x=>E(date(x.due_at))},{label:'',actions:true,html:x=>action(t('Organizar seguimiento','Organiser le suivi','Assign follow-up'),`data-auto-assign="${E(x.key)}"`)+(x.source_id?action(t('Abrir dossier','Ouvrir le dossier','Open case'),`data-auto-source="${E(x.key)}"`):'')}],items:d.exceptions})}</div>
 ${d.admin?`<div class="arcPanel card"><h3>${t('Reglas y delegaciones','Règles et délégations','Rules and delegations')}</h3>${action(t('Ver rendimiento observado','Voir les performances mesurées','View observed performance'),'data-auto-performance')}${action(t('Configurar envíos','Configurer les envois','Configure messages'),'data-auto-messages')}${action(t('Configurar trayectos por carretera','Configurer les trajets routiers','Configure road distances'),'data-auto-roads')}${U.table({columns:[{key:'title',label:t('Regla','Règle','Rule')},{key:'enabled',label:t('Estado','État','Status'),html:r=>E(r.enabled?t('Activa','Active','Enabled'):t('Inactiva','Inactive','Disabled'))},{key:'version',label:t('Versión','Version','Version')},{key:'approved_until',label:t('Delegación hasta','Délégation jusqu’au','Delegation until'),html:r=>E(r.delegated?date(r.approved_until):'—')},{label:'',actions:true,html:r=>action(t('Configurar','Configurer','Configure'),`data-auto-rule="${E(r.kind)}"`)+(r.enabled?action(t('Ejecutar una vez','Exécuter une fois','Run once'),`data-auto-run="${E(r.kind)}"`):'')}],items:d.rules})}</div>`:''}
 <div class="arcPanel card"><h3>${t('Historial de tratamientos','Historique des traitements','Job history')}</h3>${U.table({columns:[{key:'title',label:t('Tratamiento','Traitement','Job')},{key:'state',label:t('Estado','État','Status'),html:j=>E(label(j.state))},{key:'updated_at',label:t('Actualizado','Actualisé','Updated'),html:j=>E(date(j.updated_at))},{key:'error_code',label:t('Motivo','Motif','Reason')},{key:'attempts',label:t('Intentos','Tentatives','Attempts')},{label:'',actions:true,html:j=>action(t('Historial','Historique','History'),`data-auto-history="${E(j.id)}"`)+(d.admin&&['blocked','dead','retry','queued'].includes(j.state)?action(t('Reintentar','Réessayer','Retry'),`data-auto-retry="${E(j.id)}"`)+action(t('Cancelar','Annuler','Cancel'),`data-auto-cancel="${E(j.id)}"`):'')}],items:d.jobs})}<div class="goTools">${action(t('Anterior','Précédent','Previous'),'data-auto-prev '+(d.offset?'':'disabled'))}<span>${E(d.offset+1)}–${E(d.offset+d.jobs.length)} / ${E(d.total)}</span>${action(t('Siguiente','Suivant','Next'),'data-auto-next '+(d.offset+d.jobs.length<d.total?'':'disabled'))}</div></div>`);
 host.querySelector('[data-auto-roads]')?.addEventListener('click',()=>window.CocoFlows.roads());
 host.querySelector('[data-auto-messages]')?.addEventListener('click',()=>window.CocoFlows.messages());
 host.querySelector('[data-auto-performance]')?.addEventListener('click',()=>window.ArchitectPerformance.open().catch(e=>window.gamaToast?.(window.ArcErrors.message(e))));
 host.querySelector('[data-auto-refresh]').onclick=()=>mount(host,options);
 host.querySelector('[data-auto-state]').onchange=e=>mount(host,{state:e.target.value,offset:0});
 host.querySelector('[data-auto-prev]').onclick=()=>mount(host,{...options,offset:Math.max(0,d.offset-50)});
 host.querySelector('[data-auto-next]').onclick=()=>mount(host,{...options,offset:d.offset+50});
 const bind=(selector,fn)=>host.querySelectorAll(selector).forEach(b=>b.onclick=async()=>{b.disabled=true;try{await fn(b);if(session===epoch)await mount(host,options)}catch(e){window.gamaToast?.(window.ArcErrors?.message(e)||e.message)}finally{b.disabled=false}});
 bind('[data-auto-run]',b=>rpc('run_once',{kind:b.dataset.autoRun,request_key:crypto.randomUUID()}));
 for(const a of ['retry','cancel'])bind(`[data-auto-${a}]`,b=>rpc(a,{id:b.dataset['auto'+a[0].toUpperCase()+a.slice(1)]}));
 host.querySelectorAll('[data-auto-rule]').forEach(b=>b.onclick=()=>configure(d.rules.find(r=>r.kind===b.dataset.autoRule),()=>mount(host,options)));
 host.querySelectorAll('[data-auto-assign]').forEach(b=>b.onclick=()=>assign(d.exceptions.find(x=>x.key===b.dataset.autoAssign),()=>mount(host,options)));
 host.querySelectorAll('[data-auto-source]').forEach(b=>b.onclick=()=>{const x=d.exceptions.find(x=>x.key===b.dataset.autoSource);x.source_type==='supplier_invoice'?window.CocoFlows.draftBills(x.source_id):window.GamaOperations?.dossier({target:x.source_type,target_id:x.source_id,reference:x.reference})});
 host.querySelectorAll('[data-auto-history]').forEach(b=>b.onclick=()=>{const j=d.jobs.find(j=>j.id===b.dataset.autoHistory);U.dialog({title:j.title,saveLabel:t('Cerrar','Fermer','Close'),body:U.table({columns:[{key:'attempt',label:t('Intento','Tentative','Attempt')},{key:'started_at',label:t('Inicio','Début','Started'),html:a=>E(date(a.started_at))},{key:'outcome',label:t('Resultado','Résultat','Outcome'),html:a=>E(label(a.outcome))},{key:'milliseconds',label:'ms'},{key:'error_code',label:t('Motivo','Motif','Reason')}],items:j.attempts_log}),onSave:async()=>{}})});
 }catch(e){if(session===epoch&&Number(host.dataset.autoRevision)===revision)fail(host,e)}
}
const fields={survey_feedback:[['survey_id','Cuestionario de satisfacción','Questionnaire de satisfaction','Satisfaction survey','text',''],['rating_question_id','Identificador de la pregunta de valoración (1–5)','Identifiant de la question de note (1–5)','Rating question ID (1–5)','text','']],replenishment:[['max_order_total','Importe máximo por compra','Montant maximal par achat','Maximum purchase amount','number',1000]],request_quote:[['max_quote_total','Importe máximo del presupuesto','Montant maximal du devis','Maximum quote amount','number',1000]],accepted_order:[['max_order_total','Importe máximo del pedido','Montant maximal de commande','Maximum order amount','number',1000]],crm_followup:[['followup_days','Próxima actividad en días','Prochaine activité dans N jours','Follow-up in days','number',3]],reminders:[['interval_days','Intervalo entre recordatorios','Intervalle entre rappels','Reminder interval in days','number',7]],survey_followup:[['survey_id','Cuestionario publicado','Questionnaire publié','Published survey','text','']],cycle_counts:[['warehouse_id','Almacén','Entrepôt','Warehouse','warehouse','']]};
async function configure(r,refresh){try{
 const extra=[];for(const [key,es,fr,en,type,fallback] of fields[r.kind]||[]){let options;if(type==='warehouse'){const w=await window.ArcData.all('warehouses',{select:'id,name',eq:{active:true},order:'name'});if(w.error)throw w.error;options=w.data.map(w=>({id:w.id,name:w.name}))}extra.push(F({key,label:t(es,fr,en),type:type==='warehouse'?'select':type,value:r.config[key]??fallback,options,step:'any',min:0}))}
 U.dialog({title:r.title,body:`<p>${t('Una nueva versión suspende los trabajos de la versión anterior. La ejecución delegada vuelve a comprobar tus derechos y caduca como máximo en 90 días.','Une nouvelle version suspend les traitements de la version précédente. La délégation vérifie à nouveau vos droits et expire au plus tard après 90 jours.','A new version suspends jobs using the previous version. Delegation rechecks your permissions and expires within 90 days.')}</p>${F({key:'enabled',label:t('Estado','État','Status'),type:'select',value:r.enabled?'true':'false',options:[{id:'false',name:t('Inactiva','Inactive','Disabled')},{id:'true',name:t('Activa','Active','Enabled')}]})}${F({key:'interval_minutes',label:t('Frecuencia (minutos)','Fréquence (minutes)','Interval (minutes)'),type:'number',value:r.config.interval_minutes||60,min:1,max:10080})}${r.delegated?F({key:'delegation_days',label:t('Delegación (días)','Délégation (jours)','Delegation (days)'),type:'number',value:90,min:1,max:90}):''}${extra.join('')}`,onSave:async el=>{const data=Object.fromEntries(new FormData(el.querySelector('form'))),config={...r.config,interval_minutes:Number(data.interval_minutes)};for(const [key,,,,type] of fields[r.kind]||[])config[key]=type==='number'?Number(data[key]):data[key];await rpc('rule_save',{kind:r.kind,expected_version:r.version,enabled:data.enabled==='true',delegation_days:Number(data.delegation_days||90),config});await refresh()}});
 }catch(e){window.gamaToast?.(window.ArcErrors?.message(e)||e.message)}}
function assign(x,refresh){U.dialog({title:t('Seguimiento del expediente','Suivi du dossier','Case follow-up'),body:`<p>${E(x.reference)} · ${E(x.reason)}</p>${F({key:'next_action',label:t('Próxima acción','Prochaine action','Next action'),value:x.next_action,required:true})}${F({key:'due_at',label:t('Plazo','Échéance','Due'),type:'datetime-local'})}`,onSave:async el=>{const f=Object.fromEntries(new FormData(el.querySelector('form')));await rpc('assign',{key:x.key,...f});await refresh()}})}
window.addEventListener('gama:auth-change',e=>{if(e.detail?.event==='TOKEN_REFRESHED')return;epoch++;for(const host of hosts){host.replaceChildren();hosts.delete(host)}});
window.CocoAutomation={mount};
})();
