/* Review prepared source documents and approve time before canonical posting. */
(function(){'use strict';const U=window.ArcUI,E=U.esc,F=U.field;let epoch=0;
const t=(es,fr,en)=>({fr,en}[window.GamaI18n?.locale?.slice(0,2)]||es);
const rpc=(name,action,data={})=>window.ArcData.rpc(name,{p_action:action,p_data:data});
const finance=(a,d)=>rpc('gama_flow_finance',a,d),data=el=>Object.fromEntries(new FormData(el.querySelector('form')));
const error=e=>window.gamaToast?.(window.ArcErrors.message(e));
const dlg=o=>{const d=U.dialog(o);d.dataset.flowTools='';d.dataset.giIgnore='';return d};
const now=()=>new Date().toISOString().slice(0,10);
async function draftBills(id){const token=epoch;try{const r=await finance('drafts');if(token!==epoch)return;
 if(id)return bill(id);const d=dlg({title:t('Recepciones y facturas por revisar','Réceptions et factures à vérifier','Receipts and bills to review'),saveLabel:t('Cerrar','Fermer','Close'),body:`<p>${t('Los borradores se preparan con las cantidades recibidas. Revisa el documento real del proveedor antes de contabilizar; el borrador no genera pago ni asiento.','Les brouillons reprennent les quantités reçues. Vérifiez le document réel du fournisseur avant de comptabiliser ; le brouillon ne crée aucun paiement ni écriture.','Drafts use received quantities. Review the actual supplier document before posting; drafts create no payment or journal entry.')}</p>${U.table({columns:[{key:'erp_reference',label:t('Referencia','Référence','Reference')},{key:'supplier_name',label:t('Proveedor','Fournisseur','Supplier')},{key:'number',label:t('Documento','Document','Document')},{key:'total',label:t('Total','Total','Total'),value:b=>window.ArcFormat.money(b.total,'USD')},{label:'',actions:true,html:b=>`<button type="button" class="arcButton secondary" data-flow-bill="${E(b.id)}">${t('Revisar','Vérifier','Review')}</button>`}],items:r.bills})}`,onSave:async()=>{}});
 d.querySelectorAll('[data-flow-bill]').forEach(b=>b.onclick=()=>{d.close();bill(b.dataset.flowBill)});
 }catch(e){if(token===epoch)error(e)}}
async function bill(id){const token=epoch;try{const r=await finance('context',{id});if(token!==epoch)return;const b=r.bill,lines=r.matching?.lines||[];
 const d=dlg({title:b.erp_reference||b.number,saveLabel:t('Guardar borrador','Enregistrer le brouillon','Save draft'),body:F({key:'number',label:t('Número real del proveedor','Numéro réel du fournisseur','Actual supplier number'),value:b.number,required:true,maxLength:100})+F({key:'issue_date',label:t('Fecha de emisión','Date d’émission','Issue date'),type:'date',value:b.issue_date,required:true})+F({key:'payment_terms_days',label:t('Plazo de pago (días)','Délai de paiement (jours)','Payment terms (days)'),type:'number',min:0,max:3650,value:b.payment_terms_days||0})+F({key:'subtotal',label:t('Base imponible','Base taxable','Taxable amount'),type:'number',min:0,step:.01,value:b.subtotal,required:true})+F({key:'tax',label:t('Impuesto del documento','Taxe du document','Document tax'),type:'number',min:0,step:.01,value:b.tax,required:true})+F({key:'notes',label:t('Comentario','Commentaire','Comment'),type:'textarea',value:b.notes})+`<p>${t('Guarda los campos revisados antes de validar.','Enregistrez les champs vérifiés avant de valider.','Save reviewed fields before posting.')}</p><button type="button" class="arcButton primary" data-flow-post>${t('Revisar líneas y contabilizar','Vérifier les lignes et comptabiliser','Review lines and post')}</button>`,onSave:async el=>{await finance('save',{id,expected_updated_at:b.updated_at,...data(el)});window.dispatchEvent(new Event('gama:process-change'));await bill(id)}});
 d.querySelector('[data-flow-post]').onclick=()=>{d.close();post(b,lines)};
 }catch(e){if(token===epoch)error(e)}}
function post(b,lines){const key=crypto.randomUUID();const d=dlg({title:t('Validar compra, recepción y factura','Valider achat, réception et facture','Approve purchase, receipt and bill'),saveLabel:t('Contabilizar','Comptabiliser','Post'),body:`<p>${E(b.number)} · ${E(window.ArcFormat.money(b.total,'USD'))}</p>${lines.map((l,i)=>`<fieldset data-match-line="${E(l.id)}"><legend>${E(l.name)}</legend><p>${t('Recibido / ya facturado','Reçu / déjà facturé','Received / already billed')}: ${E(l.received_quantity)} / ${E(l.already_matched)}</p>${F({key:'quantity-'+i,label:t('Cantidad facturada','Quantité facturée','Billed quantity'),type:'number',min:0,max:Math.max(0,l.received_quantity-l.already_matched),step:.001,value:Math.max(0,l.received_quantity-l.already_matched)})}${F({key:'cost-'+i,label:t('Coste unitario','Coût unitaire','Unit cost'),type:'number',min:0,step:.0001,value:l.unit_cost})}${F({key:'tax-'+i,label:t('IVA (%)','TVA (%)','Tax (%)'),type:'number',min:0,max:100,step:.01,value:l.tax_rate})}</fieldset>`).join('')}${F({key:'reason',label:t('Motivo de diferencias de precio / impuesto','Motif des écarts de prix / taxe','Reason for price / tax variance'),type:'textarea'})}${F({key:'reviewed',label:t('He verificado el documento del proveedor y sus importes','J’ai vérifié le document fournisseur et ses montants','I reviewed the supplier document and amounts'),type:'checkbox',required:true})}`,onSave:async el=>{const f=data(el),matched=lines.map((l,i)=>({purchase_line_id:l.id,quantity:Number(f['quantity-'+i]),unit_cost:Number(f['cost-'+i]),tax_rate:Number(f['tax-'+i])})).filter(l=>l.quantity>0);await finance('post',{id:b.id,request_key:key,expected_updated_at:b.updated_at,reviewed:el.querySelector('[name=reviewed]').checked,reason:f.reason,lines:matched});window.dispatchEvent(new Event('gama:process-change'));window.gamaToast?.(t('Factura contabilizada','Facture comptabilisée','Bill posted'))}});return d}
async function projectTime(projectId){const token=epoch,time=(a,d={})=>rpc('gama_project_time',a,{project_id:projectId,...d});try{const r=await time('list');if(token!==epoch)return;
 const d=dlg({title:t('Horas del proyecto','Heures du projet','Project hours'),saveLabel:t('Cerrar','Fermer','Close'),body:`<p>${t('Las horas aprobadas generan un único coste en la divisa del proyecto. No modifican la nómina.','Les heures approuvées créent un coût unique dans la devise du projet. Elles ne modifient pas la paie.','Approved hours create one cost in the project currency. They do not change payroll.')}</p><button type="button" class="arcButton primary" data-time-new>${t('Registrar horas','Saisir des heures','Record hours')}</button>${U.table({columns:[{key:'worked_on',label:t('Fecha','Date','Date')},{key:'employee_name',label:t('Empleado','Salarié','Employee')},{key:'hours',label:t('Horas','Heures','Hours')},{key:'description',label:t('Trabajo','Travail','Work')},{key:'status',label:t('Estado','État','Status')},{label:'',actions:true,html:e=>`${e.status==='submitted'?`<button type="button" data-time-approve="${E(e.id)}">${t('Aprobar','Approuver','Approve')}</button>`:''}${e.status!=='cancelled'?`<button type="button" data-time-cancel="${E(e.id)}">${t('Anular','Annuler','Cancel')}</button>`:''}`}],items:r.rows})}`,onSave:async()=>{}});
 const refresh=async()=>{d.close();window.dispatchEvent(new Event('gama:process-change'));await projectTime(projectId)};
 d.querySelector('[data-time-new]').onclick=()=>{const request=crypto.randomUUID();dlg({title:t('Registrar horas','Saisir des heures','Record hours'),body:F({key:'employee_id',label:t('Empleado','Salarié','Employee'),type:'select',options:r.employees,required:true})+F({key:'worked_on',label:t('Fecha','Date','Date'),type:'date',value:now(),max:now(),required:true})+F({key:'hours',label:t('Horas','Heures','Hours'),type:'number',min:.001,max:24,step:.001,required:true})+F({key:'description',label:t('Trabajo realizado','Travail effectué','Work completed'),required:true}),onSave:async el=>{await time('submit',{request_key:request,...data(el)});await refresh()}})};
 d.querySelectorAll('[data-time-approve]').forEach(b=>b.onclick=()=>dlg({title:t('Aprobar horas y coste','Approuver les heures et le coût','Approve hours and cost'),body:F({key:'hourly_cost',label:t('Coste por hora en la divisa del proyecto','Coût horaire dans la devise du projet','Hourly cost in project currency'),type:'number',min:.0001,step:.0001,required:true})+F({key:'evidence',label:t('Referencia de la aprobación','Référence de l’approbation','Approval reference'),required:true}),onSave:async el=>{await time('approve',{id:b.dataset.timeApprove,...data(el)});await refresh()}}));
 d.querySelectorAll('[data-time-cancel]').forEach(b=>b.onclick=()=>dlg({title:t('Anular horas','Annuler les heures','Cancel hours'),body:F({key:'reason',label:t('Motivo','Motif','Reason'),required:true}),onSave:async el=>{await time('cancel',{id:b.dataset.timeCancel,...data(el)});await refresh()}}));
 }catch(e){if(token===epoch)error(e)}}
window.addEventListener('gama:auth-change',e=>{if(e.detail?.event==='TOKEN_REFRESHED')return;epoch++;document.querySelectorAll('[data-flow-tools]').forEach(d=>d.close())});
async function importSupplierXml(){const token=epoch;try{const purchases=await window.ArcData.all('purchase_orders',{select:'id,order_number,status',order:'order_number'});if(purchases.error)throw purchases.error;if(token!==epoch)return;
 dlg({title:t('Importar XML del proveedor','Importer le XML fournisseur','Import supplier XML'),body:`<p>${t('Se busca un proveedor existente por RUC. Se conserva el XML original y se prepara un borrador. Revisa la firma, autorización SRI, impuestos y recepción antes de contabilizar.','Le fournisseur existant est recherché par RUC. Le XML original est conservé et un brouillon est préparé. Vérifiez la signature, l’autorisation SRI, les taxes et la réception avant de comptabiliser.','The existing supplier is matched by RUC. The original XML is kept and a draft prepared. Review signature, SRI authorization, taxes and receipts before posting.')}</p>${F({key:'purchase_order_id',label:t('Pedido de compra','Commande fournisseur','Purchase order'),type:'select',options:purchases.data.filter(p=>p.status!=='cancelled').map(p=>({id:p.id,name:p.order_number}))})}<label class="arcField"><span>XML (2 MB)</span><input type="file" name="xmlFile" accept=".xml,text/xml,application/xml" required></label>`,onSave:async el=>{const file=el.querySelector('[name=xmlFile]').files[0];if(!file||file.size>2097152)throw Error('INVALID_XML');const xml=await file.text();if(token!==epoch)throw Error('ROLE_NOT_ALLOWED');const r=await window.ArcData.rpc('gama_supplier_xml',{p_data:{xml,filename:file.name,purchase_order_id:data(el).purchase_order_id||null}});window.dispatchEvent(new Event('gama:process-change'));await bill(r.id)}});
 }catch(e){if(token===epoch)error(e)}}
async function messages(){const token=epoch;try{const r=await rpc('gama_messages','context');if(token!==epoch)return;const d=dlg({title:t('Envíos automáticos','Envois automatiques','Automatic messages'),saveLabel:t('Cerrar','Fermer','Close'),body:`<p>${t('Resend: conecta una clave API y un remitente de un dominio verificado. Los destinatarios deben haber activado sus preferencias; las reglas de automatización mantienen su delegación y permisos.','Resend : connectez une clé API et un expéditeur d’un domaine vérifié. Les destinataires doivent avoir activé leurs préférences ; les règles conservent leur délégation et leurs permissions.','Resend: connect an API key and a sender on a verified domain. Recipients must enable their preferences; rules retain their delegation and permissions.')}</p><p>${E(r.provider?.sender||t('Sin proveedor configurado','Fournisseur à configurer','Provider not configured'))} · ${r.provider?.enabled?t('Activo','Actif','Enabled'):t('Inactivo','Inactif','Disabled')}</p><button type="button" class="arcButton secondary" data-message-connect>${t('Configurar proveedor','Configurer le fournisseur','Configure provider')}</button>${U.table({columns:[{key:'created_at',label:t('Fecha','Date','Date')},{key:'subject',label:t('Mensaje','Message','Message')},{key:'state',label:t('Estado','État','Status')},{key:'attempts',label:t('Intentos','Tentatives','Attempts')},{key:'error_code',label:t('Motivo','Motif','Reason')}],items:r.outbox})}`,onSave:async()=>{}});
 d.querySelector('[data-message-connect]').onclick=()=>dlg({title:t('Conectar Resend','Connecter Resend','Connect Resend'),body:F({key:'sender',label:t('Correo del remitente verificado','E-mail de l’expéditeur vérifié','Verified sender email'),type:'email',required:true,value:r.provider?.sender})+F({key:'api_key',label:'Resend API key',type:'password',required:true,attrs:'autocomplete="new-password"'})+F({key:'enabled',label:t('Activar envíos autorizados','Activer les envois autorisés','Enable authorized sends'),type:'checkbox'}),onSave:async el=>{const f=data(el);await rpc('gama_messages','configure',{...f,enabled:el.querySelector('[name=enabled]').checked});el.querySelector('[name=api_key]').value='';d.close();await messages()}});
 }catch(e){if(token===epoch)error(e)}}
async function roads(){const token=epoch;try{const r=await rpc('gama_tms_roads','context');if(token!==epoch)return;const d=dlg({title:t('Trayectos por carretera','Trajets routiers','Road distances'),body:`<p>OpenRouteService · ${t('La clave queda en el servidor. La matriz mejora las distancias y rellena los horarios de ruta; verifica las restricciones del vehículo antes de salir.','La clé reste sur le serveur. La matrice améliore les distances et remplit les horaires ; vérifiez les restrictions du véhicule avant de partir.','The key stays on the server. The matrix improves distances and fills schedule legs; check vehicle restrictions before departure.')}</p>${F({key:'api_key',label:t('Clave API','Clé API','API key'),type:'password',required:true})}${F({key:'profile',label:t('Perfil','Profil','Profile'),type:'select',value:r.provider?.profile||'driving-car',options:[{id:'driving-car',name:t('Carretera estándar','Route standard','Standard road')},{id:'driving-hgv',name:t('Camión','Poids lourd','Truck')}]})}<label><input name="enabled" type="checkbox" ${r.provider?.enabled?'checked':''}> ${t('Activar cálculo por carretera','Activer le calcul routier','Enable road calculation')}</label><button type="button" class="arcButton secondary" data-road-disable>${t('Suspender proveedor','Suspendre le fournisseur','Disable provider')}</button>${U.table({columns:[{key:'day',label:t('Día','Jour','Day')},{key:'state',label:t('Estado','État','Status')},{key:'error_code',label:t('Motivo','Motif','Reason')}],items:r.requests||[]})}`,onSave:async el=>{const v=data(el);await rpc('gama_tms_roads','configure',{api_key:v.api_key,profile:v.profile,enabled:!!el.querySelector('[name=enabled]').checked});el.querySelector('[name=api_key]').value='';}});d.querySelector('[data-road-disable]').onclick=async()=>{try{await rpc('gama_tms_roads','disable');d.close()}catch(e){error(e)}};}catch(e){error(e)}}
window.CocoFlows={roads,draftBills,projectTime,importSupplierXml,messages};
})();
