(function(){'use strict';const U=window.ArcUI,E=U.esc,$=id=>document.getElementById(id),t=(es,fr,en)=>({es,fr,en}[window.GamaI18n?.language||'es']||es);let offset=0,request=0;
function admin(){return ['admin','administrador'].includes(JSON.parse(localStorage.getItem('gama_session_v1')||'{}').role)}
async function mount(){if(!admin()||!$('audit'))return;let host=$('erpAudit');if(!host){host=document.createElement('div');host.id='erpAudit';host.className='arcPanel';$('audit').prepend(host)}host.dataset.giIgnore='';
 U.render(host,`<h3>${t('Historial de todos los módulos','Historique de tous les modules','History across modules')}</h3><div class="arcFormGrid"><label>${t('Tabla','Table','Table')}<input id="eaTable" placeholder="products / sales_orders / …"></label><label>${t('Referencia interna','Identifiant interne','Record ID')}<input id="eaRecord"></label><label>${t('Usuario (ID)','Utilisateur (ID)','User (ID)')}<input id="eaActor"></label><label>${t('Desde','Depuis','From')}<input id="eaDate" type="date"></label></div><div class="arcToolbar"><button class="arcButton secondary" id="eaFilter">${t('Filtrar','Filtrer','Filter')}</button><button class="arcButton secondary" id="eaExport">${t('Exportar selección','Exporter la sélection','Export selection')}</button></div><p id="eaStatus" role="status"></p><div id="eaRows"></div><div class="arcToolbar"><button class="arcButton secondary" id="eaPrev">←</button><button class="arcButton secondary" id="eaNext">→</button></div>`);
 $('eaFilter').onclick=()=>{offset=0;load()};$('eaPrev').onclick=()=>{offset=Math.max(0,offset-50);load()};$('eaNext').onclick=()=>{offset+=50;load()};$('eaExport').onclick=()=>load(true);offset=0;await load();}
function filters(){const eq={};for(const [id,key] of [['eaTable','table_name'],['eaRecord','record_id'],['eaActor','actor_id']])if($(id).value.trim())eq[key]=$(id).value.trim();const options={eq,order:'id',ascending:false};if($('eaDate').value)options.gte={created_at:$('eaDate').value+'T00:00:00Z'};return options}
async function load(exporting=false){const token=++request;try{const r=exporting?await window.ArcData.all('erp_audit_events',filters()):await window.GamaCloud.list('erp_audit_events',{...filters(),range:[offset,offset+49],count:'exact'});if(r.error)throw r.error;if(token!==request||!admin())return;
 if(exporting){await window.ArchitectAccessControls.requireAction('audit','export');const blob=new Blob([JSON.stringify(r.data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='architect-audit.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);return}
 U.render($('eaRows'),U.table({columns:[{key:'created_at',label:'Date',value:r=>new Date(r.created_at).toLocaleString()},{key:'table_name',label:'Table'},{key:'operation',label:'Action'},{key:'actor_id',label:t('Usuario','Utilisateur','User')},{key:'record_id',label:'ID'},{label:'',actions:true,html:r=>source(r)?`<button type=button class="arcButton secondary" data-audit-source="${E(r.id)}">${t('Abrir origen','Ouvrir la source','Open source')}</button>`:''},{label:t('Cambios','Modifications','Changes'),html:r=>{const keys=new Set([...Object.keys(r.before_data||{}),...Object.keys(r.after_data||{})]);return '<details><summary>'+t('Antes / después','Avant / après','Before / after')+'</summary>'+[...keys].filter(k=>JSON.stringify(r.before_data?.[k])!==JSON.stringify(r.after_data?.[k])).map(k=>'<p><b>'+E(k)+'</b><br>'+E(JSON.stringify(r.before_data?.[k]??null))+' → '+E(JSON.stringify(r.after_data?.[k]??null))+'</p>').join('')+'</details>'}}],items:r.data||[]}));$('eaRows').querySelectorAll('[data-audit-source]').forEach(b=>b.onclick=()=>{const item=r.data.find(row=>String(row.id)===b.dataset.auditSource);const dest=source(item);if(dest)Promise.resolve(dest.open()).catch(e=>window.gamaToast?.(window.ArcErrors.message(e)))});$('eaPrev').disabled=offset===0;$('eaNext').disabled=offset+50>=r.count;$('eaStatus').textContent=String(r.count||0)+' '+t('eventos','événements','events');
 }catch(e){if(token===request&&$('eaStatus'))$('eaStatus').textContent=window.ArcErrors.message(e)}}

function source(row){const d=row.after_data||row.before_data||{},id=d.id||row.record_id;const map={
 products:['products',()=>window.ArchitectProductsControls.open(id)],product_units:['products',()=>window.ArchitectProductsControls.open(d.product_id)],
 customers:['clients',()=>window.ArchitectPartners.open('customer',id)],customer_addresses:['clients',()=>window.ArchitectPartners.open('customer',d.customer_id)],suppliers:['suppliers',()=>window.ArchitectPartners.open('supplier',id)],supplier_product_offers:['suppliers',()=>window.ArchitectSourcing.open(d.supplier_id)],
 invoices:['quotes',()=>window.GamaQuotes.view(id)],invoice_lines:['quotes',()=>window.GamaQuotes.view(d.invoice_id)],sales_orders:['sales-orders',()=>window.GamaSales.openOrder(id)],sales_order_lines:['sales-orders',()=>window.GamaSales.openOrder(d.order_id)],purchase_orders:['gamaPurchasesV14',()=>window.gamaOpenPurchaseDossier(id)],purchase_order_lines:['gamaPurchasesV14',()=>window.gamaOpenPurchaseDossier(d.purchase_order_id)],
 external_invoices:['payments',()=>window.GamaPayments.open({invoiceId:id})],external_invoice_payments:['payments',()=>window.GamaPayments.open({invoiceId:d.invoice_id})],return_orders:['returns',()=>window.GamaReturns.openReturn(id)],service_tickets:['sav',()=>window.GamaService.openTicket(id)],
 pm_projects:['projects',()=>window.GamaProjects.open({projectId:id})],pm_items:['projects',()=>window.GamaProjects.open({projectId:d.project_id,itemId:id})],erp_policies:['settings',()=>window.ArchitectControls.policies()],role_module_access:['access-settings',()=>window.ArcRouter.open('access-settings')],erp_action_permissions:['access-settings',()=>window.ArchitectAccessControls.permissions()]
};const hit=map[row.table_name];return hit&&window.gamaAccessAllowed?.(hit[0])?{module:hit[0],open:hit[1]}:null}
window.addEventListener('arc:route-change',e=>{if(e.detail.id==='audit')mount()});window.addEventListener('gama:auth-change',()=>{request++;$('erpAudit')?.remove()});
})();
