/* GAMA · Pedidos de venta, expediciones y facturas emitidas en otro software.
   Every mutation is one checked database transaction. No fiscal emission here. */
(function(){
'use strict';
if(window.GamaSales)return;
const $=id=>document.getElementById(id), C=()=>window.GamaCloud;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v||0).toLocaleString('es-EC',{style:'currency',currency:'USD'});
const num=v=>Number(v||0).toLocaleString('es-EC',{maximumFractionDigits:3});
const day=()=>{const d=new Date();return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const label=s=>({draft:'Borrador',confirmed:'Confirmado',cancelled:'Cancelado',unverified:'Por verificar',authorized:'Autorizada (declarado)',rejected:'Rechazada',pending:'Pendiente',partial:'Pago parcial',paid:'Pagada',overdue:'Vencida'}[s]||s);
const role=()=>{try{return JSON.parse(localStorage.getItem('gama_session_v1')||'{}').role}catch(_){return ''}};
const sell=()=>['admin','administrador','commercial','comercial'].includes(role());
const warehouse=()=>['admin','administrador','magasinier','almacenero'].includes(role());
const allowed=()=>['admin','administrador','commercial','comercial','magasinier','almacenero'].includes(role())&&(!window.gamaAccessAllowed||window.gamaAccessAllowed('sales-orders'));
let tab='orders',page=0,search='',detail=null,version=0,busy=false;
const SIZE=20,PCOLS='id,name,reference,sale_price,sale_price_b,tax_rate,active';
function error(e){
 const s=String(e?.message||e||'');
 const messages={AUTH_REQUIRED:'Vuelve a iniciar sesión.',ROLE_NOT_ALLOWED:'Tu perfil no puede realizar esta operación.',ORDER_NOT_FOUND:'Pedido no encontrado.',ORDER_CANCELLED:'El pedido está cancelado.',CONFIRM_ORDER_FIRST:'Confirma el pedido antes de continuar.',CUSTOMER_REQUIRED:'Selecciona un cliente activo.',PRODUCT_NOT_FOUND:'Uno de los productos ya no está disponible.',INVALID_SOURCE:'El documento de origen no está disponible.',INVALID_LINES:'Revisa las líneas del documento.',INVALID_QUANTITY:'Introduce una cantidad positiva con hasta tres decimales.',INSUFFICIENT_RESERVED:'La reserva ha cambiado. Actualiza el pedido y revisa las cantidades.',INSUFFICIENT_STOCK:'No hay existencias suficientes.',EXCEEDS_ORDERED:'La cantidad supera lo pendiente de expedición.',EXCEEDS_UNBILLED:'La cantidad ya está vinculada a otra factura.',ADDRESS_REQUIRED:'El pedido necesita una dirección de entrega.',CUSTOMER_MISMATCH:'La identificación del receptor no coincide con el cliente del pedido.',AMOUNT_MISMATCH:'Los importes de la factura no coinciden con las líneas seleccionadas. Revisa cantidades, precios e impuestos.',ORDER_HAS_DOCUMENTS:'No se puede cancelar un pedido con expediciones o facturas vigentes.',INVOICE_CLOSED:'Este registro está cerrado. Conserva el historial y registra el documento correcto.',INVOICE_NOT_FOUND:'Factura no encontrada.',DELIVERY_REQUIRED:'Selecciona al menos una expedición.',DELIVERY_ORDER_MISMATCH:'La expedición no pertenece a este pedido.',INVALID_PAYMENT_AMOUNT:'Introduce un importe positivo con dos decimales como máximo.',INVALID_PAYMENT_METHOD:'Selecciona un medio de pago.',PAYMENT_EXCEEDS_BALANCE:'El cobro supera el saldo pendiente de la factura.',PAYMENT_NOT_FOUND:'Cobro no encontrado.',REASON_REQUIRED:'Escribe el motivo del cambio.',TOO_MANY_FILES:'Se admiten hasta cuatro archivos por factura.',INVALID_FILE_SIZE:'Cada archivo debe tener contenido y ocupar como máximo 5 MB.',MIXED_PRODUCT_TAX:'El mismo producto tiene distintos impuestos en el origen. Corrige el presupuesto antes de convertirlo.'};
 for(const [key,text] of Object.entries(messages))if(s.includes(key))return text;
 if(e?.code==='23505'||/duplicate key/i.test(s))return 'Este documento ya está registrado. Actualiza la lista para consultarlo.';
 if(/sales_|external_|schema cache|does not exist/i.test(s))return 'No se pudo acceder a los datos de ventas. Reintenta; si continúa, contacta con el administrador.';
 return 'No se pudo completar la operación. '+s;
}
async function rows(table,options={}){const r=await C().list(table,options);if(r.error)throw r.error;return r.data||[]}
async function refs(table,select){let out=[];for(let offset=0;;offset+=500){const a=await rows(table,{select,order:'id',range:[offset,offset+499]});out.push(...a);if(a.length<500)return out}}
async function rpc(action,data){const c=await C().db();const r=await c.rpc('gama_sales_action',{p_action:action,p_data:data});if(r.error)throw r.error;window.dispatchEvent(new CustomEvent('gama:stock-cloud-change'));window.dispatchEvent(new CustomEvent('gama:sales-change'));return r.data}
async function commercialRpc(action,data){const c=await C().db();const r=await c.rpc('gama_commercial_action',{p_action:action,p_data:data});if(r.error)throw r.error;window.dispatchEvent(new CustomEvent('gama:sales-change'));return r.data}
function css(){if($('gsStyle'))return;const s=document.createElement('style');s.id='gsStyle';s.textContent=`
#sales-orders{display:none}#sales-orders.active{display:block}.gsCard{background:#fff;border:1px solid #d6e1e6;border-radius:14px;padding:18px;margin-bottom:16px}.gsTabs,.gsActions,.gsTools{display:flex;gap:9px;align-items:center;flex-wrap:wrap;margin:12px 0}.gsTabs button[aria-pressed=true]{background:#087c8b;color:#fff}.gsTools input{flex:1;min-width:160px;width:auto}.gsScroll{overflow:auto}.gsScroll table{width:100%;border-collapse:collapse;display:table!important;white-space:normal}.gsScroll th,.gsScroll td{padding:11px;text-align:left;border-bottom:1px solid #e5ecef;font-size:14px}.gsScroll th{background:#f4f8f9}.gsBadge{display:inline-block;padding:4px 8px;border-radius:8px;background:#e8f5f6;color:#075965;font-size:14px}.gsGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.gsGrid label,.gsField{display:block;font-size:14px}.gsGrid input,.gsGrid select{margin-top:5px}.gsHint{color:#516572;font-size:14px;line-height:1.5}.gsError{color:#a32e28;white-space:pre-wrap}.gsKpis{display:flex;gap:20px;flex-wrap:wrap;margin:15px 0}.gsKpis span{display:block;font-size:14px;color:#516572}.gsKpis b{font-size:20px}.gsNumber{width:110px!important;min-width:90px}.gsDialog{border:0;border-radius:16px;padding:22px;width:min(960px,calc(100vw - 24px));max-height:90vh;overflow:auto;color:#173246}.gsDialog::backdrop{background:#17324680}.gsDialog h2{margin-top:0}.gsDialog button,.gsCard button{min-height:42px}.gsDialog input,.gsDialog select,.gsDialog textarea{font-size:16px}.gsFiles{overflow-wrap:anywhere}.gsActions{justify-content:flex-end}.gsPager{display:flex;gap:12px;align-items:center;justify-content:space-between}.gsSummary{display:flex;justify-content:space-between;gap:15px;flex-wrap:wrap}.gsCard h3{margin-top:0}@media(max-width:600px){.gsGrid{grid-template-columns:1fr}.gsCard{padding:12px}.gsActions button{flex:1}.gsTabs button{flex:1 1 40%}.gsDialog{padding:15px}.gsScroll td,.gsScroll th{padding:9px}}`;
 s.textContent+='[data-invoice-delivery]{width:auto;margin-right:8px}';document.head.appendChild(s)}
function ensure(){css();let sec=$('sales-orders');if(!sec){sec=document.createElement('section');sec.id='sales-orders';(document.querySelector('.wrap')||document.body).appendChild(sec)}return sec}
function shell(){const sec=ensure();sec.innerHTML=window.GamaUI.header({title:'Pedidos de venta',lead:'Pedidos, expediciones y documentos de facturación externa.'})+`<div class="gsTabs">${[['orders','Pedidos'],['deliveries','Expediciones'],...(sell()?[['pending','Pendiente de facturar'],['invoices','Facturas externas']]:[])].map(([id,t])=>`<button class="secondary" data-gs-tab="${id}" aria-pressed="${tab===id}">${t}</button>`).join('')}</div><div id="gsMain" aria-live="polite"></div>`;window.GamaUI.bindBack(sec);sec.querySelectorAll('[data-gs-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.gsTab;page=0;search='';detail=null;shell();load()})}
function badge(s){return `<span class="gsBadge">${esc(label(s))}</span>`}
function pager(hasNext){return `<div class="gsPager"><button class="secondary" id="gsPrev" ${page===0?'disabled':''}>Anterior</button><span>Página ${page+1}</span><button class="secondary" id="gsNext" ${hasNext?'':'disabled'}>Siguiente</button></div>`}
function wirePager(){if($('gsPrev'))$('gsPrev').onclick=()=>{page--;load()};if($('gsNext'))$('gsNext').onclick=()=>{page++;load()}}
function openButtons(root){root.querySelectorAll('[data-gs-order]').forEach(b=>b.onclick=()=>openOrder(b.dataset.gsOrder))}
async function load(){
 if(!allowed())return;
 const token=++version,host=$('gsMain');if(!host)return;host.innerHTML='<div class="gsCard">Cargando…</div>';
 try{
  if(tab==='orders'||tab==='pending'){
   const opt={order:'created_at',ascending:false,range:[page*SIZE,page*SIZE+SIZE]};
   if(tab==='pending')opt.eq={status:'confirmed'};
   if(search)opt.ilike={customer_name:'%'+search+'%'};
   const a=await rows('sales_orders',opt);if(token!==version)return;const more=a.length>SIZE;a.splice(SIZE);
   const ids=a.map(o=>o.id),ls=ids.length?await rows('sales_order_lines',{in:{order_id:ids}}):[];
   let il=[],invoices=[];if(tab==='pending'&&ids.length){invoices=await rows('external_invoices',{in:{order_id:ids}});const ii=invoices.filter(i=>!['cancelled','rejected'].includes(i.fiscal_status)).map(i=>i.id);il=ii.length?await rows('external_invoice_lines',{in:{invoice_id:ii}}):[]}
   if(token!==version)return;
   host.innerHTML=`<div class="gsCard"><div class="gsTools"><input id="gsSearch" aria-label="Buscar pedidos por cliente" placeholder="Buscar por cliente" value="${esc(search)}"><button class="secondary" id="gsFind">Buscar</button>${sell()?'<button class="primary" id="gsNew">Nuevo pedido</button>':''}<button class="secondary" id="gsRefresh">Actualizar</button></div>${tab==='pending'?'<p class="gsHint">Cantidades confirmadas sin factura vinculada. Los registros por verificar también apartan cantidades para evitar duplicados. La expedición y la facturación son independientes.</p>':''}<div class="gsScroll"><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Estado</th><th>${tab==='pending'?'Pendiente de vincular':'Total'}</th><th></th></tr></thead><tbody>${a.map(o=>{const lines=ls.filter(l=>l.order_id===o.id);const amount=lines.reduce((s,l)=>s+Number(l.quantity)*Number(l.unit_price)*(1+Number(l.tax_rate)/100),0);const remaining=lines.reduce((s,l)=>s+Math.max(0,Number(l.quantity)-il.filter(x=>x.order_line_id===l.id).reduce((n,x)=>n+Number(x.quantity),0)),0);return `<tr><td>${esc(o.number)}</td><td>${esc(o.customer_name)}</td><td>${badge(o.status)}</td><td>${tab==='pending'?num(remaining):money(amount)}</td><td><button class="secondary" data-gs-order="${esc(o.id)}">Abrir</button></td></tr>`}).join('')}</tbody></table></div>${!a.length?'<p>No hay pedidos para mostrar.</p>':''}${pager(more)}</div>`;
   $('gsFind').onclick=()=>{search=$('gsSearch').value.trim();page=0;load()};$('gsSearch').onkeydown=e=>{if(e.key==='Enter')$('gsFind').click()};$('gsNew')?.addEventListener('click',()=>newOrder());$('gsRefresh').onclick=load;
  }else if(tab==='deliveries'){
   const a=await rows('sales_deliveries',{order:'dispatched_at',ascending:false,range:[page*SIZE,page*SIZE+SIZE]}),more=a.length>SIZE;a.splice(SIZE);
   const ts=a.length?await rows('tms_deliveries',{in:{id:a.map(x=>x.tms_delivery_id)}}):[];
   if(token!==version)return;
   host.innerHTML=`<div class="gsCard"><p class="gsHint">La salida de stock se registra al validar la expedición. La entrega al cliente se sigue en Transporte y entregas.</p><div class="gsScroll"><table><thead><tr><th>Expedición</th><th>Cliente</th><th>Transporte</th><th>Fecha</th><th></th></tr></thead><tbody>${a.map(d=>{const t=ts.find(x=>x.id===d.tms_delivery_id);return `<tr><td>${esc(d.number)}</td><td>${esc(t?.customer||'—')}</td><td>${esc(t?.status||'Consultar TMS')}</td><td>${esc(d.dispatched_at.slice(0,10))}</td><td><button class="secondary" data-gs-order="${d.order_id}">Ver pedido</button></td></tr>`}).join('')}</tbody></table></div>${!a.length?'<p>No hay expediciones.</p>':''}${pager(more)}</div>`;
  }else if(tab==='invoices'&&sell()){
   const a=await rows('external_invoices',{select:'id,order_id,number,software,issue_date,due_date,total,fiscal_status',order:'created_at',ascending:false,range:[page*SIZE,page*SIZE+SIZE]}),more=a.length>SIZE;a.splice(SIZE);
   const payments=a.length?await rows('external_invoice_payments',{in:{invoice_id:a.map(i=>i.id)}}):[];if(token!==version)return;
   host.innerHTML=`<div class="gsCard"><p class="gsHint">Documentos emitidos en otro software, expediciones vinculadas y cobros registrados en GAMA.</p><div class="gsScroll"><table><thead><tr><th>Factura</th><th>Software</th><th>Fecha</th><th>Importe</th><th>Cobrado</th><th>Saldo</th><th>Cobro</th><th>Estado SRI declarado</th><th></th></tr></thead><tbody>${a.map(i=>{const paid=payments.filter(p=>p.invoice_id===i.id&&p.status==='confirmed').reduce((s,p)=>s+Number(p.amount),0),balance=Math.max(0,Number(i.total)-paid),ps=paymentStatus(i,paid);return `<tr><td>${esc(i.number)}</td><td>${esc(i.software)}</td><td>${esc(i.issue_date)}</td><td>${money(i.total)}</td><td>${money(paid)}</td><td><b>${money(balance)}</b></td><td>${badge(ps)}</td><td>${badge(i.fiscal_status)}</td><td><button class="secondary" data-gs-order="${i.order_id}">Ver vínculo</button></td></tr>`}).join('')}</tbody></table></div>${!a.length?'<p>Vincula una factura desde el detalle de un pedido confirmado.</p>':''}${pager(more)}</div>`;
  }
  openButtons(host);wirePager();
 }catch(e){if(token===version){host.innerHTML='<div class="gsCard gsError">'+esc(error(e))+'<p><button class="secondary" id="gsRetry">Reintentar</button></p></div>';$('gsRetry').onclick=load}}
}
function sum(a,filter){return a.filter(filter).reduce((s,x)=>s+Number(x.quantity||0),0)}
function counts(l,d=detail){const reserved=sum(d.reservations,r=>r.status==='active'&&d.links.some(x=>x.reservation_id===r.id&&x.line_id===l.id));const shipped=sum(d.shipLines,x=>x.order_line_id===l.id);const billed=sum(d.invoiceLines,x=>x.order_line_id===l.id&&d.invoices.some(i=>i.id===x.invoice_id&&i.fiscal_status==='authorized'));const linked=sum(d.invoiceLines,x=>x.order_line_id===l.id&&d.invoices.some(i=>i.id===x.invoice_id&&!['cancelled','rejected'].includes(i.fiscal_status)));return{reserved,shipped,billed,linked}}
function stockCounts(l,d=detail){const own=d.quants.filter(q=>q.product_id===l.product_id),physical=own.reduce((s,q)=>s+Number(q.quantity||0),0),reserved=own.reduce((s,q)=>s+Number(q.reserved_quantity||0),0);return{physical,reserved,available:physical-reserved}}
function paidFor(invoice,d=detail){return d.payments.filter(p=>p.invoice_id===invoice.id&&p.status==='confirmed').reduce((s,p)=>s+Number(p.amount||0),0)}
function paymentStatus(invoice,paid){const balance=Math.max(0,Math.round(Number(invoice.total||0)*100)-Math.round(Number(paid||0)*100));if(balance===0)return'paid';if(invoice.due_date&&invoice.due_date<day())return'overdue';if(paid>0)return'partial';return'pending'}
async function openOrder(id){
 if(!allowed())return;ensure();if(!$('gsMain'))shell();window.showTab?.('sales-orders');const token=++version;const host=$('gsMain');host.innerHTML='<div class="gsCard">Cargando pedido…</div>';
 try{
  const [orders,lines,shipments,reservations]=await Promise.all([rows('sales_orders',{eq:{id}}),rows('sales_order_lines',{eq:{order_id:id},order:'product_name'}),rows('sales_deliveries',{eq:{order_id:id},order:'dispatched_at',ascending:false}),rows('stock_reservations',{eq:{reference_type:'sales_order',reference_id:id}})]);
  const order=orders[0];if(!order)throw new Error('ORDER_NOT_FOUND');
  const [links,shipLines,invoices,locations]=await Promise.all([lines.length?rows('sales_reservation_links',{in:{line_id:lines.map(l=>l.id)}}):[],shipments.length?rows('sales_delivery_lines',{in:{delivery_id:shipments.map(s=>s.id)}}):[],sell()?rows('external_invoices',{eq:{order_id:id},order:'created_at',ascending:false}):[],refs('warehouse_locations','id,code,name,warehouse_id')]);
  const [invoiceLines,files,events,transport,quants,invoiceDeliveries,payments]=await Promise.all([invoices.length?rows('external_invoice_lines',{in:{invoice_id:invoices.map(i=>i.id)}}):[],invoices.length?rows('external_invoice_files',{select:'id,invoice_id,filename,mime_type',in:{invoice_id:invoices.map(i=>i.id)}}):[],rows('sales_events',{eq:{order_id:id},order:'created_at',ascending:false,limit:30}),shipments.length?rows('tms_deliveries',{select:'id,status,delivery_date',in:{id:shipments.map(s=>s.tms_delivery_id)}}):[],lines.length?rows('stock_quants',{in:{product_id:lines.map(l=>l.product_id)}}):[],invoices.length?rows('external_invoice_deliveries',{in:{invoice_id:invoices.map(i=>i.id)}}):[],invoices.length?rows('external_invoice_payments',{in:{invoice_id:invoices.map(i=>i.id)},order:'paid_at',ascending:false}):[]]);
  if(token!==version)return;detail={order,lines,shipments,shipLines,reservations,links,invoices,invoiceLines,locations,files,events,transport,quants,invoiceDeliveries,payments};renderDetail();
 }catch(e){if(token===version)host.innerHTML='<div class="gsCard gsError">'+esc(error(e))+'</div>'}
}
function renderDetail(){
 const d=detail,o=d.order,total=d.lines.reduce((s,l)=>s+Number(l.quantity)*Number(l.unit_price)*(1+Number(l.tax_rate)/100),0);
 const origin=o.source_opportunity_id?`<p class="gsHint">Origen CRM: oportunidad ${esc(String(o.source_opportunity_id).slice(0,8).toUpperCase())}${o.source_quote_id?' → presupuesto '+esc(String(o.source_quote_id).slice(0,8).toUpperCase()):''}</p>`:'';
 $('gsMain').innerHTML=`<div class="gsCard"><div class="gsSummary"><div><h2>${esc(o.number)}</h2><b>${esc(o.customer_name)}</b><p class="gsHint">${esc(o.customer_identification)} · ${esc(o.delivery_address)}</p>${origin}</div><div>${badge(o.status)}<p>${money(total)}</p></div></div>${o.notes?`<p>${esc(o.notes)}</p>`:''}<div class="gsActions"><button class="secondary" id="gsBack">Volver a la lista</button><button class="secondary" id="gsReload">Actualizar</button>${sell()&&o.status==='draft'?'<button class="primary" id="gsConfirm">Confirmar y reservar</button>':''}${o.status==='confirmed'?'<button class="secondary" id="gsReserve">Reservar pendientes</button>':''}${warehouse()&&o.status==='confirmed'?'<button class="primary" id="gsShip">Registrar expedición</button>':''}${sell()&&o.status==='confirmed'?'<button class="primary" id="gsInvoice">Vincular factura externa</button>':''}${sell()&&o.status!=='cancelled'&&!d.shipments.length&&!d.invoices.some(i=>!['rejected','cancelled'].includes(i.fiscal_status))?'<button class="danger" id="gsCancel">Cancelar pedido</button>':''}</div><div id="gsMessage" role="status"></div><div class="gsScroll"><table><thead><tr><th>Producto</th><th>Pedido</th><th>Stock físico</th><th>Reservado pedido</th><th>Disponible global</th><th>Por aprovisionar</th><th>Expedido</th><th>Por expedir</th>${sell()?'<th>Facturado autorizado</th><th>Sin vincular</th>':''}</tr></thead><tbody>${d.lines.map(l=>{const n=counts(l),s=stockCounts(l),short=Math.max(0,Number(l.quantity)-n.shipped-n.reserved);return `<tr><td>${esc(l.product_name)}<br><small>${esc(l.reference)}</small></td><td>${num(l.quantity)}</td><td>${num(s.physical)}</td><td>${num(n.reserved)}</td><td><b>${num(s.available)}</b></td><td>${short?`<b class="gsError">${num(short)}</b>`:'—'}</td><td>${num(n.shipped)}</td><td>${num(Number(l.quantity)-n.shipped)}</td>${sell()?`<td>${num(n.billed)}</td><td>${num(Number(l.quantity)-n.linked)}</td>`:''}</tr>`}).join('')}</tbody></table></div><p class="gsHint">Físico − todas las reservas = disponible. El faltante alimenta automáticamente las necesidades de compra; las recepciones se asignan primero a los pedidos confirmados más antiguos.</p></div>
<div class="gsCard"><h3>Expediciones vinculadas</h3>${d.shipments.map(s=>`<div class="gsCard"><b>${esc(s.number)}</b> · ${esc(s.dispatched_at.slice(0,10))} · ${esc(d.transport.find(t=>t.id===s.tms_delivery_id)?.status||'Consultar TMS')}<ul>${d.shipLines.filter(l=>l.delivery_id===s.id).map(l=>`<li>${esc(d.lines.find(x=>x.id===l.order_line_id)?.product_name)} — ${num(l.quantity)} · ${esc(d.locations.find(x=>x.id===l.location_id)?.code)}</li>`).join('')}</ul>${s.notes?`<p>${esc(s.notes)}</p>`:''}${warehouse()?'<button class="secondary" data-gs-tms>Ver Transporte y entregas</button>':''}</div>`).join('')||'<p>Aún no hay expediciones.</p>'}</div>
${sell()?`<div class="gsCard"><h3>Facturas externas y cobros</h3><p class="gsHint">Estados SRI declarados manualmente según el software emisor. Los cobros no generan asientos contables.</p>${d.invoices.map(i=>{const paid=paidFor(i),balance=Math.max(0,Number(i.total)-paid),ps=paymentStatus(i,paid),linked=d.invoiceDeliveries.filter(x=>x.invoice_id===i.id).map(x=>d.shipments.find(s=>s.id===x.delivery_id)?.number).filter(Boolean);return `<div class="gsCard"><div class="gsSummary"><div><b>${esc(i.number)}</b> · ${money(i.total)} · ${badge(i.fiscal_status)}<p class="gsHint">${esc(i.software)} · ${esc(i.issue_date)}${i.due_date?' · Vencimiento '+esc(i.due_date):''}<br>RUC emisor: ${esc(i.issuer_ruc)}<br>Expediciones: ${linked.length?esc(linked.join(', ')):'sin vínculo'}</p></div><div>${badge(ps)}<p>${money(paid)} cobrado<br><b>${money(balance)} pendiente</b></p></div></div>${i.access_key?`<p class="gsFiles">Clave de acceso: ${esc(i.access_key)}</p>`:''}<ul>${d.invoiceLines.filter(l=>l.invoice_id===i.id).map(l=>`<li>${esc(d.lines.find(x=>x.id===l.order_line_id)?.product_name)} — ${num(l.quantity)}</li>`).join('')}</ul>${d.payments.filter(p=>p.invoice_id===i.id).map(p=>`<p class="gsHint">${esc(p.paid_at)} · ${money(p.amount)} · ${esc(({transfer:'Transferencia',cash:'Efectivo',card:'Tarjeta',check:'Cheque',other:'Otro'})[p.method]||p.method)}${p.reference?' · '+esc(p.reference):''} · ${p.status==='cancelled'?'<s>ANULADO</s>':'Confirmado'} ${p.status==='confirmed'?`<button class="secondary" data-gs-cancel-payment="${p.id}" data-gs-invoice="${i.id}">Anular cobro</button>`:''}</p>`).join('')}<div class="gsFiles">${d.files.filter(f=>f.invoice_id===i.id).map(f=>`<button class="secondary" data-gs-file="${f.id}">${esc(f.filename)}</button>`).join(' ')}</div>${i.notes?`<p>${esc(i.notes)}</p>`:''}${i.cancellation_reason?`<p>${esc(i.cancellation_reason)}</p>`:''}<div class="gsActions">${d.shipments.length?`<button class="secondary" data-gs-link-delivery="${i.id}">Asociar expediciones</button>`:''}<button class="secondary" data-gs-attach="${i.id}">Adjuntar PDF / XML</button>${!['rejected','cancelled'].includes(i.fiscal_status)&&balance>=0.01?`<button class="primary" data-gs-payment="${i.id}">Registrar cobro</button>`:''}${!['rejected','cancelled'].includes(i.fiscal_status)?`<button class="secondary" data-gs-status="${i.id}">Actualizar estado declarado</button>`:''}</div></div>`}).join('')||'<p>Aún no hay facturas vinculadas.</p>'}</div>`:''}
<div class="gsCard"><h3>Historial reciente</h3>${d.events.map(e=>`<p class="gsHint">${esc(new Date(e.created_at).toLocaleString('es-EC'))} · ${esc(({created:'Pedido creado',confirm:'Pedido confirmado',reserve:'Reservas actualizadas',ship:'Expedición registrada',cancel:'Pedido cancelado',invoice:'Factura vinculada',invoice_status:'Estado de factura actualizado',attach:'Archivo adjuntado',invoice_delivery_linked:'Factura vinculada a expedición',payment:'Cobro registrado',payment_cancelled:'Cobro anulado',receipt_auto_reserved:'Reserva automática tras recepción'})[e.action]||e.action)}${e.detail?.reason?' · '+esc(e.detail.reason):''}</p>`).join('')}</div>`;
 $('gsBack').onclick=()=>{detail=null;load()};$('gsReload').onclick=()=>openOrder(o.id);
 $('gsConfirm')?.addEventListener('click',()=>action('confirm'));$('gsReserve')?.addEventListener('click',()=>action('reserve'));
 $('gsCancel')?.addEventListener('click',()=>{if(confirm('¿Cancelar el pedido y liberar sus reservas?'))action('cancel')});
 $('gsShip')?.addEventListener('click',shipForm);$('gsInvoice')?.addEventListener('click',invoiceForm);
 document.querySelectorAll('[data-gs-status]').forEach(b=>b.onclick=()=>statusForm(b.dataset.gsStatus));
 document.querySelectorAll('[data-gs-link-delivery]').forEach(b=>b.onclick=()=>linkDeliveryForm(b.dataset.gsLinkDelivery));
 document.querySelectorAll('[data-gs-attach]').forEach(b=>b.onclick=()=>attachForm(b.dataset.gsAttach));
 document.querySelectorAll('[data-gs-payment]').forEach(b=>b.onclick=()=>paymentForm(b.dataset.gsPayment));
 document.querySelectorAll('[data-gs-cancel-payment]').forEach(b=>b.onclick=()=>cancelPaymentForm(b.dataset.gsInvoice,b.dataset.gsCancelPayment));
 document.querySelectorAll('[data-gs-file]').forEach(b=>b.onclick=()=>download(b.dataset.gsFile));
 document.querySelectorAll('[data-gs-tms]').forEach(b=>b.onclick=()=>window.gamaTMS?.open('tracking'));
}
async function action(name){if(busy)return;busy=true;const id=detail.order.id;const buttons=[...$('gsMain').querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await rpc(name,{order_id:id});await openOrder(id)}catch(e){$('gsMessage').textContent=error(e);$('gsMessage').className='gsError'}finally{busy=false;buttons.forEach(b=>b.disabled=false)}}
function modal(title,body,saveLabel,save){const el=document.createElement('dialog');el.className='gsDialog';el.innerHTML=`<form><h2>${esc(title)}</h2>${body}<p class="gsError" role="alert" id="gsFormError"></p><div class="gsActions"><button class="secondary" type="button" id="gsClose">Volver</button><button class="primary" type="submit" id="gsSave">${esc(saveLabel)}</button></div></form>`;document.body.appendChild(el);const close=()=>el.remove();el.querySelector('#gsClose').onclick=close;el.addEventListener('close',close);let pending=false;el.addEventListener('cancel',e=>{if(pending)e.preventDefault()});el.querySelector('form').onsubmit=async e=>{e.preventDefault();if(pending)return;pending=true;el.querySelector('#gsSave').disabled=true;el.querySelector('#gsClose').disabled=true;el.querySelector('#gsFormError').textContent='';try{await save(el);close()}catch(err){el.querySelector('#gsFormError').textContent=error(err)}finally{pending=false;el.querySelector('#gsSave').disabled=false;el.querySelector('#gsClose').disabled=false}};el.showModal();return el}
const value=(el,id)=>el.querySelector('#'+id).value;
async function newOrder(source='manual',sourceId=''){
 if(!sell()||!allowed())return;
 try{
  const [customers,products,quotes,requests]=await Promise.all([refs('customers','id,name,identification,address,category,active'),refs('products',PCOLS),rows('invoices',{select:'id,invoice_number,archive_number,customer_id',order:'created_at',ascending:false,limit:200}),rows('customer_requests',{select:'id,customer_id,requester_name,status',order:'created_at',ascending:false,limit:200})]);
  const key=crypto.randomUUID();let draft=[];
  const el=modal('Nuevo pedido',`<div class="gsGrid"><label>Origen<select id="gsSource"><option value="manual">Pedido directo</option><option value="quote">Presupuesto existente</option><option value="request">Solicitud de cliente</option></select></label><label id="gsSourceLabel">Documento de origen<select id="gsSourceId"></select><small>Últimos 200 documentos</small></label><label>Cliente<select id="gsCustomer" required><option value="">Seleccionar…</option>${customers.filter(c=>c.active).map(c=>`<option value="${c.id}">${esc(c.name)} · ${esc(c.identification)}</option>`).join('')}</select></label><label>Dirección de entrega<input id="gsAddress" required maxlength="500"></label></div><label class="gsField">Comentario<textarea id="gsNotes" maxlength="2000"></textarea></label><div id="gsManual"><div class="gsGrid"><label>Producto<select id="gsProduct"><option value="">Seleccionar…</option>${products.filter(p=>p.active).map(p=>`<option value="${p.id}">${esc(p.name)} · ${esc(p.reference)}</option>`).join('')}</select></label><label>Cantidad<input id="gsQty" type="number" min="0.001" step="0.001" value="1"></label><label>Precio unitario sin IVA<input id="gsPrice" type="number" min="0" step="0.0001" value="0"></label><label>IVA (%)<input id="gsTax" type="number" min="0" max="100" step="0.0001" value="0"></label></div><button class="secondary" type="button" id="gsAdd">Añadir producto</button><div id="gsDraft"></div></div><p class="gsHint" id="gsSourceHint">El pedido se guarda como borrador. Confírmalo después de revisar sus líneas.</p>`,'Guardar pedido',async form=>{const s=value(form,'gsSource');if(s==='manual'&&!draft.length)throw new Error('INVALID_LINES');const r=await rpc('create',{request_key:key,source:s,source_id:s==='manual'?null:value(form,'gsSourceId'),customer_id:value(form,'gsCustomer'),delivery_address:value(form,'gsAddress'),notes:value(form,'gsNotes'),lines:draft});await openOrder(r.id)});
  const f=id=>el.querySelector('#'+id);const chooseCustomer=id=>{f('gsCustomer').value=id||'';f('gsAddress').value=customers.find(c=>c.id===id)?.address||''};
  function chooseSource(){const s=f('gsSource').value;f('gsManual').hidden=s!=='manual';f('gsSourceLabel').hidden=s==='manual';f('gsSourceId').required=s!=='manual';const a=s==='quote'?quotes:requests.filter(r=>!['cancelled','rejected'].includes(r.status));f('gsSourceId').innerHTML='<option value="">Seleccionar…</option>'+a.map(x=>`<option value="${x.id}">${esc(s==='quote'?(x.invoice_number||'Archivo '+x.archive_number):x.id.slice(0,8))} · ${esc(customers.find(c=>c.id===x.customer_id)?.name||x.requester_name||'Sin cliente')}</option>`).join('');if(sourceId){f('gsSourceId').value=sourceId;if(!f('gsSourceId').value){const opt=document.createElement('option');opt.value=sourceId;opt.textContent='Documento seleccionado';f('gsSourceId').appendChild(opt);f('gsSourceId').value=sourceId}}f('gsSourceId').onchange=()=>{const row=a.find(x=>x.id===f('gsSourceId').value);chooseCustomer(row?.customer_id);f('gsCustomer').disabled=!!row?.customer_id};f('gsCustomer').disabled=false;if(s!=='manual')f('gsSourceId').onchange()}
  function draftView(){f('gsDraft').innerHTML=draft.map((l,i)=>`<p>${esc(products.find(p=>p.id===l.product_id)?.name)} · ${num(l.quantity)} × ${money(l.unit_price)} <button type="button" class="secondary" data-remove="${i}">Quitar</button></p>`).join('');f('gsDraft').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{draft.splice(Number(b.dataset.remove),1);draftView()})}
  f('gsSource').value=source;f('gsSource').onchange=()=>{sourceId='';chooseSource()};chooseSource();
  f('gsCustomer').onchange=()=>{f('gsAddress').value=customers.find(c=>c.id===f('gsCustomer').value)?.address||''};
  f('gsProduct').onchange=async()=>{const p=products.find(x=>x.id===f('gsProduct').value),c=customers.find(x=>x.id===f('gsCustomer').value);if(!p)return;f('gsPrice').value=c?.category==='B'?p.sale_price_b:p.sale_price;f('gsTax').value=p.tax_rate;if(c?.category==='C'){try{const sp=await rows('customer_special_prices',{eq:{customer_id:c.id,product_id:p.id}});if(sp[0]&&f('gsProduct').value===p.id)f('gsPrice').value=sp[0].unit_price}catch(e){f('gsFormError').textContent=error(e)}}};
  f('gsAdd').onclick=()=>{const p=f('gsProduct').value,q=Number(f('gsQty').value),price=Number(f('gsPrice').value),tax=Number(f('gsTax').value);if(!p||!Number.isFinite(q)||q<=0||!Number.isFinite(price)||price<0||!Number.isFinite(tax)||tax<0||tax>100){f('gsFormError').textContent='Selecciona un producto y revisa cantidad, precio e IVA.';return}if(draft.some(l=>l.product_id===p)){f('gsFormError').textContent='El producto ya está en el pedido. Quita la línea para cambiar la cantidad.';return}draft.push({product_id:p,quantity:q,unit_price:price,tax_rate:tax});f('gsFormError').textContent='';draftView()};
 }catch(e){window.gamaToast?.(error(e))}
}
function shipForm(){const d=detail,key=crypto.randomUUID();const allocations=[];for(const l of d.lines){for(const loc of d.locations){const q=sum(d.reservations,r=>r.location_id===loc.id&&r.status==='active'&&d.links.some(x=>x.reservation_id===r.id&&x.line_id===l.id));if(q>0)allocations.push({line:l,location:loc,quantity:q})}}
 if(!allocations.length){$('gsMessage').textContent='No hay cantidades reservadas. Repón existencias y pulsa «Reservar pendientes».';return}
 modal('Registrar expedición',`<p class="gsHint">Valida únicamente la mercancía que sale del almacén. Esta operación descuenta el stock y crea una entrega vinculada en Transporte.</p><label class="gsField">Fecha prevista de entrega<input id="gsDeliveryDate" type="date" required value="${day()}"></label><div class="gsScroll"><table><thead><tr><th>Producto</th><th>Ubicación</th><th>Reservado</th><th>Expedir</th></tr></thead><tbody>${allocations.map((a,i)=>`<tr><td>${esc(a.line.product_name)}</td><td>${esc(a.location.code)}</td><td>${num(a.quantity)}</td><td><input aria-label="Expedir ${esc(a.line.product_name)} desde ${esc(a.location.code)}" class="gsNumber" data-dispatch="${i}" type="number" min="0" max="${a.quantity}" step="0.001" value="${a.quantity}"></td></tr>`).join('')}</tbody></table></div><label class="gsField">Comentario<textarea id="gsDispatchNote"></textarea></label>`,'Validar salida de stock',async el=>{const lines=[...el.querySelectorAll('[data-dispatch]')].map(input=>({line_id:allocations[Number(input.dataset.dispatch)].line.id,location_id:allocations[Number(input.dataset.dispatch)].location.id,quantity:Number(input.value)})).filter(l=>l.quantity>0);if(!lines.length)throw new Error('INVALID_LINES');await rpc('ship',{order_id:d.order.id,request_key:key,delivery_date:value(el,'gsDeliveryDate'),notes:value(el,'gsDispatchNote'),lines});await openOrder(d.order.id)})
}
const fileInput='<label class="gsField">PDF / XML (opcional, hasta 2 archivos de 5 MB)<input id="gsFiles" type="file" accept=".pdf,.xml,application/pdf,application/xml,text/xml" multiple></label>';
async function readFiles(el){const a=[...(el.querySelector('#gsFiles')?.files||[])];if(a.length>2)throw new Error('TOO_MANY_FILES');return Promise.all(a.map(async f=>{const ext=f.name.split('.').pop().toLowerCase();if(!['pdf','xml'].includes(ext))throw new Error('Solo se admiten PDF y XML.');if(f.size<=0||f.size>5000000)throw new Error('INVALID_FILE_SIZE');const bytes=new Uint8Array(await f.arrayBuffer());if(ext==='pdf'&&new TextDecoder().decode(bytes.slice(0,5))!=='%PDF-')throw new Error('El archivo no es un PDF válido.');if(ext==='xml'){const xml=new DOMParser().parseFromString(new TextDecoder().decode(bytes),'application/xml');if(xml.querySelector('parsererror'))throw new Error('El XML no es válido.')}let binary='';for(let n=0;n<bytes.length;n+=8192)binary+=String.fromCharCode(...bytes.subarray(n,n+8192));return{filename:f.name,mime_type:ext==='pdf'?'application/pdf':'application/xml',content_base64:btoa(binary)}}))}
function invoiceForm(){const d=detail,key=crypto.randomUUID(),remaining=d.lines.map(l=>({line:l,quantity:Number(l.quantity)-counts(l).linked})).filter(x=>x.quantity>0);if(!remaining.length){$('gsMessage').textContent='Todas las cantidades ya tienen una factura vinculada.';return}
 const deliveryBlock=d.shipments.length?`<h3>Expediciones cubiertas</h3><p class="gsHint">Marca las salidas incluidas en este documento.</p>${d.shipments.map(s=>`<label><input type="checkbox" data-invoice-delivery value="${s.id}" checked> ${esc(s.number)} · ${esc(s.dispatched_at.slice(0,10))}</label>`).join('')}`:'<p class="gsHint">Todavía no hay expediciones: la factura quedará vinculada al pedido y podrá asociarse a una salida más adelante.</p>';
 const el=modal('Vincular factura externa',`<p class="gsHint">Copia los datos del documento emitido en tu otro software. El estado es una declaración manual. GAMA comprobará el receptor y los importes; no emitirá una factura.</p><div class="gsGrid"><label>Número de factura<input id="gsInvNumber" required maxlength="80"></label><label>RUC del emisor<input id="gsIssuer" required pattern="[0-9]{13}" maxlength="13" inputmode="numeric"></label><label>Identificación del receptor<input id="gsReceiver" required value="${esc(d.order.customer_identification)}"></label><label>Software emisor<input id="gsSoftware" maxlength="120"></label><label>Fecha de emisión<input id="gsIssue" type="date" required value="${day()}"></label><label>Vencimiento<input id="gsDue" type="date"></label><label>Clave de acceso (opcional)<input id="gsAccess" pattern="[0-9]{49}" maxlength="49" inputmode="numeric"></label><label>Estado declarado<select id="gsFiscal"><option value="unverified">Por verificar</option><option value="authorized">Autorizada según software emisor</option><option value="rejected">Rechazada</option></select></label></div>${deliveryBlock}<h3>Líneas de esta factura</h3><div class="gsScroll"><table><thead><tr><th>Producto</th><th>Sin vincular</th><th>Cantidad en factura</th></tr></thead><tbody>${remaining.map((a,i)=>`<tr><td>${esc(a.line.product_name)}</td><td>${num(a.quantity)}</td><td><input class="gsNumber" aria-label="Facturar ${esc(a.line.product_name)}" data-invoice-qty="${i}" type="number" min="0" max="${a.quantity}" step="0.001" value="${a.quantity}"></td></tr>`).join('')}</tbody></table></div><p class="gsHint" id="gsExpected"></p><div class="gsGrid"><label>Subtotal del documento<input id="gsSubtotal" type="number" required min="0" step="0.01"></label><label>IVA del documento<input id="gsInvoiceTax" type="number" required min="0" step="0.01"></label></div>${fileInput}<label class="gsField">Comentario<textarea id="gsInvNotes"></textarea></label>`,'Vincular documento',async form=>{const lines=[...form.querySelectorAll('[data-invoice-qty]')].map(input=>({line_id:remaining[Number(input.dataset.invoiceQty)].line.id,quantity:Number(input.value)})).filter(x=>x.quantity>0);if(!lines.length)throw new Error('INVALID_LINES');const deliveryIds=[...form.querySelectorAll('[data-invoice-delivery]:checked')].map(x=>x.value);if(d.shipments.length&&!deliveryIds.length)throw new Error('DELIVERY_REQUIRED');const inv=await rpc('invoice',{order_id:d.order.id,request_key:key,number:value(form,'gsInvNumber'),issuer_ruc:value(form,'gsIssuer'),customer_identification:value(form,'gsReceiver'),software:value(form,'gsSoftware'),issue_date:value(form,'gsIssue'),due_date:value(form,'gsDue'),access_key:value(form,'gsAccess'),fiscal_status:value(form,'gsFiscal'),subtotal:Number(value(form,'gsSubtotal')),tax:Number(value(form,'gsInvoiceTax')),notes:value(form,'gsInvNotes'),files:await readFiles(form),lines,delivery_ids:deliveryIds});await openOrder(d.order.id)});
 const expected=()=>{let s=0,t=0;el.querySelectorAll('[data-invoice-qty]').forEach(input=>{const l=remaining[Number(input.dataset.invoiceQty)].line,q=Number(input.value),v=Math.round((q*Number(l.unit_price)+Number.EPSILON)*100)/100;s+=v;t+=Math.round((v*Number(l.tax_rate)/100+Number.EPSILON)*100)/100});el.querySelector('#gsExpected').textContent=`Según pedido: subtotal ${money(s)} · IVA ${money(t)} · total ${money(s+t)}. Introduce los importes del documento externo.`};el.querySelectorAll('[data-invoice-qty]').forEach(input=>input.oninput=expected);expected();
}
function linkDeliveryForm(invoiceId){
 const d=detail;
 modal('Asociar expediciones', '<p class="gsHint">Selecciona las expediciones de este pedido que cubre la factura. Los vínculos existentes se conservan.</p>'+d.shipments.map(s=>`<label><input type="checkbox" data-invoice-delivery value="${s.id}" ${d.invoiceDeliveries.some(x=>x.invoice_id===invoiceId&&x.delivery_id===s.id)?'checked disabled':''}> ${esc(s.number)}</label>`).join(''),'Guardar vínculos',async el=>{
  const ids=[...el.querySelectorAll('[data-invoice-delivery]:checked')].map(x=>x.value);
  if(!ids.length)throw new Error('DELIVERY_REQUIRED');
  await commercialRpc('link_invoice_delivery',{invoice_id:invoiceId,delivery_ids:ids});
  await openOrder(d.order.id);
 });
}
function paymentForm(invoiceId){const d=detail,i=d.invoices.find(x=>x.id===invoiceId);if(!i)return;const paid=paidFor(i),balance=Math.max(0,Number(i.total)-paid),key=crypto.randomUUID();modal('Registrar cobro',`<p class="gsHint">Factura ${esc(i.number)} · saldo pendiente <b>${money(balance)}</b>. Se admiten cobros parciales.</p><div class="gsGrid"><label>Importe<input id="gsPayAmount" type="number" min="0.01" max="${balance.toFixed(2)}" step="0.01" required value="${balance.toFixed(2)}"></label><label>Fecha<input id="gsPayDate" type="date" required value="${day()}"></label><label>Medio<select id="gsPayMethod"><option value="transfer">Transferencia</option><option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="check">Cheque</option><option value="other">Otro</option></select></label><label>Referencia bancaria / recibo<input id="gsPayReference" maxlength="180"></label><label>Cuenta / caja<input id="gsPayAccount" maxlength="180"></label></div><label class="gsField">Comentario<textarea id="gsPayNotes" maxlength="2000"></textarea></label>`,'Guardar cobro',async el=>{await commercialRpc('payment',{invoice_id:i.id,request_key:key,amount:Number(value(el,'gsPayAmount')),paid_at:value(el,'gsPayDate'),method:value(el,'gsPayMethod'),reference:value(el,'gsPayReference'),account:value(el,'gsPayAccount'),notes:value(el,'gsPayNotes')});await openOrder(d.order.id)})}
function cancelPaymentForm(invoiceId,paymentId){const oid=detail.order.id;modal('Anular cobro',`<p class="gsHint">El cobro se conservará en el historial y volverá a abrir el saldo de la factura.</p><label class="gsField">Motivo<textarea id="gsPayCancelReason" required minlength="3"></textarea></label>`,'Anular cobro',async el=>{await commercialRpc('cancel_payment',{invoice_id:invoiceId,payment_id:paymentId,reason:value(el,'gsPayCancelReason')});await openOrder(oid)})}
function statusForm(id){const d=detail;modal('Actualizar estado declarado',`<p class="gsHint">Registra el cambio confirmado en el software emisor. Cancelar aquí no anula un documento ante el SRI y no devuelve mercancía al stock.</p><label class="gsField">Estado<select id="gsNewStatus"><option value="authorized">Autorizada</option><option value="rejected">Rechazada</option><option value="cancelled">Cancelada en el software emisor</option></select></label><label class="gsField">Motivo / referencia de comprobación<textarea id="gsReason" required minlength="3"></textarea></label>`,'Guardar estado',async el=>{await rpc('invoice_status',{order_id:d.order.id,invoice_id:id,fiscal_status:value(el,'gsNewStatus'),reason:value(el,'gsReason')});await openOrder(d.order.id)})}
function attachForm(id){const oid=detail.order.id;modal('Adjuntar documento',fileInput,'Guardar archivos',async el=>{const files=await readFiles(el);if(!files.length)throw new Error('Selecciona al menos un archivo.');await rpc('attach',{order_id:oid,invoice_id:id,files});await openOrder(oid)})}
async function download(id){try{const a=await rows('external_invoice_files',{eq:{id}}),f=a[0];if(!f)throw new Error('Archivo no disponible.');const b=Uint8Array.from(atob(f.content_base64),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([b],{type:f.mime_type})),link=document.createElement('a');link.href=url;link.download=f.filename.replace(/[\\/]/g,'_');link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){window.gamaToast?.(error(e))}}
async function open(){if(!allowed())return;await window.GamaCloudReady;detail=null;shell();window.showTab?.('sales-orders');await load()}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-gs-source]');if(!b||!allowed()||!sell())return;const source=b.dataset.gsSource,id=b.dataset.gsSourceId;b.disabled=true;try{const existing=await rows('sales_orders',{eq:{[source==='quote'?'source_quote_id':'source_request_id']:id},limit:1});if(existing[0])await openOrder(existing[0].id);else await newOrder(source,id)}catch(err){window.gamaToast?.(error(err))}finally{b.disabled=false}});
window.GamaSales={open,openOrder,newOrder,counts,error};
})();
