/* Generated from src/features/website/site.js. Edit the source and run npm run build. */
/* Test storefront: same-origin ERP session; no anonymous data exposure. */
(function(){'use strict';
const $=id=>document.getElementById(id),E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let catalogue=null,cart=[],offset=0,search='',category='',generation=0,photoGeneration=0,timer,sending=false,receipt=null;
const money=v=>new Intl.NumberFormat('es-EC',{style:'currency',currency:catalogue?.currency||'USD'}).format(Number(v||0));
async function rpc(action,data={}){await window.GamaCloudReady;const r=await(await window.GamaCloud.db()).rpc('gama_website',{p_action:action,p_data:data});if(r.error)throw r.error;return r.data}
function error(e){const m=String(e?.message||e);if(/ACCESS_DENIED|JWT|permission denied|session/i.test(m))return 'Abre Coco ERP e inicia sesión con tu cuenta de administrador. Después, vuelve aquí y pulsa Actualizar.';if(m.includes('PREVIEW_PAUSED'))return 'La vista de prueba está pausada. Puedes activarla en Administración → Sitio web.';if(m.includes('PRODUCT_NOT_FOUND'))return 'Un producto de tu selección ya no está disponible en el sitio. Actualiza el catálogo y revisa tu selección.';if(/QUANTITY|PACK_QUANTITY/.test(m))return 'Revisa las cantidades y los múltiplos indicados para cada producto.';if(m.includes('CONTACT_REQUIRED'))return 'Revisa el nombre de contacto y el correo electrónico.';return 'No se pudo completar la operación. Revisa tu conexión e inténtalo de nuevo. Tu selección se conserva.'}
function state(title,text){$('siteProducts').innerHTML=`<div class="empty-state"><h3>${E(title)}</h3><p>${E(text)}</p><a class="button primary" href="index.html" target="_blank" rel="noopener">Abrir Coco ERP ↗</a></div>`;$('sitePager').replaceChildren();$('productCount').textContent=''}
async function load(){const token=++generation;$('siteStatus').textContent='Actualizando el catálogo…';
 try{const data=await rpc('catalog',{search,category,offset,limit:24});if(token!==generation)return;catalogue=data;
 $('headline').textContent=data.settings.headline;$('introduction').textContent=data.settings.introduction;
 $('siteCategory').innerHTML='<option value="" data-gi=425a839def0b>Todas las categorías</option>'+data.categories.map(c=>`<option ${c===category?'selected':''}>${E(c)}</option>`).join('');
 $('productCount').textContent=data.total+' productos';$('siteStatus').textContent='';
 const phone=data.settings.phone||'',email=data.settings.email||'';$('contactDetails').innerHTML=`${phone?`<a href="tel:${E(phone.replace(/[^+\d]/g,''))}">${E(phone)}</a>`:''}${email?`<a href="mailto:${E(email)}">${E(email)}</a>`:''}<address>${E(data.settings.address)}</address>`;
 $('siteProducts').innerHTML=data.items.length?data.items.map(product).join(''):'<div class="empty-state"><h3>No hay productos para esta selección.</h3><p>Prueba otra búsqueda o selecciona productos en el módulo Sitio web de Coco ERP.</p></div>';
 $('siteProducts').querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(data.items.find(p=>p.id===b.dataset.add)));
 $('sitePager').innerHTML=data.total>24?`<button type="button" class="button outline" data-page="prev" ${offset===0?'disabled':''} data-gi=e4ce7c09d51e>Anterior</button><span>${offset+1}–${Math.min(offset+24,data.total)} / ${data.total}</span><button type="button" class="button outline" data-page="next" ${offset+24>=data.total?'disabled':''}>Siguiente</button>`:'';
 $('sitePager').querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{offset=Math.max(0,offset+(b.dataset.page==='next'?24:-24));load()});
 photos(data.items,token);updateCartCount();
 }catch(e){if(token!==generation)return;$('siteStatus').textContent='';state('Vista de prueba de GAMA',error(e));}
}
function product(p){const selected=cart.find(x=>x.id===p.id);return `<article class="product"><div class="product-image" data-photo="${E(p.id)}">${p.featured?'<span class="feature">Selección GAMA</span>':''}<span class="initial" aria-hidden="true">${E(p.name.slice(0,1))}</span></div><div class="product-content"><span class="product-category">${E(p.category)}</span><h3>${E(p.name)}</h3><span class="product-ref">${E(p.reference||'')}</span>${p.description?`<p class="product-description">${E(p.description)}</p>`:''}<div class="product-bottom"><div class="product-price">${p.unit_price!=null?E(money(p.unit_price)):'Consultar precio'}</div><p class="product-note">${p.unit_price!=null?'Precio por unidad, sin IVA.':'Cotización personalizada.'}</p><button type="button" class="add" data-add="${E(p.id)}">${selected?'En mi cotización · '+E(selected.quantity):'Añadir a mi cotización +'}</button></div></div></article>`}
async function photos(items,token){const ids=items.filter(p=>p.has_photo).map(p=>p.id);if(!ids.length)return;const photoToken=++photoGeneration;try{const rows=await rpc('photo',{ids});if(token!==generation||photoToken!==photoGeneration)return;for(const r of rows){if(!/^data:image\/(png|jpeg|webp);base64,/i.test(r.photo_data||''))continue;const slot=document.querySelector('[data-photo="'+r.id+'"]');if(!slot)continue;const img=document.createElement('img');img.src=r.photo_data;img.alt='';img.loading='lazy';slot.querySelector('.initial')?.remove();slot.appendChild(img)}}catch(_){/* Product text and ordering remain usable without a photo. */}}
function add(p){if(!p)return;const row=cart.find(x=>x.id===p.id);if(row){openCart();return}const step=Number(p.order_multiple)||1;cart.push({...p,quantity:Math.round(Math.ceil(Math.max(Number(p.order_minimum)||1,1)/step)*step*1000)/1000});receipt=null;updateCartCount();const b=document.querySelector('[data-add="'+p.id+'"]');if(b)b.textContent='En mi cotización · '+cart.at(-1).quantity}
function updateCartCount(){$('cartCount').textContent=String(cart.length);$('quoteSend').disabled=!cart.length||sending}
function openCart(){renderCart();$('cartDialog').showModal()}
function renderCart(){$('cartLines').innerHTML=cart.map(p=>`<div class="cart-line"><div><strong>${E(p.name)}</strong><small>${E(p.reference)} · mínimo ${E(p.order_minimum||1)}, múltiplo ${E(p.order_multiple||1)}</small></div><input type="number" value="${E(p.quantity)}" min="${E(p.order_minimum||.001)}" step="${E(p.order_multiple||.001)}" max="100000" aria-label="Cantidad de ${E(p.name)}" data-qty="${E(p.id)}"><button class="icon-button" type="button" aria-label="Quitar ${E(p.name)}" data-remove="${E(p.id)}">×</button></div>`).join('')||'<p>Tu selección está vacía. Añade productos desde el catálogo.</p>';
 $('cartLines').querySelectorAll('[data-qty]').forEach(i=>i.onchange=()=>{const p=cart.find(p=>p.id===i.dataset.qty),value=Number(i.value);if(!i.checkValidity()||!Number.isFinite(value)||value<=0){i.reportValidity();return}p.quantity=value;receipt=null;totals()});
 $('cartLines').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(p=>p.id!==b.dataset.remove);receipt=null;renderCart();updateCartCount();const addButton=document.querySelector('[data-add="'+b.dataset.remove+'"]');if(addButton)addButton.textContent='Añadir a mi cotización +'});totals();updateCartCount()}
function totals(){$('cartTotal').textContent=cart.length&&catalogue?.settings.show_prices?'Total indicativo con IVA: '+money(cart.reduce((s,p)=>s+Math.round(p.quantity*Number(p.unit_price||0)*100)/100+Math.round(Math.round(p.quantity*Number(p.unit_price||0)*100)/100*Number(p.tax_rate||0))/100,0)):''}
$('cartOpen').onclick=openCart;$('cartClose').onclick=()=>$('cartDialog').close();$('siteReload').onclick=load;
$('siteSearch').oninput=e=>{search=e.target.value;clearTimeout(timer);timer=setTimeout(()=>{offset=0;load()},300)};$('siteCategory').onchange=e=>{category=e.target.value;offset=0;load()};
$('quoteForm').onsubmit=async e=>{e.preventDefault();if(sending||!cart.length)return;for(const i of $('cartLines').querySelectorAll('input'))if(!i.checkValidity()){i.reportValidity();return}
 const payload={...Object.fromEntries(new FormData(e.currentTarget)),lines:cart.map(p=>({product_id:p.id,quantity:p.quantity}))},signature=JSON.stringify(payload);
 if(!receipt||receipt.signature!==signature)receipt={signature,key:crypto.randomUUID()};sending=true;updateCartCount();$('quoteStatus').textContent='Enviando…';
 try{const r=await rpc('submit',{...payload,request_key:receipt.key});$('quoteStatus').textContent='Solicitud de prueba recibida: '+r.reference+'.\nYa está disponible en Coco ERP → Administración → Sitio web → Solicitudes de prueba.';cart=[];receipt=null;renderCart();$('quoteForm').reset();load();}
 catch(e){$('quoteStatus').textContent=error(e)}finally{sending=false;updateCartCount()}
};
window.addEventListener('gama:auth-change',e=>{if(e.detail?.event==='TOKEN_REFRESHED'||e.detail?.event==='INITIAL_SESSION')return;generation++;photoGeneration++;cart=[];catalogue=null;receipt=null;updateCartCount();$('cartDialog').close();load()});
load();
})();
