/* Versioned quotes and a customer-scoped delivery portal. */
(function(){
'use strict';
const $=id=>document.getElementById(id), C=()=>window.GamaCloud;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v||0).toLocaleString('es-EC',{style:'currency',currency:'USD'});
const today=()=>new Date().toLocaleDateString('en-CA');
const role=()=>{try{return JSON.parse(localStorage.getItem('gama_session_v1')||'{}').role}catch(_){return ''}};
const client=()=>role()==='client';
const state=q=>q.quote_state||'draft';
const label=s=>({draft:'Borrador',sent:'Enviado',accepted:'Aceptado',rejected:'Rechazado',cancelled:'Cancelado'}[s]||s);
let page=0,deliveryPage=0,version=0;
const errors={QUOTE_CHANGED:'El presupuesto ha cambiado. Actualiza y revisa la nueva versión antes de continuar.',QUOTE_LOCKED:'Este presupuesto ya no permite esta acción.',QUOTE_EXPIRED:'El presupuesto ha vencido. Solicita una actualización.',QUOTE_HAS_ORDER:'Este presupuesto ya tiene un pedido. Consúltalo en Pedidos de venta.',QUOTE_NOT_FOUND:'Presupuesto no disponible para tu cuenta.',ROLE_NOT_ALLOWED:'Tu perfil no permite esta acción.',DETAILS_REQUIRED:'Completa emisor, cliente y dirección de entrega.',VALIDITY_REQUIRED:'Revisa la fecha y la vigencia.',DESCRIPTION_REQUIRED:'Cada producto necesita una descripción.',DUPLICATE_PRODUCT:'Agrupa las cantidades del mismo producto en una sola línea.',ACCEPTANCE_REFERENCE_REQUIRED:'Indica el medio y la referencia del acuerdo del cliente.',PRODUCT_NOT_FOUND:'Un producto ya no está disponible. Reabre el presupuesto y sustitúyelo.',INVALID_LINES:'Revisa productos, cantidades, precios, descuentos e impuestos.',CUSTOMER_REQUIRED:'Selecciona un cliente activo.',USE_QUOTE_ACTION:'Gestiona este documento desde Presupuestos.'};
const message=e=>Object.keys(errors).find(k=>String(e?.message||e).includes(k))?errors[Object.keys(errors).find(k=>String(e?.message||e).includes(k))]:String(e?.message||e);
async function rows(t,o={}){const r=await C().list(t,o);if(r.error)throw r.error;return r.data||[]}
async function rpc(name,data){const r=await (await C().db()).rpc(name,data);if(r.error)throw r.error;return r.data}
const action=(a,d)=>rpc('gama_quote_action',{p_action:a,p_data:d});
function css(){if($('gqCss'))return;const el=document.createElement('style');el.id='gqCss';el.textContent=`.gqCard{background:#fff;border:1px solid #dce5e9;border-radius:16px;padding:22px;margin:16px 0;color:#18324a}.gqTools{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:15px 0}.gqGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.gqGrid label,.gqField{display:flex;flex-direction:column;gap:5px;font-size:12px;font-weight:700}.gqCard input,.gqCard select,.gqCard textarea{width:100%;box-sizing:border-box;min-width:0;padding:10px;border:1px solid #cbd8df;border-radius:8px;font:inherit}.gqCard textarea{min-height:72px}.gqScroll{overflow:auto}.gqCard table{width:100%;border-collapse:collapse}.gqCard th,.gqCard td{padding:11px 8px;text-align:left;border-bottom:1px solid #e5edef}.gqBadge{display:inline-block;background:#e6f3f4;color:#075b65;border-radius:20px;padding:5px 10px;font-size:12px;font-weight:700}.gqLinked{background:#f1f7f8;border-left:3px solid #087c8b;padding:14px;white-space:normal;overflow-wrap:anywhere}.gqInvoice{padding:12px 0;border-bottom:1px solid #dce5e9}.gqInvoice p{margin:8px 0}.gqInvoiceRow td{padding-top:0!important}.gqError{color:#ad2828}.gqMuted{color:#647985;font-size:13px}.gqPaper{max-width:850px;margin:auto}.gqBrand{display:flex;justify-content:space-between;gap:20px;border-bottom:4px solid #087c8b;padding-bottom:22px;margin-bottom:22px}.gqBrand img{width:120px;height:70px;object-fit:contain}.gqBrand h2{letter-spacing:2px;margin:0 0 8px}.gqTotal{text-align:right;font-size:23px;color:#087c8b;font-weight:800;margin:20px 0}.gqProof img{display:block;max-width:100%;max-height:480px;object-fit:contain;background:#f4f7f8;margin:12px 0}.gqLine{border:1px solid #dce5e9;padding:15px;border-radius:12px;margin:12px 0}.gqLine .gqGrid{grid-template-columns:repeat(4,minmax(0,1fr))}.gqConfirm{background:#eff7f8;border-radius:12px;padding:18px;margin:20px 0}.gqPaper p{white-space:pre-wrap;overflow-wrap:anywhere}@media(max-width:650px){.gqCard{padding:14px}.gqGrid,.gqLine .gqGrid{grid-template-columns:1fr 1fr}.gqBrand{flex-direction:column}.gqTools button{flex:1}.gqCard th,.gqCard td{padding:8px;font-size:12px}}`;document.head.appendChild(el)}
function shell(id,title,lead){css();let s=$(id);if(!s){s=document.createElement('section');s.id=id;(document.querySelector('.wrap')||document.body).appendChild(s)}s.innerHTML=window.GamaUI.header({title,lead})+`<div id="${id}-main" aria-live="polite"></div>`;window.GamaUI.bindBack(s);window.showTab?.(id);return $(id+'-main')}
function fail(host,e){host.innerHTML=`<div class="gqCard gqError">${esc(message(e))}<div class="gqTools"><button class="secondary" id="gqRetry" data-gi=ff28c7b64a28>Volver a intentar</button></div></div>`;$('gqRetry').onclick=()=>host.id.startsWith('client-deliveries')?deliveries():open()}
async function run(button,fn){button.disabled=true;try{await fn()}catch(e){const m=$('gqMessage');if(m)m.textContent=message(e);else alert(message(e))}finally{button.disabled=false}}
const invoiceAccess=()=>!client()&&['admin','administrador','commercial','comercial'].includes(role())&&!!window.gamaAccessAllowed?.('sales-orders');
async function invoiceList(quotes){
 if(!invoiceAccess()||!quotes.length)return {invoices:[],orders:[]};
 const ids=quotes.map(q=>q.id),fetch=async(t,o)=>{const result=[];for(let offset=0;;offset+=300){const a=await rows(t,{...o,order:'id',range:[offset,offset+299]});result.push(...a);if(a.length<300)return result}};
 const select='id,source_quote_id,order_id,number,document_kind,fiscal_status,total,external_number,external_status,software,due_date';
 const orders=await fetch('sales_orders',{select:'id,source_quote_id,status',in:{source_quote_id:ids}});
 const [direct,linked,eligibility]=await Promise.all([fetch('external_invoices',{select,in:{source_quote_id:ids}}),orders.length?fetch('external_invoices',{select,in:{order_id:orders.map(o=>o.id)}}):[],GamaInternalInvoices.eligibility(ids)]);
 return {orders,eligibility,invoices:[...new Map([...direct,...linked].map(i=>[i.id,i])).values()]};
}
function invoiceRows(q,bundle){
 if(!invoiceAccess())return '';
 const orders=bundle.orders.filter(o=>o.source_quote_id===q.id),invoices=bundle.invoices.filter(i=>i.source_quote_id===q.id||orders.some(o=>o.id===i.order_id));
 const active=invoices.some(i=>!['cancelled','rejected'].includes(i.fiscal_status));
 const create=bundle.eligibility?.some(e=>e.quote_id===q.id&&e.ready)&&q.quote_state==='accepted'&&!active&&!orders.some(o=>o.status==='cancelled');
 return `<tr class="gqInvoiceRow"><td colspan="6"><div class="gqLinked"><b data-gi-live data-gi=421a0aa5c679>Facturas asociadas al presupuesto</b> ${esc(q.invoice_number||'')}<div>${invoices.map(i=>`<div class="gqInvoice"><b>${esc(i.number)}</b> · <span data-gi-live>${i.document_kind==='internal'?'Documento interno · sin validez fiscal':'Factura externa'}</span> · ${money(i.total)}${['cancelled','rejected'].includes(i.fiscal_status)?` · <span data-gi-live>${i.fiscal_status==='cancelled'?'Cancelado':'Rechazado'}</span>`:''}<p><span data-gi-live data-gi=12ae633c750f>Número externo</span>: <b>${esc(i.external_number||'—')}</b></p><div class="gqTools">${i.document_kind==='internal'?`<button class="secondary" data-gq-invoice="${esc(i.id)}" data-gi-live data-gi=6ee45e8fd296>Ver factura interna</button>${i.fiscal_status!=='cancelled'?`<button class="secondary" data-gq-external="${esc(i.id)}" data-gi-live>${i.external_number?'Ver / actualizar referencia externa':'Asociar número externo'}</button>`:''}`:`<button class="secondary" data-gq-invoice-order="${esc(i.order_id)}" data-gi-live data-gi=34b9bc6a0473>Ver factura y cobros</button>`}</div></div>`).join('')||'<p data-gi-live data-gi=86f7e6486d72>Todavía no hay factura asociada.</p>'}</div>${create?`<button class="primary" data-gq-create-invoice="${esc(q.id)}" data-gi-live data-gi=abd4f5befb0f>Crear factura interna</button>`:q.quote_state==='accepted'&&!active?'<p data-gi-live data-gi=4588079588de>La factura interna estará disponible después de validar la entrega completa y su prueba firmada.</p>':''}</div></td></tr>`;
}
function bindInvoiceRows(host){
 host.querySelectorAll('[data-gq-create-invoice]').forEach(b=>b.onclick=()=>{if(invoiceAccess())GamaInternalInvoices.create(b.dataset.gqCreateInvoice,open)});
 host.querySelectorAll('[data-gq-invoice]').forEach(b=>b.onclick=()=>run(b,()=>invoiceAccess()&&GamaInternalInvoices.view(b.dataset.gqInvoice,open)));
 host.querySelectorAll('[data-gq-external]').forEach(b=>b.onclick=()=>run(b,()=>invoiceAccess()&&GamaInternalInvoices.link(b.dataset.gqExternal,open)));
 host.querySelectorAll('[data-gq-invoice-order]').forEach(b=>b.onclick=()=>run(b,()=>invoiceAccess()&&GamaSales.openOrder(b.dataset.gqInvoiceOrder)));
}
async function open(){if(!window.gamaAccessAllowed?.('quotes'))return;const host=shell('quotes',client()?'Mis presupuestos':'Presupuestos y facturas','Revisa las condiciones, valida y sigue tu pedido.');host.textContent='Cargando…';const token=++version;try{await window.GamaCloudReady;const a=await rows('invoices',{order:'created_at',ascending:false,range:[page*20,page*20+20]}),more=a.length>20;a.splice(20);const bundle=await invoiceList(a);if(token!==version)return;host.innerHTML=`<div class="gqCard"><div class="gqTools">${client()?'<button class="secondary" id="gfClientOptions" data-gi=53321f69380b>Opciones de entrega</button>':'<button class="secondary" id="gqInvoices" data-gi-live data-gi=36842cc2f911>Facturas y cobros</button><button class="primary" id="gqNew" data-gi=080a5b7caa91>Nuevo presupuesto</button>'}<button class="secondary" id="gqRefresh" data-gi=fe5f6628c7b5>Actualizar</button>${client()?'':'<button class="secondary" id="gqLegacy" data-gi=92917c6126df>Formulario y archivo anteriores</button>'}</div><div class="gqScroll"><table><thead><tr><th data-gi=f7c9c2d9d560>Presupuesto</th><th data-gi=f851d9a83ab0>Cliente</th><th data-gi=98e5acddb6c4>Estado</th><th data-gi=9a6608c1ae2a>Vigencia</th><th data-gi=c9b3c38247f7>Total</th><th></th></tr></thead><tbody>${a.map(q=>`<tr><td>${esc(q.invoice_number||'Archivo '+q.archive_number)}</td><td>${esc(q.quote_details?.client||'Documento anterior')}</td><td><span class="gqBadge">${label(state(q))}</span></td><td>${esc(q.quote_valid_until||'—')}</td><td>${money(q.total)}</td><td><button class="secondary" data-gq-open="${esc(q.id)}" data-gi=20ab386d12d9>Ver</button></td></tr>${invoiceRows(q,bundle)}`).join('')}</tbody></table></div>${a.length?'':'<p data-gi=fccee2a3fc85>No hay presupuestos disponibles.</p>'}<div class="gqTools"><button class="secondary" id="gqPrev" ${page?'':'disabled'} data-gi=e4ce7c09d51e>Anterior</button><span data-gi-live>Página ${page+1}</span><button class="secondary" id="gqNext" ${more?'':'disabled'} data-gi=49683b71c6ac>Siguiente</button></div></div>`;$('gfClientOptions')?.addEventListener('click',()=>window.GamaFulfillment?.clientOptions());$('gqInvoices')?.addEventListener('click',()=>window.GamaSales.open('invoices'));$('gqNew')?.addEventListener('click',()=>edit());$('gqLegacy')?.addEventListener('click',()=>window.showTab('billing'));$('gqRefresh').onclick=open;$('gqPrev').onclick=()=>{page--;open()};$('gqNext').onclick=()=>{page++;open()};host.querySelectorAll('[data-gq-open]').forEach(b=>b.onclick=()=>view(b.dataset.gqOpen));bindInvoiceRows(host)}catch(e){fail(host,e)}}
async function documentData(id){const a=await rows('invoices',{eq:{id},limit:1});if(!a[0])throw Error('QUOTE_NOT_FOUND');const q=a[0];q.lines=await rows('invoice_lines',{eq:{invoice_id:id},order:'id'});if(!q.quote_state){const cs=await rows('customers',{eq:{id:q.customer_id},limit:1}),c=cs[0]||{};let m={};try{m=JSON.parse((q.notes||'').replace(/^GAMA_META:/,''))}catch(_){}q.quote_details={seller:m.sellerName||'GAMA',sellerRuc:m.sellerRuc||'',client:c.name||'',clientId:c.identification||'',clientEmail:c.email||'',clientAddress:c.address||'',delivery_address:c.address||'',payment:m.payment||'',notes:'',customer_comment:q.quote_details?.customer_comment??m.customerComment};const ps=q.lines.length?await rows('products',{in:{id:q.lines.map(l=>l.product_id)},select:'id,name'}):[];q.lines.forEach(l=>{l.quote_description=ps.find(p=>p.id===l.product_id)?.name||'Producto'})}if(q.quote_details.customer_comment==null){const requests=await rows('customer_requests',{eq:{invoice_id:id},limit:1});q.quote_details.customer_comment=requests[0]?.notes||''}return q}
function paper(q){const d=q.quote_details;return `<div class="gqPaper"><div class="gqBrand"><div><img src="gama-logo.jpg" alt="GAMA"><p><b>${esc(d.seller)}</b><br>RUC: ${esc(d.sellerRuc||'—')}<br>${esc(d.sellerAddress||'')}</p></div><div><h2 data-gi=d684c0be2b1d>PRESUPUESTO</h2><b>${esc(q.invoice_number||q.archive_number)}</b><p><span data-gi=5964f4d099df>Fecha: </span>${esc(q.issue_date?.slice(0,10))}<br>Válido hasta: ${esc(q.quote_valid_until||'—')}<br>Versión: ${q.quote_revision||0}</p><span class="gqBadge">${label(state(q))}</span></div></div><div class="gqGrid"><div><b data-gi=362ab5aaa773>Preparado para</b><p>${esc(d.client)}<br>${esc(d.clientId)}<br>${esc(d.clientEmail)}<br>${esc(d.clientAddress)}</p></div><div><b data-gi=24d49b8597db>Entrega</b><p>${esc(d.delivery_address)}<br>${esc(d.delivery_terms||'')}</p></div></div><div class="gqScroll"><table><thead><tr><th data-gi=77b9238931ed>Producto</th><th data-gi=4805b9ed5d23>Cant.</th><th data-gi=2e4385b6057f>Precio</th><th data-gi=178503aa09d0>Dto.</th><th data-gi=ba6da46c5e1c>IVA</th><th data-gi=8c0f2cb34079>Subtotal</th></tr></thead><tbody>${q.lines.map(l=>`<tr><td>${esc(l.quote_description)}</td><td>${esc(l.quantity)}</td><td>${money(l.quote_list_price??l.unit_price)}</td><td>${esc(l.quote_discount||0)}%</td><td>${esc(l.tax_rate)}%</td><td>${money(Math.round(Number(l.quantity)*Number(l.unit_price)*100)/100)}</td></tr>`).join('')}</tbody></table></div><p style="text-align:right"><span data-gi=8cf83a44f28a>Subtotal: </span>${money(q.subtotal)} · IVA: ${money(q.tax)}</p><div class="gqTotal"><span data-gi=ab2882c86465>TOTAL </span>${money(q.total)}</div><p><b data-gi=e883f19c9bd9>Pago:</b> ${esc(d.payment||'—')}</p><p><b data-gi=fdf4c545de20>Condiciones:</b> ${esc(d.terms||'—')}</p>${d.customer_comment?`<p style="white-space:pre-wrap"><b data-gi-live data-gi=03169a11ba99>Comentario del cliente</b><br>${esc(d.customer_comment)}</p>`:''}<p>${esc(d.notes||'')}</p><p class="gqMuted" data-gi=40e465f455ef>Documento informativo. No constituye una factura.</p></div>`}
function pdfData(q){return {...q.quote_details,number:q.invoice_number||q.archive_number,dateLabel:q.issue_date?.slice(0,10),validUntil:q.quote_valid_until,revision:q.quote_revision,items:q.lines.map(l=>({name:l.quote_description,qty:l.quantity,price:l.unit_price,listPrice:l.quote_list_price??l.unit_price,discount:l.quote_discount||0,taxRate:l.tax_rate})),sub:q.subtotal,tax:q.tax,total:q.total}}
async function pdf(q){await window.GamaQuotePdf.logoReady;const blob=window.GamaQuotePdf.build(pdfData(q));const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Presupuesto-'+String(q.invoice_number||q.archive_number).replace(/[^\w-]/g,'_')+'.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
async function view(id){const host=$('quotes-main')||shell('quotes','Presupuestos y facturas','');host.textContent='Cargando…';try{const q=await documentData(id),st=state(q);host.innerHTML=`<div class="gqCard"><div class="gqTools"><button class="secondary" id="gqBack" data-gi=ab26ae7bca36>Volver</button><button class="secondary" id="gqPdf" data-gi=59e0b6ca6f89>Descargar PDF</button>${!client()?'<button class="secondary" id="gqEmail" data-gi=eba46265fdfb>Preparar correo</button>':''}${!client()&&st==='draft'?'<button class="primary" id="gqEdit" data-gi=c7090bcb74ba>Editar todos los campos</button>':''}${!client()&&q.quote_state==='draft'?'<button class="primary" id="gqSend" data-gi=b3d4750309b8>Enviar al cliente en la aplicación</button>':''}${!client()&&['sent','rejected'].includes(st)?'<button class="secondary" id="gqReopen" data-gi=4c1075a30f5a>Reabrir para modificar</button>':''}${!client()&&['draft','sent','rejected'].includes(st)?'<button class="secondary" id="gqCancel" data-gi=f7fb19797d82>Cancelar presupuesto</button>':''}</div>${paper(q)}<p id="gqMessage" class="gqError" role="status"></p>${st==='sent'?`<div class="gqConfirm"><h3>${client()?'Aceptar este presupuesto':'Registrar aceptación externa'}</h3><p data-gi=7b439df759a2>Al aceptar, se crea el pedido y se reservan las existencias disponibles. Las cantidades faltantes quedan pendientes de reposición.</p>${client()?'<label><input id="gqAgree" type="checkbox" style="width:auto" data-gi=300fa30005d1> He revisado y acepto los productos, importes y condiciones.</label>':'<div class="gqGrid"><label data-gi=c6ccca144c33>Medio de aceptación<select id="gqChannel"><option value="email" data-gi=ec64dc30a483>Correo electrónico</option><option value="phone" data-gi=f1186abd0b8b>Teléfono</option><option value="in_person" data-gi=09eee726e7cd>Presencial</option><option value="other" data-gi=0d5a52a92cb9>Otro</option></select></label><label data-gi=4bc61eb37238>Referencia del acuerdo<input id="gqReference" data-gi-placeholder=457eddd26d78 placeholder="Ej.: correo de María, 12/09/2026, asunto…" maxlength="2000"></label></div>'}<div class="gqTools"><button class="primary" id="gqAccept" data-gi-live>${client()?'Aceptar y confirmar pedido':'Confirmar aceptación del cliente'}</button>${client()?'<button class="secondary" id="gqReject" data-gi=2a0515602d31>Rechazar</button>':''}</div></div>`:''}${st==='accepted'?'<div class="gqConfirm">Presupuesto aceptado. El pedido y sus reservas están registrados.'+(!client()?'<div class="gqTools"><button class="secondary" id="gqOrder" data-gi=23cf4f554a03>Ver pedido y reservas</button><button class="primary" id="gqInternalInvoice" data-gi=d602f723f853>Crear / ver factura interna</button></div>':'<p data-gi=1ba191376ffc>Puedes consultar las expediciones y sus pruebas en Mis entregas.</p>')+'</div>':''}<div id="gqReservations"></div><div id="gqHistory"></div></div>`;
 $('gqBack').onclick=open;$('gqPdf').onclick=e=>run(e.target,()=>pdf(q));$('gqEmail')?.addEventListener('click',e=>run(e.target,()=>window.GamaQuotePdf.send({q:pdfData(q),email:q.quote_details.clientEmail,subject:'Presupuesto '+q.invoice_number,body:'Estimado/a '+q.quote_details.client+',\n\nAdjuntamos el presupuesto '+q.invoice_number+' por '+money(q.total)+'.\nPuede revisarlo y aceptarlo en GAMA, en Presupuestos: '+location.origin+location.pathname+'\n\n'+q.quote_details.seller,filename:'Presupuesto-'+String(q.invoice_number).replace(/[^\w-]/g,'_')+'.pdf'})));$('gqEdit')?.addEventListener('click',()=>edit(q));
 for(const [btn,a] of [['gqSend','send'],['gqReopen','reopen'],['gqCancel','cancel'],['gqReject','reject']])$(btn)?.addEventListener('click',e=>run(e.target,async()=>{if(a==='reopen'&&!confirm('La versión enviada dejará de estar disponible para aceptar. ¿Reabrir?'))return;if(['cancel','reject'].includes(a)&&!confirm('¿Confirmar esta acción?'))return;await action(a,{id:q.id,revision:q.quote_revision});await view(id)}));
 $('gqAccept')?.addEventListener('click',e=>run(e.target,async()=>{if(client()&&!$('gqAgree').checked)throw Error('Confirma que has revisado las condiciones.');await action('accept',{id:q.id,revision:q.quote_revision,channel:$('gqChannel')?.value,reference:$('gqReference')?.value});await view(id)}));
 $('gqInternalInvoice')?.addEventListener('click',()=>window.GamaInternalInvoices.create(id,()=>view(id)));
 $('gqOrder')?.addEventListener('click',e=>run(e.target,async()=>{const a=await rows('sales_orders',{eq:{source_quote_id:id},limit:1});if(a[0])window.GamaSales.openOrder(a[0].id)}));
 if(st==='accepted'){const rs=await rpc('gama_quote_reservations',{p_id:q.id});if($('gqReservations'))$('gqReservations').innerHTML='<h3 data-gi=7a68bac983b0>Estado de las cantidades</h3><div class="gqScroll"><table><thead><tr><th data-gi=77b9238931ed>Producto</th><th data-gi=9e9ea5774a2d>Pedido</th><th data-gi=16434c0b6242>Reservado</th><th data-gi=efa85ba37848>Expedido</th><th data-gi=df6ad8d35691>Pendiente de reposición</th></tr></thead><tbody>'+rs.map(l=>`<tr><td>${esc(l.description)}${l.order_status==='cancelled'?' · Pedido cancelado':''}</td><td>${l.quantity}</td><td>${l.reserved}</td><td>${l.shipped}</td><td>${l.order_status==='cancelled'?0:Math.max(0,l.quantity-l.reserved-l.shipped)}</td></tr>`).join('')+'</tbody></table></div>'}
 if(!client()){const ev=await rows('quote_events',{eq:{quote_id:id},order:'at',ascending:false,limit:50});if($('gqHistory'))$('gqHistory').innerHTML='<details><summary data-gi=8b7d4b3b3cfd>Historial de versiones y aceptación</summary>'+ev.map(e=>`<p>${esc(new Date(e.at).toLocaleString('es-EC'))} · v${e.revision} · ${esc({save:'Guardado',send:'Enviado',accept:'Aceptado',reject:'Rechazado',reopen:'Reabierto',cancel:'Cancelado'}[e.action]||e.action)}${e.detail?.channel?' · '+esc(e.detail.channel):''}${e.detail?.reference?' · '+esc(e.detail.reference):''}</p>`).join('')+'</details>'}
 }catch(e){fail(host,e)}}
async function all(t,select){const a=[];for(let offset=0;;offset+=500){const b=await rows(t,{select,order:'id',range:[offset,offset+499]});a.push(...b);if(b.length<500)return a}}
async function edit(q=null){if(client())return;const host=$('quotes-main');host.textContent='Cargando editor…';try{const [customers,products]=await Promise.all([all('customers','id,name,identification,email,address,category,active'),all('products','id,name,reference,sale_price,sale_price_b,tax_rate,active')]);const key=crypto.randomUUID(),d=q?.quote_details||{seller:$('sellerName')?.value||'GAMA',sellerRuc:$('sellerRuc')?.value||''};let lines=(q?.lines||[]).map(l=>({product_id:l.product_id,description:l.quote_description,quantity:Number(l.quantity),list_price:Number(l.quote_list_price??l.unit_price),discount:Number(l.quote_discount||0),tax_rate:Number(l.tax_rate)}));
 const field=(id,title,value='',type='text')=>`<label data-gi-live>${title}<input id="${id}" type="${type}" value="${esc(value)}" maxlength="500"></label>`;
 const fields=[['seller','Emisor'],['sellerRuc','RUC emisor'],['sellerAddress','Dirección del emisor'],['client','Nombre del cliente'],['clientId','Identificación del cliente'],['clientEmail','Correo del cliente'],['clientAddress','Dirección del cliente'],['delivery_address','Dirección de entrega'],['delivery_terms','Plazo / condiciones de entrega'],['payment','Forma de pago']];
 host.innerHTML=`<form id="gqForm" class="gqCard"><h2>${q?'Editar presupuesto':'Nuevo presupuesto'}</h2><p class="gqMuted" data-gi=6867869c11c3>Todos los valores propuestos se pueden modificar. Sustituye un producto o aplica un descuento antes de enviar.</p><div class="gqGrid"><label data-gi=f9899c6e66a7>Ficha cliente<select id="gqCustomer" required><option value="" data-gi=3c41f9546e61>Seleccionar…</option>${customers.filter(c=>c.active).map(c=>`<option value="${esc(c.id)}" ${c.id===q?.customer_id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label>${field('gqNumber','Número (automático si está vacío)',q?.invoice_number||'')}${field('gqDate','Fecha',q?.issue_date?.slice(0,10)||today(),'date')}${field('gqValid','Válido hasta',q?.quote_valid_until||new Date(Date.now()+30*864e5).toLocaleDateString('en-CA'),'date')}${fields.map(([k,t])=>field('gqd_'+k,t,d[k]||'')).join('')}</div><h3 data-gi=7cb3dd8438bc>Productos y oferta</h3><div id="gqLines"></div><button class="secondary" type="button" id="gqAdd" data-gi=f24e9be8c27d>Añadir producto</button><div id="gqTotals" class="gqTotal"></div><div class="gqGrid"><label data-gi=a8b46e93f208>Condiciones comerciales<textarea id="gqd_terms" maxlength="3000">${esc(d.terms||'')}</textarea></label><label data-gi-live data-gi=03169a11ba99>Comentario del cliente<textarea id="gqd_customer_comment" readonly>${esc(d.customer_comment||'')}</textarea></label><label data-gi=8ef60b6d94c0>Observaciones<textarea id="gqd_notes" maxlength="3000">${esc(d.notes||'')}</textarea></label></div><p class="gqError" id="gqMessage" role="status"></p><div class="gqTools"><button class="primary" type="submit" id="gqSave" data-gi=474b28f85eb2>Guardar borrador</button><button class="secondary" type="button" id="gqDiscard" data-gi=ab26ae7bca36>Volver</button></div></form>`;
 function totals(){let sub=0,tax=0;for(const l of lines){const net=Math.round(l.list_price*(1-l.discount/100)*10000)/10000,b=Math.round(l.quantity*net*100)/100;sub+=b;tax+=Math.round(b*l.tax_rate)/100}$('gqTotals').textContent='Total estimado: '+money(sub+tax)}
 function renderLines(){$('gqLines').innerHTML=lines.map((l,i)=>`<div class="gqLine" data-line="${i}"><label class="gqField" data-gi=77b9238931ed>Producto<select data-k="product_id" required><option value="" data-gi=3c41f9546e61>Seleccionar…</option>${products.filter(p=>p.active||p.id===l.product_id).map(p=>`<option value="${esc(p.id)}" ${p.id===l.product_id?'selected':''}>${esc(p.name)} · ${esc(p.reference)}</option>`).join('')}</select></label><label class="gqField" data-gi=a275b0991123>Descripción en el presupuesto<input data-k="description" value="${esc(l.description||'')}" maxlength="500" required></label><div class="gqGrid">${[['quantity','Cantidad','0.001','0.001'],['list_price','Precio sin IVA','0','0.0001'],['discount','Descuento (%)','0','0.01'],['tax_rate','IVA (%)','0','0.0001']].map(([k,t,min,step])=>`<label data-gi-live>${t}<input type="number" data-k="${k}" value="${l[k]}" min="${min}" ${['discount','tax_rate'].includes(k)?'max="100"':''} step="${step}" required></label>`).join('')}</div><button class="secondary" type="button" data-remove="${i}" data-gi=ff9069996f4a>Quitar producto</button></div>`).join('');$('gqLines').querySelectorAll('[data-k]').forEach(el=>el.onchange=async()=>{const l=lines[Number(el.closest('[data-line]').dataset.line)],k=el.dataset.k;l[k]=['product_id','description'].includes(k)?el.value:Number(el.value);if(k==='product_id'){const p=products.find(p=>p.id===el.value),c=customers.find(c=>c.id===$('gqCustomer').value);l.description=p?.name||'';l.list_price=Number(c?.category==='B'&&p?.sale_price_b!=null?p.sale_price_b:p?.sale_price||0);l.tax_rate=Number(p?.tax_rate||0);l.discount=0;if(c?.category==='C'&&p){$('gqSave').disabled=true;el.disabled=true;try{const a=await rows('customer_special_prices',{eq:{customer_id:c.id,product_id:p.id},limit:1});if(a[0])l.list_price=Number(a[0].unit_price)}catch(e){$('gqMessage').textContent='No se pudo cargar la tarifa. Revisa el precio: '+message(e)}finally{$('gqSave').disabled=false;el.disabled=false}}renderLines()}totals()});$('gqLines').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{lines.splice(Number(b.dataset.remove),1);renderLines();totals()})}
 $('gqCustomer').onchange=()=>{const c=customers.find(c=>c.id===$('gqCustomer').value);if(!c)return;for(const [k,v] of Object.entries({client:c.name,clientId:c.identification,clientEmail:c.email,clientAddress:c.address,delivery_address:c.address}))$('gqd_'+k).value=v||''};
 $('gqAdd').onclick=()=>{lines.push({product_id:'',description:'',quantity:1,list_price:0,discount:0,tax_rate:0});renderLines();totals()};$('gqDiscard').onclick=()=>q?view(q.id):open();
 $('gqForm').onsubmit=e=>{e.preventDefault();run($('gqSave'),async()=>{const details=Object.fromEntries([...fields.map(x=>x[0]),'terms','notes','customer_comment'].map(k=>[k,$('gqd_'+k).value]));const result=await action('save',{id:q?.id,revision:q?.quote_revision||0,request_key:key,customer_id:$('gqCustomer').value,number:$('gqNumber').value,issue_date:$('gqDate').value,valid_until:$('gqValid').value,details,lines});await view(result.id)})};renderLines();totals();
 }catch(e){fail(host,e)}}
async function deliveries(id=null){if(!window.gamaAccessAllowed?.('client-deliveries'))return;const host=shell('client-deliveries',client()?'Mis entregas':'Entregas de clientes','Estado de entrega, productos y pruebas de recepción.');host.textContent='Cargando…';try{await window.GamaCloudReady;const a=await rpc('gama_client_deliveries',{p_id:id,p_offset:id?0:deliveryPage*20});if(id){const d=a[0];if(!d)throw Error('Entrega no disponible para tu cuenta.');const safe=v=>/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=\s]+$/.test(v||'');host.innerHTML=`<div class="gqCard"><button class="secondary" id="gqDeliveryBack" data-gi=ab26ae7bca36>Volver</button><h2>${esc(d.shipment_number||'Entrega')}</h2><p>${esc(d.customer)} · ${esc(d.order_number||'')}</p><span class="gqBadge">${esc(d.status)}</span><p>${esc(d.date)} · ${esc(d.time_window||'')}<br>${esc(d.address)}</p>${d.lines.map(l=>`<p>${esc(l.description)} × ${esc(l.quantity)}</p>`).join('')}<h3 data-gi=a65bd00b186f>Prueba de entrega</h3>${d.proof?`<p>Registrada: ${esc(new Date(d.proof.captured_at).toLocaleString('es-EC'))}</p><div class="gqProof">${[['photo','Fotografía'],['signature','Firma de recepción']].map(([k,t])=>safe(d.proof[k])?`<h4>${t}</h4><img src="${esc(d.proof[k])}" alt="${t}"><a download="${k}-${d.id}.${d.proof[k].includes('image/png')?'png':'jpg'}" href="${esc(d.proof[k])}">Descargar ${t.toLowerCase()}</a>`:'').join('')}</div>`:'<p data-gi=f5f592de8636>Todavía no hay una prueba de entrega registrada.</p>'}</div>`;$('gqDeliveryBack').onclick=()=>deliveries();return}const more=a.length>20;a.splice(20);host.innerHTML=`<div class="gqCard"><button class="secondary" id="gqDeliveryRefresh" data-gi=fe5f6628c7b5>Actualizar</button>${a.map(d=>`<div class="gqLine"><b>${esc(d.shipment_number||'Entrega')} · ${esc(d.customer)}</b><p>${esc(d.date)} · ${esc(d.status)}<br>${esc(d.address)}</p><button class="secondary" data-delivery="${esc(d.id)}" data-gi-live>${d.has_proof?'Ver entrega y prueba':'Ver entrega'}</button></div>`).join('')||'<p data-gi=691945def937>No hay entregas asociadas a tu cuenta.</p>'}<div class="gqTools"><button class="secondary" id="gqDeliveryPrev" ${deliveryPage?'':'disabled'} data-gi=e4ce7c09d51e>Anterior</button><span data-gi-live>Página ${deliveryPage+1}</span><button class="secondary" id="gqDeliveryNext" ${more?'':'disabled'} data-gi=49683b71c6ac>Siguiente</button></div></div>`;$('gqDeliveryRefresh').onclick=()=>deliveries();$('gqDeliveryPrev').onclick=()=>{deliveryPage--;deliveries()};$('gqDeliveryNext').onclick=()=>{deliveryPage++;deliveries()};host.querySelectorAll('[data-delivery]').forEach(b=>b.onclick=()=>deliveries(b.dataset.delivery))}catch(e){fail(host,e)}}
async function remind(id){if(client()||!window.gamaAccessAllowed?.('quotes'))throw Error('Acceso no permitido.');const q=await documentData(id);if(q.quote_state!=='sent'||!q.quote_sent_at||Date.parse(q.quote_sent_at)>=Date.now()-7*86400000)throw Error('El presupuesto ya no requiere este recordatorio.');await open();await view(id);return window.GamaQuotePdf.send({q:pdfData(q),email:q.quote_details.clientEmail,subject:'Seguimiento del presupuesto '+q.invoice_number,body:'Estimado/a '+q.quote_details.client+',\n\n¿Ha podido revisar nuestro presupuesto '+q.invoice_number+' por '+money(q.total)+'? Quedamos atentos a su respuesta y disponibles para resolver sus dudas.\nPuede consultarlo en GAMA: '+location.origin+location.pathname+'\n\n'+q.quote_details.seller,filename:'Presupuesto-'+String(q.invoice_number).replace(/[^\w-]/g,'_')+'.pdf'})}
window.GamaQuotes={open,view,edit,deliveries,pdfData,remind};
})();
