/* Versioned quotes and a customer-scoped delivery portal. */
(function(){
'use strict';
const $=id=>document.getElementById(id), C=()=>window.GamaCloud;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v||0).toLocaleString('es-EC',{style:'currency',currency:'USD'});
const today=()=>new Date().toLocaleDateString('en-CA');
const role=()=>{try{return JSON.parse(localStorage.getItem('gama_session_v1')||'{}').role}catch(_){return ''}};
const client=()=>role()==='client';
const state=q=>q.quote_state||'draft';
const label=s=>({draft:'Borrador',sent:'Enviado',accepted:'Aceptado',rejected:'Rechazado',cancelled:'Cancelado'}[s]||s);
let page=0,deliveryPage=0,version=0;
const errors={QUOTE_CHANGED:'El presupuesto ha cambiado. Actualiza y revisa la nueva versión antes de continuar.',QUOTE_LOCKED:'Este presupuesto ya no permite esta acción.',QUOTE_EXPIRED:'El presupuesto ha vencido. Solicita una actualización.',QUOTE_HAS_ORDER:'Este presupuesto ya tiene un pedido. Consúltalo en Pedidos de venta.',QUOTE_NOT_FOUND:'Presupuesto no disponible para tu cuenta.',ROLE_NOT_ALLOWED:'Tu perfil no permite esta acción.',DETAILS_REQUIRED:'Completa emisor, cliente y dirección de entrega.',VALIDITY_REQUIRED:'Revisa la fecha y la vigencia.',DESCRIPTION_REQUIRED:'Cada producto necesita una descripción.',DUPLICATE_PRODUCT:'Agrupa las cantidades del mismo producto en una sola línea.',ACCEPTANCE_REFERENCE_REQUIRED:'Indica el medio y la referencia del acuerdo del cliente.',PRODUCT_NOT_FOUND:'Un producto ya no está disponible. Reabre el presupuesto y sustitúyelo.',INVALID_LINES:'Revisa productos, cantidades, precios, descuentos e impuestos.',CUSTOMER_REQUIRED:'Selecciona un cliente activo.',USE_QUOTE_ACTION:'Gestiona este documento desde Presupuestos.'};
const message=e=>Object.keys(errors).find(k=>String(e?.message||e).includes(k))?errors[Object.keys(errors).find(k=>String(e?.message||e).includes(k))]:String(e?.message||e);
async function rows(t,o={}){const r=await C().list(t,o);if(r.error)throw r.error;return r.data||[]}
async function rpc(name,data){const r=await (await C().db()).rpc(name,data);if(r.error)throw r.error;return r.data}
const action=(a,d)=>rpc('gama_quote_action',{p_action:a,p_data:d});
function css(){if($('gqCss'))return;const el=document.createElement('style');el.id='gqCss';el.textContent=`.gqCard{background:#fff;border:1px solid #dce5e9;border-radius:16px;padding:22px;margin:16px 0;color:#18324a}.gqTools{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:15px 0}.gqGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.gqGrid label,.gqField{display:flex;flex-direction:column;gap:5px;font-size:12px;font-weight:700}.gqCard input,.gqCard select,.gqCard textarea{width:100%;box-sizing:border-box;min-width:0;padding:10px;border:1px solid #cbd8df;border-radius:8px;font:inherit}.gqCard textarea{min-height:72px}.gqScroll{overflow:auto}.gqCard table{width:100%;border-collapse:collapse}.gqCard th,.gqCard td{padding:11px 8px;text-align:left;border-bottom:1px solid #e5edef}.gqBadge{display:inline-block;background:#e6f3f4;color:#075b65;border-radius:20px;padding:5px 10px;font-size:12px;font-weight:700}.gqError{color:#ad2828}.gqMuted{color:#647985;font-size:13px}.gqPaper{max-width:850px;margin:auto}.gqBrand{display:flex;justify-content:space-between;gap:20px;border-bottom:4px solid #087c8b;padding-bottom:22px;margin-bottom:22px}.gqBrand img{width:120px;height:70px;object-fit:contain}.gqBrand h2{letter-spacing:2px;margin:0 0 8px}.gqTotal{text-align:right;font-size:23px;color:#087c8b;font-weight:800;margin:20px 0}.gqProof img{display:block;max-width:100%;max-height:480px;object-fit:contain;background:#f4f7f8;margin:12px 0}.gqLine{border:1px solid #dce5e9;padding:15px;border-radius:12px;margin:12px 0}.gqLine .gqGrid{grid-template-columns:repeat(4,minmax(0,1fr))}.gqConfirm{background:#eff7f8;border-radius:12px;padding:18px;margin:20px 0}.gqPaper p{white-space:pre-wrap;overflow-wrap:anywhere}@media(max-width:650px){.gqCard{padding:14px}.gqGrid,.gqLine .gqGrid{grid-template-columns:1fr 1fr}.gqBrand{flex-direction:column}.gqTools button{flex:1}.gqCard th,.gqCard td{padding:8px;font-size:12px}}`;document.head.appendChild(el)}
function shell(id,title,lead){css();let s=$(id);if(!s){s=document.createElement('section');s.id=id;(document.querySelector('.wrap')||document.body).appendChild(s)}s.innerHTML=window.GamaUI.header({title,lead})+`<div id="${id}-main" aria-live="polite"></div>`;window.GamaUI.bindBack(s);window.showTab?.(id);return $(id+'-main')}
function fail(host,e){host.innerHTML=`<div class="gqCard gqError">${esc(message(e))}<div class="gqTools"><button class="secondary" id="gqRetry">Volver a intentar</button></div></div>`;$('gqRetry').onclick=()=>host.id.startsWith('client-deliveries')?deliveries():open()}
async function run(button,fn){button.disabled=true;try{await fn()}catch(e){const m=$('gqMessage');if(m)m.textContent=message(e);else alert(message(e))}finally{button.disabled=false}}
async function open(){if(!window.gamaAccessAllowed?.('quotes'))return;const host=shell('quotes',client()?'Mis presupuestos':'Presupuestos','Revisa las condiciones, valida y sigue tu pedido.');host.textContent='Cargando…';const token=++version;try{await window.GamaCloudReady;const a=await rows('invoices',{order:'created_at',ascending:false,range:[page*20,page*20+20]}),more=a.length>20;a.splice(20);if(token!==version)return;host.innerHTML=`<div class="gqCard"><div class="gqTools">${client()?'<button class="secondary" id="gfClientOptions">Opciones de entrega</button>':'<button class="primary" id="gqNew">Nuevo presupuesto</button>'}<button class="secondary" id="gqRefresh">Actualizar</button>${client()?'':'<button class="secondary" id="gqLegacy">Formulario y archivo anteriores</button>'}</div><div class="gqScroll"><table><thead><tr><th>Presupuesto</th><th>Cliente</th><th>Estado</th><th>Vigencia</th><th>Total</th><th></th></tr></thead><tbody>${a.map(q=>`<tr><td>${esc(q.invoice_number||'Archivo '+q.archive_number)}</td><td>${esc(q.quote_details?.client||'Documento anterior')}</td><td><span class="gqBadge">${label(state(q))}</span></td><td>${esc(q.quote_valid_until||'—')}</td><td>${money(q.total)}</td><td><button class="secondary" data-gq-open="${esc(q.id)}">Ver</button></td></tr>`).join('')}</tbody></table></div>${a.length?'':'<p>No hay presupuestos disponibles.</p>'}<div class="gqTools"><button class="secondary" id="gqPrev" ${page?'':'disabled'}>Anterior</button><span>Página ${page+1}</span><button class="secondary" id="gqNext" ${more?'':'disabled'}>Siguiente</button></div></div>`;$('gfClientOptions')?.addEventListener('click',()=>window.GamaFulfillment?.clientOptions());$('gqNew')?.addEventListener('click',()=>edit());$('gqLegacy')?.addEventListener('click',()=>window.showTab('billing'));$('gqRefresh').onclick=open;$('gqPrev').onclick=()=>{page--;open()};$('gqNext').onclick=()=>{page++;open()};host.querySelectorAll('[data-gq-open]').forEach(b=>b.onclick=()=>view(b.dataset.gqOpen))}catch(e){fail(host,e)}}
async function documentData(id){const a=await rows('invoices',{eq:{id},limit:1});if(!a[0])throw Error('QUOTE_NOT_FOUND');const q=a[0];q.lines=await rows('invoice_lines',{eq:{invoice_id:id},order:'id'});if(!q.quote_state){const cs=await rows('customers',{eq:{id:q.customer_id},limit:1}),c=cs[0]||{};let m={};try{m=JSON.parse((q.notes||'').replace(/^GAMA_META:/,''))}catch(_){}q.quote_details={seller:m.sellerName||'GAMA',sellerRuc:m.sellerRuc||'',client:c.name||'',clientId:c.identification||'',clientEmail:c.email||'',clientAddress:c.address||'',delivery_address:c.address||'',payment:m.payment||'',notes:''};const ps=q.lines.length?await rows('products',{in:{id:q.lines.map(l=>l.product_id)},select:'id,name'}):[];q.lines.forEach(l=>{l.quote_description=ps.find(p=>p.id===l.product_id)?.name||'Producto'})}return q}
function paper(q){const d=q.quote_details;return `<div class="gqPaper"><div class="gqBrand"><div><img src="gama-logo.jpg" alt="GAMA"><p><b>${esc(d.seller)}</b><br>RUC: ${esc(d.sellerRuc||'—')}<br>${esc(d.sellerAddress||'')}</p></div><div><h2>PRESUPUESTO</h2><b>${esc(q.invoice_number||q.archive_number)}</b><p>Fecha: ${esc(q.issue_date?.slice(0,10))}<br>Válido hasta: ${esc(q.quote_valid_until||'—')}<br>Versión: ${q.quote_revision||0}</p><span class="gqBadge">${label(state(q))}</span></div></div><div class="gqGrid"><div><b>Preparado para</b><p>${esc(d.client)}<br>${esc(d.clientId)}<br>${esc(d.clientEmail)}<br>${esc(d.clientAddress)}</p></div><div><b>Entrega</b><p>${esc(d.delivery_address)}<br>${esc(d.delivery_terms||'')}</p></div></div><div class="gqScroll"><table><thead><tr><th>Producto</th><th>Cant.</th><th>Precio</th><th>Dto.</th><th>IVA</th><th>Subtotal</th></tr></thead><tbody>${q.lines.map(l=>`<tr><td>${esc(l.quote_description)}</td><td>${esc(l.quantity)}</td><td>${money(l.quote_list_price??l.unit_price)}</td><td>${esc(l.quote_discount||0)}%</td><td>${esc(l.tax_rate)}%</td><td>${money(Math.round(Number(l.quantity)*Number(l.unit_price)*100)/100)}</td></tr>`).join('')}</tbody></table></div><p style="text-align:right">Subtotal: ${money(q.subtotal)} · IVA: ${money(q.tax)}</p><div class="gqTotal">TOTAL ${money(q.total)}</div><p><b>Pago:</b> ${esc(d.payment||'—')}</p><p><b>Condiciones:</b> ${esc(d.terms||'—')}</p><p>${esc(d.notes||'')}</p><p class="gqMuted">Documento informativo. No constituye una factura.</p></div>`}
function pdfData(q){return {...q.quote_details,number:q.invoice_number||q.archive_number,dateLabel:q.issue_date?.slice(0,10),validUntil:q.quote_valid_until,revision:q.quote_revision,items:q.lines.map(l=>({name:l.quote_description,qty:l.quantity,price:l.unit_price,listPrice:l.quote_list_price??l.unit_price,discount:l.quote_discount||0,taxRate:l.tax_rate})),sub:q.subtotal,tax:q.tax,total:q.total}}
async function pdf(q){await window.GamaQuotePdf.logoReady;const blob=window.GamaQuotePdf.build(pdfData(q));const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Presupuesto-'+String(q.invoice_number||q.archive_number).replace(/[^\w-]/g,'_')+'.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
async function view(id){const host=$('quotes-main')||shell('quotes','Presupuestos','');host.textContent='Cargando…';try{const q=await documentData(id),st=state(q);host.innerHTML=`<div class="gqCard"><div class="gqTools"><button class="secondary" id="gqBack">Volver</button><button class="secondary" id="gqPdf">Descargar PDF</button>${!client()?'<button class="secondary" id="gqEmail">Preparar correo</button>':''}${!client()&&st==='draft'?'<button class="primary" id="gqEdit">Editar todos los campos</button>':''}${!client()&&q.quote_state==='draft'?'<button class="primary" id="gqSend">Enviar al cliente en la aplicación</button>':''}${!client()&&['sent','rejected'].includes(st)?'<button class="secondary" id="gqReopen">Reabrir para modificar</button>':''}${!client()&&['draft','sent','rejected'].includes(st)?'<button class="secondary" id="gqCancel">Cancelar presupuesto</button>':''}</div>${paper(q)}<p id="gqMessage" class="gqError" role="status"></p>${st==='sent'?`<div class="gqConfirm"><h3>${client()?'Aceptar este presupuesto':'Registrar aceptación externa'}</h3><p>Al aceptar, se crea el pedido y se reservan las existencias disponibles. Las cantidades faltantes quedan pendientes de reposición.</p>${client()?'<label><input id="gqAgree" type="checkbox" style="width:auto"> He revisado y acepto los productos, importes y condiciones.</label>':'<div class="gqGrid"><label>Medio de aceptación<select id="gqChannel"><option value="email">Correo electrónico</option><option value="phone">Teléfono</option><option value="in_person">Presencial</option><option value="other">Otro</option></select></label><label>Referencia del acuerdo<input id="gqReference" placeholder="Ej.: correo de María, 12/09/2026, asunto…" maxlength="2000"></label></div>'}<div class="gqTools"><button class="primary" id="gqAccept">${client()?'Aceptar y confirmar pedido':'Confirmar aceptación del cliente'}</button>${client()?'<button class="secondary" id="gqReject">Rechazar</button>':''}</div></div>`:''}${st==='accepted'?'<div class="gqConfirm">Presupuesto aceptado. El pedido y sus reservas están registrados.'+(!client()?'<div class="gqTools"><button class="secondary" id="gqOrder">Ver pedido y reservas</button><button class="primary" id="gqInternalInvoice">Crear / ver factura interna</button></div>':'<p>Puedes consultar las expediciones y sus pruebas en Mis entregas.</p>')+'</div>':''}<div id="gqReservations"></div><div id="gqHistory"></div></div>`;
 $('gqBack').onclick=open;$('gqPdf').onclick=e=>run(e.target,()=>pdf(q));$('gqEmail')?.addEventListener('click',e=>run(e.target,()=>window.GamaQuotePdf.send({q:pdfData(q),email:q.quote_details.clientEmail,subject:'Presupuesto '+q.invoice_number,body:'Estimado/a '+q.quote_details.client+',\n\nAdjuntamos el presupuesto '+q.invoice_number+' por '+money(q.total)+'.\nPuede revisarlo y aceptarlo en GAMA, en Presupuestos: '+location.origin+location.pathname+'\n\n'+q.quote_details.seller,filename:'Presupuesto-'+String(q.invoice_number).replace(/[^\w-]/g,'_')+'.pdf'})));$('gqEdit')?.addEventListener('click',()=>edit(q));
 for(const [btn,a] of [['gqSend','send'],['gqReopen','reopen'],['gqCancel','cancel'],['gqReject','reject']])$(btn)?.addEventListener('click',e=>run(e.target,async()=>{if(a==='reopen'&&!confirm('La versión enviada dejará de estar disponible para aceptar. ¿Reabrir?'))return;if(['cancel','reject'].includes(a)&&!confirm('¿Confirmar esta acción?'))return;await action(a,{id:q.id,revision:q.quote_revision});await view(id)}));
 $('gqAccept')?.addEventListener('click',e=>run(e.target,async()=>{if(client()&&!$('gqAgree').checked)throw Error('Confirma que has revisado las condiciones.');await action('accept',{id:q.id,revision:q.quote_revision,channel:$('gqChannel')?.value,reference:$('gqReference')?.value});await view(id)}));
 $('gqInternalInvoice')?.addEventListener('click',()=>window.GamaInternalInvoices.create(id));
 $('gqOrder')?.addEventListener('click',e=>run(e.target,async()=>{const a=await rows('sales_orders',{eq:{source_quote_id:id},limit:1});if(a[0])window.GamaSales.openOrder(a[0].id)}));
 if(st==='accepted'){const rs=await rpc('gama_quote_reservations',{p_id:q.id});if($('gqReservations'))$('gqReservations').innerHTML='<h3>Estado de las cantidades</h3><div class="gqScroll"><table><thead><tr><th>Producto</th><th>Pedido</th><th>Reservado</th><th>Expedido</th><th>Pendiente de reposición</th></tr></thead><tbody>'+rs.map(l=>`<tr><td>${esc(l.description)}${l.order_status==='cancelled'?' · Pedido cancelado':''}</td><td>${l.quantity}</td><td>${l.reserved}</td><td>${l.shipped}</td><td>${l.order_status==='cancelled'?0:Math.max(0,l.quantity-l.reserved-l.shipped)}</td></tr>`).join('')+'</tbody></table></div>'}
 if(!client()){const ev=await rows('quote_events',{eq:{quote_id:id},order:'at',ascending:false,limit:50});if($('gqHistory'))$('gqHistory').innerHTML='<details><summary>Historial de versiones y aceptación</summary>'+ev.map(e=>`<p>${esc(new Date(e.at).toLocaleString('es-EC'))} · v${e.revision} · ${esc({save:'Guardado',send:'Enviado',accept:'Aceptado',reject:'Rechazado',reopen:'Reabierto',cancel:'Cancelado'}[e.action]||e.action)}${e.detail?.channel?' · '+esc(e.detail.channel):''}${e.detail?.reference?' · '+esc(e.detail.reference):''}</p>`).join('')+'</details>'}
 }catch(e){fail(host,e)}}
async function all(t,select){const a=[];for(let offset=0;;offset+=500){const b=await rows(t,{select,order:'id',range:[offset,offset+499]});a.push(...b);if(b.length<500)return a}}
async function edit(q=null){if(client())return;const host=$('quotes-main');host.textContent='Cargando editor…';try{const [customers,products]=await Promise.all([all('customers','id,name,identification,email,address,category,active'),all('products','id,name,reference,sale_price,sale_price_b,tax_rate,active')]);const key=crypto.randomUUID(),d=q?.quote_details||{seller:$('sellerName')?.value||'GAMA',sellerRuc:$('sellerRuc')?.value||''};let lines=(q?.lines||[]).map(l=>({product_id:l.product_id,description:l.quote_description,quantity:Number(l.quantity),list_price:Number(l.quote_list_price??l.unit_price),discount:Number(l.quote_discount||0),tax_rate:Number(l.tax_rate)}));
 const field=(id,title,value='',type='text')=>`<label>${title}<input id="${id}" type="${type}" value="${esc(value)}" maxlength="500"></label>`;
 const fields=[['seller','Emisor'],['sellerRuc','RUC emisor'],['sellerAddress','Dirección del emisor'],['client','Nombre del cliente'],['clientId','Identificación del cliente'],['clientEmail','Correo del cliente'],['clientAddress','Dirección del cliente'],['delivery_address','Dirección de entrega'],['delivery_terms','Plazo / condiciones de entrega'],['payment','Forma de pago']];
 host.innerHTML=`<form id="gqForm" class="gqCard"><h2>${q?'Editar presupuesto':'Nuevo presupuesto'}</h2><p class="gqMuted">Todos los valores propuestos se pueden modificar. Sustituye un producto o aplica un descuento antes de enviar.</p><div class="gqGrid"><label>Ficha cliente<select id="gqCustomer" required><option value="">Seleccionar…</option>${customers.filter(c=>c.active).map(c=>`<option value="${esc(c.id)}" ${c.id===q?.customer_id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label>${field('gqNumber','Número (automático si está vacío)',q?.invoice_number||'')}${field('gqDate','Fecha',q?.issue_date?.slice(0,10)||today(),'date')}${field('gqValid','Válido hasta',q?.quote_valid_until||new Date(Date.now()+30*864e5).toLocaleDateString('en-CA'),'date')}${fields.map(([k,t])=>field('gqd_'+k,t,d[k]||'')).join('')}</div><h3>Productos y oferta</h3><div id="gqLines"></div><button class="secondary" type="button" id="gqAdd">Añadir producto</button><div id="gqTotals" class="gqTotal"></div><div class="gqGrid"><label>Condiciones comerciales<textarea id="gqd_terms" maxlength="3000">${esc(d.terms||'')}</textarea></label><label>Observaciones<textarea id="gqd_notes" maxlength="3000">${esc(d.notes||'')}</textarea></label></div><p class="gqError" id="gqMessage" role="status"></p><div class="gqTools"><button class="primary" type="submit" id="gqSave">Guardar borrador</button><button class="secondary" type="button" id="gqDiscard">Volver</button></div></form>`;
 function totals(){let sub=0,tax=0;for(const l of lines){const net=Math.round(l.list_price*(1-l.discount/100)*10000)/10000,b=Math.round(l.quantity*net*100)/100;sub+=b;tax+=Math.round(b*l.tax_rate)/100}$('gqTotals').textContent='Total estimado: '+money(sub+tax)}
 function renderLines(){$('gqLines').innerHTML=lines.map((l,i)=>`<div class="gqLine" data-line="${i}"><label class="gqField">Producto<select data-k="product_id" required><option value="">Seleccionar…</option>${products.filter(p=>p.active||p.id===l.product_id).map(p=>`<option value="${esc(p.id)}" ${p.id===l.product_id?'selected':''}>${esc(p.name)} · ${esc(p.reference)}</option>`).join('')}</select></label><label class="gqField">Descripción en el presupuesto<input data-k="description" value="${esc(l.description||'')}" maxlength="500" required></label><div class="gqGrid">${[['quantity','Cantidad','0.001','0.001'],['list_price','Precio sin IVA','0','0.0001'],['discount','Descuento (%)','0','0.01'],['tax_rate','IVA (%)','0','0.0001']].map(([k,t,min,step])=>`<label>${t}<input type="number" data-k="${k}" value="${l[k]}" min="${min}" ${['discount','tax_rate'].includes(k)?'max="100"':''} step="${step}" required></label>`).join('')}</div><button class="secondary" type="button" data-remove="${i}">Quitar producto</button></div>`).join('');$('gqLines').querySelectorAll('[data-k]').forEach(el=>el.onchange=async()=>{const l=lines[Number(el.closest('[data-line]').dataset.line)],k=el.dataset.k;l[k]=['product_id','description'].includes(k)?el.value:Number(el.value);if(k==='product_id'){const p=products.find(p=>p.id===el.value),c=customers.find(c=>c.id===$('gqCustomer').value);l.description=p?.name||'';l.list_price=Number(c?.category==='B'&&p?.sale_price_b!=null?p.sale_price_b:p?.sale_price||0);l.tax_rate=Number(p?.tax_rate||0);l.discount=0;if(c?.category==='C'&&p){$('gqSave').disabled=true;el.disabled=true;try{const a=await rows('customer_special_prices',{eq:{customer_id:c.id,product_id:p.id},limit:1});if(a[0])l.list_price=Number(a[0].unit_price)}catch(e){$('gqMessage').textContent='No se pudo cargar la tarifa. Revisa el precio: '+message(e)}finally{$('gqSave').disabled=false;el.disabled=false}}renderLines()}totals()});$('gqLines').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{lines.splice(Number(b.dataset.remove),1);renderLines();totals()})}
 $('gqCustomer').onchange=()=>{const c=customers.find(c=>c.id===$('gqCustomer').value);if(!c)return;for(const [k,v] of Object.entries({client:c.name,clientId:c.identification,clientEmail:c.email,clientAddress:c.address,delivery_address:c.address}))$('gqd_'+k).value=v||''};
 $('gqAdd').onclick=()=>{lines.push({product_id:'',description:'',quantity:1,list_price:0,discount:0,tax_rate:0});renderLines();totals()};$('gqDiscard').onclick=()=>q?view(q.id):open();
 $('gqForm').onsubmit=e=>{e.preventDefault();run($('gqSave'),async()=>{const details=Object.fromEntries([...fields.map(x=>x[0]),'terms','notes'].map(k=>[k,$('gqd_'+k).value]));const result=await action('save',{id:q?.id,revision:q?.quote_revision||0,request_key:key,customer_id:$('gqCustomer').value,number:$('gqNumber').value,issue_date:$('gqDate').value,valid_until:$('gqValid').value,details,lines});await view(result.id)})};renderLines();totals();
 }catch(e){fail(host,e)}}
async function deliveries(id=null){if(!window.gamaAccessAllowed?.('client-deliveries'))return;const host=shell('client-deliveries',client()?'Mis entregas':'Entregas de clientes','Estado de entrega, productos y pruebas de recepción.');host.textContent='Cargando…';try{await window.GamaCloudReady;const a=await rpc('gama_client_deliveries',{p_id:id,p_offset:id?0:deliveryPage*20});if(id){const d=a[0];if(!d)throw Error('Entrega no disponible para tu cuenta.');const safe=v=>/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=\s]+$/.test(v||'');host.innerHTML=`<div class="gqCard"><button class="secondary" id="gqDeliveryBack">Volver</button><h2>${esc(d.shipment_number||'Entrega')}</h2><p>${esc(d.customer)} · ${esc(d.order_number||'')}</p><span class="gqBadge">${esc(d.status)}</span><p>${esc(d.date)} · ${esc(d.time_window||'')}<br>${esc(d.address)}</p>${d.lines.map(l=>`<p>${esc(l.description)} × ${esc(l.quantity)}</p>`).join('')}<h3>Prueba de entrega</h3>${d.proof?`<p>Registrada: ${esc(new Date(d.proof.captured_at).toLocaleString('es-EC'))}</p><div class="gqProof">${[['photo','Fotografía'],['signature','Firma de recepción']].map(([k,t])=>safe(d.proof[k])?`<h4>${t}</h4><img src="${esc(d.proof[k])}" alt="${t}"><a download="${k}-${d.id}.${d.proof[k].includes('image/png')?'png':'jpg'}" href="${esc(d.proof[k])}">Descargar ${t.toLowerCase()}</a>`:'').join('')}</div>`:'<p>Todavía no hay una prueba de entrega registrada.</p>'}</div>`;$('gqDeliveryBack').onclick=()=>deliveries();return}const more=a.length>20;a.splice(20);host.innerHTML=`<div class="gqCard"><button class="secondary" id="gqDeliveryRefresh">Actualizar</button>${a.map(d=>`<div class="gqLine"><b>${esc(d.shipment_number||'Entrega')} · ${esc(d.customer)}</b><p>${esc(d.date)} · ${esc(d.status)}<br>${esc(d.address)}</p><button class="secondary" data-delivery="${esc(d.id)}">${d.has_proof?'Ver entrega y prueba':'Ver entrega'}</button></div>`).join('')||'<p>No hay entregas asociadas a tu cuenta.</p>'}<div class="gqTools"><button class="secondary" id="gqDeliveryPrev" ${deliveryPage?'':'disabled'}>Anterior</button><span>Página ${deliveryPage+1}</span><button class="secondary" id="gqDeliveryNext" ${more?'':'disabled'}>Siguiente</button></div></div>`;$('gqDeliveryRefresh').onclick=()=>deliveries();$('gqDeliveryPrev').onclick=()=>{deliveryPage--;deliveries()};$('gqDeliveryNext').onclick=()=>{deliveryPage++;deliveries()};host.querySelectorAll('[data-delivery]').forEach(b=>b.onclick=()=>deliveries(b.dataset.delivery))}catch(e){fail(host,e)}}
async function remind(id){if(client()||!window.gamaAccessAllowed?.('quotes'))throw Error('Acceso no permitido.');const q=await documentData(id);if(q.quote_state!=='sent'||!q.quote_sent_at||Date.parse(q.quote_sent_at)>=Date.now()-7*86400000)throw Error('El presupuesto ya no requiere este recordatorio.');await open();await view(id);return window.GamaQuotePdf.send({q:pdfData(q),email:q.quote_details.clientEmail,subject:'Seguimiento del presupuesto '+q.invoice_number,body:'Estimado/a '+q.quote_details.client+',\n\n¿Ha podido revisar nuestro presupuesto '+q.invoice_number+' por '+money(q.total)+'? Quedamos atentos a su respuesta y disponibles para resolver sus dudas.\nPuede consultarlo en GAMA: '+location.origin+location.pathname+'\n\n'+q.quote_details.seller,filename:'Presupuesto-'+String(q.invoice_number).replace(/[^\w-]/g,'_')+'.pdf'})}
window.GamaQuotes={open,view,edit,deliveries,pdfData,remind};
})();
