const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID:uuid,createHash}=require('node:crypto'),{restore}=require('../scripts/restore-schema.cjs');
test('Agent reports have immutable unique references, private PDF bytes, sorted pagination and fresh authorization',async()=>{
 const db=await restore(),admin=uuid(),staff=uuid(),client=uuid();const q=(s,p=[])=>db.query(s,p),one=async(s,p=[])=>Object.values((await q(s,p)).rows[0])[0],as=async id=>{await db.exec('reset role');await q("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated')},rpc=(a,d={})=>one('select gama_agent_reports($1,$2)',[a,d]);
 try{for(const [id,role] of [[admin,'administrador'],[staff,'comercial'],[client,'cliente']]){await q('insert into auth.users(id,email) values($1,$2)',[id,id+'@example.invalid']);await q('update profiles set active=true,role=$2 where id=$1',[id,role])}
 await as(admin);const file=Buffer.from('%PDF-1.7\n'+'isolated-fixture\n'.repeat(20)+'%%EOF'),hash=createHash('sha256').update(file).digest('hex'),data={report_key:'weekly:2026-09-28:2026-10-04',title:'Weekly analysis',report_date:'2026-10-05',period_from:'2026-09-28',period_to:'2026-10-04',filename:'weekly.pdf',content_base64:file.toString('base64'),sha256:hash};
 const r=await rpc('import',data);assert.equal(r.reference,'RCO-00000001');assert.equal((await rpc('import',data)).id,r.id);await assert.rejects(rpc('import',{...data,title:'Overwritten report'}),/REPORT_EDITION_CONFLICT/);await assert.rejects(rpc('import',{...data,sha256:'0'.repeat(64)}),/REPORT_HASH_MISMATCH/);await assert.rejects(rpc('import',{...data,content_base64:Buffer.alloc(200).toString('base64')}),/REPORT_PDF_REQUIRED/);
 for(let i=0;i<26;i++)await rpc('import',{...data,report_key:'historical:'+i,title:'Historical '+i,report_date:'2026-09-'+String(i+1).padStart(2,'0'),period_from:null,period_to:null,content_base64:Buffer.from(file.toString()+' '+i).toString('base64'),sha256:null});
 const list=await rpc('list');assert.equal(list.total,27);assert.equal(list.rows.length,25);assert.equal(list.rows[0].id,r.id);assert.equal(list.rows[0].content_base64,undefined);assert.equal(list.rows[0].sha256,undefined);assert.equal((await rpc('list',{offset:25})).rows.length,2);assert.equal((await rpc('list',{order:'asc'})).rows[0].report_date,'2026-09-01');
 const download=await rpc('download',{id:r.id});assert.equal(download.filename,'RCO-00000001.pdf');assert.deepEqual(Buffer.from(download.content_base64,'base64'),file);
 await assert.rejects(q('select * from private.agent_report_files'),/permission denied/);await assert.rejects(one('select private.agent_report_import_data($1)',[data]),/permission denied/);
 for(const id of [staff,client]){await as(id);await assert.rejects(rpc('list'),/ADMIN_REQUIRED/);await assert.rejects(rpc('download',{id:r.id}),/ADMIN_REQUIRED/)}
 await as(admin);await db.exec('reset role');await q('update profiles set active=false where id=$1',[admin]);await db.exec('set role authenticated');await assert.rejects(rpc('download',{id:r.id}),/ADMIN_REQUIRED/);
 }finally{await db.close()}
});
