import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createHandler,tools} from '../supabase/functions/coco-agent-mcp/handler.mjs';
const root='https://test-project.supabase.co',endpoint=root+'/functions/v1/coco-agent-mcp';
function fixture({user=true,result={items:[]},failure=false}={}){const calls=[];return {calls,handle:createHandler({env:k=>({SUPABASE_URL:root,SUPABASE_ANON_KEY:'public-test-key'}[k]),fetch:async(url,options)=>{calls.push({url,...options});if(url.endsWith('/auth/v1/user'))return Response.json(user?{id:randomUUID()}:{error:'invalid'}, {status:user?200:401});return Response.json(failure?{message:'ROLE_NOT_ALLOWED',details:'private information'}:result,{status:failure?403:200})}})}}
const request=(method,params={},options={})=>new Request(endpoint,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer isolated-test-token',...options.headers},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})});
test('OAuth metadata is public, stock tools are not',async()=>{const f=fixture();let r=await f.handle(new Request(endpoint+'/.well-known/oauth-protected-resource'));assert.equal(r.status,200);assert.equal((await r.json()).resource,endpoint);assert.equal(f.calls.length,0);r=await f.handle(new Request(endpoint,{method:'POST',body:'{}'}));assert.equal(r.status,401);assert.match(r.headers.get('WWW-Authenticate'),/resource_metadata/);assert.equal(f.calls.length,0)});
test('invalid user tokens cannot reach the database',async()=>{const f=fixture({user:false}),r=await f.handle(request('tools/list'));assert.equal(r.status,401);assert.equal(f.calls.length,1)});
test('MCP initialization and tools declare precise write behavior',async()=>{const f=fixture();const init=await(await f.handle(request('initialize'))).json();assert.equal(init.result.serverInfo.name,'agent-coco');const list=await(await f.handle(request('tools/list'))).json();assert.equal(list.result.tools.length,5);assert.ok(list.result.tools.every(t=>!('action' in t)));assert.equal(tools.find(t=>t.name==='coco_execute_stock').annotations.destructiveHint,true);assert.equal(tools.find(t=>t.name==='coco_prepare_stock').annotations.readOnlyHint,false)});
test('unknown tools, arbitrary SQL and extra fields are rejected',async()=>{for(const params of [{name:'execute_sql',arguments:{query:'delete from products'}},{name:'coco_get_stock',arguments:{product_id:randomUUID(),sql:'select 1'}},{name:'coco_get_stock',arguments:{product_id:'bad'}}]){const f=fixture(),r=await(await f.handle(request('tools/call',params))).json();assert.equal(r.error.code,-32602);assert.equal(f.calls.length,1)}});
test('prepare validates finite quantities and explicit identity',async()=>{for(const quantity of [-1,0,0.0001]){const f=fixture(),r=await(await f.handle(request('tools/call',{name:'coco_prepare_stock',arguments:{request_key:randomUUID(),product_id:randomUUID(),operation:'out',kind:'internal_use',reason:'internal use',quantity}}))).json();assert.equal(r.error.code,-32602)}});
test('execute requires the exact proposal digest and confirmed true',async()=>{for(const confirmed of [false,'true',null]){const f=fixture(),r=await(await f.handle(request('tools/call',{name:'coco_execute_stock',arguments:{command_id:randomUUID(),digest:'a'.repeat(64),confirmed}}))).json();assert.equal(r.error.code,-32602);assert.equal(f.calls.length,1)}});
test('valid writes forward only the authenticated user token and a named action',async()=>{const data={command_id:randomUUID(),digest:'a'.repeat(64),confirmed:true},f=fixture({result:{status:'executed',stock_after:0}});const r=await(await f.handle(request('tools/call',{name:'coco_execute_stock',arguments:data}))).json();assert.equal(r.result.structuredContent.stock_after,0);assert.equal(f.calls[1].url,root+'/rest/v1/rpc/coco_agent');assert.equal(f.calls[1].headers.Authorization,'Bearer isolated-test-token');assert.equal(f.calls[1].headers.apikey,'public-test-key');assert.deepEqual(JSON.parse(f.calls[1].body),{p_action:'execute',p_data:data});assert.ok(!JSON.stringify(f.calls).includes('service_role'))});
test('approval-pending and rejected results are never changed to executed',async()=>{for(const status of ['pending_approval','rejected']){const f=fixture({result:{status,error:status==='rejected'?'STOCK_CHANGED_RECOUNT':undefined}});const r=await(await f.handle(request('tools/call',{name:'coco_stock_history',arguments:{}}))).json();assert.equal(r.result.structuredContent.status,status);assert.equal(r.result.isError,status==='rejected')}});
test('business errors do not expose database details',async()=>{const f=fixture({failure:true}),r=await(await f.handle(request('tools/call',{name:'coco_get_stock',arguments:{product_id:randomUUID()}}))).json();assert.equal(r.result.structuredContent.error,'ROLE_NOT_ALLOWED');assert.ok(!JSON.stringify(r).includes('private information'))});
test('unapproved browser origins are rejected before authentication',async()=>{const f=fixture(),r=await f.handle(request('tools/list',{}, {headers:{Origin:'https://attacker.invalid'}}));assert.equal(r.status,403);assert.equal(f.calls.length,0)});
test('non-POST transport and batch requests fail closed',async()=>{const f=fixture();assert.equal((await f.handle(new Request(endpoint))).status,405);const r=await f.handle(new Request(endpoint,{method:'POST',headers:{Authorization:'Bearer test'},body:'[]'}));assert.equal(r.status,400)});
