const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID:uuid}=require('node:crypto');
const {restore}=require('../scripts/restore-schema.cjs');
test('Agent Coco: authenticated prepare/confirm, immutable receipts, no duplicate stock movements and delegated isolation',async()=>{
 const db=await restore(),admin=uuid(),other=uuid(),product=uuid();
 const as=async(id,client)=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claims',$2,false)",[id||'',JSON.stringify({sub:id,role:'authenticated',...(client?{client_id:client}:{})})]);await db.exec('set role authenticated')};
 const rpc=async(action,data={})=>(await db.query('select public.coco_agent($1,$2::jsonb) result',[action,JSON.stringify(data)])).rows[0].result;
 let location;
 const quantity=async()=>{await db.exec('reset role');return Number((await db.query('select quantity from stock_quants where product_id=$1 and location_id=$2',[product,location])).rows[0].quantity)};
 const seedQuantity=async qty=>{await db.exec('reset role');await db.query('update stock_quants set quantity=$1,reserved_quantity=0 where product_id=$2 and location_id=$3',[qty,product,location]);await as(admin)};
 const config={enabled:true,can_write:true,client_ids:['agent-test-client','read-only-client'],write_client_ids:['agent-test-client']};
 const prepare=(extra={})=>rpc('prepare',{request_key:uuid(),product_id:product,location_id:location,operation:'out',kind:'internal_use',quantity:1,reason:'consommation interne',...extra});
 const execute=p=>rpc('execute',{command_id:p.id,digest:p.digest,confirmed:true});
 try{
  await db.query('insert into auth.users(id,email) values($1,$3),($2,$4)',[admin,other,'agent-test@example.invalid','agent-other@example.invalid']);
  await db.exec("update profiles set role='administrador',active=true;update erp_policies set stock_adjustment_limit=null,stock_adjustment_value_limit=null,stock_adjustment_approval_kinds='{}'");
  await db.query('insert into products(id,name,barcode,reference,purchase_price) values($1,$2,$3,$4,2)',[product,'Agent test item','AGENT-TEST-BARCODE','AGENT-TEST']);
  location=(await db.query('select id from warehouse_locations where active limit 1')).rows[0].id;
  await db.query('insert into stock_quants(product_id,location_id,quantity,reserved_quantity) values($1,$2,65,0)',[product,location]);
  await as(admin);await assert.rejects(rpc('search',{query:'AGENT-TEST'}),/AGENT_ACCESS_DISABLED/);
  await rpc('configure',config);assert.equal((await rpc('search',{query:'AGENT-TEST'})).items[0].id,product);
  const input={request_key:uuid(),product_id:product,operation:'out',kind:'internal_use',all_stock:true,reason:'consommation interne'};
  const proposal=await rpc('prepare',input);assert.equal(proposal.state,'prepared');assert.equal(proposal.snapshot.quantity_changed,65);
  assert.equal(await quantity(),65);await as(admin);assert.deepEqual(await rpc('prepare',input),proposal);
  await assert.rejects(rpc('prepare',{...input,reason:'different reason'}),/REQUEST_KEY_REUSED/);
  await assert.rejects(rpc('execute',{command_id:proposal.id,digest:proposal.digest,confirmed:false}),/AGENT_CONFIRMATION_REQUIRED/);
  await assert.rejects(rpc('execute',{command_id:proposal.id,digest:'a'.repeat(64),confirmed:true}),/AGENT_CONFIRMATION_REQUIRED/);
  const done=await execute(proposal);assert.equal(done.status,'executed');assert.equal(done.stock_after,0);const verified=await rpc('status',{command_id:proposal.id});assert.equal(verified.status,'executed');assert.equal(verified.movements.length,1);assert.equal(verified.stock_now,0);assert.ok(done.adjustments[0].movement_id);
  assert.equal(await quantity(),0);await as(admin);assert.deepEqual(await execute(proposal),done);
  await db.exec('reset role');const count=Number((await db.query("select count(*) count from stock_movements where product_id=$1 and reference_type='adjustment_request'",[product])).rows[0].count);assert.equal(count,1);
  assert.equal((await db.query('select reason,kind from stock_adjustment_requests where id=$1',[done.adjustments[0].id])).rows[0].reason,'consommation interne');
  await seedQuantity(10);let p=await prepare({quantity:2});await seedQuantity(9);let r=await execute(p);assert.equal(r.status,'rejected');assert.equal(r.error,'STOCK_CHANGED_RECOUNT');assert.equal(await quantity(),9);
  await as(admin);p=await prepare();await rpc('configure',config);r=await execute(p);assert.equal(r.error,'AGENT_ACCESS_CHANGED');
  p=await prepare();await db.exec('reset role');await db.query("update private.coco_agent_commands set expires_at=now()-interval '1 second' where id=$1",[p.id]);await as(admin);assert.equal((await execute(p)).error,'AGENT_PROPOSAL_EXPIRED');
  await db.exec('reset role');await db.query('update stock_quants set reserved_quantity=1 where product_id=$1',[product]);await as(admin);await assert.rejects(rpc('prepare',{...input,request_key:uuid()}),/RESERVED_EXCEEDS_QUANTITY/);
  await seedQuantity(10);await db.exec('reset role');await db.exec('update erp_policies set stock_adjustment_limit=1');await as(admin);p=await prepare({quantity:2});r=await execute(p);assert.equal(r.status,'pending_approval');assert.equal(r.adjustments[0].status,'pending');assert.equal(await quantity(),10);
  await db.exec('reset role');await db.exec('update erp_policies set stock_adjustment_limit=null');await as(admin);
  p=await prepare();await as(other);await rpc('configure',config);await assert.rejects(execute(p),/AGENT_COMMAND_NOT_FOUND/);
  await as(admin,'unapproved-client');await assert.rejects(rpc('stock',{product_id:product}),/AGENT_CLIENT_NOT_ALLOWED/);
  await as(admin,'read-only-client');assert.equal((await rpc('stock',{product_id:product})).product_id,product);await assert.rejects(prepare(),/AGENT_WRITE_NOT_ALLOWED/);
  await as(admin,'agent-test-client');assert.equal((await rpc('stock',{product_id:product})).product_id,product);
  assert.equal((await db.query('select id from products where id=$1',[product])).rows.length,0);
  await assert.rejects(rpc('configure',config),/ROLE_NOT_ALLOWED/);
  await db.query("select set_config('request.path','/rpc/gama_stock_adjust',false)");await assert.rejects(db.query('select public.coco_agent_request_guard()'),/AGENT_ENDPOINT_NOT_ALLOWED/);
  await db.query("select set_config('request.path','/rpc/coco_agent',false)");await db.query('select public.coco_agent_request_guard()');
  const delegated=await prepare();await as(admin);await assert.rejects(execute(delegated),/AGENT_COMMAND_NOT_FOUND/);
  await rpc('configure',{enabled:false,can_write:false,client_ids:[]});await as(admin,'agent-test-client');await assert.rejects(execute(delegated),/AGENT_ACCESS_DISABLED/);
  await as(admin);await rpc('configure',config);await db.exec('reset role');await db.query("insert into auth.mfa_factors(user_id,status) values($1,'verified')",[admin]);await as(admin);await assert.rejects(rpc('stock',{product_id:product}),/AUTH_OR_MFA_REQUIRED/);
 }finally{await db.close()}
});
