const {test,expect}=require('@playwright/test');
const fs=require('fs'),path=require('path');
const mock=fs.readFileSync(path.join(__dirname,'mock-gama-cloud.js'),'utf8');
const models=['EC','FR','BE'].map(c=>{const m=require('../config/localizations/'+c+'.json');return {...m,account_count:m.accounts.length,accounts:undefined,mapping:undefined}});
async function boot(page,role='admin'){
 await page.addInitScript(({role,models})=>{localStorage.setItem('gama_session_v1',JSON.stringify({role,name:'Company QA'}));localStorage.setItem('gama_language_v1','fr');window.__DB={products:[],customers:[],suppliers:[],profiles:[],invoices:[]};window.__models=models},{role,models});
 await page.route('https://**/*',r=>r.abort());
 const root=process.env.PM_QA_ASSETS;if(root)await page.route('**/jspdf.umd.min.js*',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync(path.join(root,'jspdf/dist/jspdf.umd.min.js'),'utf8')}));
 await page.route('**/gama-supabase.js*',r=>r.fulfill({contentType:'text/javascript',body:mock+`;(()=>{const old=GamaCloud.db;GamaCloud.db=async()=>{const c=await old(),rpc=c.rpc;c.rpc=(fn,a)=>fn==='gama_company_action'&&a.p_action==='options'?Promise.resolve({data:{ledger_empty:true,templates:window.__models}}):rpc(fn,a);return c}})();`}));
 await page.goto('/index.html');await page.evaluate(()=>GamaSettings.open('company'));
 if(role==='admin')await expect(page.locator('#co_legal_name')).toBeVisible();
}
async function upload(page){const data=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=400;c.height=100;const x=c.getContext('2d');x.fillStyle='#123456';x.fillRect(0,0,280,100);x.fillStyle='#E87824';x.fillRect(280,0,120,100);return c.toDataURL().split(',')[1]});await page.locator('#coLogo').setInputFiles({name:'wide-company-logo.png',mimeType:'image/png',buffer:Buffer.from(data,'base64')});await expect(page.locator('#coMessage')).toContainText('Couleurs du logo détectées');}
test('company form saves identity, detects both logo colors, preserves language drafts and stays within all viewports',async({page})=>{
 await boot(page);await page.locator('#co_legal_name').fill('Atelier Test & Associés');await page.locator('#co_address').fill('10 rue de la Gare\n1000 Bruxelles');await page.locator('#co_tax_id').fill('BE0123456789');await page.locator('#co_email').fill('contact@example.invalid');await page.locator('#co_country').selectOption('BE');await expect(page.locator('#co_currency')).toHaveValue('EUR');await expect(page.locator('#coFiscalBody')).toContainText('426 comptes');await expect(page.locator('#coInstall')).toBeChecked();await upload(page);
 await expect(page.locator('#co_document_primary')).toHaveValue('#123456');expect(await page.locator('#co_document_secondary').inputValue()).toMatch(/^#e[78]7824$/);
 for(const [lang,text] of [['en','Save company'],['es','Guardar empresa'],['fr','Enregistrer l’entreprise']]){await page.evaluate(lang=>GamaI18n.setLanguage(lang),lang);await expect(page.locator('#coSave')).toHaveText(text);await expect(page.locator('#co_legal_name')).toHaveValue('Atelier Test & Associés')}
 for(const width of [1920,1440,1024,768,430,390]){await page.setViewportSize({width,height:900});await page.waitForTimeout(50);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),String(width)).toBe(true)}
 await page.locator('#cfgTab-fiscal').click();await page.locator('#coInstall').uncheck();await page.locator('#coSave').click();await expect(page.locator('#coMessage')).toContainText('Entreprise enregistrée');await page.keyboard.press('Escape');await expect(page.locator('#arcSettingsDialog')).toHaveCount(0);await page.evaluate(()=>GamaSettings.open('company'));await expect(page.locator('#co_legal_name')).toHaveValue('Atelier Test & Associés');await expect(page.locator('#coPreview img')).toHaveJSProperty('naturalWidth',512);expect(await page.evaluate(()=>GamaCompany.defaultsForQuote().currency)).toBe('EUR');
});
test('failed saves preserve edits and non-admin users only have personal settings',async({page})=>{
 await boot(page);await page.locator('#co_legal_name').fill('Draft survives conflict');await page.evaluate(()=>{window.__DB.company_settings=[{...GamaCompany.get(),company_version:8}]});await page.locator('#coSave').click();await expect(page.locator('#coMessage')).toContainText('modifiée ailleurs');await expect(page.locator('#co_legal_name')).toHaveValue('Draft survives conflict');await page.evaluate(()=>{localStorage.setItem('gama_session_v1',JSON.stringify({role:'client'}));window.dispatchEvent(new CustomEvent('gama:auth-change',{detail:{event:'SIGNED_OUT'}}));GamaSettings.open()});await expect(page.locator('#coForm')).toHaveCount(0);await expect(page.locator('#gamaSettingsLanguage')).toBeVisible();
});
test('real PDF documents use company branding, custom currency and the uploaded logo ratio',async({page},testInfo)=>{
 test.skip(!process.env.PM_QA_ASSETS,'Set PM_QA_ASSETS for real jsPDF verification');await boot(page);await page.locator('#co_legal_name').fill('Atelier Test & Associés');await page.locator('#co_address').fill('10 rue de la Gare\n1000 Bruxelles');await page.locator('#co_email').fill('contact@example.invalid');await page.locator('#co_country').selectOption('BE');await upload(page);await page.locator('#cfgTab-fiscal').click();await page.locator('#coInstall').uncheck();await page.locator('#coSave').click();await expect(page.locator('#coMessage')).toContainText('Entreprise enregistrée');
 const result=await page.evaluate(async()=>{const items=Array.from({length:50},(_,i)=>({name:'Prestation de configuration et accompagnement '+(i+1),qty:2,price:15,listPrice:15,taxRate:21}));const q={...GamaCompany.defaultsForQuote(),number:'DEV-QA-001',dateLabel:'19/09/2026',client:'Client de démonstration',items,sub:1500,tax:315,total:1815};const blob=GamaQuotePdf.build(q);const data=await new Promise(r=>{const f=new FileReader();f.onload=()=>r(f.result);f.readAsDataURL(blob)});const doc=new jspdf.jsPDF();GamaPdfTemplate.header(doc,{title:'TEST'});const images=Object.values(doc.internal.collections.addImage_images);const l=GamaPdfTemplate.layout({title:'RAPPORT'});l.section('Détail');l.text('Preuve de livraison');return {data,ratio:images[0].width/images[0].height,pages:(await blob.text()).match(/\/Type \/Page\b/g).length,report:l.finish().output('datauristring'),purchase:await new Promise(r=>{const f=new FileReader();f.onload=()=>r(f.result);f.readAsDataURL(GamaPurchaseOrderPdf.build({number:'PO-QA-001',currency:'EUR',supplier:'Fournisseur test',items:[{name:'Article',qty:2,cost:15}],total:30}))})}});
 expect(result.ratio).toBe(4);expect(result.pages).toBeGreaterThan(1);for(const [key,name] of [['data','company-quote.pdf'],['report','company-report.pdf'],['purchase','company-purchase.pdf']])fs.writeFileSync(testInfo.outputPath(name),Buffer.from(result[key].split(',')[1],'base64'));
 await page.screenshot({path:testInfo.outputPath('company-settings.png'),fullPage:true});
});
