const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {PGlite}=require('@electric-sql/pglite');
const admin='00000000-0000-0000-0000-000000000001',client='00000000-0000-0000-0000-000000000002';
async function boot(){const db=new PGlite();await db.exec(`
create schema auth;create schema private;create role anon;create role authenticated;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table auth.users(id uuid primary key);
create table public.profiles(id uuid primary key,role text,active boolean);
insert into auth.users values ('${admin}'),('${client}');insert into profiles values('${admin}','administrador',true),('${client}','cliente',true);
create function private.current_user_role() returns text language sql stable security definer set search_path='' as $$select role from public.profiles where id=auth.uid() and active$$;
grant usage on schema public,auth,private to authenticated;
create table public.accounting_accounts(id uuid primary key default gen_random_uuid(),code text unique check(length(btrim(code)) between 1 and 20),name text check(length(btrim(name)) between 1 and 160),type text check(type in ('asset','liability','equity','income','expense')),active boolean default true,is_system boolean default false);
insert into accounting_accounts(code,name,type) values('6090','Existing software account','expense');
create table public.accounting_entries(id uuid primary key default gen_random_uuid());
create table public.accounting_taxes(id uuid primary key default gen_random_uuid(),code text unique,name text,rate numeric,kind text,country text,valid_from date,collected_account_id uuid references accounting_accounts,deductible_account_id uuid references accounting_accounts,active boolean default true);
create table public.company_settings(id boolean primary key default true,currency text default 'USD',country text default 'EC',updated_at timestamptz default now(),updated_by uuid references auth.users,receivable_account_id uuid references accounting_accounts,payable_account_id uuid references accounting_accounts,sales_account_id uuid references accounting_accounts,purchase_account_id uuid references accounting_accounts,tax_collected_account_id uuid references accounting_accounts,tax_deductible_account_id uuid references accounting_accounts);
insert into company_settings(id) values(true);alter table company_settings enable row level security;
create policy company_settings_read on company_settings for select to authenticated using(true);
create table public.gama_audit(id bigint generated always as identity,table_name text,row_id text,action text,actor_id uuid,actor_role text,old_data jsonb,new_data jsonb,changed_fields text[]);
`);await db.exec(fs.readFileSync(__dirname+'/../supabase/migrations/20260919094748_company_identity_localization.sql','utf8'));
await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${admin}',false)`);
const call=async(action,data={})=>(await db.query('select public.gama_company_action($1,$2) result',[action,data])).rows[0].result;return {db,call};}
function data(extra={}){return {legal_name:'Entreprise test',address:'Quito',tax_id:'0999',email:'qa@example.invalid',website:'https://example.invalid',country:'EC',currency:'USD',company_version:0,...extra}}
test('company identity persists centrally, rejects stale saves and leaves no direct write path',async()=>{const {db,call}=await boot();try{const saved=await call('save',data());assert.equal(saved.company_version,1);assert.equal((await call('get')).legal_name,'Entreprise test');await assert.rejects(call('save',data()),/COMPANY_STALE/);await assert.rejects(db.query("update company_settings set legal_name='bypass'"),/permission denied/);assert.equal((await call('get')).legal_name,'Entreprise test');await db.exec(`select set_config('request.jwt.claim.sub','${client}',false)`);assert.equal((await call('get')).legal_name,'Entreprise test');await assert.rejects(call('save',data({company_version:1})),/COMPANY_ADMIN_REQUIRED/);await assert.rejects(call('options'),/COMPANY_ADMIN_REQUIRED/);await db.exec('reset role;update profiles set active=false');await db.exec(`set role authenticated`);await assert.rejects(call('get'),/AUTH_REQUIRED/);assert.equal((await db.query('select * from company_settings')).rows.length,0)}finally{await db.close()}});
for(const country of ['EC','FR','BE'])test('localization '+country+' installs its chart and VAT atomically, preserves collisions and is idempotent',async()=>{const {db,call}=await boot();try{const options=await call('options'),model=options.templates.find(x=>x.country===country);const saved=await call('save',data({country,currency:model.currency,install_localization:true}));assert.equal(saved.localization_country,country);assert.equal(saved.currency,model.currency);await db.exec('reset role');const counts=(await db.query('select (select count(*) from accounting_accounts) accounts,(select count(*) from accounting_taxes) taxes')).rows[0];assert.equal(counts.accounts,model.account_count+1);assert.equal(counts.taxes,model.taxes.length);assert.equal((await db.query("select name from accounting_accounts where code='6090'")).rows[0].name,'Existing software account');if(country==='BE')assert.equal((await db.query("select localization_source_code from accounting_accounts where code='BE-6090'")).rows[0].localization_source_code,'6090');await db.exec('set role authenticated');await call('save',data({...saved,install_localization:true}));const current=await call('get');await assert.rejects(call('save',data({...current,country:country==='EC'?'FR':'EC'})),/COMPANY_LOCALIZATION_LOCKED/);await db.exec('reset role');assert.equal((await db.query('select count(*) n from accounting_accounts')).rows[0].n,counts.accounts);assert.equal((await db.query("select count(*) n from gama_audit where new_data ? 'logo_data'")).rows[0].n,0)}finally{await db.close()}});
test('existing ledger blocks initialization without partial company changes; malformed logo and email are rejected',async()=>{const {db,call}=await boot();try{await db.exec('reset role;insert into accounting_entries default values;set role authenticated');await assert.rejects(call('save',data({install_localization:true})),/COMPANY_LEDGER_NOT_EMPTY/);assert.equal((await call('get')).configured,false);await assert.rejects(call('save',data({logo_data:'data:image/svg+xml;base64,PHN2Zz4='})),/COMPANY_LOGO_INVALID/);await assert.rejects(call('save',data({email:'invalid'})),/COMPANY_EMAIL_INVALID/);await assert.rejects(call('save',data({website:'javascript:alert(1)'})),/COMPANY_WEBSITE_INVALID/);await call('save',data());assert.equal((await call('get')).configured,true)}finally{await db.close()}});
