const {test,expect}=require('@playwright/test');
const fs=require('fs'),vm=require('vm'),path=require('path');
const source=fs.readFileSync(path.join(__dirname,'../gama-references.js'),'utf8');
function setup(refs){const window={};vm.runInNewContext(source,{window});const client={from:()=>{let rows=refs;return {select(){return this},eq(k,v){rows=rows.filter(r=>r[k]===v);return this},in(k,vs){rows=rows.filter(r=>vs.includes(r[k]));return this},then(resolve){return Promise.resolve({data:rows}).then(resolve)}}}};return {api:window.GamaReferences,client}}
test('shares dossier number across documents without losing original/fiscal identifiers',async()=>{
 const refs=[['invoices','q','COT-00000012'],['sales_orders','o','PED-00000012'],['external_invoices','i','FAC-00000012']].map(([table_name,document_id,document_reference])=>({table_name,document_id,document_reference,dossier_number:12}));const {api,client}=setup(refs);
 const quote=await api.attach('invoices',{data:[{id:'q',invoice_number:'OLD-5'}]},client);expect(quote.data[0].invoice_number).toBe('COT-00000012');expect(quote.data[0].original_number).toBe('OLD-5');
 const inv=await api.attach('external_invoices',{data:[{id:'i',number:'001-001-000000123',document_kind:'external',order_id:'o'}]},client);expect(inv.data[0].number).toBe('FAC-00000012');expect(inv.data[0].external_number).toBe('001-001-000000123');expect(inv.data[0].dossier_label).toBe('EXP-00000012');
 const internal=await api.attach('external_invoices',{data:[{id:'i',number:'INT-3',document_kind:'internal',order_id:'o',source_quote_id:'q',document_snapshot:{quote_number:'OLD-5',order_number:'PV-4'}}]},client);expect(internal.data[0].document_snapshot.quote_number).toBe('COT-00000012');expect(internal.data[0].document_snapshot.order_number).toBe('PED-00000012');expect(internal.data[0].external_number).toBeUndefined();
});
test('handles proof primary key, does not change barcode and propagates read errors',async()=>{
 const {api,client}=setup([{table_name:'tms_proofs',document_id:'d',dossier_number:12,document_reference:'PDE-00000012'},{table_name:'fulfillment_packages',document_id:'p',dossier_number:12,document_reference:'PAQ-00000012'}]);const proof=await api.attach('tms_proofs',{data:[{delivery_id:'d',signature:'signed'}]},client);expect(proof.data[0].dossier_reference).toBe('PDE-00000012');const pack=await api.attach('fulfillment_packages',{data:[{id:'p',barcode:'PK-1'}]},client);expect(pack.data[0].barcode).toBe('PK-1');
 const broken={from:()=>({select(){return this},eq(){return this},in:async()=>({error:{message:'offline'}})})};const r=await api.attach('sales_orders',{data:[{id:'o',number:'PV-1'}]},broken);expect(r.error.message).toBe('offline');expect(r.data).toBeNull();
});
test('menu opens quotes and invoices and the case/PDF use shared references',async({page})=>{
 const mock=fs.readFileSync(path.join(__dirname,'mock-gama-cloud.js'),'utf8');
 await page.addInitScript(()=>{localStorage.setItem('gama_session_v1',JSON.stringify({role:'admin',name:'QA'}));window.__DB={products:[],customers:[],suppliers:[],invoices:[{id:'q',invoice_number:'OLD-5',quote_state:'draft',quote_details:{client:'Client'},issue_date:'2026-09-13',quote_revision:1}],invoice_lines:[],sales_orders:[{id:'o',number:'PV-7',source_quote_id:'q',customer_name:'Client',status:'draft'}],sales_order_lines:[],gama_document_references:[{table_name:'invoices',document_id:'q',dossier_number:12,document_reference:'COT-00000012'},{table_name:'sales_orders',document_id:'o',dossier_number:12,document_reference:'PED-00000012'}]};});
 await page.route('**/gama-supabase.js*',r=>r.fulfill({contentType:'text/javascript',body:mock+`;const originalList=GamaCloud.list;GamaCloud.list=async(t,o)=>GamaReferences.attach(t,await originalList(t,o),await GamaCloud.db());`}));await page.route('**/@supabase/**',r=>r.abort());await page.goto('/index.html');await page.waitForTimeout(1200);
 await page.locator('#mainmenu [data-gama-module="quotes"]').click();await expect(page.locator('#quotes')).toContainText('Presupuestos y facturas');await expect(page.locator('#quotes')).toContainText('COT-00000012');
 await page.locator('[data-gq-open]').click();const pdf=await page.evaluate(async()=>GamaQuotes.pdfData({...((await GamaCloud.list('invoices')).data[0]),lines:[]}));expect(pdf.number).toBe('COT-00000012');
 await page.evaluate(()=>GamaQuotes.open());await page.locator('#gqInvoices').click();await expect(page.locator('#sales-orders')).toBeVisible();
 await page.evaluate(()=>GamaDossierFlow.open());await expect(page.locator('#gdfDetail')).toContainText('EXP-00000012');await expect(page.locator('#gdfDetail')).toContainText('PED-00000012');await expect(page.locator('#gdfDetail')).toContainText('COT-00000012');
});
