const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID:uuid}=require('node:crypto'),{restore}=require('../scripts/restore-schema.cjs');
test('Explicit B2B membership scopes prices, requests, favorites, invoices, proofs and debt; management and stock use real sales',async t=>{
 const db=await restore(),admin=uuid(),sales=uuid(),client=uuid(),other=uuid(),customer=uuid(),otherCustomer=uuid(),p1=uuid(),p2=uuid(),order=uuid(),order2=uuid(),line=uuid(),delivery=uuid(),delivery2=uuid(),shipment=uuid(),invoice=uuid(),invoice2=uuid(),quote=uuid(),quote2=uuid(),file=uuid(),file2=uuid(),address=uuid(),sri=uuid();
 const q=(s,p=[])=>db.query(s,p),one=async(s,p=[])=>Object.values((await q(s,p)).rows[0])[0],rpc=(a,d={})=>one('select gama_b2b_action($1,$2::jsonb)',[a,JSON.stringify(d)]),adm=(a,d={})=>one('select gama_b2b_admin($1,$2::jsonb)',[a,JSON.stringify(d)]),as=async id=>{await db.exec('reset role');await q("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated')};let requested;
 try{
 await db.exec(`insert into auth.users(id,email,email_confirmed_at) values('${admin}','b2b-admin@example.invalid',now()),('${sales}','b2b-sales@example.invalid',now()),('${client}','shared@example.invalid',now()),('${other}','other@example.invalid',now());update profiles set active=true,role=case when id='${admin}' then 'administrador' when id='${sales}' then 'comercial' else 'cliente' end;
 insert into customers(id,name,email,category,address) values('${customer}','Explicit company','unrelated@example.invalid','B','Head office'),('${otherCustomer}','Other company','shared@example.invalid','A','Other address');
 insert into products(id,name,barcode,purchase_price,sale_price,sale_price_b,order_minimum,order_multiple,created_at) values('${p1}','B2B paper','B2B-PAPER',4,10,8,1,1,now()-interval '100 days'),('${p2}','Dormant paper','B2B-DORMANT',4,9,7,1,1,now()-interval '100 days');
 select set_config('request.jwt.claim.sub','${admin}',false);update profiles set active=true;
 insert into customer_addresses(id,customer_id,label,purpose,address,city) values('${address}','${customer}','Agencia norte','delivery','North branch','Quito');
 set session_replication_role=replica;
 insert into sales_orders(id,number,request_key,customer_id,customer_name,status,created_by) values('${order}','PV-QA1',gen_random_uuid(),'${customer}','Explicit company','confirmed','${admin}'),('${order2}','PV-QA2',gen_random_uuid(),'${otherCustomer}','Other company','confirmed','${admin}');
 insert into sales_order_lines(id,order_id,product_id,product_name,quantity,unit_price,tax_rate) values('${line}','${order}','${p1}','B2B paper',90,10,15);
 insert into tms_deliveries(id,customer_id,customer,address,delivery_date,status,erp_reference) values('${delivery}','${customer}','Explicit company','North branch',(now() at time zone private.erp_timezone())::date-1,'Entregada','DOC-00000017'),('${delivery2}','${otherCustomer}','Other company','Other address',(now() at time zone private.erp_timezone())::date-1,'En camino','DOC-00000018');
 insert into sales_deliveries(id,number,order_id,tms_delivery_id,request_key,created_by,dispatched_at) values('${shipment}','EX-QA1','${order}','${delivery}',gen_random_uuid(),'${admin}',now()-interval '5 days'),(gen_random_uuid(),'EX-QA2','${order2}','${delivery2}',gen_random_uuid(),'${admin}',now()-interval '5 days');
 insert into sales_delivery_lines(delivery_id,order_line_id,location_id,quantity) select '${shipment}','${line}',id,90 from warehouse_locations where active limit 1;
 insert into stock_quants(product_id,location_id,quantity,reserved_quantity) select '${p2}',id,20,0 from warehouse_locations where active limit 1;
 insert into stock_movements(product_id,type,quantity,movement_type,reference_type,reference_id,unit_cost_at_movement,created_at) values('${p1}','out',90,'delivery','sales_delivery','${shipment}',4,now()-interval '5 days'),('${p1}','out',10000,'manual_out',null,null,4,now()-interval '2 days');
 insert into invoices(id,invoice_number,customer_id,quote_state,quote_details) values('${quote}','B2B-QUOTE','${customer}','accepted','{}'),('${quote2}','OTHER-QUOTE','${otherCustomer}','accepted','{}');
 insert into external_invoices(id,request_key,order_id,number,issuer_ruc,issue_date,due_date,subtotal,tax,fiscal_status,created_by,document_kind,source_quote_id,document_snapshot,erp_reference) values('${invoice}',gen_random_uuid(),'${order}','001-001-000000017','1790012345001',(now() at time zone private.erp_timezone())::date-2,(now() at time zone private.erp_timezone())::date-1,100,15,'unverified','${admin}','internal','${quote}','{}','DOC-00000017'),('${invoice2}',gen_random_uuid(),'${order2}','001-001-000000018','1790012345001',(now() at time zone private.erp_timezone())::date-2,null,900,0,'unverified','${admin}','internal','${quote2}','{}','DOC-00000018');
 insert into external_invoice_lines(invoice_id,order_line_id,quantity) values('${invoice}','${line}',10);
 insert into external_invoice_files(id,invoice_id,filename,mime_type,content_base64) values('${file}','${invoice}','database-random-identifier.pdf','application/pdf','JVBERi0xLjQ='),('${file2}','${invoice2}','private.pdf','application/pdf','JVBERi0xLjQ=');
 insert into external_invoice_payments(invoice_id,request_key,amount,paid_at,method,status,created_by) values('${invoice}',gen_random_uuid(),20,current_date,'cash','confirmed','${admin}');
 insert into tms_proofs(delivery_id,photo,signature,captured_at,latitude,longitude,gps_accuracy_m) values('${delivery}','data:image/png;base64,TEST','data:image/png;base64,SIGN',now(),-.2,-78.5,12);
 insert into sri_invoice_issues(id,source_invoice_id,customer_id,environment,issuer_ruc,establishment,emission_point,sequential,snapshot,status,authorized_xml_path,ride_path,created_by) values('${sri}','${invoice}','${customer}','pruebas','1790012345001','001','001','000000017','{}','authorized','private/authorized.xml','private/ride.pdf','${admin}');
 set session_replication_role=origin;`);
 await t.test('email matching never grants B2B access; activation and membership are explicitly managed',async()=>{
 await as(client);await assert.rejects(rpc('bootstrap'),/B2B_ACCESS_REQUIRED/);await assert.rejects(adm('list'),/ROLE_NOT_ALLOWED/);
 await as(admin);assert.deepEqual((await q('select role,active from profiles where id=$1',[client])).rows[0],{role:'cliente',active:false});await assert.rejects(adm('invitation_context',{customer_id:customer}),/B2B_ACCESS_REQUIRED/);await adm('access',{customer_id:customer,enabled:true});assert.equal((await adm('invitation_context',{customer_id:customer})).allowed,true);await adm('member',{customer_id:customer,profile_id:client,active:true});
 await as(client);const b=await rpc('bootstrap');assert.equal(b.customer.name,'Explicit company');assert.equal(b.customer.category,'B');assert.equal(b.total,95);assert.equal(b.overdue,95);assert.equal(b.addresses[0].label,'Agencia norte');
 assert.equal(Number(await one('select count(*) from products')),0,'retired clients cannot read ERP tables directly');await assert.rejects(one('select gama_resolve_price($1,$2,1,null)',[customer,p1]),/ROLE_NOT_ALLOWED/);await assert.rejects(one('select private.erp_price_calculate($1,$2,1,null)',[customer,p1]),/permission denied/);await assert.rejects(q('update b2b_memberships set customer_id=$1 where profile_id=$2',[otherCustomer,client]),/permission denied/);await assert.rejects(one('select private.gama_b2b_customer()'),/permission denied/);
 });
 await t.test('customer prices are recalculated; retries create one real request and retain the delivery branch',async()=>{
 const catalog=await rpc('catalog');assert.equal(catalog.items.find(p=>p.id===p1).unit_price,8);const lines=[{product_id:p1,quantity:2}],preview=await rpc('preview',{lines});assert.equal(preview.total,16);
 const payload={request_key:uuid(),lines,price_hash:preview.price_hash,address_id:address,notes:'Repeat office supplies'};requested=await rpc('submit',payload);assert.deepEqual(await rpc('submit',payload),requested);assert.ok(requested.reference);await db.exec('reset role');assert.equal(Number(await one('select count(*) from customer_requests where id=$1',[requested.id])),1);
 assert.equal(await one('select delivery_address_snapshot from customer_requests where id=$1',[requested.id]),'North branch, Quito');await as(client);
 await assert.rejects(rpc('submit',{...payload,notes:'Changed'}),/REQUEST_KEY_REUSED/);await assert.rejects(rpc('submit',{...payload,request_key:uuid(),price_hash:'invented'}),/CART_PRICE_CHANGED/);await assert.rejects(rpc('preview',{lines:[{product_id:p1,quantity:'NaN'}]}),/INVALID_QUANTITY/);
 const saved=await rpc('favorite_save',{request_key:uuid(),name:'Office month',lines});assert.equal((await rpc('favorites'))[0].id,saved.id);await as(other);await assert.rejects(rpc('favorites'),/B2B_ACCESS_REQUIRED/);await as(client);
 });
 await t.test('invoices and proofs expose only this company and show ERP references in file names',async()=>{
 const list=await rpc('invoices');assert.equal(list.total,1);assert.equal(list.items[0].id,invoice);assert.equal(list.items[0].balance,95);assert.equal((await rpc('invoice_file',{id:file})).filename,'DOC-00000017.pdf');await assert.rejects(rpc('invoice_file',{id:file2}),/NOT_FOUND/);
 const deliveries=await rpc('deliveries');assert.equal(deliveries.total,1);assert.equal(deliveries.items[0].reference,'DOC-00000017');const proof=await rpc('proof',{id:delivery});assert.equal(proof.latitude,-.2);assert.equal(proof.signature,'data:image/png;base64,SIGN');await assert.rejects(rpc('proof',{id:delivery2}),/NOT_FOUND/);
 const statement=await rpc('statement',{export:true});assert.equal(statement.total,95);assert.equal(statement.rows.length,1);assert.equal(statement.customer.name,'Explicit company');const s=await rpc('sri_document',{id:sri,kind:'ride'});assert.equal(s.path,'private/ride.pdf');assert.equal(s.filename,'DOC-00000017.pdf');
 });
 await t.test('the document center is scoped, filtered and rechecked on every download; only administrators manage cloud accounts',async()=>{
 const docs=await rpc('documents');assert.equal(docs.total,3);assert.deepEqual(new Set(docs.items.map(d=>d.kind)),new Set(['invoice','delivery_proof','quote']));assert.ok(docs.items.every(d=>[invoice,delivery,quote].includes(d.id)));assert.ok(docs.items.every(d=>!('photo' in d)&&!('authorized_xml_path' in d)));
 assert.equal((await rpc('documents',{kind:'invoice'})).total,1);assert.equal((await rpc('documents',{search:'does-not-exist'})).total,0);assert.equal((await rpc('documents',{offset:30})).items.length,0);
 const safeQuote=await rpc('quote_document',{id:quote});assert.equal(safeQuote.customer.name,'Explicit company');assert.ok(!('quote_details' in safeQuote));await assert.rejects(rpc('quote_document',{id:quote2}),/NOT_FOUND/);
 await assert.rejects(one('select gama_b2b_customer_accounts($1)',[customer]),/ROLE_NOT_ALLOWED/);await as(sales);await assert.rejects(one('select gama_b2b_customer_accounts($1)',[customer]),/ROLE_NOT_ALLOWED/);
 await as(admin);const accounts=await one('select gama_b2b_customer_accounts($1)',[customer]);assert.equal(accounts.customer.enabled,true);assert.deepEqual(accounts.members.map(p=>p.id),[client]);assert.ok(accounts.available.some(p=>p.id===other));assert.ok(!accounts.available.some(p=>p.id===client));await as(client);
 });
 await t.test('revocation, unverified accounts and stale membership updates cannot keep customer access',async()=>{
 await as(admin);await assert.rejects(adm('member',{customer_id:otherCustomer,profile_id:client,active:true,expected_customer_id:null}),/MEMBERSHIP_CHANGED/);await adm('access',{customer_id:customer,enabled:false});await as(client);await assert.rejects(rpc('invoices'),/B2B_ACCESS_REQUIRED/);await as(admin);await adm('access',{customer_id:customer,enabled:true});await db.exec('reset role');await q('update auth.users set email_confirmed_at=null where id=$1',[client]);await as(client);await assert.rejects(rpc('bootstrap'),/B2B_ACCESS_REQUIRED/);await db.exec('reset role');await q('update auth.users set email_confirmed_at=now() where id=$1',[client]);
 await q("update auth.users set banned_until=now()+interval '1 hour' where id=$1",[client]);await as(client);await assert.rejects(rpc('bootstrap'),/AUTH_OR_MFA_REQUIRED/);await db.exec('reset role');await q('update auth.users set banned_until=null where id=$1',[client]);
 await q("insert into auth.mfa_factors(user_id,status) values($1,'verified')",[client]);await as(client);await assert.rejects(rpc('bootstrap'),/AUTH_OR_MFA_REQUIRED/);await q("select set_config('request.jwt.claims','{\"aal\":\"aal2\"}',false)");assert.equal((await rpc('bootstrap')).customer.name,'Explicit company');await q("select set_config('request.jwt.claims','{}',false)");await db.exec('reset role');await q('delete from auth.mfa_factors where user_id=$1',[client]);
 });
 await t.test('a B2B request keeps its reviewed delivery branch when staff prepare a quotation',async()=>{
 await as(admin);const today=await one('select (now() at time zone private.erp_timezone())::date'),data={customer_id:customer,issue_date:today,valid_until:today,details:{seller:'GAMA',client:'Explicit company',delivery_address:'Injected head office'},lines:[{product_id:p1,description:'B2B paper',quantity:2,list_price:8,discount:0,tax_rate:0}]};
 await assert.rejects(one('select gama_quote_from_request($1,$2::jsonb)',[requested.id,JSON.stringify({...data,customer_id:otherCustomer})]),/B2B_ADDRESS_CUSTOMER_CHANGED/);
 const quote=await one('select gama_quote_from_request($1,$2::jsonb)',[requested.id,JSON.stringify(data)]);assert.equal(await one("select quote_details->>'delivery_address' from invoices where id=$1",[quote.id]),'North branch, Quito');assert.equal((await one('select gama_quote_from_request($1,$2::jsonb)',[requested.id,JSON.stringify(data)])).id,quote.id);
 });
 await t.test('supplier score measures the actual final lead time and an incomplete first delivery',async()=>{
 await as(admin);const supplier=uuid(),purchase=uuid();await db.exec('reset role');await q("insert into suppliers(id,name) values($1,'Measured supplier')",[supplier]);await db.exec('set session_replication_role=replica');await q("insert into purchase_orders(id,supplier_id,order_number,order_date,expected_date,status,created_by) values($1,$2,'OC-QA',now()-interval '30 days',now()-interval '20 days','received',$3)",[purchase,supplier,admin]);await q('insert into purchase_order_lines(purchase_order_id,product_id,quantity,received_quantity,unit_cost) values($1,$2,10,10,4)',[purchase,p1]);await q("insert into stock_movements(product_id,type,quantity,movement_type,reference_type,reference_id,unit_cost_at_movement,created_at) values($1,'in',5,'receipt','purchase_order',$2,4,now()-interval '25 days'),($1,'in',5,'receipt','purchase_order',$2,4,now()-interval '15 days')",[p1,purchase]);await db.exec('set session_replication_role=origin');await as(admin);
 const r=await one('select gama_supplier_performance($1)',[supplier]);assert.equal(r.average_lead_days,15);assert.equal(r.promised_lead_days,10);assert.equal(r.average_delay_days,5);assert.equal(r.incomplete_percent,100);assert.equal(r.receipts_measured,1);assert.equal(r.on_time_percent,0);
 });
 await t.test('confirmed dispatch sales over 90 days propose exact thresholds and one-click validation never moves stock',async()=>{
 await as(admin);const stock=await one("select gama_stock_sales_thresholds('list','{}')");const p=stock.rows.find(x=>x.id===p1);assert.equal(p.sales90,90);assert.equal(p.proposed_min,11);assert.equal(p.proposed_max,25);const before=await q('select product_id,quantity from stock_quants order by product_id');const data={request_key:uuid(),items:[{id:p1,fingerprint:p.fingerprint}]};assert.equal((await one("select gama_stock_sales_thresholds('apply',$1::jsonb)",[JSON.stringify(data)])).updated,1);assert.equal((await one("select gama_stock_sales_thresholds('apply',$1::jsonb)",[JSON.stringify(data)])).updated,1);assert.equal(Number(await one('select min_stock from products where id=$1',[p1])),11);assert.deepEqual((await q('select product_id,quantity from stock_quants order by product_id')).rows,before.rows);await assert.rejects(one("select gama_stock_sales_thresholds('apply',$1::jsonb)",[JSON.stringify({...data,request_key:uuid()})]),/THRESHOLDS_CHANGED/);
 });
 await t.test('management sees current month net sales, historical cost coverage, exact overdue balance and operational exceptions',async()=>{
 const r=await one("select gama_management_overview('dashboard')");assert.equal(r.metrics.sales_month,1000);assert.equal(r.metrics.margin_month,null);assert.equal(r.metrics.margin_missing_invoices,1);assert.equal(r.metrics.overdue,995);assert.equal(r.metrics.dormant_stock_value,80);assert.equal(r.metrics.late_deliveries,1);assert.equal(r.client_count,2);await db.exec('reset role');const credit=await one('select private.gama_credit_snapshot($1)',[otherCustomer]);assert.equal(credit.blocked,true);assert.equal(credit.overdue.length,1,'missing maturity uses the same issue-date fallback as the collections view');await as(admin);
 await as(sales);await assert.rejects(one("select gama_management_overview('dashboard')"),/ROLE_NOT_ALLOWED/);
 });
 await t.test('the unified returns module closes service access while preserving Documents and role boundaries',async()=>{
 await as(admin);assert.equal(await one("select private.service_access('sav')"),true);await db.exec('reset role');await db.exec("insert into app_modules(id,enabled) values('returns',false) on conflict(id) do update set enabled=false");await as(admin);assert.equal(await one("select private.service_access('sav')"),false);assert.equal(await one("select private.service_access('documents')"),true);await db.exec('reset role');await db.exec("update app_modules set enabled=true where id='returns'");await as(client);assert.equal(await one("select private.service_access('sav')"),false);
 });
 }finally{await db.close()}
});
