const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID:uuid}=require('node:crypto'),{restore}=require('../scripts/restore-schema.cjs');
test('Ecuador payroll uses reviewed parameters, real contracts, employee choices and exact annual pools',async t=>{
 const db=await restore(),admin=uuid(),own=uuid(),other=uuid(),e1=uuid(),e2=uuid(),e3=uuid(),acc=uuid();const q=(s,p=[])=>db.query(s,p),one=async(s,p=[])=>Object.values((await q(s,p)).rows[0])[0],rpc=(a,d={})=>one('select gama_hr_ec_action($1,$2::jsonb)',[a,JSON.stringify(d)]),as=async id=>{await db.exec('reset role');await q("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated')};
 const params={sbu:482,iess_personal_rate:9.45,iess_employer_rate:11.15,iess_health_min_rate:4.41,reserve_rate:8.33,additional_employer_rate:0,util_work_rate:10,util_family_rate:5},terms={period:'2026-01-01',decimo13_mode:'monthly',decimo14_mode:'monthly',reserve_mode:'direct',region:'costa',work_ratio:1,bank_name:'Banco QA',bank_number:'0001234567',bank_kind:'savings',beneficiary_id:'1719304188',evidence:'Solicitud escrita del empleado, verificada por RRHH'};let pay;
 try{
 await db.exec(`insert into auth.users(id,email) values('${admin}','hr-ec-admin@example.invalid'),('${own}','hr-ec-own@example.invalid'),('${other}','hr-ec-other@example.invalid');update profiles set active=true,role=case when id='${admin}' then 'administrador' else 'almacenero' end;select set_config('request.jwt.claim.sub','${admin}',false);update company_settings set configured=true,country='EC',currency='USD';insert into hr_employees(id,full_name,profile_id) values('${e1}','Empleado Uno','${own}'),('${e2}','Empleado Parcial','${other}'),('${e3}','Exempleado',null);insert into hr_employee_private(employee_id,salary,hire_date,end_date,identification) values('${e1}',1000,'2024-01-01',null,'1719304188'),('${e2}',500,'2026-01-01',null,'1719304188'),('${e3}',700,'2025-01-01','2025-12-31','1719304188');insert into financial_accounts(id,name,kind,account_id) select '${acc}','Bank QA','bank',id from accounting_accounts where code='1000';update accounting_ec_profile set payroll_expense_account_id=(select id from accounting_accounts where code='6030'),payroll_payable_account_id=(select id from accounting_accounts where code='2000'),payroll_deductions_account_id=(select id from accounting_accounts where code='2100');`);
 await as(admin);
 await t.test('no unreviewed rate or missing employee choice is silently used',async()=>{
 await assert.rejects(rpc('preview',{employee_id:e1,period:'2026-09-01',inputs:{worked_days:30}}),/PARAMETERS_REVIEW/);await rpc('parameters_save',{year:2026,parameters:params,evidence:'Reglas IESS y SBU revisadas con la contabilidad'});await assert.rejects(rpc('preview',{employee_id:e1,period:'2026-09-01',inputs:{worked_days:30}}),/EMPLOYEE_CHOICES/);
 await rpc('terms_save',{...terms,employee_id:e1});await rpc('terms_save',{...terms,employee_id:e2,work_ratio:.5,decimo13_mode:'accrued',decimo14_mode:'accrued',reserve_mode:'iess'});
 });
 await t.test('monthly, accumulated and second-year amounts are calculated on the server',async()=>{
 const c=await rpc('preview',{employee_id:e1,period:'2026-09-01',inputs:{worked_days:30}});assert.equal(c.gross,1000);assert.equal(c.personal_iess,94.5);assert.equal(c.employer_iess,111.5);assert.equal(c.decimo13,83.33);assert.equal(c.decimo14,40.17);assert.equal(c.reserve,83.3);assert.equal(c.net,1112.3);assert.equal(c.employer_cost,1318.3);
 const p=await rpc('preview',{employee_id:e2,period:'2026-09-01',inputs:{worked_days:30}});assert.equal(p.decimo14,20.08);assert.equal(p.reserve,0);assert.equal(p.net,452.75);assert.equal(p.employer_cost,617.5);
 pay=await rpc('calculate',{employee_id:e1,period:'2026-09-01',inputs:{worked_days:30}});assert.equal(pay.net,1112.3);assert.equal((await rpc('calculate',{employee_id:e1,period:'2026-09-01',inputs:{worked_days:30}})).id,pay.id);
 await q('update hr_payroll set gross=1,net=1,employer_cost=1 where id=$1',[pay.id]);assert.equal(Number(await one('select net from hr_payroll where id=$1',[pay.id])),1112.3);
 await assert.rejects(rpc('preview',{employee_id:e1,period:'2026-09-01',inputs:{worked_days:31}}),/INVALID_AMOUNT|WORKED_DAYS/);await assert.rejects(rpc('preview',{employee_id:e1,period:'2026-09-01',inputs:{worked_days:30,income_tax:2000}}),/INVALID_AMOUNT/);
 });
 await t.test('salary changes require recalculation and validation freezes totals and the ledger once',async()=>{
 await q('update hr_employee_private set salary=1100 where employee_id=$1',[e1]);await assert.rejects(q("update hr_payroll set status='validated' where id=$1",[pay.id]),/RECALCULATE/);await q('update hr_employee_private set salary=1000 where employee_id=$1',[e1]);await q("update hr_payroll set status='validated' where id=$1",[pay.id]);await q("update hr_payroll set status='validated' where id=$1",[pay.id]);
 await assert.rejects(q('update hr_payroll set net=1 where id=$1',[pay.id]),/immutable/i);await assert.rejects(rpc('calculate',{employee_id:e1,period:'2026-09-01',inputs:{worked_days:30}}),/ALREADY_VALIDATED/);assert.equal(Number(await one("select count(*) from accounting_entries where source_type='payroll' and source_id=$1",[pay.id])),1);
 const exp=await rpc('bank_export',{period:'2026-09-01'});assert.equal(exp.rows.length,1);assert.equal(exp.rows[0].account,'0001234567');assert.equal(exp.total,1112.3);
 });
 await t.test('each employee sees and acknowledges only their own validated slip',async()=>{
 await as(other);await assert.rejects(rpc('slip',{payroll_id:pay.id}),/NOT_FOUND/);await assert.rejects(rpc('parameters_save',{year:2026,parameters:params,evidence:'Forged policy'}),/ROLE_NOT_ALLOWED/);await assert.rejects(q('insert into hr_ec_parameters(year,parameters,evidence) values(2026,$1,$2)',[params,'Forged']),/permission denied/);
 await as(own);assert.equal((await rpc('slip',{payroll_id:pay.id})).employee.name,'Empleado Uno');await assert.rejects(rpc('sign',{payroll_id:pay.id,signature_png:'data:image/png;base64,FAKE'}),/SIGNATURE/);assert.equal((await rpc('list',{period:'2026-09-01'})).employees.length,1);const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aOc8AAAAASUVORK5CYII=';const sig=await rpc('sign',{payroll_id:pay.id,signature_png:png});assert.equal(sig.snapshot_hash.length,64);assert.equal((await rpc('sign',{payroll_id:pay.id,signature_png:png})).signed_at,sig.signed_at);await assert.rejects(rpc('sign',{payroll_id:uuid(),signature_png:png}),/NOT_FOUND/);await assert.rejects(rpc('bank_export',{period:'2026-09-01'}),/ROLE_NOT_ALLOWED/);await as(admin);
 });
 await t.test('partial contracts cover the minimum health premium and actual employee IR appears in draft 103',async()=>{
 await q('update hr_employee_private set salary=241 where employee_id=$1',[e2]);const c=await rpc('preview',{employee_id:e2,period:'2026-09-01',inputs:{worked_days:30,income_tax:10}});assert.equal(c.health_complement,10.63);assert.equal(c.employer_cost,318.66);assert.equal(c.net,208.23);
 const p=await rpc('calculate',{employee_id:e2,period:'2026-09-01',inputs:{worked_days:30,income_tax:10}});await q("update hr_payroll set status='validated' where id=$1",[p.id]);const tax=await one('select gama_ec_tax_drafts($1::jsonb)',[JSON.stringify({from:'2026-09-01',to:'2026-09-30'})]);assert.equal(tax.form103.payroll.withheld,10);assert.equal(tax.form103.total,10);
 await q('update hr_employee_private set salary=500 where employee_id=$1',[e2]);
 });
 await t.test('annual utilidades include former workers, dependents and part-time weights, with exact rounding',async()=>{
 await rpc('parameters_save',{year:2025,parameters:{...params,sbu:470},evidence:'Parámetros del ejercicio 2025 revisados'});
 const people=[{employee_id:e1,worked_days:360,work_ratio:1,dependents:1,evidence:'Cargas 2025 verificadas'},{employee_id:e3,worked_days:360,work_ratio:.5,dependents:2,evidence:'Cargas 2025 verificadas'}];const c=await rpc('utilities_preview',{year:2025,net_profit:10000,people});assert.equal(c.total,1500);assert.equal(c.people.length,2);assert.equal(c.people.find(p=>p.employee_id===e1).amount,916.67);assert.equal(c.people.find(p=>p.employee_id===e3).amount,583.33);assert.equal(c.people.reduce((n,p)=>n+p.amount,0),1500);
 await assert.rejects(rpc('utilities_preview',{year:2025,net_profit:10000,people:people.slice(0,1)}),/WORKFORCE_REVIEW/);await assert.rejects(rpc('utilities_preview',{year:2025,net_profit:10000,people:people.map(p=>({...p,dependents:0}))}),/ZERO_FAMILY_REVIEW/);
 const input={year:2025,net_profit:10000,people,evidence:'Declaración de renta y plantilla anual completas',request_key:uuid()};const c1=await rpc('utilities_confirm',input);assert.equal((await rpc('utilities_confirm',input)).id,c1.id);assert.equal(Number(await one('select count(*) from hr_ec_benefits where source_id=$1',[c1.id])),2);await assert.rejects(rpc('utilities_confirm',{...input,net_profit:20000}),/REQUEST_KEY_CONFLICT/);
 });
 await t.test('accumulated benefits release the existing provision once and preserve its supporting payroll',async()=>{
 await rpc('terms_save',{...terms,employee_id:e3,period:'2025-01-01',decimo13_mode:'accrued',decimo14_mode:'accrued',reserve_mode:'iess'});await assert.rejects(rpc('accrued_release',{employee_id:e3,year:2025,kind:'decimo13',evidence:'Periodo y provisión revisados'}),/MONTHS_REQUIRED/);
 let first;for(let m=1;m<=11;m++){const p=await rpc('calculate',{employee_id:e3,period:'2025-'+String(m).padStart(2,'0')+'-01',inputs:{worked_days:30}});await q("update hr_payroll set status='validated' where id=$1",[p.id]);first=first||p;}
 const before=await one("select sum(l.debit-l.credit) from accounting_entry_lines l join accounting_accounts a on a.id=l.account_id where a.code='6030'");const d={employee_id:e3,year:2025,kind:'decimo13',evidence:'Periodo y provisión revisados'};const b=await rpc('accrued_release',d);assert.equal(Number(b.amount),641.63);assert.equal((await rpc('accrued_release',d)).id,b.id);assert.equal(await one("select sum(l.debit-l.credit) from accounting_entry_lines l join accounting_accounts a on a.id=l.account_id where a.code='6030'"),before);await assert.rejects(q("update hr_payroll set status='cancelled' where id=$1",[first.id]),/ACCRUAL_ALREADY_RELEASED/);
 });
 await t.test('annual benefits pay partially once, using the real financial account, without overpayment',async()=>{
 const b=(await rpc('list',{year:2025,period:'2026-09-01'})).benefits.find(b=>b.employee_id===e3&&b.kind==='utilidades');const input={benefit_id:b.id,request_key:uuid(),amount:100,paid_on:'2026-09-30',financial_account_id:acc,reference:'Bank reviewed benefit'};const p=await rpc('benefit_payment',input);assert.equal((await rpc('benefit_payment',input)).id,p.id);await db.exec('reset role');assert.equal(Number(await one('select current_balance from private.gama_cash_position where id=$1',[acc])),-100);await as(admin);await assert.rejects(rpc('benefit_payment',{...input,reference:'Changed reference'}),/REQUEST_KEY_CONFLICT/);await assert.rejects(rpc('benefit_payment',{...input,request_key:uuid(),amount:1000}),/EXCEEDS_BALANCE/);
 });
 }finally{await db.close()}
});
