const {test,expect}=require('@playwright/test');
const fs=require('fs'),path=require('path');
const MOCK=fs.readFileSync(path.join(__dirname,'mock-gama-cloud.js'),'utf8');
async function boot(page,role='admin',extra={}){
 await page.addInitScript(({role,extra})=>{localStorage.setItem('gama_session_v1',JSON.stringify({role,name:'HR Test'}));window.__DB={products:[],suppliers:[],customers:[],invoices:[],invoice_lines:[],profiles:[{id:'u1',full_name:'Marie',role:'almacenero',active:true},{id:'manager',full_name:'Responsable',role:'almacenero',active:true}],_session:{profile_id:role==='admin'?'admin':role==='manager'?'manager':'u1'},hr_employees:[{id:'e1',full_name:'Marie',profile_id:'u1',manager_profile_id:'manager',active:true},{id:'e2',full_name:'Confidentiel',profile_id:'u2',active:true}],hr_employee_private:[{employee_id:'e1',annual_leave_days:15,salary:1500},{employee_id:'e2',annual_leave_days:20,salary:9876}],hr_absences:[],hr_absence_private:[],hr_permissions:role==='manager'?[{profile_id:'manager',role:'manager'}]:[],...extra};if(role==='manager')localStorage.setItem('gama_session_v1',JSON.stringify({role:'magasinier',name:'Manager'}))},{role,extra});
 await page.route('**/gama-supabase.js*',r=>r.fulfill({contentType:'text/javascript',body:MOCK}));await page.route('**/@supabase/**',r=>r.abort());await page.goto('/index.html');await page.waitForFunction(()=>window.GamaHRP1&&window.GamaHR);await page.evaluate(()=>window.GamaHR.open());await expect(page.locator('#hr .hrTabs')).toBeVisible();await page.waitForFunction(()=>window.GamaHRP1.directory.length>0||!['admin','administrador'].includes(JSON.parse(localStorage.getItem('gama_session_v1')).role));
}
async function tab(page,id){await page.locator(`#hr [data-tab="${id}"]`).click()}
test('leave engine splits years, holidays, half days and respects Saturday schedules',async({page})=>{
 await boot(page,'admin',{hr_holidays:[{day:'2027-01-01',label:'Holiday'}],hr_absences:[{id:'a',employee_id:'e1',kind:'vacaciones',status:'aprobada',start_date:'2026-12-30',end_date:'2027-01-04',start_fraction:.5,end_fraction:1}],hr_work_patterns:[{id:'p',employee_id:'e2',effective_from:'2026-01-01',weekdays:[6],daily_hours:4}]});
 expect(await page.evaluate(()=>[GamaHRP1.used('e1',2026),GamaHRP1.used('e1',2027),GamaHRP1.days('e2','2026-09-11','2026-09-13')])).toEqual([1.5,1,1]);
});
test('monthly accrual prorates employment and adds carryover once',async({page})=>{
 await boot(page,'admin',{hr_leave_accounts:[{id:'l',employee_id:'e1',year:2026,entitlement:24,carryover:2,adjustment:-.5,accrual_mode:'monthly',active_from:'2026-02-01'}]});
 const actual=await page.evaluate(()=>GamaHRP1.entitlement('e1',2026,'2026-04-15'));expect(actual).toBeCloseTo(Math.round(24*59/365*100)/100+1.5,2);
});
test('rules form saves employee/year and working pattern',async({page})=>{
 await boot(page);await tab(page,'reglas');await page.fill('#hpWeekdays','1,2,3,4,5,6');await page.fill('#hpDailyHours','7');await page.click('#hpPatternSave');await expect.poll(()=>page.evaluate(()=>window.__DB.hr_work_patterns?.length)).toBe(1);
 await page.fill('#hpEntitlement','18');await page.fill('#hpCarryover','2');await page.fill('#hpLeaveReason','Opening approved');await page.click('#hpLeaveSave');await expect.poll(()=>page.evaluate(()=>window.__DB.hr_leave_accounts?.[0]?.entitlement)).toBe(18);expect(await page.evaluate(()=>window.__DB.hr_leave_accounts[0].carryover)).toBe(2);
});
test('half-day request captures fractions and cancellation retains row',async({page})=>{
 await boot(page,'magasinier');await tab(page,'misDias');await page.selectOption('#hpStartFraction','0.5');await page.fill('#hrAbsFrom','2026-10-05');await page.fill('#hrAbsTo','2026-10-05');await page.click('#hrAbsAdd');await expect.poll(()=>page.evaluate(()=>window.__DB.hr_absences.length)).toBe(1);expect(await page.evaluate(()=>window.__DB.hr_absences[0].start_fraction)).toBe(.5);
 page.on('dialog',d=>d.accept('Cancelled by employee'));await page.locator('#hr [data-del]').click();await expect.poll(()=>page.evaluate(()=>window.__DB.hr_absences[0].status)).toBe('cancelada');expect(await page.evaluate(()=>window.__DB.hr_absences.length)).toBe(1);
});
test('manager can approve team requests without salary or admin controls',async({page})=>{
 await boot(page,'manager',{hr_absences:[{id:'a',employee_id:'e1',start_date:'2026-10-05',end_date:'2026-10-05',kind:'vacaciones',status:'pendiente'}]});await expect(page.locator('#hr [data-tab="permisos"]')).toHaveCount(0);await expect(page.locator('#hr')).not.toContainText('9.876');await tab(page,'validaciones');await page.locator('[data-absence-status="aprobada"]').click();await expect.poll(()=>page.evaluate(()=>window.__DB.hr_absences[0].status)).toBe('aprobada');
});
test('multiple daily clock sessions share the scheduled hours once',async({page})=>{
 const records=[{id:'a',employee_id:'e1',started_at:'2026-09-10T13:00:00Z',ended_at:'2026-09-10T17:00:00Z',break_seconds:0,status:'approved'},{id:'b',employee_id:'e1',started_at:'2026-09-10T18:00:00Z',ended_at:'2026-09-11T00:00:00Z',break_seconds:3600,status:'pending'}];await boot(page,'admin',{hr_attendance:records});
 expect(await page.evaluate(()=>window.__DB.hr_attendance.map(a=>[GamaHRP1.hours(a),GamaHRP1.overtime(a)]))).toEqual([[4,0],[5,1]]);
});
test('payroll KPI uses validated cost once and subtracts partial payments',async({page})=>{
 const month=new Date().toISOString().slice(0,7);await boot(page,'admin',{hr_payroll:[{id:'p1',employee_id:'e1',period:month+'-01',source_ref:'SAL-1',gross:1000,net:800,employer_cost:1200,status:'validated',cost_center:'Warehouse'},{id:'p2',employee_id:'e2',period:month+'-01',source_ref:'SAL-2',gross:3000,net:2000,employer_cost:4000,status:'draft'}],hr_payroll_payments:[{id:'pay1',payroll_id:'p1',paid_on:month+'-03',amount:300,reference:'BANK-1',status:'confirmed'},{id:'pay2',payroll_id:'p1',paid_on:month+'-03',amount:200,reference:'BANK-2',status:'cancelled'}]});await tab(page,'nomina');const texts=await page.locator('.hpKpis strong').allTextContents();expect(texts.map(s=>Number(s.replace(/[^\d]/g,''))/100)).toEqual([1200,800,300,500]);
});
test('CSV import previews rows and refuses duplicate employee month before write',async({page})=>{
 await boot(page);await tab(page,'nomina');await page.locator('summary:has-text("Importar CSV")').click();const csv='employee_id,period,source_ref,gross,net,employer_cost,cost_center\ne1,2026-10-01,EXT-1,1000,800,1200,"Entrepôt, nord"';await page.setInputFiles('#hpCsvFile',{name:'payroll.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});await expect(page.locator('#hpCsvPreview')).toContainText('Marie');await expect(page.locator('#hpCsvConfirm')).toBeVisible();expect(await page.evaluate(()=>GamaHRP1.parseCSV('employee_id,period,source_ref,gross,net,employer_cost,cost_center\ne1,2026-10-01,EXT-1,1000,800,1200,"Entrepôt, nord"')[0].cost_center)).toBe('Entrepôt, nord');
 await page.setInputFiles('#hpCsvFile',{name:'duplicates.csv',mimeType:'text/csv',buffer:Buffer.from(csv+'\ne1,2026-10-01,EXT-2,1000,800,1200,North')});await expect(page.locator('#hpError')).toContainText('duplicada');await expect(page.locator('#hpCsvConfirm')).toHaveCount(0);expect(await page.evaluate(()=>window.__DB.hr_payroll?.length||0)).toBe(0);
});
test('new HR interface switches French English Spanish without translating names',async({page})=>{
 await page.setViewportSize({width:390,height:844});await boot(page,'admin');await page.evaluate(()=>GamaI18n.setLanguage('fr'));await tab(page,'nomina');await expect(page.locator('#hpPayrollSave')).toContainText('Enregistrer le brouillon');await page.fill('#hpPayrollRef','Référence à conserver');await page.evaluate(()=>GamaI18n.setLanguage('en'));await expect(page.locator('#hpPayrollSave')).toContainText('Save draft');await expect(page.locator('#hpPayrollRef')).toHaveValue('Référence à conserver');await page.evaluate(()=>GamaI18n.setLanguage('es'));await expect(page.locator('#hpPayrollSave')).toContainText('Guardar borrador');await page.screenshot({path:'test-results/hr-p1-mobile.png',fullPage:true});
});
test('valid CSV import writes one atomic batch after explicit confirmation',async({page})=>{
 await boot(page);await page.evaluate(()=>{const old=GamaCloud.db;GamaCloud.db=async()=>({...await old(),from:table=>({insert:async rows=>{window.__csvWrites=(window.__csvWrites||0)+1;window.__DB[table]=rows.map((r,i)=>({id:'csv'+i,status:'draft',...r}));return {data:rows,error:null}}})})});await tab(page,'nomina');await page.locator('summary:has-text("Importar CSV")').click();await page.setInputFiles('#hpCsvFile',{name:'payroll.csv',mimeType:'text/csv',buffer:Buffer.from('employee_id,period,source_ref,gross,net,employer_cost,cost_center\ne1,2026-10-01,IMPORT-1,1000,800,1200,North\ne2,2026-10-01,IMPORT-2,1500,1200,1700,South')});await expect(page.locator('#hpCsvConfirm')).toBeVisible();expect(await page.evaluate(()=>window.__csvWrites||0)).toBe(0);await page.click('#hpCsvConfirm');await expect.poll(()=>page.evaluate(()=>window.__csvWrites)).toBe(1);expect(await page.evaluate(()=>window.__DB.hr_payroll.length)).toBe(2);
});
test('private document upload records version metadata and a scoped storage path',async({page})=>{
 await boot(page);await page.evaluate(()=>{const old=GamaCloud.db;GamaCloud.db=async()=>({...await old(),storage:{from:bucket=>({upload:async(path,file)=>{window.__upload={bucket,path,type:file.type};return {data:{path},error:null}}})}})});await tab(page,'documentos');await page.selectOption('#hpDocEmployee','e1');await page.fill('#hpDocTitle','Contrat signé');await page.setInputFiles('#hpDocFile',{name:'contract.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n%%EOF')});await page.click('#hpDocSave');await expect.poll(()=>page.evaluate(()=>window.__DB.hr_documents?.length)).toBe(1);const row=await page.evaluate(()=>window.__DB.hr_documents[0]);expect(row.employee_id).toBe('e1');expect(row.storage_path).toMatch(/^e1\/.+\.pdf$/);expect(row.title).toBe('Contrat signé');expect(await page.evaluate(()=>window.__upload.bucket)).toBe('hr-documents');
});
test('mobile attendance buttons call the clock workflow and update open state',async({page})=>{
 await boot(page,'magasinier');await page.evaluate(()=>{const old=GamaCloud.db;GamaCloud.db=async()=>{const db=await old();return {...db,rpc:async(fn,args)=>{if(fn!=='gama_hr_clock')return db.rpc(fn,args);window.__clockActions=(window.__clockActions||[]).concat(args.p_action);window.__DB.hr_attendance=window.__DB.hr_attendance||[];if(args.p_action==='in')window.__DB.hr_attendance.push({id:'clock',employee_id:'e1',started_at:'2026-09-13T08:00:00Z',break_seconds:0,status:'open'});if(args.p_action==='out')Object.assign(window.__DB.hr_attendance[0],{ended_at:'2026-09-13T17:00:00Z',status:'pending'});return {data:{},error:null}}}}});await tab(page,'tiempo');await page.locator('[data-clock="in"]').click();await expect(page.locator('[data-clock="in"]')).toBeDisabled();await page.locator('[data-clock="out"]').click();await expect(page.locator('[data-clock="in"]')).toBeEnabled();expect(await page.evaluate(()=>window.__clockActions)).toEqual(['in','out']);
});
