const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto'),{spawnSync}=require('node:child_process');
const ctx={window:{},TextEncoder,btoa,atob,crypto};vm.runInNewContext(fs.readFileSync(__dirname+'/../src/domain/marketing-mail.js','utf8'),ctx);const build=ctx.window.CocoMarketingMail.build;
test('MIME draft independently parses recipient, Unicode subject/body/names and exact binary attachment bytes',()=>{
 const bytes=Buffer.from(Array.from({length:256},(_,i)=>i)),name='Présentation "été" 🥭 '+('é'.repeat(90))+'.pdf',draft={channel:'email',address:'customer+campaign@example.invalid',subject:'Offre spéciale 🥭 '+('été '.repeat(40)),message:'Bonjour Ana,\nDécouvrez notre offre à Quito.\nÀ bientôt !'};
 const files=[{filename:name,mime_type:'application/pdf',size:bytes.length,content_base64:bytes.toString('base64')},{filename:'Résumé.csv',mime_type:'text/csv',size:4,content_base64:'AAECAw=='}];const eml=build(draft,files);
 const parsed=spawnSync('python3',['-c',"import sys,json,base64\nfrom email import policy\nfrom email.parser import BytesParser\nm=BytesParser(policy=policy.default).parsebytes(sys.stdin.buffer.read())\nprint(json.dumps({'to':m['To'],'subject':m['Subject'],'unsent':m['X-Unsent'],'body':m.get_body(preferencelist=('plain',)).get_content(),'defects':[str(x) for p in m.walk() for x in p.defects],'files':[{'name':p.get_filename(),'mime':p.get_content_type(),'data':base64.b64encode(p.get_payload(decode=True)).decode()} for p in m.iter_attachments()]}))"],{input:eml,encoding:'utf8'});
 assert.equal(parsed.status,0,parsed.stderr);const result=JSON.parse(parsed.stdout);assert.equal(result.to,draft.address);assert.equal(result.subject,draft.subject);assert.equal(result.unsent,'1');assert.equal(result.body,draft.message);assert.deepEqual(result.defects,[]);assert.equal(result.files[0].name,name);assert.deepEqual(Buffer.from(result.files[0].data,'base64'),bytes);assert.equal(result.files[1].name,'Résumé.csv');assert.equal(result.files[1].data,'AAECAw==');assert.ok(eml.split('\r\n').every(line=>line.length<=998));assert.ok(!eml.includes('\r\nFrom:'));
});
test('MIME builder rejects header injection, corrupted bytes and false attachment sizes',()=>{
 const draft={channel:'email',address:'a@example.invalid',subject:'Subject',message:'Text'},file={filename:'file.pdf',mime_type:'application/pdf',size:4,content_base64:'AAECAw=='};
 for(const d of [{...draft,address:'a@example.invalid\r\nBcc: x@example.invalid'},{...draft,subject:'Subject\nBcc: x'},{...draft,channel:'whatsapp'}])assert.throws(()=>build(d,[file]),/INVALID_DATA/);
 for(const f of [{...file,filename:'file\r\nInjected.pdf'},{...file,size:5},{...file,mime_type:'application/pdf\r\nInjected'},{...file,content_base64:'bad%'}])assert.throws(()=>build(draft,[f]),/FILE_FORMAT/);
});
