const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID:uuid}=require('node:crypto'),{restore}=require('../scripts/restore-schema.cjs');
test('Messages require preferences and fresh delegation, retry with one provider key, follow real status and stop after source resolution',async()=>{
 const db=await restore(),admin=uuid(),customer=uuid(),order=uuid(),invoice=uuid();const q=(s,p=[])=>db.query(s,p),one=async(s,p=[])=>Object.values((await q(s,p)).rows[0])[0];const as=()=>db.exec(`reset role;select set_config('request.jwt.claim.sub','${admin}',false);set role authenticated`);const rpc=(n,a,d={})=>one('select '+n+'($1,$2)',[a,d]);const run=async()=>{await db.exec('reset role');await one('select private.automation_run(30)');await as()};const scan=async()=>{await rpc('gama_automation','run_once',{kind:'reminders',request_key:uuid()});await run()};
 try{
 await q('insert into auth.users(id,email) values($1,$2)',[admin,'outbox-admin@example.invalid']);await q("update profiles set active=true,role='administrador' where id=$1",[admin]);await q("insert into customers(id,name,email) values($1,'Customer','outbox-customer@example.invalid')",[customer]);await q("select set_config('request.jwt.claim.sub',$1,false)",[admin]);await db.exec('set session_replication_role=replica');await q("insert into sales_orders(id,number,customer_id,customer_name,request_key,status,created_by) values($1,'OUT-O',$2,'Customer',gen_random_uuid(),'confirmed',$3)",[order,customer,admin]);await q("insert into external_invoices(id,request_key,order_id,number,issue_date,due_date,subtotal,tax,fiscal_status,issuer_ruc,created_by) values($1,gen_random_uuid(),$2,'OUT-I',current_date-10,current_date-5,100,15,'unverified','1790012345001',$3)",[invoice,order,admin]);await db.exec('set session_replication_role=origin');await as();
 await rpc('gama_automation','rule_save',{kind:'reminders',expected_version:1,enabled:true,config:{interval_days:7},delegation_days:30});await scan();await db.exec('reset role');assert.equal(Number(await one('select count(*) from private.message_outbox')),0);await as();
 await rpc('gama_messages','configure',{sender:'sender@example.invalid',api_key:'isolated-fixture-key',enabled:true});await scan();await db.exec('reset role');assert.equal(Number(await one('select count(*) from private.message_outbox')),0);await as();await rpc('gama_messages','preferences_save',{customer_id:customer,invoice_reminders:true,surveys:false,evidence:'Customer explicitly requested invoice reminders'});await scan();await scan();
 await db.exec('reset role');assert.equal(Number(await one('select count(*) from private.message_outbox')),1);await one('select private.message_dispatch()');let msg=(await q('select * from private.message_outbox')).rows[0];assert.equal(msg.state,'dispatching');const first=(await q('select * from net.fixture_requests')).rows[0];assert.equal(first.url,'https://api.resend.com/emails');assert.equal(first.body.to[0],'outbox-customer@example.invalid');
 await q('update private.message_outbox set next_poll_at=now(),lease_until=now()-interval \'1 minute\' where id=$1',[msg.id]);await one('select private.message_dispatch()');await q('update private.message_outbox set next_poll_at=now()');await one('select private.message_dispatch()');const requests=(await q('select * from net.fixture_requests order by id')).rows;assert.equal(requests.length,2);assert.equal(requests[0].headers['Idempotency-Key'],requests[1].headers['Idempotency-Key']);assert.deepEqual(requests[0].body,requests[1].body);
 msg=(await q('select * from private.message_outbox')).rows[0];const provider=uuid();await q('insert into net._http_response(id,status_code,content) values($1,200,$2)',[msg.request_id,JSON.stringify({id:provider})]);await q('update private.message_outbox set next_poll_at=now()');await one('select private.message_dispatch()');assert.equal(await one('select state from private.message_outbox'),'accepted');await q('update private.message_outbox set next_poll_at=now()');await one('select private.message_dispatch()');msg=(await q('select * from private.message_outbox')).rows[0];await q('insert into net._http_response(id,status_code,content) values($1,200,$2)',[msg.request_id,JSON.stringify({id:provider,last_event:'delivered'})]);await q('update private.message_outbox set next_poll_at=now()');await one('select private.message_dispatch()');assert.equal(await one('select state from private.message_outbox'),'delivered');assert.equal(Number(await one('select count(*) from private.automation_execution_context')),0);
 await q("update private.message_outbox set key=key||':old'");await as();await scan();await db.exec('reset role');await q("update profiles set active=false where id=$1",[admin]);await one('select private.message_dispatch()');assert.equal(Number(await one("select count(*) from private.message_outbox where state='cancelled'")),1);assert.equal(Number(await one('select count(*) from net.fixture_requests')),3);
 }finally{await db.close()}
});
