const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID:uuid}=require('node:crypto'),{restore}=require('../scripts/restore-schema.cjs');
test('Manual mail drafts need preferences, never dispatch, require confirmation and cancel withdrawn recipients',async()=>{
 const db=await restore(),admin=uuid(),customer=uuid(),order=uuid(),invoice=uuid();const q=(s,p=[])=>db.query(s,p),one=async(s,p=[])=>Object.values((await q(s,p)).rows[0])[0];const as=()=>db.exec(`reset role;select set_config('request.jwt.claim.sub','${admin}',false);set role authenticated`);const rpc=(n,a,d={})=>one('select '+n+'($1,$2)',[a,d]);const run=async()=>{await db.exec('reset role');await one('select private.automation_run(30)');await as()};const scan=async()=>{await rpc('gama_automation','run_once',{kind:'reminders',request_key:uuid()});await run()};
 try{
 await q('insert into auth.users(id,email) values($1,$2)',[admin,'outbox-admin@example.invalid']);await q("update profiles set active=true,role='administrador' where id=$1",[admin]);await q("insert into customers(id,name,email) values($1,'Customer','outbox-customer@example.invalid')",[customer]);await q("select set_config('request.jwt.claim.sub',$1,false)",[admin]);await db.exec('set session_replication_role=replica');await q("insert into sales_orders(id,number,customer_id,customer_name,request_key,status,created_by) values($1,'OUT-O',$2,'Customer',gen_random_uuid(),'confirmed',$3)",[order,customer,admin]);await q("insert into external_invoices(id,request_key,order_id,number,issue_date,due_date,subtotal,tax,fiscal_status,issuer_ruc,created_by) values($1,gen_random_uuid(),$2,'OUT-I',current_date-10,current_date-5,100,15,'unverified','1790012345001',$3)",[invoice,order,admin]);await q("insert into external_invoices(id,request_key,order_id,number,issue_date,due_date,subtotal,tax,fiscal_status,issuer_ruc,created_by) values($1,gen_random_uuid(),$2,'OUT-II',current_date-10,current_date-5,100,15,'unverified','1790012345001',$3)",[uuid(),order,admin]);await db.exec('set session_replication_role=origin');await as();
 await rpc('gama_automation','rule_save',{kind:'reminders',expected_version:1,enabled:true,config:{interval_days:7},delegation_days:30});await scan();await db.exec('reset role');assert.equal(Number(await one('select count(*) from private.message_outbox')),0);await as();
 await assert.rejects(rpc('gama_messages','configure',{sender:'sender@example.invalid',api_key:'not-used',enabled:true}),/MANUAL_MAIL_ONLY/);
 await rpc('gama_messages','preferences_save',{customer_id:customer,invoice_reminders:true,surveys:false,evidence:'Customer explicitly requested invoice reminders'});await scan();await scan();
 const context=await rpc('gama_messages','context');assert.equal(context.mode,'manual');assert.equal(context.outbox.length,2);assert.equal(context.outbox[0].recipient,'outbox-customer@example.invalid');
 const first=context.outbox.find(m=>m.source_id===invoice),second=context.outbox.find(m=>m.source_id!==invoice);
 const draft=await rpc('gama_messages','draft',{id:first.id});assert.equal(draft.state,'draft');assert.ok(draft.body.includes('OUT-I'));assert.equal(draft.recipient,'outbox-customer@example.invalid');
 await assert.rejects(rpc('gama_messages','manual_sent',{id:first.id,confirmed:false}),/MANUAL_SEND_CONFIRMATION_REQUIRED/);
 const sent=await rpc('gama_messages','manual_sent',{id:first.id,confirmed:true});assert.equal(sent.state,'sent_manually');assert.equal(sent.manual_sent_by,admin);const again=await rpc('gama_messages','manual_sent',{id:first.id,confirmed:true});assert.equal(again.manual_sent_at,sent.manual_sent_at);
 await rpc('gama_messages','preferences_save',{customer_id:customer,invoice_reminders:false,surveys:false,evidence:'Customer withdrew reminder preference'});
 const cancelled=await rpc('gama_messages','draft',{id:second.id});assert.equal(cancelled.state,'cancelled');assert.equal(cancelled.body,undefined);
 await db.exec('reset role');assert.equal((await one('select private.message_dispatch()')).dispatched,0);assert.equal(Number(await one('select count(*) from net.fixture_requests')),0);assert.equal(Number(await one("select count(*) from cron.job where jobname in ('coco-message-dispatch','coco-road-matrix')")),0);assert.equal(Number(await one("select count(*) from private.message_outbox where state='delivered'")),0);
 await q("update profiles set active=false where id=$1",[admin]);await as();await assert.rejects(rpc('gama_messages','context'),/ROLE_NOT_ALLOWED/);await db.exec('reset role');
 await db.exec('set role anon');await assert.rejects(rpc('gama_messages','context'),/permission denied/);await assert.rejects(q('select * from private.message_outbox'),/permission denied/);
 }finally{await db.close()}
});
