const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID:uuid}=require('node:crypto'),{restore}=require('../scripts/restore-schema.cjs');
test('Lots require received quantity identification, preserve transfers, enforce expiry and retry identity',async()=>{const db=await restore(),admin=uuid(),product=uuid();const rpc=async(n,...args)=>(await db.query('select public.'+n+'('+args.map((_,i)=>'$'+(i+1)).join(',')+') r',args)).rows[0].r;try{
 await db.exec(`insert into auth.users(id,email) values('${admin}','lots@example.invalid');update profiles set active=true,role='administrador' where id='${admin}';select set_config('request.jwt.claim.sub','${admin}',false);insert into products(id,name,barcode,lot_tracking) values('${product}','Tracked goods','LOT-GOODS',true);set role authenticated;`);
 await rpc('gama_register_stock_movement',product,'in',10,'Supplier receipt','RCPT-01');const inbound=(await db.query('select * from stock_movements where product_id=$1',[product])).rows[0];
 await assert.rejects(rpc('gama_register_stock_movement',product,'out',1,'Issue untracked','TEST'),/IDENTIFY_RECEIVED_LOTS_OR_CHECK_EXPIRY/);
 let context=await rpc('gama_lots','context',{product_id:product});assert.equal(context.pending[0].remaining,10);const input={product_id:product,movement_id:inbound.id,code:'LOT-A',expires_on:'2099-01-01',quantity:6,request_key:uuid()};const lot=await rpc('gama_lots','identify',input);assert.equal((await rpc('gama_lots','identify',input)).id,lot.id);await assert.rejects(rpc('gama_lots','identify',{...input,quantity:5}),/REQUEST_KEY_CONFLICT/);
 await rpc('gama_lots','identify',{...input,code:'LOT-EXPIRED',expires_on:'2000-01-01',quantity:4,request_key:uuid()});await assert.rejects(rpc('gama_lots','identify',{...input,quantity:1,request_key:uuid()}),/LOT_QUANTITY_EXCEEDED/);
 const plan=await rpc('gama_lot_pick_plan',product,inbound.destination_location_id,3);assert.equal(plan.length,1);assert.equal(plan[0].code,'LOT-A');
 await rpc('gama_register_stock_movement',product,'out',3,'Customer issue','ISSUE-01');context=await rpc('gama_lots','context',{product_id:product});assert.equal(context.pending.length,0);assert.equal(context.balances.find(b=>b.code==='LOT-A').quantity,3);assert.equal(context.balances.find(b=>b.code==='LOT-EXPIRED').quantity,4);
 await assert.rejects(rpc('gama_register_stock_movement',product,'out',4,'Expired issue','ISSUE-02'),/IDENTIFY_RECEIVED_LOTS_OR_CHECK_EXPIRY/);
 const source=(await db.query('select warehouse_id from warehouse_locations where id=$1',[inbound.destination_location_id])).rows[0];const dest=(await db.query("insert into warehouse_locations(warehouse_id,code,name) values($1,'LOT-DEST','Lot destination') returning id",[source.warehouse_id])).rows[0].id;
 await rpc('gama_stock_transfer',product,inbound.destination_location_id,dest,2,'Internal transfer','MOVE-01');context=await rpc('gama_lots','context',{product_id:product});assert.equal(context.balances.find(b=>b.code==='LOT-EXPIRED'&&b.location_id===dest).quantity,2);assert.ok(context.history.some(h=>h.source_location_id===inbound.destination_location_id&&h.destination_location_id===dest&&h.quantity===2));
 await assert.rejects(db.query('update products set lot_tracking=false where id=$1',[product]),/LOT_MODE_REQUIRES_ZERO_STOCK|LOT_MODE_ALREADY_USED/);
 }finally{await db.close()}});
