const {test,expect}=require('@playwright/test'),fs=require('node:fs'),{randomUUID:uuid}=require('node:crypto');
const {restore}=require('../scripts/restore-schema.cjs');
const mock=fs.readFileSync(__dirname+'/mock-gama-cloud.js','utf8');
async function boot(page){const db=await restore(),admin=uuid(),customer=uuid(),product=uuid(),unit=uuid(),account=uuid();await db.exec(`insert into auth.users(id,email) values('${admin}','browser-p1@example.invalid');update profiles set active=true,role='administrador' where id='${admin}';select set_config('request.jwt.claim.sub','${admin}',false);insert into customers(id,name) values('${customer}','Client P1');insert into products(id,name,barcode,sale_price,purchase_price) values('${product}','Article P1','5901234123457',12,5);insert into product_units(id,product_id,label,factor,barcode) values('${unit}','${product}','Carton 12',12,'BOX-P1');insert into financial_accounts(id,name,kind,account_id) select '${account}','Banque P1','bank',id from accounting_accounts where code='1000';set role authenticated;`);
 const safe=s=>{if(!/^[a-z_][a-z0-9_]*$/i.test(s))throw Error('TEST_IDENTIFIER');return '"'+s+'"'};
 await page.exposeFunction('__erpRpc',async(fn,args={})=>{try{const entries=Object.entries(args);return {data:(await db.query('select public.'+safe(fn)+'('+entries.map(([k],i)=>safe(k)+'=> $'+(i+1)).join(',')+') r',entries.map(([,v])=>v))).rows[0].r}}catch(e){return {error:{message:e.message,code:e.code}}}});
 await page.exposeFunction('__erpList',async(table,opts={})=>{try{const params=[],where=[];for(const [k,v] of Object.entries(opts.eq||{})){params.push(v);where.push(safe(k)+'=$'+params.length)}for(const [k,v] of Object.entries(opts.in||{})){params.push(v);where.push(safe(k)+'=any($'+params.length+')')}const sql=' from public.'+safe(table)+(where.length?' where '+where.join(' and '):'');const select=opts.select&&opts.select!=='*'?opts.select.split(',').map(safe).join(','):'*';const order=typeof opts.order==='string'?' order by '+safe(opts.order)+(opts.ascending===false?' desc':' asc'):'';const start=opts.range?.[0]||0,limit=opts.range?opts.range[1]-start+1:opts.limit||200;return {data:opts.head?[]:(await db.query('select '+select+sql+order+' limit '+Number(limit)+' offset '+Number(start),params)).rows,count:(await db.query('select count(*)::int n'+sql,params)).rows[0].n,error:null}}catch(e){return {data:[],error:{message:e.message}}}});
 await page.addInitScript(()=>{localStorage.setItem('gama_session_v1',JSON.stringify({role:'admin',name:'Test P1'}));localStorage.setItem('gama_language_v1','fr')});
 await page.route('https://**/*',r=>r.abort());
 await page.route('**/gama-supabase.js*',r=>r.fulfill({contentType:'text/javascript',body:mock+`;(()=>{const old=GamaCloud.db;GamaCloud.db=async()=>{const c=await old();return {...c,rpc:(fn,args)=>window.__erpRpc(fn,args)}};GamaCloud.list=(table,opts)=>window.__erpList(table,opts);})();`}));
 await page.goto('/index.html');await page.waitForFunction(()=>window.GamaRoleAccess?.isReady()&&window.ArchitectBarcode);return {db,admin,customer,product,unit,account};
}
test('Connection library loads locally when external hosts are unavailable',async({page})=>{await page.route('https://**/*',r=>r.abort());await page.goto('/index.html');await page.waitForFunction(()=>typeof window.supabase?.createClient==='function');expect(await page.evaluate(()=>[...document.scripts].some(s=>s.src.includes('assets/vendor/supabase-2.115.0.js')))).toBe(true)});
test('Item and pack codes generate readable batch labels on mobile, invalid check digits fail',async({page})=>{await page.setViewportSize({width:390,height:844});const {db}=await boot(page);try{
 const encoded=await page.evaluate(()=>({ean:eanBits('5901234123457'),c39:code39Bits('A')}));expect(encoded.ean[0]).toHaveLength(95);expect(encoded.ean[1]).toBe('5901234123457');expect(encoded.c39).toBe('1001011011010'+'1101010010110'+'1001011011010');expect(await page.evaluate(()=>{try{eanBits('5901234123458');return false}catch{return true}})).toBe(true);
 await page.evaluate(()=>ArchitectBarcode.batch());await page.locator('dialog [name=codes]').fill('5901234123457;2\nBOX-P1;1');const download=page.waitForEvent('download');await page.locator('dialog [type=submit]').click();expect((await download).suggestedFilename()).toBe('architect-labels.pdf');await expect(page.locator('dialog')).toHaveCount(0);
 await page.evaluate(()=>ArchitectBarcode.identify());await page.locator('#identifyCode').fill('BOX-P1');await page.locator('dialog [type=submit]').click();await expect(page.locator('dialog')).toContainText('Carton 12 = 12 unit');expect(await page.locator('dialog').evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true);
 }finally{await db.close()}});
test('Credit settings and access restrictions save through protected commands',async({page})=>{const {db,customer}=await boot(page);try{
 await page.evaluate(id=>ArchitectPartners.open('customer',id),customer);await page.locator('[data-credit]').click();await page.locator('dialog').last().locator('[name=credit_limit]').fill('500');await page.locator('dialog').last().locator('[name=credit_hold_reason]').fill('Vérifier le paiement');await page.locator('dialog').last().locator('[type=submit]').click();await expect(page.locator('dialog')).toContainText('Vérifier le paiement');await page.locator('dialog [data-arc-dialog-close]').click();
 await page.evaluate(()=>ArchitectAccessControls.permissions());await page.locator('#actionRole').selectOption('comercial');await page.locator('[data-action-module=products] [data-action=create]').uncheck();await page.locator('dialog [type=submit]').click();await expect(page.locator('dialog')).toHaveCount(0);expect((await db.query("select allow_create from erp_action_permissions where role='comercial' and module='products'")).rows[0].allow_create).toBe(false);
 await page.evaluate(()=>ArchitectAccessControls.reviews());await page.locator('[name=next_review]').fill('2099-01-01');await page.locator('[name=note]').fill('Revue P1 : droits vérifiés');await page.locator('dialog [type=submit]').click();await expect(page.locator('dialog')).toHaveCount(0);expect((await db.query('select count(*)::int n from erp_access_reviews')).rows[0].n).toBe(1);
 }finally{await db.close()}});
test('Deposit form creates one receipt and balanced cash entry with the chosen account',async({page})=>{const {db,customer,account}=await boot(page);try{
 await page.evaluate(()=>ArchitectFinanceControls.receipts());await page.locator('[data-receive]').click();const form=page.locator('dialog').last();await form.locator('[name=customer_id]').selectOption(customer);await form.locator('[name=financial_account_id]').selectOption(account);await form.locator('[name=amount]').fill('150');await form.locator('[name=method]').selectOption('transfer');await form.locator('[name=reference]').fill('BANK-P1-150');await form.locator('[type=submit]').click();await expect(page.locator('dialog')).toContainText('BANK-P1-150');const receipt=(await db.query('select * from customer_receipts')).rows;expect(receipt).toHaveLength(1);expect(receipt[0].financial_account_id).toBe(account);
 }finally{await db.close()}});
test('Service execution form records actual work without creating a shipment',async({page})=>{const {db,customer}=await boot(page);try{
 const pid=uuid();await db.query("insert into products(id,name,barcode,product_kind,base_unit,sale_price) values($1,'Installation P1','SERVICE-UI','service','hour',50)",[pid]);
 const order=await page.evaluate(async({customer,pid})=>{const r=await ArcData.rpc('gama_sales_action',{p_action:'create',p_data:{source:'manual',request_key:crypto.randomUUID(),customer_id:customer,delivery_address:'Customer site',lines:[{product_id:pid,quantity:2,unit_price:50,tax_rate:15}]}});await ArcData.rpc('gama_sales_action',{p_action:'confirm',p_data:{order_id:r.id}});return r},{customer,pid});
 await page.evaluate(id=>ArchitectServiceProducts.open(id),order.id);await page.locator('[data-perform]').click();const form=page.locator('dialog').last();await form.locator('[name=quantity]').fill('1');await form.locator('[name=evidence]').fill('Compte rendu P1 signé');await form.locator('[type=submit]').click();await expect(page.locator('[data-service-products]')).toHaveCount(1);await expect(page.locator('[data-service-products]')).toContainText('Compte rendu P1 signé');expect((await db.query('select count(*)::int n from sales_service_completions')).rows[0].n).toBe(1);expect((await db.query('select count(*)::int n from sales_deliveries')).rows[0].n).toBe(0);
 }finally{await db.close()}});
test('Lot receiving form identifies stock and picker must confirm each lot code',async({page})=>{const {db,product}=await boot(page);try{
 await db.query('update products set lot_tracking=true where id=$1',[product]);await db.query("select gama_register_stock_movement($1,'in',5,'UI receipt','RCPT-UI')",[product]);
 await page.evaluate(id=>ArchitectLots.open(id),product);await page.locator('[data-identify-lot]').click();const form=page.locator('dialog').last();await form.locator('[name=code]').fill('LOT-UI-A');await form.locator('[name=expires_on]').fill('2099-12-31');await form.locator('[type=submit]').click();await expect(page.locator('[data-lot-controls]')).toContainText('LOT-UI-A');await page.locator('[data-lot-controls] [data-arc-dialog-close]').click();
 const location=(await db.query('select location_id from stock_lot_balances')).rows[0].location_id;await page.evaluate(({product,location})=>{window.__pickResult='pending';ArchitectLots.confirmPick(product,location,2).then(r=>window.__pickResult=r)},{product,location});await page.locator('dialog [name=lot0]').fill('WRONG-LOT');await page.locator('dialog [type=submit]').click();await expect(page.locator('dialog [role=alert]')).toContainText('Le code ne correspond');await page.locator('dialog [name=lot0]').fill('LOT-UI-A');await page.locator('dialog [type=submit]').click();await page.waitForFunction(()=>Array.isArray(window.__pickResult));expect(await page.evaluate(()=>__pickResult[0].quantity)).toBe(2);
 }finally{await db.close()}});
