const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID:uuid}=require('node:crypto');
const {restore}=require('../scripts/restore-schema.cjs');
test('Dated pricing, scoped catalog, atomic submission and retry safety',async()=>{const db=await restore(),admin=uuid(),buyer=uuid(),other=uuid(),customer=uuid(),second=uuid(),product=uuid();
 const as=async id=>db.exec(`reset role;select set_config('request.jwt.claim.sub','${id}',false);set role authenticated`);
 const rpc=async(name,args)=>(await db.query(`select ${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;
 try{await db.exec(`insert into auth.users(id,email) values('${admin}','admin-price@example.invalid'),('${buyer}','buyer-price@example.invalid'),('${other}','other-price@example.invalid');update profiles set active=true,role=case when id='${admin}' then 'administrador' else 'cliente' end;insert into customers(id,name,email,category) values('${customer}','Buyer','buyer-price@example.invalid','A'),('${second}','Other','other-price@example.invalid','B');insert into products(id,name,reference,barcode,sale_price,sale_price_b,tax_rate) values('${product}','Item','PRICE1','PRICE1',20,22,15);`);
 await as(admin);const data={request_key:uuid(),name:'Contract',kind:'contract',valid_from:'2020-01-01',valid_to:'2099-12-31',customers:[customer],lines:[{product_id:product,min_quantity:1,unit_price:18},{product_id:product,min_quantity:10,unit_price:15}]};
 const book=await rpc('gama_price_book_action',['save',data]);assert.deepEqual(await rpc('gama_price_book_action',['save',data]),book);
 assert.equal((await rpc('gama_resolve_price',[customer,product,10,null])).unit_price,20);await rpc('gama_price_book_action',['approve',{id:book.id}]);
 assert.equal((await rpc('gama_resolve_price',[customer,product,9,null])).unit_price,18);assert.equal((await rpc('gama_resolve_price',[customer,product,10,null])).unit_price,15);assert.equal((await rpc('gama_resolve_price',[customer,product,10,'2100-01-01'])).unit_price,20);
 await as(buyer);await assert.rejects(rpc('gama_resolve_price',[second,product,1,null]),/ROLE_NOT_ALLOWED/);await assert.rejects(rpc('gama_price_book_action',['approve',{id:book.id}]),/ROLE_NOT_ALLOWED/);
 const cart={request_key:uuid(),lines:[{product_id:product,quantity:10,unit_price:15}],notes:'test'};
 assert.equal((await rpc('gama_catalog_command',['preview',cart]))[0].unit_price,15);
 await assert.rejects(rpc('gama_catalog_command',['submit',{...cart,lines:[...cart.lines,{product_id:uuid(),quantity:1,unit_price:1}]}]),/PRODUCT_NOT_FOUND/);
 assert.equal((await db.query('select count(*)::int n from customer_requests')).rows[0].n,0);
 await assert.rejects(rpc('gama_catalog_command',['submit',{...cart,lines:[{...cart.lines[0],unit_price:12}]}]),/CART_PRICE_CHANGED/);
 const order=await rpc('gama_catalog_command',['submit',cart]);assert.equal(order.total,172.5);assert.deepEqual(await rpc('gama_catalog_command',['submit',cart]),order);assert.equal((await db.query('select count(*)::int n from customer_requests')).rows[0].n,1);
 await as(other);assert.equal((await db.query('select count(*)::int n from customer_requests')).rows[0].n,0);await assert.rejects(rpc('gama_catalog_command',['submit',cart]),/REQUEST_KEY_REUSED/);
 }finally{await db.close()}});
