const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID:uuid}=require('node:crypto'),{restore}=require('../scripts/restore-schema.cjs');
async function setup(){const db=await restore(),admin=uuid(),client=uuid(),other=uuid(),customer=uuid(),product=uuid();await db.exec(`insert into auth.users(id,email,email_confirmed_at) values('${admin}','services-admin@example.invalid',now()),('${client}','services-client@example.invalid',now()),('${other}','services-other@example.invalid',now());update profiles set active=true,role=case when id='${admin}' then 'administrador' else 'cliente' end;select set_config('request.jwt.claim.sub','${admin}',false);insert into customers(id,name,email,payment_terms_days) values('${customer}','Service customer','services-client@example.invalid',15);insert into products(id,name,barcode,product_kind,base_unit,sale_price,tax_rate) values('${product}','Installation service','SERVICE-P','service','hour',50,15);set role authenticated;`);const rpc=async(n,...args)=>(await db.query('select public.'+n+'('+args.map((_,i)=>'$'+(i+1)).join(',')+') r',args)).rows[0].r;return{db,admin,client,other,customer,product,rpc,as:async id=>db.exec(`reset role;select set_config('request.jwt.claim.sub','${id}',false);set role authenticated`)}}
test('Service execution is partial, idempotent, private, never stocks goods, and creates an invoice only after completion',async()=>{const {db,admin,client,other,customer,product,rpc,as}=await setup();try{
 const quote=await rpc('gama_quote_action','save',{request_key:uuid(),customer_id:customer,issue_date:new Date().toISOString().slice(0,10),valid_until:'2099-01-01',details:{client:'Service customer',seller:'Staff',delivery_address:'Customer site'},lines:[{product_id:product,description:'Installation service',quantity:2,list_price:50,discount:0,tax_rate:15}]});const sent=await rpc('gama_quote_action','send',{id:quote.id,revision:quote.revision});await rpc('gama_quote_action','accept',{id:quote.id,revision:sent.revision,channel:'email',reference:'Signed installation offer'});
 const order=(await db.query('select * from sales_orders where source_quote_id=$1',[quote.id])).rows[0];assert.ok(order);const line=(await db.query('select * from sales_order_lines where order_id=$1',[order.id])).rows[0];assert.equal(line.product_kind,'service');
 assert.equal((await db.query('select count(*)::int n from fulfillment_preparations where order_id=$1',[order.id])).rows[0].n,0);assert.equal((await db.query('select count(*)::int n from stock_reservations where product_id=$1',[product])).rows[0].n,0);assert.equal((await db.query('select count(*)::int n from replenishment_needs where product_id=$1',[product])).rows[0].n,0);
 await assert.rejects(db.query("update products set product_kind='goods' where id=$1",[product]),/PRODUCT_KIND_ALREADY_USED/);
 await assert.rejects(rpc('gama_register_stock_movement',product,'in',1,'Wrong stock',null),/SERVICE_HAS_NO_STOCK/);
 const data={order_id:order.id,line_id:line.id,quantity:1,performed_on:new Date().toISOString().slice(0,10),evidence:'Work report A',request_key:uuid()};const first=await rpc('gama_service_execution','complete',data);assert.equal((await rpc('gama_service_execution','complete',data)).id,first.id);await assert.rejects(rpc('gama_service_execution','complete',{...data,quantity:2}),/REQUEST_KEY_CONFLICT/);assert.equal((await db.query('select count(*)::int n from external_invoices where order_id=$1',[order.id])).rows[0].n,0);
 await as(client);const mine=await rpc('gama_client_services');assert.equal(mine.length,1);assert.equal(mine[0].performed,1);assert.equal(mine[0].history[0].evidence,undefined);await assert.rejects(rpc('gama_service_execution','complete',data),/ROLE_NOT_ALLOWED/);assert.equal((await db.query('select * from sales_service_completions')).rows.length,0);await as(other);assert.equal((await rpc('gama_client_services')).length,0);await as(admin);
 const second=await rpc('gama_service_execution','complete',{...data,evidence:'Work report B',request_key:uuid()});assert.ok(second.invoice,JSON.stringify((await db.query("select detail from sales_events where action='invoice_auto_failed'")).rows));const invoice=(await db.query('select * from external_invoices where id=$1',[second.invoice.id])).rows[0];assert.equal(invoice.total,'115.00');assert.equal(invoice.payment_delivery_date.toISOString().slice(0,10),data.performed_on);assert.ok(invoice.due_date.toISOString().slice(0,10)>data.performed_on);await assert.rejects(rpc('gama_service_execution','complete',{...data,request_key:uuid()}),/SERVICE_QUANTITY_EXCEEDED/);await assert.rejects(rpc('gama_service_execution','cancel',{id:first.id,order_id:order.id,reason:'Wrong execution',request_key:uuid()}),/CANCEL_INVOICE_FIRST/);
 assert.equal((await db.query('select count(*)::int n from sales_deliveries')).rows[0].n,0);
 }finally{await db.close()}});
test('Supplier service acceptance records evidence once and never creates physical stock',async()=>{const {db,product,rpc}=await setup();try{
 const supplier=(await db.query("insert into suppliers(name) values('Service supplier') returning id")).rows[0].id;const po=await rpc('gama_purchase_save',{request_key:uuid(),supplier_id:supplier,lines:[{product_id:product,quantity:2,unit_cost:20,tax_rate:15}]});await db.query("update purchase_orders set status='sent' where id=$1",[po.id]);const line=(await db.query('select id from purchase_order_lines where purchase_order_id=$1',[po.id])).rows[0].id;const input={request_key:uuid(),purchase_order_id:po.id,lines:[{line_id:line,quantity:1}],comment:'Supplier report accepted'};const receipt=await rpc('gama_receive_purchase_once',input);assert.deepEqual(await rpc('gama_receive_purchase_once',input),receipt);await assert.rejects(rpc('gama_receive_purchase_once',{...input,comment:'Changed'}),/REQUEST_KEY_CONFLICT/);assert.equal((await db.query('select count(*)::int n from purchase_service_acceptances')).rows[0].n,1);assert.equal((await db.query('select count(*)::int n from stock_movements where product_id=$1',[product])).rows[0].n,0);assert.equal(Number((await db.query('select received_quantity from purchase_order_lines where id=$1',[line])).rows[0].received_quantity),1);
 }finally{await db.close()}});
