create schema auth;create schema private;create schema storage;
create role anon;create role authenticated;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth,public,storage to authenticated;
create table auth.users(id uuid primary key,email text);
create table public.profiles(id uuid primary key references auth.users(id),full_name text,role text,active boolean default true,email text);
create function private.current_user_role() returns text language sql stable security definer set search_path='' as $$select role from public.profiles where id=auth.uid() and active$$;
create table public.app_modules(id text primary key,enabled boolean);
create table public.customers(id uuid primary key default gen_random_uuid(),name text,active boolean default true);
create table public.suppliers(id uuid primary key default gen_random_uuid(),name text,active boolean default true);
create table public.products(id uuid primary key default gen_random_uuid(),name text,reference text,active boolean default true);
create table public.warehouse_locations(id uuid primary key default gen_random_uuid(),name text,code text,active boolean default true);
create table public.hr_employees(id uuid primary key default gen_random_uuid(),full_name text,profile_id uuid,department text,active boolean default true);
create table public.crm_pipeline_stages(id uuid primary key,is_won boolean);
create table public.crm_opportunities(id uuid primary key,title text,description text,customer_id uuid,owner_id uuid,stage_id uuid);
create table public.invoices(id uuid primary key,invoice_number text,notes text,customer_id uuid,quote_state text);
create table public.sales_orders(id uuid primary key,number text,customer_name text,notes text,customer_id uuid,status text);
create table public.purchase_orders(id uuid primary key default gen_random_uuid(),order_number text,status text,total numeric,supplier_id uuid,order_date timestamptz,expected_date timestamptz,notes text,subtotal numeric,tax numeric,created_by uuid);
create table public.purchase_order_lines(id uuid primary key default gen_random_uuid(),purchase_order_id uuid,quantity numeric,received_quantity numeric,unit_cost numeric,product_id uuid,tax_rate numeric,line_total numeric);
create table public.stock_reservations(id uuid primary key default gen_random_uuid(),product_id uuid,location_id uuid,quantity numeric,status text default 'active',reference_type text,reference_id uuid);
create function public.gama_stock_reserve(p_product_id uuid,p_location_id uuid,p_quantity numeric,p_reference_type text,p_reference_id uuid) returns public.stock_reservations language plpgsql as $$declare r public.stock_reservations;begin insert into public.stock_reservations(product_id,location_id,quantity,reference_type,reference_id) values(p_product_id,p_location_id,p_quantity,p_reference_type,p_reference_id) returning * into r;return r;end$$;
create function public.gama_stock_unreserve(p_reservation_id uuid,p_consumed boolean default false) returns public.stock_reservations language plpgsql as $$declare r public.stock_reservations;begin update public.stock_reservations set status='released' where id=p_reservation_id returning * into r;return r;end$$;
create table public.knowledge_articles(id uuid primary key default gen_random_uuid(),title text,body text,properties jsonb);
create table public.gama_audit(id bigint generated always as identity primary key,table_name text,row_id text,action text,actor_id uuid,actor_role text,changed_at timestamptz default now(),old_data jsonb,new_data jsonb,changed_fields text[]);
create function private.gama_audit_row() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.gama_audit(table_name,row_id,action,actor_id,actor_role,old_data,new_data) values(tg_table_name,coalesce(new.id,old.id)::text,tg_op,auth.uid(),private.current_user_role(),case when tg_op<>'INSERT' then to_jsonb(old) end,case when tg_op<>'DELETE' then to_jsonb(new) end);return coalesce(new,old);end$$;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,owner_id text);
alter table storage.objects enable row level security;
grant select,insert,delete on storage.objects to authenticated;
