const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID:uuid}=require('node:crypto'),{restore}=require('../scripts/restore-schema.cjs');
test('process history resolves actual actors, scopes financial stages, paginates and audits returns',async()=>{
 const db=await restore(),admin=uuid(),other=uuid(),warehouse=uuid(),customer=uuid(),supplier=uuid(),order=uuid(),purchase=uuid(),ret=uuid();const q=async(s,p=[])=>(await db.query(s,p)).rows;const history=async(key,step=0,offset=0)=>(await q('select gama_process_history($1,$2,$3) r',[key,step,offset]))[0].r;
 try{await q('insert into auth.users(id,email) values($1,$2),($3,$4),($5,$6)',[admin,'history-admin@example.invalid',other,'history-other@example.invalid',warehouse,'history-warehouse@example.invalid']);await q("update profiles set role='administrador',active=true,full_name=case when id=$1 then 'Alice' else 'Bob' end where id in ($1,$2)",[admin,other]);await q("update profiles set role='almacenero',active=true,full_name='Warehouse' where id=$1",[warehouse]);await q("select set_config('request.jwt.claim.sub',$1,false)",[admin]);
 await q("insert into customers(id,name) values($1,'History customer')",[customer]);await q("insert into suppliers(id,name) values($1,'History supplier')",[supplier]);await q("insert into sales_orders(id,customer_id,customer_name,created_by,request_key,status) values($1,$2,'History customer',$3,gen_random_uuid(),'confirmed')",[order,customer,admin]);
 await q("insert into sales_events(order_id,action,actor_id) values($1,'confirm',$2)",[order,other]);
 await q("insert into purchase_orders(id,supplier_id,order_number,status,created_by) values($1,$2,'HISTORY-PO','draft',$3)",[purchase,supplier,admin]);await q("select set_config('request.jwt.claim.sub',$1,false)",[other]);await q("update purchase_orders set status='sent' where id=$1",[purchase]);
 await q("insert into return_orders(id,kind,status,customer_id,order_id,reason,created_by) values($1,'customer','to_process',$2,$3,'defective',$4)",[ret,customer,order,admin]);await q("update return_orders set received_at=now(),status='received' where id=$1",[ret]);await db.exec('set role authenticated');
 let h=await history('o:'+order);assert(h.items.some(e=>e.action==='confirm'&&e.actor_name==='Bob'&&e.step===3));assert(!JSON.stringify(h).includes('example.invalid'));assert(h.items.every(e=>!('before_data' in e)&&!('actor_id' in e)));
 h=await history('p:'+purchase);assert(h.items.some(e=>e.action==='purchase_created'&&e.actor_name==='Alice'));assert(h.items.some(e=>e.action==='purchase'&&e.actor_name==='Bob'&&e.step===2));
 h=await history('return:'+ret);assert(h.items.some(e=>e.action==='return_created'&&e.actor_name==='Alice'));assert(h.items.some(e=>e.action==='receipt'&&e.actor_name==='Bob'&&e.step===3));
 await db.exec('reset role');await q("insert into sales_events(order_id,action,actor_id) select $1,'fulfillment_pick',$2 from generate_series(1,61)",[order,other]);await q("insert into sales_events(order_id,action,actor_id) values($1,'internal_invoice',$2)",[order,other]);await db.exec('set role authenticated');assert.equal((await history('o:'+order,4)).items.length,50);assert.equal((await history('o:'+order,4,50)).items.length,11);assert((await history('o:'+order)).items.some(e=>e.step===6));
 await q("select set_config('request.jwt.claim.sub',$1,false)",[warehouse]);h=await history('o:'+order);assert(!h.items.some(e=>e.step>=6));await assert.rejects(history('invalid'),/INVALID_PROCESS_KEY/);await db.exec('reset role;set role anon');await assert.rejects(history('o:'+order),/permission denied/);
 }finally{await db.close()}
});
