const {test,expect}=require('@playwright/test'),fs=require('fs');
const mock=fs.readFileSync(__dirname+'/mock-gama-cloud.js','utf8')+fs.readFileSync(__dirname+'/mock-service-documents.js','utf8');
async function boot(page,role='admin'){
 await page.addInitScript(role=>{localStorage.setItem('gama_session_v1',JSON.stringify({role,name:'QA'}));window.__DB={customers:[{id:'customer1',name:'Costa Azul',active:true}],suppliers:[],sales_orders:[{id:'order1',number:'SO-001',customer_id:'customer1',customer_name:'Costa Azul'}],products:[],invoices:[],invoice_lines:[],purchase_orders:[],purchase_order_lines:[]}},role);
 await page.route('**/gama-supabase.js*',r=>r.fulfill({contentType:'text/javascript',body:mock}));await page.route('**/@supabase/**',r=>r.abort());await page.goto('/index.html');await page.waitForFunction(()=>document.body.dataset.dataSource==='supabase-central');await page.evaluate(()=>GamaI18n.setLanguage('fr'));
}
async function open(page,id){await page.locator(`#mainmenu [data-gama-module="${id}"]`).click();await expect(page.locator(`#${id} [data-sd-action="new"]`)).toBeVisible()}
async function createTicket(page){await open(page,'sav');await page.locator('#sav [data-sd-action=new]').click();await page.locator('#sd-subject').fill('Colis abîmé');await page.locator('#sd-customer_id').selectOption('customer1');await page.locator('#sd-sales_order_id').selectOption('order1');await page.locator('#sd-assigned_to').selectOption('test-admin-uid');await page.locator('#sd-description').fill('Carton reçu déchiré.');await page.locator('dialog [type=submit]').click();await expect(page.locator('#sav h2').last()).toContainText('Colis abîmé')}
test('SAV create, assign, note, resolution validation and conflict retains draft',async({page})=>{
 await boot(page);await createTicket(page);await page.locator('#sd-message').fill('Client rappelé, remplacement prévu.');await page.locator('#sd-message-form [type=submit]').click();await expect(page.locator('.sdTimeline')).toContainText('Client rappelé');
 await page.locator('#sav [data-sd-action=edit]').click();await page.locator('#sd-status').selectOption('resolved');await page.locator('dialog [type=submit]').click();await expect(page.locator('dialog [role=alert]')).toContainText('solution');await page.screenshot({path:'test-results/sav-form.png',fullPage:true});await page.locator('#sd-resolution').fill('Remplacement livré');await page.locator('dialog [type=submit]').click();await expect(page.locator('#sav .sdDetail').first()).toContainText('Remplacement livré');
 await page.locator('#sav [data-sd-action=edit]').click();await page.locator('#sd-description').fill('Brouillon à conserver');await page.evaluate(()=>__DB.service_tickets[0].version++);await page.locator('dialog [type=submit]').click();await expect(page.locator('dialog [role=alert]')).toContainText('Actualisez');await expect(page.locator('#sd-description')).toHaveValue('Brouillon à conserver');
});
test('document uploads, versions, downloads, archive/restore and failed save cleanup on mobile',async({page})=>{
 await page.setViewportSize({width:390,height:844});await boot(page);await open(page,'documents');await page.locator('#documents [data-sd-action=new]').click();await page.locator('#sd-title').fill('Contrat Costa Azul');await page.locator('#sd-category_id').selectOption('contracts');await page.locator('#sd-customer_id').selectOption('customer1');await page.locator('#sd-file').setInputFiles({name:'contrat.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 test')});
 await page.evaluate(()=>__SD.fail=true);await page.locator('dialog [type=submit]').click();await expect(page.locator('dialog [role=alert]')).toContainText('NETWORK_TEST');expect(await page.evaluate(()=>Object.keys(__SD.uploads).length)).toBe(0);await expect(page.locator('#sd-title')).toHaveValue('Contrat Costa Azul');await page.evaluate(()=>__SD.fail=false);await page.locator('dialog [type=submit]').click();await expect(page.locator('.sdVersions')).toContainText('v1');
 await page.locator('#documents [data-sd-action=version]').click();await page.locator('#sd-file').setInputFiles({name:'contrat-v2.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 version2')});await page.locator('dialog [type=submit]').click();await expect(page.locator('.sdVersions li')).toHaveCount(2);
 const dl=page.waitForEvent('download');await page.locator('[data-sd-action=download]').first().click();expect((await dl).suggestedFilename()).toBe('contrat-v2.pdf');
 await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'test-results/documents-mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 await page.locator('#documents [data-sd-action=archive]').click();await page.locator('dialog [type=submit]').click();await page.locator('#documents [data-sd-filter]').selectOption('archived');await expect(page.locator('#documents')).toContainText('Contrat Costa Azul');await page.locator('#documents [data-sd-action=detail]').click();await page.locator('#documents [data-sd-action=archive]').click();await page.locator('dialog [type=submit]').click();await page.locator('#documents [data-sd-filter]').selectOption('active');await expect(page.locator('#documents')).toContainText('Contrat Costa Azul');
 await page.locator('#documents [data-table-view=table]').click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test('SAV attachment returns to claim and opens linked document list',async({page})=>{
 await boot(page);await createTicket(page);await page.locator('#sav [data-sd-action=attach]').click();await page.locator('#sd-file').setInputFiles({name:'colis.png',mimeType:'image/png',buffer:Buffer.from('png')});await page.locator('dialog [type=submit]').click();await expect(page.locator('#sav')).toBeVisible();await expect(page.locator('#sav .sdDetail').first()).toContainText('colis');await page.locator('#sav [data-sd-action=docs]').click();await expect(page.locator('#documents')).toBeVisible();await expect(page.locator('#documents')).toContainText('colis');await page.screenshot({path:'test-results/documents-desktop.png',fullPage:true});
});
for(const role of ['client'])test('unavailable modules for '+role,async({page})=>{await boot(page,role);await expect(page.locator('#mainmenu [data-gama-module=sav]')).toBeHidden();await expect(page.locator('#mainmenu [data-gama-module=documents]')).toBeHidden();await page.evaluate(async()=>{await GamaService.open();await GamaDocuments.open()});await expect(page.locator('#sd-sav')).toHaveCount(0);await expect(page.locator('#sd-documents')).toHaveCount(0)});

test('dashboard shortcuts filter overdue or unassigned claims and expiring documents',async({page})=>{
 await boot(page);await page.evaluate(()=>{__DB.service_tickets=[{id:'late1',subject:'En retard',description:'Aide',customer_id:'customer1',archived:false,status:'new',priority:'normal',due_date:'2000-01-01',assigned_to:'test-admin-uid'},{id:'free1',subject:'Sans responsable',description:'Aide',customer_id:'customer1',archived:false,status:'new',priority:'normal',assigned_to:null}];__DB.business_documents=[{id:'expired1',title:'Contrat expiré',folder:'Contrats',visibility:'team',archived:false,expires_on:'2000-01-01'},{id:'valid1',title:'Contrat valide',folder:'Contrats',visibility:'team',archived:false,expires_on:'2099-01-01'}]});
 await page.evaluate(()=>GamaService.open({filter:'late'}));await expect(page.locator('#sav')).toContainText('En retard');await expect(page.locator('#sav tbody')).not.toContainText('Sans responsable');await page.evaluate(()=>GamaService.open({filter:'unassigned'}));await expect(page.locator('#sav')).toContainText('Sans responsable');await expect(page.locator('#sav tbody')).not.toContainText('En retard');await page.evaluate(()=>GamaDocuments.open({filter:'expired'}));await expect(page.locator('#documents')).toContainText('Contrat expiré');await expect(page.locator('#documents')).not.toContainText('Contrat valide');
});

test('categories, employee links, three access levels and synchronized files',async({page})=>{
 await page.setViewportSize({width:390,height:844});await boot(page);await open(page,'documents');await page.locator('#documents [data-sd-action=new]').click();
 await page.locator('[data-sd-create-category]').click();await page.locator('#sd-category-name').fill('Permis et habilitations');await page.locator('dialog').last().locator('[type=submit]').click();
 await expect(page.locator('#sd-category_id option:checked')).toHaveText('Permis et habilitations');await page.locator('#sd-title').fill('Permis de conduire');await page.locator('#sd-employee_id').selectOption('employee1');await page.locator('#sd-visibility').selectOption('hr');
 await page.locator('#sd-file').setInputFiles({name:'permis.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF test')});await page.locator('dialog [type=submit]').click();await expect(page.locator('#documents')).toContainText('Employé de contrôle');await expect(page.locator('#documents')).toContainText('RH et administrateurs');
 const saved=await page.evaluate(()=>__DB.business_documents[0]);expect(saved.employee_id).toBe('employee1');expect(saved.visibility).toBe('hr');expect(saved.category_id).toBeTruthy();
 await page.locator('#documents [data-sd-action=list]').click();await page.locator('[data-sd-employee]').selectOption('employee1');await expect(page.locator('#documents tbody')).toContainText('Permis de conduire');
 await page.evaluate(()=>{__DB.business_documents.push({id:'source1',title:'Assurance du véhicule',folder:'Fleet',category_id:'fleet',source_table:'fleet_documents',source_id:'fleet1',source_module:'fleet',source_filename:'permis.pdf',visibility:'source',archived:false,version:1})});
 await page.locator('[data-sd-employee]').selectOption('');await page.locator('[data-sd-source]').selectOption('fleet');await expect(page.locator('#documents tbody')).toContainText('Assurance du véhicule');await expect(page.locator('#documents tbody')).not.toContainText('Permis de conduire');await page.locator('#documents [data-sd-action=detail]').click();
 await expect(page.locator('#documents [data-sd-action=version]')).toHaveCount(0);const dl=page.waitForEvent('download');await page.locator('[data-sd-action=source-download]').click();expect((await dl).suggestedFilename()).toBe('permis.pdf');
 await page.locator('#documents [data-sd-action=edit]').click();await page.locator('#sd-visibility').selectOption('management');await page.locator('dialog [type=submit]').click();await expect(page.locator('#documents')).toContainText('Administrateurs uniquement');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test('employee can open Documents and cannot see SAV',async({page})=>{await boot(page,'magasinier');await expect(page.locator('#mainmenu [data-gama-module=sav]')).toBeHidden();await open(page,'documents');await page.locator('#documents [data-sd-action=new]').click();await expect(page.locator('#sd-visibility option[value=management]')).toHaveCount(0);await expect(page.locator('#sd-visibility option[value=hr]')).toHaveCount(0)});
