const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID:uuid}=require('node:crypto'),fs=require('node:fs');
const {restore}=require('../scripts/restore-schema.cjs');
test('public catalogue exposes selected products only; staff settings and inquiries are isolated and writes are idempotent',async()=>{
 const db=await restore(),admin=uuid(),client=uuid(),product=uuid(),hidden=uuid();
 const q=async(s,a=[])=>(await db.query(s,a)).rows,web=async(a,d={})=>(await q('select gama_website($1,$2) r',[a,d]))[0].r,site=async(a,d={})=>(await q('select gama_storefront($1,$2) r',[a,d]))[0].r;
 const login=async id=>{await db.exec('reset role');await q("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated')};
 try{
  await q('insert into auth.users(id,email) values($1,$2),($3,$4)',[admin,'site-admin@example.invalid',client,'site-client@example.invalid']);await q("update profiles set active=true,role=case when id=$1 then 'cliente' else 'administrador' end",[client]);
  await q("insert into products(id,name,reference,category,purchase_price,sale_price,tax_rate,photo_data,order_minimum,order_multiple) values($1,'Café de prueba','WEB-COFFEE','Bebidas',2,10,15,'data:image/png;base64,YWJj',2,2),($2,'Producto privado','WEB-HIDDEN','Otros',7,50,0,'private photo',1,1)",[product,hidden]);
  await login(admin);let settings=await web('public_settings');assert.deepEqual(settings.schema,JSON.parse(fs.readFileSync(__dirname+'/../config/storefront-schema.json','utf8')));const conn=await web('public_connection');assert.match(conn.token,/^[a-f0-9]{64}$/);
  await web('public_save_product',{id:product,version:0,public_visible:true,public_featured:true,public_brand:'GAMA',public_title:'Café público',public_description:'Café para oficina'});
  await assert.rejects(web('public_save_product',{id:product,version:0,public_visible:false,public_featured:false}),/WEBSITE_PRODUCT_CHANGED/);
  assert.equal((await web('catalog')).total,0,'public publication must not alter administrator preview selection');
  await assert.rejects(web('public_save_settings',{version:settings.version,config:{...settings.config,logo_url:'data:image/svg+xml;base64,YWJj'}}),/WEBSITE_INVALID_CONFIGURATION/);
  await assert.rejects(web('public_save_settings',{version:settings.version,config:{...settings.config,unknown:true}}),/WEBSITE_INVALID_CONFIGURATION/);
  await web('public_save_settings',{version:settings.version,config:{...settings.config,hero_title:'Una empresa bien abastecida'}});await assert.rejects(web('public_save_settings',{version:settings.version,config:settings.config}),/WEBSITE_SETTINGS_CHANGED/);settings=await web('public_settings');
  await db.exec('reset role;set role anon');const bootstrap=await site('bootstrap');assert.equal(bootstrap.total,1);assert.equal(bootstrap.featured[0].name,'Café público');assert.ok(!JSON.stringify(bootstrap).includes(conn.token));assert.equal(bootstrap.featured[0].purchase_price,undefined);assert.equal(bootstrap.featured[0].stock,undefined);
  assert.equal((await site('catalog',{search:'CAFE'})).total,0);assert.equal((await site('catalog',{search:'café'})).total,1);assert.equal((await site('catalog',{category:'Otros'})).total,0);
  assert.equal((await site('photos',{ids:[product,hidden]})).length,1);await assert.rejects(site('product',{id:hidden}),/WEBSITE_PRODUCT_NOT_FOUND/);await assert.rejects(site('public_inquiries'),/WEBSITE_INVALID_ACTION/);await assert.rejects(web('public_connection'),/permission denied/);await assert.rejects(q('select * from private.website_public_connection'),/permission denied/);assert.equal((await q("select has_schema_privilege('anon','private','USAGE') ok"))[0].ok,false);
  const payload={request_key:uuid(),visitor:'198.51.100.1',contact_name:'Cliente QA',email:'qa@example.invalid',company:'QA',consent:true,lines:[{product_id:product,quantity:2,unit_price:0,tax_rate:0}]};
  await assert.rejects(site('submit',payload),/WEBSITE_SERVER_KEY_REQUIRED/);await q("select set_config('request.headers',$1,false)",[JSON.stringify({'x-coco-site-token':conn.token})]);
  await assert.rejects(site('submit',{...payload,consent:false}),/WEBSITE_CONTACT_REQUIRED/);await assert.rejects(site('submit',{...payload,lines:[{product_id:product,quantity:3}]}),/WEBSITE_PACK_QUANTITY/);await assert.rejects(site('submit',{...payload,lines:[{product_id:hidden,quantity:1}]}),/WEBSITE_PRODUCT_NOT_FOUND/);await assert.rejects(site('submit',{...payload,website:'bot'}),/WEBSITE_INVALID_DATA/);
  const a=await site('submit',payload),b=await site('submit',payload);assert.deepEqual(a,b);assert.deepEqual(Object.keys(a),['reference']);await assert.rejects(site('submit',{...payload,notes:'changed'}),/WEBSITE_REQUEST_KEY_REUSED/);
  await login(admin);let inquiries=await web('public_inquiries');assert.equal(inquiries.total,1);const inquiry=inquiries.items[0];assert.equal(inquiry.total,23);assert.equal(inquiry.lines[0].unit_price,10);assert.equal(inquiry.visitor_hash,undefined);assert.equal(inquiry.payload,undefined);await web('public_review',{id:inquiry.id,status:'reviewed',internal_notes:'Contacter le client'});assert.equal((await web('public_inquiries')).items[0].status,'reviewed');
  settings=await web('public_settings');await web('public_save_settings',{version:settings.version,config:{...settings.config,show_prices:false}});await db.exec('reset role;set role anon');assert.equal((await site('product',{id:product})).item.unit_price,null);assert.equal((await site('product',{id:product})).item.tax_rate,null);
  for(let i=0;i<4;i++)await site('submit',{...payload,request_key:uuid()});await assert.rejects(site('submit',{...payload,request_key:uuid()}),/WEBSITE_RATE_LIMIT/);
  await login(client);for(const action of ['public_settings','public_connection','public_products','public_inquiries'])await assert.rejects(web(action),/WEBSITE_ACCESS_DENIED/);
  await login(admin);settings=await web('public_settings');await web('public_save_settings',{version:settings.version,config:{...settings.config,site_enabled:false}});await db.exec('reset role;set role anon');assert.equal((await site('bootstrap')).paused,true);await assert.rejects(site('photos',{ids:[product]}),/WEBSITE_PUBLIC_PAUSED/);await assert.rejects(site('catalog'),/WEBSITE_PUBLIC_PAUSED/);
  await db.exec('reset role');for(const table of ['customer_requests','sales_orders','stock_movements'])assert.equal((await q('select count(*) n from '+table))[0].n,0);
 }finally{await db.close()}
});
