const {test,expect}=require('@playwright/test'),fs=require('node:fs'),path=require('node:path');
const schema=require('../config/storefront-schema.json'),config=Object.fromEntries(schema.groups.flatMap(g=>g.fields.map(f=>[f.key,f.default])));
const ids=['10000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000002'];
const items=[{id:ids[0],name:'CAFÉ PARA OFICINA',reference:'CAFE-01',category:'Alimentos y bebidas',category_title:'Alimentos y bebidas',unit_price:10,tax_rate:15,order_minimum:2,order_multiple:2,has_photo:false,featured:true,description:'Café de Ecuador',brand:'GAMA',badge:'Para tu equipo'},{id:ids[1],name:'AGUA MINERAL',reference:'AGUA-01',category:'Bebidas',category_title:'Bebidas',unit_price:null,tax_rate:null,order_minimum:0.001,order_multiple:0.001,has_photo:false,featured:true,description:'',brand:'',badge:''}];
async function boot(page,{width=1440,paused=false,quotes=true,contact=true,catalogItems=items,categories=catalogItems.map(p=>({category:p.category,title:p.category,count:1,photo_id:p.id})),settings={},photoRows=[]}={}){
 await page.setViewportSize({width,height:960});await page.addInitScript(()=>{window.__SITE_CALLS=[];window.__SITE_FAIL=false});
 await page.route('**/site.js*',r=>r.fulfill({path:path.join(__dirname,'../dist-storefront/site.js'),contentType:'text/javascript'}));await page.route('**/site.css*',r=>r.fulfill({path:path.join(__dirname,'../dist-storefront/site.css'),contentType:'text/css'}));await page.route('**/logo.jpg',r=>r.fulfill({path:path.join(__dirname,'../gama-logo.jpg'),contentType:'image/jpeg'}));
 await page.route('**/api/storefront',async r=>{const d=r.request().postDataJSON();await page.evaluate(d=>__SITE_CALLS.push(d),d);let out;const c={...config,enable_quotes:quotes,show_contact:contact,...settings};
 if(d.p_action==='bootstrap')out={paused,settings:c,currency:'USD',total:catalogItems.length,categories,brands:[...new Set(catalogItems.map(p=>p.brand).filter(Boolean))],featured:catalogItems};
 if(d.p_action==='catalog'){const rows=catalogItems.filter(p=>(!d.p_data.search||[p.name,p.reference,p.brand].join(' ').toLowerCase().includes(d.p_data.search.toLowerCase()))&&(!d.p_data.category||p.category===d.p_data.category)&&(!d.p_data.brand||p.brand===d.p_data.brand));out={items:rows,total:rows.length,offset:0,limit:12,currency:'USD'}}
 if(d.p_action==='product')out={item:catalogItems.find(p=>p.id===d.p_data.id),currency:'USD'};if(d.p_action==='photos')out=photoRows.filter(p=>d.p_data.ids.includes(p.id));
 if(d.p_action==='submit'){if(await page.evaluate(()=>__SITE_FAIL)){await page.evaluate(()=>__SITE_FAIL=false);return r.fulfill({status:503,json:{error:'WEBSITE_UNAVAILABLE'}})}out={reference:'WEB-00000001'}}return r.fulfill({json:out})});
 await page.goto('/dist-storefront/index.html');
}
const catalogueCategories=require('../config/storefront-category-images.json').map((c,i)=>({category:c.category,title:c.category,count:100+i}));
const wideItems=[{...items[0],name:'CARTUCHO HP 712 3ED77A 3ED78A 3ED79A COLOR 3 PACK',category:catalogueCategories[1].category,category_title:catalogueCategories[1].title,reference:'CARTUCHO-'.repeat(14),brand:'Marca de accesorios para equipos de impresión',unit_price:676.89,description:'Especificaciones: '+ 'A'.repeat(160)},{...items[1],category:catalogueCategories.at(-1).category,category_title:catalogueCategories.at(-1).title}];
async function expectContained(page,selectors){
 const outside=await page.locator(selectors).evaluateAll(nodes=>nodes.filter(n=>n.getClientRects().length).map(n=>({element:n.id||n.className,left:n.getBoundingClientRect().left,right:n.getBoundingClientRect().right})).filter(r=>r.left< -1||r.right>innerWidth+1));
 expect(outside).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(await page.evaluate(()=>innerWidth+1));
}
for(const width of [320,360,390,430,600,768,1024,1440])test('full category catalogue and long product fields fit the viewport on '+width,async({page})=>{
 await boot(page,{width,catalogItems:wideItems,categories:catalogueCategories});await expect(page.locator('#siteProducts .product-card')).toHaveCount(2);
 const layout='#header, #catalogo, .catalogue-sidebar, #categoryFilters, .catalogue-content, .catalogue-tools, #siteProducts .product-card, #siteProducts .quick-order, #featuredProducts .quick-order';
 await expectContained(page,layout);
 if(width<=800){
  const filters=page.locator('#categoryFilters');expect(await filters.evaluate(n=>n.scrollWidth>n.clientWidth)).toBe(true);
  await filters.evaluate(n=>n.scrollLeft=n.scrollWidth);expect(await filters.evaluate(n=>n.scrollLeft)).toBeGreaterThan(0);
  const lastTitle=await filters.locator('[data-category] span').last().textContent();await filters.locator('[data-category]').last().click();await expect(page.locator('#activeCategory')).toHaveText(lastTitle);await page.locator('#clearFilters').click();
 }
 await page.locator('#siteSearch').fill('CARTUCHO');await page.locator('#siteSearch').press('Enter');await expect(page.locator('#siteProducts .product-card')).toHaveCount(1);await expect(page.locator('#siteProducts')).toHaveAttribute('aria-busy','false');await expectContained(page,layout);
 await page.locator('[data-view=grid]').click();await expectContained(page,layout);await page.locator('[data-view=list]').click();
 await page.locator('#siteProducts .product-details-link').click();await expect(page.locator('#productTitle')).toHaveText('Cartucho hp 712 3ed77a 3ed78a 3ed79a color 3 pack');await expectContained(page,'#productDialog, .detail-copy, .detail-order, .specifications, .related-products .quick-order');
 expect(await page.locator('#productDialog').evaluate(n=>n.scrollWidth<=n.clientWidth+1)).toBe(true);
 await page.locator('#detailForm [type=submit]').click();await page.locator('[data-close-dialog=productDialog]').click();await page.locator('#cartOpen').click();
 await expectContained(page,'#cartDialog, #quoteForm input:not([name=website]), #quoteForm textarea');expect(await page.locator('#cartDialog').evaluate(n=>n.scrollWidth<=n.clientWidth+1)).toBe(true);
 await page.locator('[data-close-dialog=cartDialog]').click();await page.evaluate(()=>scrollTo({top:document.querySelector('#catalogo').offsetTop-150,left:0,behavior:'instant'}));await page.screenshot({path:'test-results/public-storefront-catalogue-'+width+'.png'});
});
for(const width of [390,1440])test('public catalogue, product details and retry-safe inquiry on '+width,async({page})=>{
 await boot(page,{width});await expect(page.locator('#siteProducts .product-card')).toHaveCount(2);await expect(page.locator('#siteProducts')).toContainText('$11,50');await expect(page.locator('#siteProducts')).toContainText('Consultar');const categoryTitle=await page.locator('.category-card .category-copy').first().boundingBox(),categoryPhoto=await page.locator('.category-card > .category-visual').first().boundingBox();expect(categoryPhoto.y+categoryPhoto.height).toBeLessThanOrEqual(categoryTitle.y); const categoryTile=await page.locator('.category-card').first().boundingBox(); expect(categoryTitle.y+categoryTitle.height).toBeLessThanOrEqual(categoryTile.y+categoryTile.height);
 await page.locator('#siteSearch').fill('CAFÉ');await expect(page.locator('#siteProducts .product-card')).toHaveCount(1);await page.locator('#siteProducts [data-product]').first().click();await expect(page.locator('#productTitle')).toHaveText('Café para oficina');await page.locator('#detailForm [name=quantity]').fill('4');await page.locator('#detailForm [type=submit]').click();await expect(page.locator('#cartCount')).toHaveText('1');await page.locator('[data-close-dialog=productDialog]').click();await page.locator('#cartOpen').click();await expect(page.locator('#cartLines input')).toHaveValue('4');
 await page.locator('[name=contact_name]').fill('Jimmy QA');await page.locator('[name=email]').fill('qa@example.invalid');await page.locator('[name=consent]').check();await page.evaluate(()=>__SITE_FAIL=true);await page.locator('#quoteSend').click();await expect(page.locator('#quoteStatus')).toContainText('Vuelve a intentarlo');await expect(page.locator('[name=contact_name]')).toHaveValue('Jimmy QA');await page.locator('#quoteSend').click();await expect(page.locator('#quoteStatus')).toContainText('WEB-00000001');await expect(page.locator('[name=email]')).toHaveValue('');
 const calls=await page.evaluate(()=>__SITE_CALLS.filter(x=>x.p_action==='submit'));expect(calls).toHaveLength(2);expect(calls[0].p_data.request_key).toBe(calls[1].p_data.request_key);expect(calls[1].p_data.lines).toEqual([{product_id:ids[0],quantity:4}]);expect(calls[1].p_data.visitor).toBeUndefined();await page.locator('[data-close-dialog=cartDialog]').click();await page.locator('#clearFilters').click();await expect(page.locator('#siteProducts .product-card')).toHaveCount(2);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.evaluate(()=>window.scrollTo({top:0,left:0,behavior:'instant'}));await page.screenshot({path:'test-results/public-storefront-'+width+'.png',fullPage:true});
});
for(const width of [320,390,1440])test('category menu, header search and quantity selection on '+width,async({page})=>{
 await boot(page,{width});await expect(page.locator('#siteProducts .product-card')).toHaveCount(2);await page.locator('[data-view=list]').click();await expect(page.locator('#siteProducts')).toHaveClass('product-list');await expect(page.locator('#header #siteSearch')).toBeVisible();
 await page.locator('#menuOpen').click();await expect(page.locator('#menuDialog')).toBeVisible();await expect(page.locator('#menuOpen')).toHaveAttribute('aria-expanded','true');await expect(page.locator('#menuCategories [data-category]')).toHaveCount(3);await page.locator('#menuDialog').press('Escape');await expect(page.locator('#menuDialog')).not.toBeVisible();await expect(page.locator('#menuOpen')).toHaveAttribute('aria-expanded','false');expect(await page.evaluate(()=>document.body.classList.contains('menu-open'))).toBe(false);
 await page.locator('#menuOpen').click();await page.screenshot({path:'test-results/gama-category-menu-'+width+'.png'});await page.locator('#menuCategories [data-category="Bebidas"]').click();await expect(page.locator('#menuDialog')).not.toBeVisible();await expect(page.locator('#siteProducts .product-card')).toHaveCount(1);await expect(page.locator('#activeCategory')).toHaveText('Bebidas');
 const fractionalQuantity=page.locator('#siteProducts [data-card-quantity]');await expect(fractionalQuantity).toHaveValue('1');await expect(fractionalQuantity).toHaveAttribute('min','0.001');await expect(fractionalQuantity).toHaveAttribute('step','0.001');
 await page.locator('[data-view=list]').click();await page.locator('#siteProducts .product-details-link').click();await expect(page.locator('#detailForm [name=quantity]')).toHaveValue('1');await page.locator('[data-close-dialog=productDialog]').click();
 await page.locator('#siteProducts [data-add]').click();await page.locator('#cartOpen').click();await expect(page.locator('#cartLines input')).toHaveValue('1');await page.locator('#cartLines input').fill('0.5');await page.locator('#cartLines input').dispatchEvent('change');await expect(page.locator('#cartLines input')).toHaveValue('0.5');await page.locator('#cartLines [data-remove]').click();await expect(page.locator('#cartCount')).toHaveText('0');await page.locator('[data-close-dialog=cartDialog]').click();
 await page.locator('#clearFilters').click();await expect(page.locator('#siteProducts .product-card')).toHaveCount(2);
 await page.locator('#siteSearch').fill('CAFE-01');await page.locator('#siteSearch').press('Enter');await expect(page.locator('#siteProducts .product-card')).toHaveCount(1);await expect(page.locator('#activeCategory')).toContainText('CAFE-01');await page.locator('[data-view=grid]').click();await expect(page.locator('#siteProducts')).toHaveClass('product-grid');await expect(page.locator('[data-view=grid]')).toHaveAttribute('aria-pressed','true');await page.locator('[data-view=list]').click();await expect(page.locator('#siteProducts')).toHaveClass('product-list');
 const quantity=page.locator('#siteProducts [data-card-quantity]');await expect(quantity).toHaveValue('2');await quantity.fill('3');await page.locator('#siteProducts [data-add]').click();await expect(page.locator('#cartCount')).toHaveText('0');await expect(page.locator('#cartNotice')).toContainText('múltiplos');await quantity.fill('4');await page.locator('#siteProducts [data-add]').click();await expect(page.locator('#cartCount')).toHaveText('1');await expect(page.locator('#cartNotice')).toContainText('añadido');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'test-results/gama-product-list-'+width+'.png'});
 await page.locator('[data-view=list]').click();await page.locator('#siteProducts .product-details-link').click();await expect(page.locator('#productTitle')).toHaveText('Café para oficina');await expect(page.locator('.specifications')).toContainText('Múltiplos de 2 unidades');await page.screenshot({path:'test-results/gama-product-detail-'+width+'.png'});await page.locator('[data-close-dialog=productDialog]').click();await page.locator('#cartOpen').click();await expect(page.locator('#cartLines input')).toHaveValue('4');await expect(page.locator('#cartLines')).toContainText('Café para oficina');
});
test('maintenance hides the catalogue and disabled quotes remove add actions',async({page})=>{await boot(page,{paused:true});await expect(page.locator('#unavailable')).toBeVisible();await expect(page.locator('#siteProducts .product-card')).toHaveCount(0);await expect(page.locator('#cartOpen')).toBeHidden();await page.unroute('**/api/storefront');await boot(page,{quotes:false});await expect(page.locator('#siteProducts .product-card')).toHaveCount(2);await expect(page.locator('[data-add]')).toHaveCount(0);await expect(page.locator('#cartOpen')).toBeHidden()});
for(const width of [390,1280])test('publication button saves only publication, preserves drafts and reports failures on '+width,async({page})=>{
 await adminBoot(page,width,{siteEnabled:false});const toggle=page.locator('#gsPublicationToggle'),state=page.locator('#gsPublicationState');await expect(state).toHaveText('Publication désactivée');await expect(toggle).toHaveText('Activer la publication');
 await page.locator('[data-gs-path=brand_name]').fill('Brouillon à conserver');await toggle.click();await expect(state).toHaveText('Site publié');await expect(toggle).toHaveText('Désactiver la publication');await expect(page.locator('[data-gs-path=brand_name]')).toHaveValue('Brouillon à conserver');await expect(page.locator('#gsStatus')).toContainText('non enregistrées');const saved=await page.evaluate(()=>__PUBLIC.calls.filter(c=>c.p_action==='public_save_settings'));expect(saved).toHaveLength(1);expect(saved[0].p_data.config).toEqual({...config,site_enabled:true});
 await page.evaluate(()=>__PUBLIC.fail=true);await toggle.click();await expect(page.locator('#gsStatus')).toContainText('conservées');await expect(state).toHaveText('Site publié');await expect(toggle).toBeEnabled();expect(await page.evaluate(()=>__PUBLIC.config.site_enabled)).toBe(true);
 await toggle.click();await expect(state).toHaveText('Publication désactivée');await expect(toggle).toHaveText('Activer la publication');await expect(page.locator('[data-gs-path=brand_name]')).toHaveValue('Brouillon à conserver');await page.locator('#gsSettings [type=submit]').click();await expect(page.locator('#gsStatus')).toContainText('enregistrées');expect(await page.evaluate(()=>__PUBLIC.config.brand_name)).toBe('Brouillon à conserver');expect(await page.evaluate(()=>__PUBLIC.config.site_enabled)).toBe(false);
 await page.locator('[data-gs-tab=publication]').click();await expect(page.locator('[data-gs-path=site_enabled]')).not.toBeChecked();await page.locator('[data-gs-path=site_enabled]').check();await expect(state).toHaveText('Publication désactivée');await page.locator('#gsSettings [type=submit]').click();await expect(state).toHaveText('Site publié');await toggle.click();await expect(page.locator('[data-gs-path=site_enabled]')).not.toBeChecked();await expect(state).toHaveText('Publication désactivée');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'test-results/publication-button-'+width+'.png',fullPage:true});
 await page.locator('#gwReload').click();await expect(page.locator('#gsPublicationState')).toHaveText('Publication désactivée');await expect(page.locator('#gsPublicationToggle')).toHaveText('Activer la publication');
});
const cloud=fs.readFileSync(__dirname+'/mock-gama-cloud.js','utf8');
async function adminBoot(page,width=1280,{siteEnabled=true}={}){await page.setViewportSize({width,height:900});await page.addInitScript(({schema,config,items})=>{localStorage.setItem('gama_session_v1',JSON.stringify({role:'admin',name:'QA'}));localStorage.setItem('gama_language_v1','fr');window.__DB={products:[],customers:[],suppliers:[],invoices:[],app_modules:[]};window.__PUBLIC={schema,config,version:1,selected:2,unread:0,categories:['Bebidas'],items,calls:[]};},{schema,config:{...config,site_enabled:siteEnabled},items});const mock=cloud+`;(()=>{const old=GamaCloud.db;GamaCloud.db=async()=>{const c=await old();return {...c,rpc:async(fn,args)=>{if(fn!=='gama_website')return c.rpc(fn,args);const w=window.__PUBLIC,a=args.p_action,d=args.p_data;w.calls.push(structuredClone(args));let data;if(a==='overview')data={settings:{},currency:'USD',selected:0,inquiries:0,unread:0};if(a==='public_settings')data=w;if(a==='public_save_settings'){if(w.fail){w.fail=false;return {error:{message:'WEBSITE_SETTINGS_CHANGED'}}}w.config=d.config;w.version++;data={config:w.config,version:w.version};}if(a==='public_products')data={items:w.items.map(p=>({...p,public_visible:p.public_visible??true,public_featured:p.public_featured??false,version:p.version??1})),total:2};if(a==='public_save_product'){if(w.productFail){w.productFail=false;return {error:{message:'offline'}}}Object.assign(w.items.find(p=>p.id===d.id),d,{version:d.version+1});data={ok:true};}if(a==='public_inquiries')data={items:[],total:0};if(a==='public_connection')data={token:'a'.repeat(64)};return {data:structuredClone(data)}}};}})();`;await page.route('**/gama-supabase.js*',r=>r.fulfill({body:mock,contentType:'text/javascript'}));await page.goto('/index.html');await page.waitForFunction(()=>window.gamaAccessAllowed?.('website'));await page.locator('#mainmenu [data-gama-module=website]').click();await page.locator('[data-gw-tab=public]').click();await expect(page.locator('#gsSettings')).toBeVisible();await expect(page.locator('[data-gw-tab]')).toHaveCount(1);await expect(page.locator('#gwPreview,#gwStats,#gwSettings,.gwIntro')).toHaveCount(0);expect(await page.evaluate(()=>__PUBLIC.calls.every(c=>c.p_action.startsWith('public_')))).toBe(true)}
for(const width of [390,1280])test('all public settings are editable in Coco and failed saves retain the draft on '+width,async({page})=>{await adminBoot(page,width);await page.locator('[data-gs-path=brand_name]').fill('GAMA Moderne');await page.locator('[data-gs-tab=home]').click();await page.locator('[data-gs-path=hero_title]').fill('Un titre moderne');await page.locator('[data-gs-tab=content]').click();await page.locator('[data-gs-add=faq]').click();await page.locator('[data-gs-path="faq.2.question"]').fill('Une question');await page.locator('[data-gs-path="faq.2.answer"]').fill('Une réponse');await page.evaluate(()=>__PUBLIC.fail=true);await page.locator('#gsSettings [type=submit]').click();await expect(page.locator('#gsStatus')).toContainText('conservées');await expect(page.locator('[data-gs-path="faq.2.question"]')).toHaveValue('Une question');await page.locator('#gsSettings [type=submit]').click();await expect(page.locator('#gsStatus')).toContainText('enregistrées');expect(await page.evaluate(()=>__PUBLIC.config.brand_name)).toBe('GAMA Moderne');expect(await page.evaluate(()=>__PUBLIC.config.hero_title)).toBe('Un titre moderne');await page.locator('[data-gs-tab=products]').click();await expect(page.locator('[data-gs-edit]')).toHaveCount(2);await page.locator('[data-gs-edit]').first().click();await page.locator('[name=public_visible]').uncheck();await page.locator('dialog [type=submit]').click();await expect(page.locator('.gsDialog')).toHaveCount(0);await page.locator('[data-gs-tab=connection]').click();await page.locator('#gsShowKey').click();await expect(page.locator('#gsKey')).toHaveValue('a'.repeat(64));expect(await page.evaluate(()=>JSON.stringify(localStorage).includes('a'.repeat(64)))).toBe(false);await page.locator('[data-gs-tab=publication]').click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'test-results/public-admin-'+width+'.png',fullPage:true})});

for(const width of [390,1280])test('product publication checkbox saves directly and rolls back failed saves at '+width,async({page})=>{
 await adminBoot(page,width,{siteEnabled:false});await page.locator('[data-gs-tab=products]').click();const box=page.locator('[data-gs-visible]').first();await expect(box).toBeChecked();await box.uncheck();await expect(page.locator('#gsStatus')).toContainText('enregistrées');await expect(box).not.toBeChecked();expect(await page.evaluate(()=>__PUBLIC.calls.filter(c=>c.p_action==='public_save_product').at(-1).p_data.public_visible)).toBe(false);await page.evaluate(()=>__PUBLIC.productFail=true);await box.click();await expect(page.locator('#gsStatus')).toContainText('Échec');await expect(box).not.toBeChecked();await expect(page.locator('#gsPublicationState')).toHaveText('Publication désactivée');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
for(const width of [390,1280])test('B2B administration invites only the explicitly selected company after reviewing the email at '+width,async({page})=>{
 await adminBoot(page,width);await page.evaluate(()=>{window.__PORTAL_ADMIN=[];window.__PORTAL_INVITES=[];const old=GamaCloud.db;GamaCloud.db=async()=>{const c=await old();return {...c,functions:{...c.functions,invoke:async(name,{body})=>{__PORTAL_INVITES.push({name,body});return {data:{invited:true,portal_access:true}}}},rpc:async(fn,args)=>{if(fn!=='gama_b2b_admin')return c.rpc(fn,args);__PORTAL_ADMIN.push(args);return {data:{customers:[{id:'10000000-0000-4000-8000-000000000001',name:'Empresa de prueba',category:'B',enabled:true},{id:'10000000-0000-4000-8000-000000000002',name:'Empresa sin portal',category:'A',enabled:false}],accounts:[],memberships:[]}}}}}});
 await page.locator('[data-gs-tab=b2b]').click();await expect(page.locator('#b2bCustomerSearch')).toBeVisible();await expect(page.locator('#b2bAccountSearch')).toBeVisible();await expect(page.locator('#b2bAccountSearch').locator('..')).toContainText('Chercher un compte');await page.locator('#b2bAccountSearch').fill('cliente@example.invalid');await page.locator('#b2bSearch').click();await expect.poll(()=>page.evaluate(()=>__PORTAL_ADMIN.at(-1)?.p_data?.account_search)).toBe('cliente@example.invalid');await expect(page.locator('[data-b2b-invite]')).toHaveCount(2);await expect(page.locator('[data-b2b-invite]').nth(1)).toBeDisabled();await page.locator('[data-b2b-invite]').first().click();await expect(page.locator('dialog')).toContainText('Empresa de prueba');expect(await page.evaluate(()=>__PORTAL_INVITES)).toHaveLength(0);
 await page.locator('dialog [name=name]').fill('Compte client');await page.locator('dialog [name=email]').fill('client@example.invalid');await page.locator('dialog [name=message]').fill('Invitation relue par l’administrateur');await page.locator('dialog [type=submit]').click();await expect(page.locator('dialog [role=status]')).toContainText('Invitation envoyée');await expect(page.locator('dialog [type=submit]')).toBeDisabled();const calls=await page.evaluate(()=>__PORTAL_INVITES);expect(calls).toHaveLength(1);expect(calls[0]).toMatchObject({name:'architect-user-admin',body:{action:'invite_b2b',customer_id:'10000000-0000-4000-8000-000000000001',email:'client@example.invalid',message:'Invitation relue par l’administrateur'}});await page.locator('dialog [data-close]').click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'test-results/gama-b2b-admin-'+width+'.png',fullPage:true});
});
for(const width of [320,390,1440])test('company login stays accessible beside the cart when contact is hidden on '+width,async({page})=>{
 await boot(page,{width,contact:false});await expect(page.locator('#siteProducts .product-card')).toHaveCount(2);
 const login=page.getByRole('link',{name:'Iniciar sesión en Mi empresa'}),cart=page.locator('#cartOpen');
 await expect(login).toBeVisible();await expect(login).toHaveAttribute('href','/b2b.html');await expect(page.locator('#headerContact')).toBeHidden();await expect(cart).toBeVisible();
 const a=await login.boundingBox(),b=await cart.boundingBox();expect(Math.abs(a.y+a.height/2-b.y-b.height/2)).toBeLessThan(2);expect(a.x+a.width).toBeLessThanOrEqual(b.x+1);
 if(width<=600){expect(a.width).toBeGreaterThanOrEqual(44);expect(a.height).toBeGreaterThanOrEqual(44)}
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 await page.locator('#header').screenshot({path:'test-results/gama-company-access-bar-'+width+'.png'});
});

for(const width of [390,1440])test('real product photo, readable prose and legal disclosures are shared across views on '+width,async({page})=>{
 const photo='data:image/jpeg;base64,'+fs.readFileSync(path.join(__dirname,'../gama-logo.jpg')).toString('base64');
 const product={...items[0],has_photo:true,description:'PAPELERÍA PARA TU OFICINA',category_title:'SUMINISTROS DE OFICINA'};
 await boot(page,{width,catalogItems:[product],photoRows:[{id:product.id,photo_data:photo}],settings:{legal_tax_id:'12345',privacy_email:'privacidad@example.invalid',legal_name:'Distribuidora de prueba'}});
 await expect(page.locator('#siteProducts .product-image img')).toHaveAttribute('src',photo);
 await page.locator('#siteProducts .product-name').click();await expect(page.locator('#productTitle')).toHaveText('Café para oficina');
 await expect(page.locator('.detail-copy .eyebrow')).toHaveText('Suministros de oficina');await expect(page.locator('.detail-photo img')).toHaveAttribute('src',photo);await expect(page.locator('.detail-copy .description')).toHaveText('papelería para tu oficina');await expect(page.locator('.specifications')).toContainText('gama');
 await page.locator('[data-close-dialog=productDialog]').click();
 for(const kind of ['notice','delivery','storage','terms','privacy']){
  await page.locator('.footer [data-legal='+kind+']').click();await expect(page.locator('#legalDialog')).toBeVisible();await expect(page.locator('#legalText')).not.toBeEmpty();await expect(page.locator('#legalText')).not.toContainText('12345');
  if(kind==='privacy'){await expect(page.locator('#legalText')).toContainText('privacidad@example.invalid');await expect(page.locator('#legalText')).toContainText('Distribuidora de prueba')}
  await expectContained(page,'#legalDialog');await page.locator('[data-close-dialog=legalDialog]').click();
 }
 await page.locator('#siteProducts [data-add]').click();await page.locator('#cartOpen').click();
 for(const name of ['contact_name','email','consent'])expect(await page.locator('#quoteForm [name='+name+']').evaluate(n=>n.required)).toBe(true);
 for(const name of ['company','phone'])expect(await page.locator('#quoteForm [name='+name+']').evaluate(n=>n.required)).toBe(false);
 await expect(page.locator('#quoteForm [name=consent]')).not.toBeChecked();await expect(page.locator('#cartLines .cart-photo img')).toHaveAttribute('src',photo);
 expect(await page.evaluate(()=>__SITE_CALLS.filter(x=>x.p_action==='submit').length)).toBe(0);
});
