const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID:uuid}=require('node:crypto'),{restore}=require('../scripts/restore-schema.cjs');
test('Supplier XML creates one reviewed-later draft and private operational metrics report actual percentiles',async()=>{
 const db=await restore(),admin=uuid(),client=uuid(),supplier=uuid();const q=(s,p=[])=>db.query(s,p),one=async(s,p=[])=>Object.values((await q(s,p)).rows[0])[0],as=id=>db.exec(`reset role;select set_config('request.jwt.claim.sub','${id}',false);set role authenticated`);
 const importXml=data=>one('select gama_supplier_xml($1)',[data]);const metric=(a,d={})=>one('select gama_operational_metrics($1,$2)',[a,d]);
 const xml='<factura><infoTributaria><ruc>1790012345001</ruc><estab>001</estab><ptoEmi>001</ptoEmi><secuencial>000000031</secuencial></infoTributaria><infoFactura><fechaEmision>05/10/2026</fechaEmision><totalSinImpuestos>100.00</totalSinImpuestos><totalConImpuestos><totalImpuesto><codigo>2</codigo><valor>15.00</valor></totalImpuesto></totalConImpuestos><importeTotal>115.00</importeTotal><moneda>DOLAR</moneda></infoFactura></factura>';
 try{await q('insert into auth.users(id,email) values($1,$2),($3,$4)',[admin,'xml-admin@example.invalid',client,'xml-client@example.invalid']);await q("update profiles set active=true,role=case id when $1 then 'administrador' else 'cliente' end",[admin]);await q("insert into suppliers(id,name,tax_id) values($1,'XML supplier','1790012345001')",[supplier]);await as(client);await assert.rejects(importXml({xml}),/ROLE_NOT_ALLOWED/);await assert.rejects(metric('report'),/ROLE_NOT_ALLOWED/);
 await as(admin);await assert.rejects(importXml({xml:'<!DOCTYPE x [<!ENTITY ext SYSTEM "file:///etc/passwd">]><factura>&ext;</factura>'}),/INVALID_XML/);await assert.rejects(importXml({xml:xml.replace('115.00','116.00')}),/XML_TOTAL_OR_CURRENCY_INVALID/);
 const r=await importXml({xml,filename:'invoice.xml'});assert.equal(r.status,'draft');assert.equal((await importXml({xml,filename:'invoice.xml'})).id,r.id);assert.equal(Number(await one('select count(*) from accounting_entries')),0);assert.equal(await one('select source_reviewed from supplier_invoices where id=$1',[r.id]),false);
 const samples=[10,20,30,100].map(duration_ms=>({metric:'rpc',module:'accounting',operation:'gama_flow_finance',duration_ms,success:true,device:'desktop',network:'normal'}));assert.equal((await metric('record',{samples})).accepted,4);const report=await metric('report');assert.equal(report.rows[0].p95_ms,90);assert.equal(report.rows[0].samples,4);assert.ok(!('actor' in report.rows[0]));await assert.rejects(metric('record',{samples:[{...samples[0],operation:'payload?token=secret'}]}),/INVALID_DATA/);await assert.rejects(q('select * from private.supplier_xml_intakes'),/permission denied/);
 }finally{await db.close()}
});
