const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID:uuid}=require('node:crypto'),{restore}=require('../scripts/restore-schema.cjs');
test('survey publication reports repairable errors and selects real unconverted prospects',async()=>{
 const db=await restore(),admin=uuid(),lead=uuid(),converted=uuid(),customer=uuid();const q=async(s,p=[])=>(await db.query(s,p)).rows;const survey=async(a,d)=>(await q('select gama_surveys($1,$2) r',[a,d]))[0].r,rec=async(a,d)=>(await q('select gama_survey_recipients($1,$2) r',[a,d]))[0].r;
 try{await q('insert into auth.users(id,email) values($1,$2)',[admin,'publish-admin@example.invalid']);await q("update profiles set role='administrador',active=true where id=$1",[admin]);await q("select set_config('request.jwt.claim.sub',$1,false)",[admin]);await q("insert into customers(id,name) values($1,'Converted customer')",[customer]);await q("insert into crm_leads(id,kind,company,email,converted_customer_id) values($1,'empresa','Actual prospect','prospect@example.invalid',null),($2,'empresa','Converted prospect','converted@example.invalid',$3)",[lead,converted,customer]);await db.exec('set role authenticated');
 let s=await survey('save',{title:'Rating survey',quiz:true,questions:[{id:'rating',type:'rating',title:'Your rating',required:false}]});await assert.rejects(survey('state',{id:s.id,version:s.version,state:'open'}),/QUIZ_ANSWERS_REQUIRED/);s=await survey('save',{...s,quiz:false});s=await survey('state',{id:s.id,version:s.version,state:'open'});assert.equal(s.state,'open');assert.equal(s.quiz,false);
 const group=await rec('search',{kind:'lead'});assert.deepEqual(group.items.map(x=>x.id),[lead]);assert.equal(group.items[0].group,'lead');const prepared=await rec('prepare',{id:s.id,recipients:[{id:lead,kind:'lead'}]});assert.equal(prepared.items[0].email,'prospect@example.invalid');assert.equal((await rec('prepare',{id:s.id,recipients:[{id:lead,kind:'lead'}]})).items[0].token,prepared.items[0].token);assert.equal((await survey('invitations',{id:s.id})).total,1);await assert.rejects(rec('prepare',{id:s.id,recipients:[{id:converted,kind:'lead'}]}),/INVALID_CONTACT/);
 s=await survey('save',{title:'Expired',closes_at:'2000-01-01',questions:[{id:'text',type:'text',title:'Text',required:false}]});await assert.rejects(survey('state',{id:s.id,version:s.version,state:'open'}),/DEADLINE_EXPIRED/);s=await survey('save',{title:'Empty',questions:[]});await assert.rejects(survey('state',{id:s.id,version:s.version,state:'open'}),/QUESTIONS_REQUIRED/);
 }finally{await db.close()}
});
