const {test,expect}=require('@playwright/test'),fs=require('node:fs');
const cloud=fs.readFileSync(__dirname+'/mock-gama-cloud.js','utf8');
const api=cloud+`;(()=>{const old=GamaCloud.db;GamaCloud.db=async()=>{const c=await old();return {...c,rpc:async(fn,args)=>{if(fn!=='gama_surveys')return c.rpc(fn,args);const a=args.p_action,d=args.p_data,w=window.__SURVEYS;w.calls.push({a,d:structuredClone(d)});if(w.failure===a){w.failure=null;return {error:{message:'offline'}}}let data,s=w.items.find(s=>s.id===d.id);if(a==='list')data={items:w.items,total:w.items.length};if(a==='get')data=s;if(a==='save'){if(!d.id){s={...d,id:'s1',token:'123e4567-e89b-42d3-a456-426614174000',version:1,responses:0};w.items.push(s)}else Object.assign(s,d,{version:s.version+1});data=s}if(a==='state'){Object.assign(s,{state:d.state,version:s.version+1});data=s}if(a==='results'||a==='export'||a==='invitations')data={items:[],total:0};return {data:structuredClone(data)}}}}})();`;
async function boot(page,width){await page.setViewportSize({width,height:950});await page.addInitScript(()=>{localStorage.setItem('gama_session_v1',JSON.stringify({role:'admin',name:'QA'}));localStorage.setItem('gama_language_v1','fr');window.__DB={products:[],customers:[],suppliers:[],invoices:[],app_modules:[]};window.__SURVEYS={items:[],calls:[]}});await page.route('**/gama-supabase.js*',r=>r.fulfill({contentType:'text/javascript',body:api}));await page.route('**/@supabase/**',r=>r.abort());await page.goto('/index.html');await page.locator('#mainmenu [data-gama-module=surveys]').click()}
for(const width of [390,1280])test('survey draft preview publication closure and retry at '+width,async({page})=>{
 await boot(page,width);await page.locator('[data-sv=new]').click();await page.locator('[name=name]').fill('Votre expérience avec GAMA');await page.locator('[name=intro]').fill('Votre avis nous aide à mieux vous servir.');await page.locator('[data-sv=add]').click();await page.locator('[data-q=title]').fill('Recommanderiez-vous GAMA ?');await page.locator('[data-q=type]').selectOption('single');await page.locator('[data-q=choices]').fill('Oui\nNon');await page.locator('[data-q=required]').check();await page.locator('[data-sv=preview]').click();await expect(page.locator('dialog')).toContainText('aucune réponse');await page.locator('dialog [value=Oui]').check();await page.locator('dialog [name=sv_consent]').check();await page.locator('dialog [type=submit]').click();await expect(page.locator('dialog [role=status]')).toContainText('Aucune réponse enregistrée');expect(await page.evaluate(()=>__SURVEYS.calls.filter(x=>x.a==='save').length)).toBe(0);await page.locator('dialog [data-close]').click();
 await page.evaluate(()=>__SURVEYS.failure='save');await page.locator('#svEditor [type=submit]').click();await expect(page.locator('#svStatus')).toContainText('échoué');await expect(page.locator('[name=name]')).toHaveValue('Votre expérience avec GAMA');await page.locator('#svEditor [type=submit]').click();await expect(page.locator('#svStatus')).toContainText('enregistré');await page.locator('[data-sv=publish]').click();await expect(page.locator('.svBadge')).toHaveText('Publié');await expect(page.locator('[name=name]')).toBeDisabled();await page.locator('[data-tab=share]').click();await expect(page.locator('.svLink')).toHaveAttribute('href',/surveys.html#/);await page.locator('[data-tab=questions]').click();await page.locator('[data-sv=closeSurvey]').click();await expect(page.locator('.svBadge')).toHaveText('Fermé');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'test-results/surveys-admin-'+width+'.png',fullPage:true});
});
const survey={title:'Votre avis compte',introduction:'Merci de partager votre expérience.',language:'fr',questions:[{id:'one',type:'multiple',title:'Quels services utilisez-vous ?',choices:['Catalogue','Livraison'],required:true},{id:'two',type:'rating',title:'Votre satisfaction',required:true}],personal:false};
for(const width of [390,1280])test('public questionnaire validates required choices and preserves retry key at '+width,async({page})=>{
 await page.setViewportSize({width,height:950});for(const file of ['survey-form.js','surveys.js','surveys.css'])await page.route('**/'+file+'*',r=>r.fulfill({path:__dirname+'/../dist-storefront/'+file,contentType:file.endsWith('.css')?'text/css':'text/javascript'}));const submits=[];await page.route('**/api/surveys',r=>{const d=r.request().postDataJSON();if(d.p_action==='get')return r.fulfill({json:survey});submits.push(d);return r.fulfill({status:submits.length===1?503:200,json:submits.length===1?{error:'SURVEY_UNAVAILABLE'}:{thanks:'À bientôt.',id:'r1'}})});await page.goto('/dist-storefront/surveys.html#123e4567-e89b-42d3-a456-426614174000');await expect(page.locator('h1')).toHaveText('Votre avis compte');await page.locator('[name=two]').selectOption('5');await page.locator('[name=sv_consent]').check();await page.locator('[type=submit]').click();await expect(page.locator('[role=status]')).toContainText('obligatoires');expect(submits).toHaveLength(0);await page.locator('[value=Catalogue]').check();await page.locator('[type=submit]').click();await expect(page.locator('[role=status]')).toContainText('indisponible');await expect(page.locator('[value=Catalogue]')).toBeChecked();await page.locator('[type=submit]').click();await expect(page.locator('h1')).toContainText('Merci');expect(submits).toHaveLength(2);expect(submits[0].p_data.request_key).toBe(submits[1].p_data.request_key);expect(submits[1].p_data.answers).toEqual({one:['Catalogue'],two:5});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
