const {test,expect}=require('@playwright/test');
const fs=require('fs'),path=require('path');
const cloud=fs.readFileSync(path.join(__dirname,'mock-gama-cloud.js'),'utf8');
const delivery={id:'t1',customer:'Cliente Andes',address:'Quito',delivery_date:'2099-01-01',status:'Planificada',driver_id:'drv1'};
const cargo={managed:true,delivery:{id:'t1',customer:'Cliente Andes',address:'Quito',date:'2099-01-01',status:'Planificada',driver_id:'drv1'},shipment:{id:'s1',number:'EXP-000001',required:true,version:3,departed_at:null},complete:false,lines:[{id:'l1',description:'Café',reference:'CAFE',barcode:'0012345678905',location:'A01',quantity:2,scanned:1},{id:'l2',description:'Guayusa',reference:'TE',barcode:'0098765432105',location:'B02',quantity:1,scanned:0}],scans:[{id:'scan1',barcode:'0012345678905',quantity:1,at:'2026-09-12T12:00:00Z',by:'Operador',voided_at:null}]};
async function boot(page){
 await page.addInitScript(({delivery,cargo})=>{localStorage.setItem('gama_session_v1',JSON.stringify({role:'magasinier',name:'Test loader'}));localStorage.setItem('gama_tms_migrated_v1','1');window.__DB={products:[],customers:[],profiles:[],tms_deliveries:[delivery],tms_drivers:[{id:'drv1',name:'Pedro',vehicle:'Camión 1',enabled:true}],tms_routes:[],tms_events:[],tms_proofs:[],tms_settings:[],hr_employees:[],hr_absences:[]};window.__cargo=cargo},{delivery,cargo});
 await page.route('**/gama-supabase.js*',r=>r.fulfill({contentType:'text/javascript',body:cloud}));await page.route('**/@supabase/**',r=>r.abort());await page.goto('/index.html');await page.waitForFunction(()=>window.GamaLoading&&window.gamaTMS&&window.GamaCloud);
 await page.evaluate(()=>{const old=GamaCloud.db;window.__loadingCalls=[];GamaCloud.db=async()=>{const c=await old();return {...c,rpc:async(fn,args)=>{if(fn!=='gama_loading_action')return c.rpc(fn,args);window.__loadingCalls.push(args);if(window.__loadError&&['scan','depart','void_scan'].includes(args.p_action))return {error:{message:window.__loadError}};if(args.p_action==='list')return {data:[{id:'t1',number:'EXP-000001',customer:'Cliente Andes',date:'2099-01-01',status:'Planificada',departed_at:null,complete:false}]};if(args.p_action==='scan'){const l=window.__cargo.lines.find(l=>l.barcode===args.p_data.barcode);if(l)l.scanned+=args.p_data.quantity;window.__cargo.complete=window.__cargo.lines.every(l=>l.scanned===l.quantity);window.__cargo.shipment.version++}if(args.p_action==='depart'){window.__cargo.shipment.departed_at='2026-09-12T12:00:00Z';window.__cargo.shipment.vehicle='Camión 1';window.__cargo.delivery.status='En tránsito'}return {data:structuredClone(window.__cargo)}}}}});
 await page.waitForTimeout(600);await page.evaluate(()=>GamaLoading.open());await page.locator('[data-gl-delivery]').click();
}
async function scan(page,code,quantity='1'){await page.locator('#glBarcode').fill(code);await page.locator('#glQty').fill(quantity);await page.locator('#glBarcode').press('Enter')}
test('all shipment lines must be scanned before the departure button unlocks',async({page})=>{
 await boot(page);await expect(page.locator('#glDepart')).toBeDisabled();await scan(page,'0012345678905');await expect(page.locator('#glDepart')).toBeDisabled();await expect(page.locator('.glTable')).toContainText('Por escanear');await scan(page,'0098765432105');await expect(page.locator('#glDepart')).toBeEnabled();await expect(page.locator('#gamaLoadingHost')).toContainText('2 / 2 líneas verificadas');await page.screenshot({path:'test-results/tms-loading-complete.png',fullPage:true});
});
test('wrong barcode and overscan errors preserve the scan fields',async({page})=>{
 await boot(page);await page.evaluate(()=>window.__loadError='WRONG_PRODUCT');await scan(page,'WRONG');await expect(page.locator('#glMessage')).toContainText('no pertenece');await expect(page.locator('#glBarcode')).toHaveValue('WRONG');await page.evaluate(()=>window.__loadError='EXCEEDS_CARGO_QUANTITY');await scan(page,'0012345678905','9');await expect(page.locator('#glMessage')).toContainText('supera');await expect(page.locator('#glQty')).toHaveValue('9');await expect(page.locator('#glDepart')).toBeDisabled();
});
test('network retry reuses its request UUID and a different scan gets another UUID',async({page})=>{
 await boot(page);await page.evaluate(()=>window.__loadError='network error');await scan(page,'0012345678905');await expect(page.locator('#glMessage')).toContainText('network');await page.locator('#glScan').click();await expect.poll(async()=>page.evaluate(()=>__loadingCalls.filter(x=>x.p_action==='scan').length)).toBe(2);await scan(page,'0098765432105');const a=await page.evaluate(()=>__loadingCalls.filter(x=>x.p_action==='scan'));expect(a[0].p_data.request_key).toBe(a[1].p_data.request_key);expect(a[2].p_data.request_key).not.toBe(a[1].p_data.request_key);
});
test('phone camera targets the loading field and submits a decoded barcode',async({page})=>{
 await boot(page);await page.evaluate(()=>window.startGamaScan=id=>window.__cameraTarget=id);await page.locator('#glCamera').click();expect(await page.evaluate(()=>__cameraTarget)).toBe('glBarcode');await page.evaluate(()=>{const e=document.getElementById('glBarcode');e.value='0012345678905';e.dispatchEvent(new CustomEvent('gama:barcode-scanned',{bubbles:true,detail:{code:e.value}}))});await expect.poll(async()=>page.evaluate(()=>__loadingCalls.filter(x=>x.p_action==='scan').length)).toBe(1);const a=await page.evaluate(()=>__loadingCalls.find(x=>x.p_action==='scan'));expect(a.p_data.barcode).toBe('0012345678905');expect(a.p_data.quantity).toBe(1);
});
test('departure sends the checked version and driver, then closes loading',async({page})=>{
 await boot(page);await scan(page,'0012345678905');await scan(page,'0098765432105');page.once('dialog',d=>d.accept());await page.locator('#glDepart').click();await expect(page.locator('#gamaLoadingHost')).toContainText('Salida registrada');await expect(page.locator('#glScanForm')).toHaveCount(0);const a=await page.evaluate(()=>__loadingCalls.find(x=>x.p_action==='depart'));expect(a.p_data).toEqual({delivery_id:'t1',version:5,driver_id:'drv1'});
});
test('voiding a scan submits its ID and a reason without deleting history',async({page})=>{
 await boot(page);await page.locator('#gamaLoadingHost summary').click();page.once('dialog',d=>d.accept('Producto retirado del camión'));await page.locator('[data-gl-void]').click();await expect.poll(async()=>page.evaluate(()=>__loadingCalls.filter(x=>x.p_action==='void_scan').length)).toBe(1);const a=await page.evaluate(()=>__loadingCalls.find(x=>x.p_action==='void_scan'));expect(a.p_data).toEqual({delivery_id:'t1',scan_id:'scan1',reason:'Producto retirado del camión'});
});
test('mobile cargo screen fits and exposes scanner and quantities',async({page})=>{
 await page.setViewportSize({width:390,height:844});await boot(page);await expect(page.locator('#glCamera')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(391);await page.screenshot({path:'test-results/tms-loading-mobile.png',fullPage:true});
});
test('manual TMS deliveries without sales lines display an explanatory message',async({page})=>{
 await boot(page);await page.evaluate(()=>{window.__cargo={managed:false,delivery:{id:'t1'},shipment:null,lines:[],scans:[]}});await page.locator('#glReload').click();await expect(page.locator('#gamaLoadingHost')).toContainText('no está vinculada');await expect(page.locator('#glScanForm')).toHaveCount(0);
});
