const {test,expect}=require('@playwright/test');
const fs=require('fs'),path=require('path');
const cloud=fs.readFileSync(path.join(__dirname,'mock-gama-cloud.js'),'utf8');
const delivery={id:'t1',customer:'Cliente Andes',address:'Quito',delivery_date:'2099-01-01',status:'Planificada',driver_id:'drv1'};
const cargo={managed:true,delivery:{id:'t1',customer:'Cliente Andes',address:'Quito',date:'2099-01-01',status:'Planificada',driver_id:'drv1'},shipment:{id:'s1',number:'EXP-000001',required:true,version:3,departed_at:null},complete:false,lines:[{id:'l1',description:'Café',reference:'CAFE',barcode:'0012345678905',location:'A01',quantity:2,scanned:1},{id:'l2',description:'Guayusa',reference:'TE',barcode:'0098765432105',location:'B02',quantity:1,scanned:0}],scans:[{id:'scan1',barcode:'0012345678905',quantity:1,at:'2026-09-12T12:00:00Z',by:'Operador',voided_at:null}]};
async function boot(page){
 await page.addInitScript(({delivery,cargo})=>{localStorage.setItem('gama_session_v1',JSON.stringify({role:'magasinier',name:'Test loader'}));localStorage.setItem('gama_tms_migrated_v1','1');window.__DB={products:[],customers:[],profiles:[],tms_deliveries:[delivery],fleet_drivers:[{id:'drv1',name:'Pedro',active:true}],fleet_vehicles:[{id:'veh1',plate:'Camión 1',status:'in_service',active:true,payload_kg:3500,cargo_volume_m3:18}],fleet_assignments:[{id:'asg1',driver_id:'drv1',vehicle_id:'veh1',ended_on:null}],tms_routes:[],tms_events:[],tms_proofs:[],tms_settings:[],hr_employees:[],hr_absences:[]};window.__cargo=cargo},{delivery,cargo});
 await page.route('**/gama-supabase.js*',r=>r.fulfill({contentType:'text/javascript',body:cloud}));await page.route('**/@supabase/**',r=>r.abort());await page.goto('/index.html');await page.waitForFunction(()=>window.GamaLoading&&window.gamaTMS&&window.GamaCloud);
 await page.evaluate(()=>{const old=GamaCloud.db;window.__loadingCalls=[];GamaCloud.db=async()=>{const c=await old();return {...c,rpc:async(fn,args)=>{if(fn!=='gama_loading_action')return c.rpc(fn,args);window.__loadingCalls.push(args);if(window.__loadError&&['scan','depart','void_scan'].includes(args.p_action))return {error:{message:window.__loadError}};if(args.p_action==='list')return {data:[{id:'t1',number:'EXP-000001',customer:'Cliente Andes',date:'2099-01-01',status:'Planificada',departed_at:null,complete:false}]};if(args.p_action==='scan'){const l=window.__cargo.lines.find(l=>l.barcode===args.p_data.barcode);if(l)l.scanned+=args.p_data.quantity;window.__cargo.complete=window.__cargo.lines.every(l=>l.scanned===l.quantity);window.__cargo.shipment.version++}if(args.p_action==='depart'){window.__cargo.shipment.departed_at='2026-09-12T12:00:00Z';window.__cargo.shipment.vehicle='Camión 1';window.__cargo.delivery.status='En tránsito'}return {data:structuredClone(window.__cargo)}}}}});
 await page.waitForTimeout(600);await page.evaluate(()=>GamaLoading.open());await page.locator('[data-gl-delivery]').click();
}
async function scan(page,code,quantity='1'){await page.locator('#glBarcode').fill(code);await page.locator('#glQty').fill(quantity);await page.locator('#glBarcode').press('Enter')}
test('transport has no product scanner and departs prepared parcels',async({page})=>{
 await boot(page);await expect(page.locator('#glBarcode,#glCamera,#glScan,#glPack')).toHaveCount(0);await expect(page.locator('#glDepart')).toBeDisabled();await page.evaluate(()=>__cargo.complete=true);await page.locator('#glReload').click();await expect(page.locator('#glDepart')).toBeEnabled();await page.locator('#glDepart').click();await expect(page.locator('#glDepart')).toHaveCount(0);expect(await page.evaluate(()=>__loadingCalls.some(c=>c.p_action==='scan'))).toBe(false);
});
test('transport refresh preserves driver and stale departure errors',async({page})=>{await boot(page);await page.evaluate(()=>{__cargo.complete=true;__loadError=null});await page.locator('#glReload').click();await page.evaluate(()=>__loadError='LOADING_CHANGED');await page.locator('#glDepart').click();await expect(page.locator('#glMessage')).toContainText('ha cambiado');await expect(page.locator('#glDriver')).toHaveValue('drv1')});
test('mobile transport fits without barcode controls',async({page})=>{await page.setViewportSize({width:390,height:844});await boot(page);await expect(page.locator('#glBarcode,#glCamera')).toHaveCount(0);expect(await page.locator('#gamaLoadingHost').evaluate(el=>el.getBoundingClientRect().width)).toBeLessThanOrEqual(390)});
