const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID:uuid}=require('node:crypto'),{restore}=require('../scripts/restore-schema.cjs');
test('Road matrices stay private, validate atomically, expire, and scheduling waits for windows without changing departure',async()=>{
 const db=await restore(),admin=uuid(),customer=uuid(),order=uuid(),driver=uuid(),vehicle=uuid(),delivery=uuid();
 const q=(s,p=[])=>db.query(s,p),one=async(s,p=[])=>Object.values((await q(s,p)).rows[0])[0],as=async()=>{await db.exec('reset role');await q("select set_config('request.jwt.claim.sub',$1,false)",[admin]);await db.exec('set role authenticated')},roads=(a,d={})=>one('select gama_tms_roads($1,$2)',[a,d]);
 try{
  await q('insert into auth.users(id,email) values($1,$2)',[admin,'roads@example.invalid']);await q("update profiles set active=true,role='administrador' where id=$1",[admin]);await q("select set_config('request.jwt.claim.sub',$1,false)",[admin]);
  const day=await one('select (now() at time zone private.erp_timezone())::date::text');
  await q("insert into customers(id,name) values($1,'Road customer')",[customer]);await q("insert into sales_orders(id,customer_id,customer_name,created_by,request_key,status) values($1,$2,'Road customer',$3,$4,'confirmed')",[order,customer,admin,uuid()]);
  await db.exec('update fleet_drivers set active=false');await q("insert into fleet_drivers(id,name,active) values($1,'Road driver',true)",[driver]);await q("insert into fleet_vehicles(id,plate,brand,model,kind,energy,status,payload_kg,cargo_volume_m3) values($1,'ROAD-TEST','Test','Truck','truck','other','in_service',100,10)",[vehicle]);await q('insert into fleet_assignments(vehicle_id,driver_id,started_on) values($1,$2,$3)',[vehicle,driver,day]);
  await db.exec("insert into tms_settings(id,depot,depot_lat,depot_lng,return_depot) values(true,'Quito',-0.2,-78.5,true) on conflict(id) do update set depot_lat=-0.2,depot_lng=-78.5,return_depot=true;begin;set session_replication_role=replica");
  await q("insert into tms_deliveries(id,customer,address,delivery_date,weight,volume,lat,lng,time_window) values($1,'Road customer','Quito',$2,1,1,-0.21,-78.51,'09:00-10:00')",[delivery,day]);await q("insert into sales_deliveries(number,order_id,request_key,tms_delivery_id,created_by,loading_required) values('ROAD-TEST',$1,$2,$3,$4,false)",[order,uuid(),delivery,admin]);await db.exec('set session_replication_role=origin;commit');
  await as();assert.equal((await roads('prepare',{day})).configured,false);await roads('configure',{api_key:'fixture-only-no-network',profile:'driving-car',enabled:true});const queued=await roads('prepare',{day});assert.equal(queued.locations,2);assert.equal((await roads('prepare',{day})).existing,true);await assert.rejects(q('select * from private.tms_road_pairs'),/permission denied/);assert.ok(!JSON.stringify(await roads('context')).includes('fixture-only'));
  await db.exec('reset role');const req=await one('select request_id from private.tms_road_requests');await q('insert into net._http_response(id,status_code,content) values($1,200,$2)',[req,JSON.stringify({distances:[[0,7],[9,0]],durations:[[0,600],[1200,0]]})]);await one('select private.tms_road_poll()');assert.equal(Number(await one('select count(*) from private.tms_road_pairs')),4);
  // Direction matters. A malformed second matrix cannot partly replace the cache.
  const loc=await one('select locations from private.tms_road_requests'),a=loc[0],b=loc[1];assert.equal((await one('select private.tms_road_metric($1,$2,$3,$4)',[a[1],a[0],b[1],b[0]])).km,7);assert.equal((await one('select private.tms_road_metric($1,$2,$3,$4)',[b[1],b[0],a[1],a[0]])).km,9);
  await q("insert into private.tms_road_requests(day,profile,locations,fingerprint,request_id) values($1,'driving-car',$2,'invalid-fixture',99999)",[day,loc]);await q('insert into net._http_response(id,status_code,content) values(99999,200,$1)',[JSON.stringify({distances:[[0,99],[9,'bad']],durations:[[0,600],[1200,0]]})]);await one('select private.tms_road_poll()');assert.equal(await one("select state from private.tms_road_requests where fingerprint='invalid-fixture'"),'failed');assert.equal((await one('select private.tms_road_metric($1,$2,$3,$4)',[a[1],a[0],b[1],b[0]])).km,7);
  await as();await one('select gama_tms_plan_day($1::date)',[day]);const route=await one('select id from tms_routes');const preview=await roads('route',{route_id:route});assert.equal(preview.missing,0);
  const starts=await one("select ($1::date+time '08:00') at time zone private.erp_timezone()",[day]),data={route_id:route,starts_at:starts.toISOString(),road_source:'fixture verified road',legs:preview.legs};const schedule=await one('select gama_route_schedule($1)',[data]);const stop=schedule.legs.find(l=>l.id===delivery);assert.ok(stop.waiting_minutes>0);assert.equal(await one('select departed_at from sales_deliveries where tms_delivery_id=$1',[delivery]),null);
  const late=await one("select ($1::date+time '12:00') at time zone private.erp_timezone()",[day]);await assert.rejects(one('select gama_route_schedule($1)',[{...data,starts_at:late.toISOString()}]),/TIME_WINDOW_EXCEPTION_REASON_REQUIRED/);assert.equal((await one('select starts_at from tms_route_schedules where route_id=$1',[route])).toISOString(),starts.toISOString());const accepted=await one('select gama_route_schedule($1)',[{...data,starts_at:late.toISOString(),window_exception_reason:'Customer approved late arrival'}]);assert.equal(accepted.window_exceptions.warnings[0].reason,'TIME_WINDOW_LATE');
  await db.exec("reset role;update private.tms_road_pairs set measured_at=now()-interval '15 days'");assert.equal(await one('select private.tms_road_metric($1,$2,$3,$4)',[a[1],a[0],b[1],b[0]]),null);
  await db.exec('set role anon');await assert.rejects(roads('context'),/permission denied/);
 }finally{await db.close()}
});
