const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID:uuid}=require('node:crypto'),{restore}=require('../scripts/restore-schema.cjs');
test('Waze replaces network matrices while manual route schedules still respect windows and departure',async()=>{
 const db=await restore(),admin=uuid(),customer=uuid(),order=uuid(),driver=uuid(),vehicle=uuid(),delivery=uuid();
 const q=(s,p=[])=>db.query(s,p),one=async(s,p=[])=>Object.values((await q(s,p)).rows[0])[0],as=async()=>{await db.exec('reset role');await q("select set_config('request.jwt.claim.sub',$1,false)",[admin]);await db.exec('set role authenticated')},roads=(a,d={})=>one('select gama_tms_roads($1,$2)',[a,d]);
 try{
  await q('insert into auth.users(id,email) values($1,$2)',[admin,'roads@example.invalid']);await q("update profiles set active=true,role='administrador' where id=$1",[admin]);await q("select set_config('request.jwt.claim.sub',$1,false)",[admin]);
  const day=await one('select (now() at time zone private.erp_timezone())::date::text');
  await q("insert into customers(id,name) values($1,'Road customer')",[customer]);await q("insert into sales_orders(id,customer_id,customer_name,created_by,request_key,status) values($1,$2,'Road customer',$3,$4,'confirmed')",[order,customer,admin,uuid()]);
  await db.exec('update fleet_drivers set active=false');await q("insert into fleet_drivers(id,name,active) values($1,'Road driver',true)",[driver]);await q("insert into fleet_vehicles(id,plate,brand,model,kind,energy,status,payload_kg,cargo_volume_m3) values($1,'ROAD-TEST','Test','Truck','truck','other','in_service',100,10)",[vehicle]);await q('insert into fleet_assignments(vehicle_id,driver_id,started_on) values($1,$2,$3)',[vehicle,driver,day]);
  await db.exec("insert into tms_settings(id,depot,depot_lat,depot_lng,return_depot) values(true,'Quito',-0.2,-78.5,true) on conflict(id) do update set depot_lat=-0.2,depot_lng=-78.5,return_depot=true;begin;set session_replication_role=replica");
  await q("insert into tms_deliveries(id,customer,address,delivery_date,weight,volume,lat,lng,time_window) values($1,'Road customer','Quito',$2,1,1,-0.21,-78.51,'09:00-10:00')",[delivery,day]);await q("insert into sales_deliveries(number,order_id,request_key,tms_delivery_id,created_by,loading_required) values('ROAD-TEST',$1,$2,$3,$4,false)",[order,uuid(),delivery,admin]);await db.exec('set session_replication_role=origin;commit');
  await as();assert.equal((await roads('prepare',{day})).provider,'waze');assert.equal((await roads('context')).provider.api_key_required,false);await assert.rejects(roads('configure',{api_key:'not-used',profile:'driving-car',enabled:true}),/WAZE_NAVIGATION_ONLY/);await assert.rejects(q('select * from private.tms_road_pairs'),/permission denied/);
  await one('select gama_tms_plan_day($1::date)',[day]);const route=await one('select id from tms_routes');const preview=await roads('route',{route_id:route});assert.equal(preview.navigation_provider,'waze');assert.ok(preview.missing>0);
  const stops=await one('select stops from tms_routes where id=$1',[route]);preview.legs=stops.map((id,i)=>({id,road_km:i?9:0,drive_minutes:i?10:0,service_minutes:0}));
  const starts=await one("select ($1::date+time '08:00') at time zone private.erp_timezone()",[day]),data={route_id:route,starts_at:starts.toISOString(),road_source:'Waze · checked manually',legs:preview.legs};const schedule=await one('select gama_route_schedule($1)',[data]);const stop=schedule.legs.find(l=>l.id===delivery);assert.ok(stop.waiting_minutes>0);assert.equal(await one('select departed_at from sales_deliveries where tms_delivery_id=$1',[delivery]),null);
  const late=await one("select ($1::date+time '12:00') at time zone private.erp_timezone()",[day]);await assert.rejects(one('select gama_route_schedule($1)',[{...data,starts_at:late.toISOString()}]),/TIME_WINDOW_EXCEPTION_REASON_REQUIRED/);assert.equal((await one('select starts_at from tms_route_schedules where route_id=$1',[route])).toISOString(),starts.toISOString());const accepted=await one('select gama_route_schedule($1)',[{...data,starts_at:late.toISOString(),window_exception_reason:'Customer approved late arrival'}]);assert.equal(accepted.window_exceptions.warnings[0].reason,'TIME_WINDOW_LATE');
  await db.exec('reset role');assert.equal((await one('select private.tms_road_poll()')).matrices_ready,0);assert.equal(Number(await one('select count(*) from net.fixture_requests')),0);assert.equal(await one('select private.tms_road_metric(-0.2,-78.5,-0.21,-78.51)'),null);
  await db.exec('set role anon');await assert.rejects(roads('context'),/permission denied/);
 }finally{await db.close()}
});
