const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID:uuid}=require('node:crypto');
const fs=require('node:fs'),path=require('node:path'),{restore}=require('../scripts/restore-schema.cjs');
const migration='20260927204151_permanent_user_deletion.sql';
test('permanent login deletion releases email, revokes stale JWTs and preserves business history atomically',async()=>{
 const db=await restore({before:migration}),admin=uuid(),target=uuid(),staff=uuid(),pending=uuid(),customer=uuid(),product=uuid();
 const query=async(s,p=[])=>(await db.query(s,p)).rows;
 const as=async id=>db.exec(`reset role;select set_config('request.jwt.claim.sub','${id}',false);set role authenticated`);
 const remove=(id,email)=>query('select gama_delete_user($1,$2) r',[id,email]);
 try{
  // Platform fixture: model the real Auth uniqueness and cascading credentials.
  await db.exec(`create unique index fixture_auth_email on auth.users(lower(email));
   alter table auth.mfa_factors drop constraint mfa_factors_user_id_fkey,add foreign key(user_id) references auth.users(id) on delete cascade;
   create table if not exists auth.sessions(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete cascade);
   alter table auth.sessions drop constraint sessions_user_id_fkey,add foreign key(user_id) references auth.users(id) on delete cascade;
   create table auth.identities(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete cascade);
   create table auth.refresh_tokens(id uuid primary key default gen_random_uuid(),user_id text,session_id uuid references auth.sessions(id) on delete cascade);
   alter table storage.objects add column owner uuid references auth.users(id);
   insert into auth.users(id,email) values('${admin}','delete-admin@example.invalid'),('${target}','reuse@example.invalid'),('${staff}','delete-staff@example.invalid'),('${pending}','pending@example.invalid');
   update profiles set role=case when id='${staff}' then 'comercial' when id='${pending}' then 'cliente' else 'administrador' end,active=(id<>'${pending}');
   select set_config('request.jwt.claim.sub','${target}',false);
   insert into customers(id,name,address) values('${customer}','Deletion regression','Test');
   insert into products(id,name,reference,barcode,purchase_price,sale_price) values('${product}','History item','DELETE-ITEM','DELETE-CODE',1,2);`);
  const loc=(await query('select id from warehouse_locations where active limit 1'))[0].id;
  await query('select gama_stock_adjust($1,$2,5,null,$3)',[product,loc,'Opening history fixture']);
  const order=(await query("select gama_sales_action('create',$1) r",[{request_key:uuid(),customer_id:customer,lines:[{product_id:product,quantity:2,unit_price:2,tax_rate:0}]}]))[0].r;
  const quote=(await query('insert into invoices(user_id) values($1) returning id',[target]))[0];
  await db.exec(`insert into sri_electronic_documents(user_id,invoice_id,ambiente,authorized_xml) values('${target}','${quote.id}','pruebas','retained XML');
   insert into accounting_permissions(profile_id,can_view) values('${target}',true);
   insert into storage.objects(bucket_id,name,owner,owner_id) values('business-documents','history.pdf','${target}','${target}');
   insert into auth.sessions(user_id) values('${target}');insert into auth.identities(user_id) values('${target}');
   insert into auth.refresh_tokens(user_id,session_id) select '${target}',id from auth.sessions where user_id='${target}';
   insert into auth.refresh_tokens(user_id) values('${target}');
   insert into auth.mfa_factors(user_id,status) values('${target}','verified');`);
  const history=async()=>({orders:await query('select * from sales_orders order by id'),quotes:await query('select * from invoices order by id'),stock:await query('select * from stock_quants order by id'),movements:await query('select * from stock_movements order by id'),sri:await query('select * from sri_electronic_documents order by id'),references:await query('select * from gama_document_references order by table_name,document_id')});
  const before=await history();await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/migrations',migration),'utf8'));
  assert.deepEqual(await history(),before);
  await as(staff);await assert.rejects(remove(target,'reuse@example.invalid'),/USER_DELETE_NOT_ALLOWED/);
  await as(pending);await assert.rejects(remove(target,'reuse@example.invalid'),/USER_DELETE_NOT_ALLOWED/);
  await as(admin);await assert.rejects(remove(admin,'delete-admin@example.invalid'),/CANNOT_DELETE_SELF/);
  await assert.rejects(remove(target,'wrong@example.invalid'),/USER_EMAIL_CONFIRMATION_MISMATCH/);
  await assert.rejects(query("update profiles set deleted_at=now(),active=false,email=null where id=$1",[target]),/USE_PERMANENT_USER_DELETION/);
  await assert.rejects(query('delete from profiles where id=$1',[target]),/USE_PERMANENT_USER_DELETION/);
  await db.exec('reset role');await query("insert into erp_action_permissions(role,module,allow_delete) values('administrador','users',false)");await as(admin);
  await assert.rejects(remove(target,'reuse@example.invalid'),/USER_DELETE_NOT_ALLOWED/);
  await db.exec('reset role');await query("update erp_action_permissions set allow_delete=true where role='administrador' and module='users'");await as(admin);
  await db.exec(`reset role;insert into auth.mfa_factors(user_id,status) values('${admin}','verified');set role authenticated`);
  await assert.rejects(remove(target,'reuse@example.invalid'),/AUTH_OR_MFA_REQUIRED/);
  await db.exec(`select set_config('request.jwt.claims','{"aal":"aal2"}',false)`);
  // A late failure rolls back both the archive and Storage ownership.
  await db.exec(`reset role;create function private.fail_fixture_delete() returns trigger language plpgsql as $$begin raise exception 'TEST_DELETE_FAILURE';end $$;
   create trigger zz_fixture_delete before delete on auth.users for each row execute function private.fail_fixture_delete();set role authenticated;`);
  await assert.rejects(remove(target,'reuse@example.invalid'),/TEST_DELETE_FAILURE/);
  await db.exec('reset role;drop trigger zz_fixture_delete on auth.users');
  assert.equal((await query('select active from profiles where id=$1',[target]))[0].active,true);
  assert.equal((await query('select owner_id from storage.objects where name=$1',['history.pdf']))[0].owner_id,target);
  await as(admin);const deleted=await remove(target,' REUSE@EXAMPLE.INVALID ');assert.equal(deleted[0].r.deleted,true);
  assert.deepEqual(await remove(target,'reuse@example.invalid'),deleted);
  await db.exec('reset role');
  for(const table of ['users','sessions','identities','mfa_factors'])assert.equal((await query(`select count(*)::int n from auth.${table} where ${table==='users'?'id':'user_id'}=$1`,[target]))[0].n,0);
  assert.equal((await query('select count(*)::int n from auth.refresh_tokens'))[0].n,0);
  const archived=(await query('select * from profiles where id=$1',[target]))[0];assert.ok(archived.deleted_at);assert.equal(archived.active,false);assert.equal(archived.email,null);
  assert.deepEqual(await history(),before);
  assert.equal((await query('select count(*)::int n from accounting_permissions where profile_id=$1',[target]))[0].n,0);
  const file=(await query('select * from storage.objects where name=$1',['history.pdf']))[0];assert.equal(file.owner,admin);assert.equal(file.owner_id,admin);
  assert.equal((await query("select count(*)::int n from erp_audit_events where operation='DELETE_LOGIN' and record_id=$1",[target]))[0].n,1);
  await as(target);assert.equal((await query('select private.erp_mfa_ok() ok'))[0].ok,false);
  assert.equal((await query('select * from sri_electronic_documents')).length,0);assert.equal((await query('select * from profiles')).length,0);
  await assert.rejects(remove(staff,'delete-staff@example.invalid'),/AUTH_OR_MFA_REQUIRED/);
  await as(admin);await assert.rejects(query('update profiles set active=true,deleted_at=null where id=$1',[target]),/USER_ALREADY_DELETED/);
  await db.exec('reset role');const fresh=uuid();await query('insert into auth.users(id,email) values($1,$2)',[fresh,'reuse@example.invalid']);
  const account=(await query('select * from profiles where id=$1',[fresh]))[0];assert.equal(account.deleted_at,null);assert.equal(account.active,false);assert.equal(account.role,'cliente');
  assert.equal((await query('select count(*)::int n from accounting_permissions where profile_id=$1',[fresh]))[0].n,0);
  assert.equal((await query('select created_by from sales_orders where id=$1',[order.id]))[0].created_by,target);
  // The existing service-role account-creation upsert remains valid.
  await db.exec('set role service_role');await query("insert into profiles(id,full_name,role,active) values($1,'Recreated','cliente',true) on conflict(id) do update set full_name=excluded.full_name,active=excluded.active",[fresh]);
  await as(admin);await remove(pending,'pending@example.invalid');
  await db.exec("reset role;select set_config('request.jwt.claim.sub','',false)");
  await assert.rejects(query('delete from auth.users where id=$1',[admin]),/LAST_ADMIN_REQUIRED/);
  await db.exec('set role anon');await assert.rejects(remove(staff,'delete-staff@example.invalid'),/permission denied/);
 }finally{await db.close()}
});
