const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID:uuid}=require('node:crypto');const {restore}=require('../scripts/restore-schema.cjs');
test('website requests match unique customers, preserve ambiguity, and resolve contacts atomically with permissions',async()=>{
 const db=await restore(),admin=uuid(),client=uuid(),p=uuid(),c1=uuid(),c2=uuid();const q=async(s,a=[])=>(await db.query(s,a)).rows;
 const login=async(id,role='authenticated')=>{await db.exec('reset role');await q("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role '+role)};
 const resolve=async(id,a,d={})=>(await q('select gama_request_contact($1,$2,$3) r',[id,a,d]))[0].r;
 const inquiry=async(name,email,company='')=>{await db.exec('reset role');const id=uuid();await q("insert into private.website_public_inquiries(id,request_key,payload,contact_name,email,company,phone,lines,currency,total,visitor_hash,consent_at) values($1,$2,'{}',$3,$4,$5,'099123',$6,'USD',23,'test',now())",[id,uuid(),name,email,company,[{product_id:p,quantity:2,unit_price:10,tax_rate:15,subtotal:20}]]);return (await q('select * from customer_requests where source_website_id=$1',[id]))[0]};
 try{
 await q('insert into auth.users(id,email) values($1,$2),($3,$4)',[admin,'webstaff@example.invalid',client,'webclient@example.invalid']);await q("update profiles set active=true,role=case when id=$1 then 'administrador' else 'cliente' end",[admin]);await q("insert into products(id,name) values($1,'Website test')",[p]);await q("insert into customers(id,name,identification,email) values($1,'Empresa Uno','WEB1','one@example.invalid'),($2,'Empresa Dos','WEB2','two@example.invalid')",[c1,c2]);
 let r=await inquiry('Someone','ONE@example.invalid');assert.equal(r.customer_id,c1);assert.equal(Number(r.total),20);assert.equal(r.created_by,null);assert.match(r.website_reference,/WEB-/);assert.equal((await q('select * from customer_request_lines where request_id=$1',[r.id])).length,1);
 r=await inquiry(' empresa   dos ','unknown@example.invalid');assert.equal(r.customer_id,c2);
 r=await inquiry('Empresa Dos','one@example.invalid');assert.equal(r.customer_id,null);await login(admin);assert.equal((await resolve(r.id,'candidates')).items.length,2);assert.equal((await resolve(r.id,'link',{customer_id:c2})).customer_id,c2);
 r=await inquiry('New Person','new@example.invalid','New Company');await login(admin);assert.equal((await resolve(r.id,'candidates')).items.length,0);await assert.rejects(resolve(r.id,'create',{identification:'',payment_terms_days:0}),/INVALID/);
 const created=await resolve(r.id,'create',{identification:'WEB3',payment_terms_days:30});assert.equal(created.status,'linked');assert.equal((await resolve(r.id,'create',{identification:'WEB3',payment_terms_days:30})).customer_id,created.customer_id);assert.equal((await q("select count(*) n from customers where identification='WEB3'"))[0].n,1);assert.equal((await q('select phone from customers where id=$1',[created.customer_id]))[0].phone,'099123');
 r=await inquiry('Pending Person','pending@example.invalid');await q("insert into customers(name,identification,email) values('Recently created','WEB4','pending@example.invalid')");await login(admin);assert.equal((await resolve(r.id,'create',{identification:'WEB5',payment_terms_days:0})).status,'candidates');assert.equal((await q("select count(*) n from customers where identification='WEB5'"))[0].n,0);
 await login(client);await assert.rejects(resolve(r.id,'candidates'),/ACCESS_DENIED/);await login('', 'anon');await assert.rejects(resolve(r.id,'link',{customer_id:c1}),/permission denied/);assert.equal((await q('select * from customer_requests')).length,0);
 await login(admin);await q("insert into app_modules(id,enabled) values('quotes',false) on conflict(id) do update set enabled=false");await assert.rejects(resolve(r.id,'candidates'),/ACCESS_DENIED/);
 }finally{await db.close()}
});
