const {test,expect}=require('@playwright/test'),fs=require('node:fs');
const cloud=fs.readFileSync(__dirname+'/mock-gama-cloud.js','utf8');
const SETTINGS={id:true,version:1,preview_enabled:true,show_prices:true,headline:'Todo para abastecer tu empresa.',introduction:'Productos para tu día a día.',phone:'02 250 1350',email:'',address:'Quito'};
const PRODUCTS=[{id:'web1',name:'CAFÉ PARA OFICINA',reference:'CAFE-01',category:'Alimentos y bebidas',unit_price:10,tax_rate:15,order_minimum:1,order_multiple:1,has_photo:false,visible:true,featured:true,description:'Café de Ecuador',version:1},{id:'web2',name:'AGUA MINERAL',reference:'AGUA-01',category:'Bebidas',unit_price:2,tax_rate:0,order_minimum:1,order_multiple:1,has_photo:false,visible:true,featured:false,description:'',version:1}];
const api=cloud+`;(()=>{if(window.__websiteMockInstalled)return;window.__websiteMockInstalled=true;const old=GamaCloud.db;GamaCloud.db=async()=>{const c=await old();return {...c,rpc:async(fn,args)=>{if(fn!=='gama_website')return c.rpc(fn,args);const w=window.__WEB,a=args.p_action,d=args.p_data;w.calls.push(structuredClone(args));if(w.denied)return {error:{message:'WEBSITE_ACCESS_DENIED'}};if(w.failure===a){w.failure=null;return {error:{message:'offline'}}}let data;
if(a==='overview')data={settings:w.settings,currency:'USD',selected:w.products.filter(p=>p.visible).length,inquiries:w.inquiries.length,unread:w.inquiries.filter(i=>i.status==='new').length};
if(a==='save_settings'){if(d.version!==w.settings.version)return {error:{message:'WEBSITE_CHANGED'}};w.settings={...d,version:d.version+1};data=w.settings;}
if(a==='save_product'){const p=w.products.find(p=>p.id===d.id);Object.assign(p,d,{version:p.version+1});data=p;}
if(a==='catalog'||a==='products'){if(a==='catalog'&&!w.settings.preview_enabled)return {error:{message:'WEBSITE_PREVIEW_PAUSED'}};const rows=w.products.filter(p=>(a==='products'||p.visible)&&(!d.search||(p.name+' '+p.reference).toLowerCase().includes(d.search.toLowerCase()))&&(!d.category||p.category===d.category));data={settings:w.settings,currency:'USD',categories:[...new Set(w.products.map(p=>p.category))],total:rows.length,items:rows};}
if(a==='photo')data=[];
if(a==='submit'){data={id:'inquiry1',reference:'WEB-TEST-00000001',is_test:true};w.inquiries.push({...d,...data,total:23,currency:'USD',status:'new',created_at:new Date().toISOString(),lines:d.lines.map(l=>({...l,name:w.products.find(p=>p.id===l.product_id).name,total:23}))});}
if(a==='inquiries')data={items:w.inquiries,total:w.inquiries.length};if(a==='review'){w.inquiries.find(i=>i.id===d.id).status='reviewed';data={ok:true};}
return {data:structuredClone(data)};}}};})();`;
async function boot(page,{site=false,role='admin',denied=false,width=1280}={}){
 await page.setViewportSize({width,height:900});
 await page.addInitScript(({role,settings,products,denied})=>{localStorage.setItem('gama_session_v1',JSON.stringify({role,name:'QA'}));localStorage.setItem('gama_language_v1','fr');window.__DB={products:[],customers:[],suppliers:[],invoices:[],app_modules:[]};window.__WEB={settings,products,inquiries:[],calls:[],denied};},{role,settings:SETTINGS,products:PRODUCTS,denied});
 await page.route('**/gama-supabase.js*',r=>r.fulfill({contentType:'text/javascript',body:api}));await page.route('**/@supabase/**',r=>r.abort());
 await page.goto(site?'/gama-site.html':'/index.html');
 if(!site){await page.waitForFunction(()=>window.GamaRoleAccess?.isReady());}
}
for(const width of [390,1280])test('GAMA test storefront searches, keeps retry identity and receives quote at '+width,async({page})=>{
 await boot(page,{site:true,width});await expect(page.locator('.product')).toHaveCount(2);await page.locator('#siteSearch').fill('CAFÉ');await expect(page.locator('.product')).toHaveCount(1);await page.locator('[data-add=web1]').click();await expect(page.locator('#cartCount')).toHaveText('1');await page.locator('#cartOpen').click();await page.locator('[data-qty=web1]').fill('2');await page.locator('[name=contact_name]').fill('Jimmy Test');await page.locator('[name=email]').fill('test@example.invalid');await page.locator('[name=notes]').fill('Demande de test');
 await page.evaluate(()=>{__WEB.failure='submit'});await page.locator('#quoteSend').click();await expect(page.locator('#quoteStatus')).toContainText('conserva');await expect(page.locator('[name=contact_name]')).toHaveValue('Jimmy Test');await page.locator('#quoteSend').click();await expect(page.locator('#quoteStatus')).toContainText('WEB-TEST-00000001');
 const submits=await page.evaluate(()=>__WEB.calls.filter(c=>c.p_action==='submit'));expect(submits).toHaveLength(2);expect(submits[0].p_data.request_key).toBe(submits[1].p_data.request_key);expect(submits[1].p_data.lines).toEqual([{product_id:'web1',quantity:2}]);await expect(page.locator('#cartCount')).toHaveText('0');await page.locator('#cartClose').click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'test-results/gama-site-'+width+'.png',fullPage:true});
});
test('website preview handles denied access and paused preview without showing products',async({page})=>{
 await boot(page,{site:true,denied:true});await expect(page.locator('.empty-state')).toContainText('administrador');await expect(page.locator('.product')).toHaveCount(0);await page.evaluate(()=>{__WEB.denied=false;__WEB.settings.preview_enabled=false});await page.locator('#siteReload').click();await expect(page.locator('.empty-state')).toContainText('pausada');await expect(page.locator('.product')).toHaveCount(0);
});
test('client has no website administration tile',async({page})=>{await boot(page,{role:'client'});await expect(page.locator('#mainmenu [data-gama-module=website]')).toBeHidden();await page.evaluate(()=>GamaWebsite.open());await expect(page.locator('#website')).toHaveCount(0)});
