/* Versioned TMS execution shared by the ERP and the offline driver page. */
(function(){'use strict';
const U=window.ArcUI,E=U.esc,Q=()=>window.ArchitectOfflineProofs,rpc=(action,data={})=>window.ArcData.rpc('gama_tms_execution',{p_action:action,p_data:data});
const messages={DELIVERY_STALE:'La entrega cambió en el servidor. Revisa la captura pendiente antes de reenviarla.',TMS_ACCESS_DENIED:'Esta entrega no está asignada a tu cuenta.',TMS_DISPATCH_REQUIRED:'Esta operación corresponde al despachador.',RECEIPT_QUANTITY_INVALID:'Las cantidades deben sumar el saldo pendiente.',RECEIPT_LINES_CHANGED:'Las líneas cambiaron. Actualiza la entrega.',RECEIPT_REASON_REQUIRED:'Indica el motivo de la entrega parcial o fallida.',RECEIVER_SIGNATURE_REQUIRED:'Indica el nombre y la firma de quien recibe.',INCIDENT_PHOTO_REQUIRED:'Añade una foto para justificar las unidades faltantes.',DEPARTURE_REQUIRED:'La salida debe estar validada antes de registrar la entrega.',DELIVERY_CLOSED:'La entrega ya está cerrada.',CARGO_MEASUREMENT_REQUIRED:'Verifica el peso y el volumen e indica el motivo.',DELIVERY_QUANTITIES_PENDING:'Quedan cantidades o retornos por resolver.',SETTLEMENT_REVIEW_REQUIRED:'Confirma la revisión de facturación y explica el cierre.',ROUTE_DELIVERIES_PENDING:'Todavía hay entregas pendientes de resolver.',OFFLINE_ROUTE_EXPIRED:'La copia sin conexión venció. Conéctate y descarga la ruta otra vez.',OFFLINE_ROUTE_REQUIRED:'Descarga primero tu ruta con conexión.',AUTH_REQUIRED:'Inicia sesión en Coco ERP antes de sincronizar.',ROUTE_SCHEDULE_REQUIRED:'Revisa y guarda el horario de la ruta antes de salir.',TIME_WINDOW_EXCEPTION_REASON_REQUIRED:'El horario incumple una ventana. Indica el motivo de la excepción.'};
const error=e=>messages[e?.message]||window.ArcErrors.message(e),toast=(text,type)=>window.gamaToast?.(text,{tipo:type||'exito'});
const request=(id,ctx)=>({delivery_id:id,version:ctx.delivery.version,request_key:crypto.randomUUID(),occurred_at:new Date().toISOString()});
async function context(id,supplied){if(navigator.onLine)return rpc('context',{delivery_id:id});if(supplied)return supplied;const data=await Q().bundle();const d=data.deliveries.find(x=>x.id===id);if(!d?.execution)throw Error('OFFLINE_ROUTE_REQUIRED');return d.execution}
const gps=()=>new Promise(resolve=>{if(!navigator.geolocation)return resolve({status:'unavailable'});navigator.geolocation.getCurrentPosition(p=>resolve({status:'captured',lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,at:new Date(p.timestamp).toISOString()}),e=>resolve({status:e.code===1?'denied':e.code===3?'timeout':'unavailable'}),{enableHighAccuracy:true,timeout:4000,maximumAge:0})});
function signature(canvas){const ctx=canvas.getContext('2d');ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#1f2937';let active=false,drawn=false;const point=e=>{const b=canvas.getBoundingClientRect();return[(e.clientX-b.left)*canvas.width/b.width,(e.clientY-b.top)*canvas.height/b.height]};canvas.onpointerdown=e=>{e.preventDefault();canvas.setPointerCapture(e.pointerId);active=true;ctx.beginPath();ctx.moveTo(...point(e))};canvas.onpointermove=e=>{if(!active)return;ctx.lineTo(...point(e));ctx.stroke();drawn=true};canvas.onpointerup=canvas.onpointercancel=()=>{active=false};return {value:()=>drawn?canvas.toDataURL('image/png'):null,clear:()=>{ctx.clearRect(0,0,canvas.width,canvas.height);drawn=false}}}
async function photo(file){if(!file)return null;if(!/^image\//.test(file.type)||file.size>25*1024*1024)throw Error('Selecciona una imagen de menos de 25 MB.');const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const scale=Math.min(1,1280/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.75)}finally{URL.revokeObjectURL(url)}}
function history(ctx){return `<h3>Historial de intentos</h3>${ctx.attempts?.length?ctx.attempts.map(a=>`<details><summary>Intento ${a.attempt_no} · ${{complete:'Completa',partial:'Parcial',failed:'Fallida'}[a.result]} · ${E(new Date(a.occurred_at).toLocaleString('es-EC'))}</summary><p>${E(a.receiver_name)} · ${E(a.reason||'')}</p><p>${E((a.lines||[]).map(l=>`${l.accepted} aceptadas · ${l.refused} rechazadas · ${l.missing} faltantes · ${l.deferred} reprogramadas`).join(' / '))}</p>${(a.proofs||[]).map(p=>`<button type="button" class="arcButton secondary" data-attempt-proof="${E(p.id)}">${p.kind==='signature'?'Firma':'Foto'}</button>`).join('')}</details>`).join(''):'<p>Aún no hay intentos registrados.</p>'}`}
function bindProofs(dialog){dialog.querySelectorAll('[data-attempt-proof]').forEach(b=>b.onclick=async()=>{try{const result=await rpc('proof',{proof_id:b.dataset.attemptProof});U.dialog({title:'Prueba del intento',saveLabel:'Cerrar',body:`<img style="max-width:100%" alt="${result.kind==='signature'?'Firma':'Foto'}" src="${E(result.data_url)}">`,onSave:async()=>{}})}catch(e){dialog.querySelector('[role=alert]').textContent=error(e)}})}
async function open(id,{context:supplied,onDone=()=>{}}={}){
 const ctx=await context(id,supplied),d=ctx.delivery,lines=ctx.lines.filter(l=>Number(l.remaining)>0),closed=['Entregada','Cancelada'].includes(d.status)||d.settled_at;
 if(closed||!lines.length){const dialog=U.dialog({title:'Recepción de la entrega',saveLabel:'Cerrar',body:`<p>${E(d.customer)} · ${E(d.status)}</p>${!closed?'<p>No quedan unidades por entregar. Revisa los retornos y el cierre con el despachador.</p>':''}${history(ctx)}`,onSave:async()=>{}});bindProofs(dialog);return dialog}
 if(ctx.shipment?.loading_required&&!ctx.shipment.departed_at)throw Error('DEPARTURE_REQUIRED');
 let sig,photoData=null,photoJob=Promise.resolve(),ctxCurrent=ctx;
 const dialog=U.dialog({title:'Registrar recepción',saveLabel:'Guardar recepción',className:'tmsExecutionDialog',error,body:`<p><b>${E(d.dossier_reference||d.erp_reference||'')}</b> · ${E(d.customer)}</p><p>${E(d.address)}</p><p class="tmsOfflineStatus">${navigator.onLine?'La recepción se confirma al sincronizar con el servidor.':'Sin conexión: la captura quedará guardada en este dispositivo.'}</p><button type="button" class="arcButton secondary" data-ex-arrive${d.actual_arrival?' disabled':''}>${d.actual_arrival?'Llegada registrada':'Registrar llegada'}</button><div class="tmsReceiptLines">${lines.map(l=>`<fieldset data-receipt-line="${E(l.id)}" data-remaining="${E(l.remaining)}"><legend>${E(l.name)} · pendiente ${E(l.remaining)}</legend><div class="tmsQuantityGrid">${[['accepted','Aceptadas',l.remaining],['refused','Rechazadas',0],['missing','Faltantes',0],['deferred','Reprogramadas',0]].map(([key,label,value])=>`<label>${label}<input aria-label="${label} · ${E(l.name)}" data-quantity="${key}" type="number" min="0" max="${E(l.remaining)}" step="0.001" required value="${value}"></label>`).join('')}</div></fieldset>`).join('')}</div><label class="arcField">Nombre de quien recibe<input name="receiver" maxlength="160" autocomplete="name"></label><label class="arcField">Motivo / observaciones<textarea name="reason" maxlength="2000" rows="2"></textarea></label><label class="arcField">Foto de entrega o incidencia<input data-ex-photo type="file" accept="image/*" capture="environment"></label><img data-ex-preview hidden alt="Foto de entrega" style="max-width:100%;max-height:220px"><p>Firma de quien recibe</p><canvas data-ex-signature width="700" height="260" class="tmsSig" aria-label="Firma de quien recibe"></canvas><button type="button" class="arcButton secondary" data-ex-clear>Borrar firma</button>${history(ctx)}`,
 onSave:async()=>{
  await photoJob;const quantities=[...dialog.querySelectorAll('[data-receipt-line]')].map(el=>{const row={id:el.dataset.receiptLine};for(const input of el.querySelectorAll('[data-quantity]'))row[input.dataset.quantity]=Number(input.value);if(Object.values(row).slice(1).some(v=>!Number.isFinite(v)||v<0)||Math.abs(row.accepted+row.refused+row.missing+row.deferred-Number(el.dataset.remaining))>.000001)throw Error('RECEIPT_QUANTITY_INVALID');return row});
  const receiver=dialog.querySelector('[name=receiver]').value.trim(),reason=dialog.querySelector('[name=reason]').value.trim(),signatureData=sig.value();
  if(quantities.some(l=>l.accepted>0)&&(!signatureData||receiver.length<2))throw Error('RECEIVER_SIGNATURE_REQUIRED');if(quantities.some(l=>l.refused+l.missing+l.deferred>0)&&reason.length<3)throw Error('RECEIPT_REASON_REQUIRED');if(quantities.some(l=>l.missing>0)&&!photoData)throw Error('INCIDENT_PHOTO_REQUIRED');
  const payload={...request(id,ctxCurrent),reference:d.erp_reference,lines:quantities,receiver_name:receiver,reason,signature:signatureData,photo:photoData,gps:await gps()},result=await Q().capture(payload,'receive');
  if(result.queued&&!navigator.onLine){const next=structuredClone(ctxCurrent);next.delivery.version++;next.pending=true;next.lines.forEach(l=>{const q=quantities.find(x=>x.id===l.id);if(q){l.remaining=Number(l.remaining)-q.accepted-q.refused-q.missing;l.accepted=Number(l.accepted)+q.accepted;l.refused=Number(l.refused)+q.refused}});await Q().updateCached(await Q().actor(),next)}
  toast(result.queued?'Captura guardada en este dispositivo. Pendiente de sincronización.':'Recepción confirmada.');await onDone();
 }});
 sig=signature(dialog.querySelector('[data-ex-signature]'));dialog.querySelector('[data-ex-clear]').onclick=()=>sig.clear();
 dialog.querySelector('[data-ex-photo]').onchange=e=>{photoJob=photo(e.target.files[0]).then(data=>{photoData=data;const preview=dialog.querySelector('[data-ex-preview]');preview.src=data||'';preview.hidden=!data}).catch(e=>{dialog.querySelector('[role=alert]').textContent=error(e);throw e});photoJob.catch(()=>{})};
 dialog.querySelector('[data-ex-arrive]').onclick=async e=>{const b=e.currentTarget;b.disabled=true;try{const payload=request(id,ctxCurrent),result=await Q().capture(payload,'arrive');if(result.queued){ctxCurrent=structuredClone(ctxCurrent);ctxCurrent.delivery.version++;ctxCurrent.delivery.actual_arrival=payload.occurred_at;await Q().updateCached(await Q().actor(),ctxCurrent)}else ctxCurrent=await context(id);b.textContent=result.queued?'Llegada pendiente de sincronizar':'Llegada registrada'}catch(e){dialog.querySelector('[role=alert]').textContent=error(e);b.disabled=false}};
 bindProofs(dialog);return dialog;
}
async function configure(id,onDone=()=>{}){const ctx=await rpc('context',{delivery_id:id}),d=ctx.delivery,time=v=>v?new Intl.DateTimeFormat('en-GB',{timeZone:'America/Guayaquil',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'';let form;
 form=U.dialog({title:'Ventana y carga de entrega',saveLabel:'Guardar',error,body:`<p>${E(d.customer)} · ${E(d.delivery_date)} · hora de Quito</p><div class="tmsForm"><label>Desde<input name="from" type="time" value="${time(d.promised_from)}"></label><label>Hasta<input name="until" type="time" value="${time(d.promised_until)}"></label><label>Servicio (minutos)<input name="service" type="number" min="0" max="480" value="${d.service_minutes}" required></label></div><p>${ctx.cargo_known?'Peso y volumen conocidos.':'Falta validar el peso o el volumen.'}</p><label><input type="checkbox" name="measure"> Registrar medición verificada de carga</label><div class="tmsForm"><label>Peso total (kg)<input name="weight" type="number" step="0.001" min="0.001" value="${d.weight}"></label><label>Volumen total (m³)<input name="volume" type="number" step="0.000001" min="0.000001" value="${d.volume}"></label></div><label>Justificación<textarea name="reason" maxlength="2000"></textarea></label><p>La primera ventana prometida se conserva para calcular el OTIF.</p>`,onSave:async()=>{const f=form.querySelector('form').elements,from=f.from.value,until=f.until.value;if(!!from!==!!until||from&&until<=from)throw Error('Indica una ventana válida dentro del día.');const data={...request(id,ctx),promised_from:from?d.delivery_date+'T'+from+':00-05:00':null,promised_until:until?d.delivery_date+'T'+until+':00-05:00':null,service_minutes:Number(f.service.value),reason:f.reason.value};if(f.measure.checked)Object.assign(data,{weight:Number(f.weight.value),volume:Number(f.volume.value)});await rpc('configure',data);await onDone()}});return form;
}
async function manifest(routeId){const data=await rpc('manifest',{route_id:routeId}),r=data.route,dialog=U.dialog({title:'Manifiesto de carga',saveLabel:'Cerrar',className:'tmsManifestDialog',body:`<div class="tmsPrintManifest"><h2>${E(r.erp_reference||'Ruta')} · ${E(r.route_date)}</h2><p>${E(r.driver_name)} · ${E(r.vehicle)}</p><p>Guía SRI: ${E(data.guide?.number||'Pendiente')} · ${E(data.guide?.status||'Sin emitir')}</p>${data.deliveries.map((c,i)=>`<h3>${i+1}. ${E(c.delivery.customer)} · ${E(c.shipment.number)}</h3><p>${E(c.delivery.address)} · ${E(c.delivery.time_window)}</p>${U.table({columns:[{key:'name',label:'Producto'},{key:'quantity',label:'Cargado'},{key:'accepted',label:'Aceptado'},{key:'remaining',label:'Pendiente'}],items:c.lines})}`).join('')}<p>Documento operativo. No sustituye la guía de remisión autorizada por el SRI.</p></div><button class="arcButton primary" type="button" data-ex-print>Imprimir / guardar PDF</button>`,onSave:async()=>{}});dialog.querySelector('[data-ex-print]').onclick=()=>window.print();return dialog}
async function closure(day,routes,onDone=()=>{}){const data=await rpc('day',{day}),dialog=U.dialog({title:'Cierre de jornada',saveLabel:'Cerrar',className:'tmsExecutionDialog',body:`<p>${E(day)} · Los retornos deben recibirse e inspeccionarse antes del cierre.</p>${U.table({columns:[{key:'reference',label:'Entrega'},{key:'customer',label:'Cliente'},{key:'status',label:'Estado'},{key:'pending_quantity',label:'Pendiente'},{key:'open_returns',label:'Retornos abiertos'},{label:'Facturación',value:r=>r.invoice_review?'Revisar':'—'},{label:'Acción',html:r=>['Entregada','Cancelada'].includes(r.status)?'':`<button class="arcButton secondary" type="button" data-ex-settle="${E(r.id)}">Resolver</button>`}],items:data.deliveries})}<h3>Rutas</h3>${routes.map(r=>`<p>${E(r.reference||r.driver)} · ${E(r.status)} <button type="button" class="arcButton secondary" data-ex-close="${E(r.id)}"${r.status==='Terminada'?' disabled':''}>Cerrar ruta</button></p>`).join('')}`,onSave:async()=>{}});
 dialog.querySelectorAll('[data-ex-settle]').forEach(b=>b.onclick=async()=>{const item=data.deliveries.find(d=>d.id===b.dataset.exSettle);let review;review=U.dialog({title:'Resolver entrega parcial',saveLabel:'Confirmar revisión',error,body:`<p>${E(item.customer)}</p><label>Resolución<textarea name="reason" required minlength="5"></textarea></label><label><input name="invoice" type="checkbox" required> He revisado la factura o el abono y las cantidades aceptadas.</label>`,onSave:async()=>{const f=review.querySelector('form').elements;await rpc('settle',{delivery_id:item.id,version:item.version,request_key:crypto.randomUUID(),reason:f.reason.value,invoice_reviewed:f.invoice.checked});dialog.close();await onDone()}})});
 dialog.querySelectorAll('[data-ex-close]').forEach(b=>b.onclick=async()=>{const r=routes.find(r=>r.id===b.dataset.exClose);b.disabled=true;try{await rpc('close',{route_id:r.id,version:r.version,request_key:crypto.randomUUID()});b.textContent='Cerrada';await onDone()}catch(e){b.disabled=false;dialog.querySelector('[role=alert]').textContent=error(e)}});return dialog;
}
async function access(){const items=await rpc('access'),dialog=U.dialog({title:'Roles TMS',saveLabel:'Cerrar',body:`<p>Los perfiles siguen necesitando acceso al módulo TMS. Un conductor solo ve sus propias entregas. Los administradores conservan el rol Gestor.</p>${U.table({columns:[{key:'name',label:'Usuario'},{label:'Función',html:r=>`<select data-ex-role="${E(r.profile_id)}"${r.admin?' disabled':''}>${[['dispatcher','Despachador'],['driver','Conductor'],['manager','Gestor']].map(([v,l])=>`<option value="${v}"${(r.role||(r.driver_id?'driver':'dispatcher'))===v?' selected':''}>${l}</option>`).join('')}</select>`},{label:'',html:r=>`<button type="button" class="arcButton secondary" data-ex-access="${E(r.profile_id)}"${r.admin?' disabled':''}>Guardar</button>`}],items})}`,onSave:async()=>{}});dialog.querySelectorAll('[data-ex-access]').forEach(b=>b.onclick=async()=>{try{await rpc('set_access',{profile_id:b.dataset.exAccess,role:dialog.querySelector(`[data-ex-role="${b.dataset.exAccess}"]`).value,request_key:crypto.randomUUID()});b.textContent='Guardado'}catch(e){dialog.querySelector('[role=alert]').textContent=error(e)}});return dialog}
async function schedule(routeId){const data=await rpc('manifest',{route_id:routeId}),r=data.route,lookup=id=>data.deliveries.find(d=>d.delivery.id===id),dialog=U.dialog({title:'Horario de ruta',saveLabel:'Guardar horario',error,body:`<p>${E(r.erp_reference)} · ${E(r.route_date)} · hora de Quito</p><label>Salida<input name="starts" type="time" required value="08:00"></label><p>Introduce los tiempos y kilómetros verificados de cada tramo. Se añade espera si llegas antes de la ventana.</p><div class="arcTableWrap"><table class="arcTable"><thead><tr><th>Parada</th><th>km desde la anterior</th><th>Conducción (min)</th><th>Servicio (min)</th></tr></thead><tbody>${r.stops.map(id=>{const c=lookup(id);return `<tr data-leg="${E(id)}"><td>${E(c?.delivery.customer||'Depósito')}<br>${E(c?.delivery.time_window||'')}</td><td><input data-km type="number" min="0" max="20000" step="0.1" required></td><td><input data-drive type="number" min="0" max="1440" required></td><td><input data-service type="number" min="0" max="480" value="${c?.delivery.service_minutes||0}" required></td></tr>`}).join('')}</tbody></table></div><label>Fuente de verificación<input name="source" required minlength="3" placeholder="Recorrido habitual / comprobación manual"></label><label>Justificación de excepción horaria (si corresponde)<textarea name="reason" maxlength="2000"></textarea></label>`,onSave:async()=>{const f=dialog.querySelector('form').elements,legs=[...dialog.querySelectorAll('[data-leg]')].map(el=>({id:el.dataset.leg,road_km:Number(el.querySelector('[data-km]').value),drive_minutes:Number(el.querySelector('[data-drive]').value),service_minutes:Number(el.querySelector('[data-service]').value)}));await window.ArcData.rpc('gama_route_schedule',{p_data:{route_id:routeId,starts_at:r.route_date+'T'+f.starts.value+':00-05:00',road_source:f.source.value,window_exception_reason:f.reason.value,legs}});toast('Horario guardado.')}});return dialog}
window.CocoTmsExecution={open,configure,manifest,closure,access,schedule,error};
})();
