/* Public catalogue. All prices and availability are rechecked by Coco. */
(()=>{'use strict';
const $=id=>document.getElementById(id),E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=v=>/^https:\/\/[^\s<>"']+$/.test(v||''),safeImage=v=>safeURL(v)||/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(v||''),uuid=v=>/^[0-9a-f-]{36}$/i.test(v||'');
let cfg={},currency='USD',boot=null,generation=0,detailGeneration=0,offset=0,search='',category='',brand='',sort='featured',timer,sending=false,retryPayload='',requestKey='';
const products=new Map(),photos=new Map();let cart=[];
try{cart=JSON.parse(sessionStorage.getItem('gama.public.selection')||'[]').filter(x=>uuid(x.id)&&Number(x.qty)>0).slice(0,30)}catch(_){cart=[]}
const friendly=e=>({WEBSITE_RATE_LIMIT:'Has enviado varias solicitudes. Espera un momento antes de volver a intentarlo.',WEBSITE_PRODUCT_NOT_FOUND:'Un producto ya no está disponible. Actualiza tu selección.',WEBSITE_PACK_QUANTITY:'Revisa las cantidades mínimas y los múltiplos de compra.',WEBSITE_CONNECTION_REQUIRED:'La recepción de solicitudes está temporalmente fuera de servicio. Contacta con nuestro equipo.',WEBSITE_QUOTES_DISABLED:'Las solicitudes están pausadas. Contacta con nuestro equipo.',WEBSITE_PUBLIC_PAUSED:'Estamos actualizando el catálogo.'}[e?.message]||'No hemos podido completar la operación. Vuelve a intentarlo.');
async function api(action,data={}){const r=await fetch('/api/storefront',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({p_action:action,p_data:data}),signal:AbortSignal.timeout(18000)});let out;try{out=await r.json()}catch(_){throw Error('NETWORK_ERROR')}if(!r.ok||out.error)throw Error(out.error||'NETWORK_ERROR');return out}
function text(id,v){$(id).textContent=v??''}
function imageHTML(id,alt){return `<span data-photo="${E(id)}">${photos.has(id)?`<img src="${E(photos.get(id))}" alt="${E(alt)}" loading="lazy">`:`<span class="product-initial" aria-hidden="true">G.</span>`}</span>`}
async function hydratePhotos(){const ids=[...new Set([...document.querySelectorAll('[data-photo]')].map(n=>n.dataset.photo))].filter(id=>!photos.has(id)&&products.get(id)?.has_photo);for(let i=0;i<ids.length;i+=24){try{const rows=await api('photos',{ids:ids.slice(i,i+24)});for(const p of rows)if(safeImage(p.photo_data))photos.set(p.id,p.photo_data)}catch(_){/* Photos do not block the catalogue. */}}document.querySelectorAll('[data-photo]').forEach(n=>{const url=photos.get(n.dataset.photo);if(url){const img=document.createElement('img');img.src=url;img.alt=products.get(n.dataset.photo)?.name||'';img.loading='lazy';n.replaceChildren(img)}});if(photos.size>150){const visible=new Set([...document.querySelectorAll('[data-photo]')].map(n=>n.dataset.photo));for(const id of photos.keys())if(!visible.has(id)&&photos.size>100)photos.delete(id)}}
const round=v=>Math.round((Number(v)+Number.EPSILON)*100)/100;
const money=v=>new Intl.NumberFormat('es-EC',{style:'currency',currency}).format(v);
function price(p){if(p.unit_price==null||Number(p.unit_price)<=0)return null;return cfg.price_display==='without_tax'?Number(p.unit_price):round(Number(p.unit_price)*(1+Number(p.tax_rate||0)/100))}
function priceHTML(p){const v=price(p);return v==null?'<strong>Consultar</strong><small>Precio a confirmar</small>':`<strong>${E(money(v))}</strong><small>${cfg.price_display==='without_tax'?'Sin impuestos':'Incluye impuestos'}</small>`}
function card(p){products.set(p.id,p);return `<article class="product-card"><button class="product-image" data-product="${E(p.id)}" aria-label="Ver ${E(p.name)}">${imageHTML(p.id,p.name)}${p.badge?`<span class="product-badge">${E(p.badge)}</span>`:''}</button><div class="product-info"><span class="product-category">${E(p.category_title)}</span><button class="product-name" data-product="${E(p.id)}">${E(p.name)}</button><span class="product-reference">${E(p.reference)}</span><div class="product-bottom"><div class="product-price">${priceHTML(p)}</div>${cfg.enable_quotes?`<button class="add-button" data-add="${E(p.id)}" aria-label="Añadir ${E(p.name)} a la cotización">+</button>`:''}</div></div></article>`}
function contactHTML(c){return [[c.phone,c.phone?'tel:'+c.phone.replace(/[^+\d]/g,''):''],[c.email,c.email?'mailto:'+c.email:''],[c.address,safeURL(c.map_url)?c.map_url:''],[c.opening_hours,'']].filter(x=>x[0]).map(([label,href])=>href?`<a href="${E(href)}">${E(label)}</a>`:`<p>${E(label)}</p>`).join('')}
function configure(){document.querySelectorAll('[data-brand]').forEach(n=>n.textContent=cfg.brand_name);for(const [id,key]of Object.entries({announcement:'announcement',tagline:'tagline',heroLabel:'hero_label',heroTitle:'hero_title',heroAccent:'hero_accent',heroIntro:'hero_intro',catalogueTitle:'catalog_title',catalogueIntro:'catalog_intro',categoriesTitle:'categories_title',featuredTitle:'featured_title',aboutTitle:'about_title',aboutText:'about_text',contactTitle:'contact_title',contactIntro:'contact_intro',footerNote:'footer_note',quoteLabel:'quote_label'}))text(id,cfg[key]);
 for(const [key,v]of Object.entries({primary:cfg.primary_color,accent:cfg.accent_color,background:cfg.background_color}))if(/^#[0-9a-f]{6}$/i.test(v))document.documentElement.style.setProperty('--'+key,v);
 document.documentElement.style.setProperty('--radius',cfg.corner_style==='square'?'0px':'12px');document.title=cfg.seo_title||cfg.brand_name;document.querySelector('meta[name=description]').content=cfg.seo_description||'';
 for(const id of ['brandLogo','footerLogo'])if(safeImage(cfg.logo_url))$(id).src=cfg.logo_url;
 $('navigation').innerHTML=(cfg.navigation||[]).filter(n=>safeURL(n.href)||/^#[a-z][a-z0-9_-]*$/i.test(n.href)).map(n=>`<a href="${E(n.href)}">${E(n.label)}</a>`).join('');
 if(cfg.phone){$('topPhone').hidden=false;$('topPhone').textContent=cfg.phone;$('topPhone').href='tel:'+cfg.phone.replace(/[^+\d]/g,'')}
 $('heroButton').innerHTML=E(cfg.hero_button)+' <span aria-hidden="true">↗</span>';$('heroButton').href='#'+(cfg.hero_button_target==='contacto'?'contacto':'catalogo');
 if(safeImage(cfg.hero_image))$('heroArt').innerHTML=`<img class="hero-cover" src="${E(cfg.hero_image)}" alt="${E(cfg.brand_name)}">`;
 if(safeImage(cfg.about_image))$('aboutArt').innerHTML=`<img class="about-cover" src="${E(cfg.about_image)}" alt="${E(cfg.about_title)}">`;
 $('benefits').hidden=!cfg.show_benefits;$('benefits').innerHTML=(cfg.benefits||[]).map(b=>`<article class="benefit"><span class="benefit-icon" aria-hidden="true">${({box:'◇',headset:'◉',truck:'↗',shield:'✓'})[b.icon]||'◇'}</span><div><strong>${E(b.title)}</strong><p>${E(b.text)}</p></div></article>`).join('');
 $('nosotros').hidden=!cfg.show_about;$('contacto').hidden=!cfg.show_contact;$('contactDetails').innerHTML=contactHTML(cfg);$('unavailableContact').innerHTML=contactHTML(cfg);
 if(/^\d{7,15}$/.test((cfg.whatsapp||'').replace(/\D/g,''))){$('whatsappLink').hidden=false;$('whatsappLink').href='https://wa.me/'+cfg.whatsapp.replace(/\D/g,'')}else $('whatsappLink').hidden=true;
 $('socialLinks').innerHTML=['facebook','instagram','linkedin'].filter(k=>safeURL(cfg[k+'_url'])).map(k=>`<a href="${E(cfg[k+'_url'])}" target="_blank" rel="noopener">${E(k[0].toUpperCase()+k.slice(1))} ↗</a>`).join('');
 $('brandsSection').hidden=!(cfg.brands||[]).length;$('brands').innerHTML=(cfg.brands||[]).map(b=>safeURL(b.image)?`<img src="${E(b.image)}" alt="${E(b.name)}" loading="lazy">`:`<span>${E(b.name)}</span>`).join('');
 $('faqSection').hidden=!cfg.show_faq||!(cfg.faq||[]).length;$('faq').innerHTML=(cfg.faq||[]).map(f=>`<details><summary>${E(f.question)}</summary><p>${E(f.answer)}</p></details>`).join('');
 text('copyright',`© ${new Date().getFullYear()} ${cfg.brand_name}.`);$('cartOpen').hidden=!cfg.enable_quotes;sort=cfg.default_sort||'featured';$('siteSort').value=sort;
}
function filters(){const cats=boot.categories||[];$('categoryFilters').className='category-filters';$('categoryFilters').innerHTML=[{category:'',title:'Todos los productos',count:boot.total},...cats].map(c=>`<button class="category-filter ${category===c.category?'active':''}" data-category="${E(c.category)}"><span>${E(c.title)}</span><small>${E(c.count)}</small></button>`).join('');$('categoriesSection').hidden=!cfg.show_categories||!cats.length;$('categories').innerHTML=cats.map(c=>`<button class="category-card" data-category="${E(c.category)}">${imageHTML(c.photo_id,c.title)}<span class="category-copy"><strong>${E(c.title)}</strong><small>${E(c.count)} productos <span aria-hidden="true">↗</span></small></span></button>`).join('');const brands=boot.brands||[];$('brandFilterWrap').hidden=!brands.length;$('brandFilter').innerHTML='<option value="">Todas las marcas</option>'+brands.map(b=>`<option value="${E(b)}">${E(b)}</option>`).join('');$('brandFilter').value=brand}
async function catalogue(){const seq=++generation;text('siteStatus','Cargando productos…');try{const r=await api('catalog',{search,category,brand,sort,offset,limit:Number(cfg.page_size)||12});if(seq!==generation)return;const items=r.items||[];text('productCount',`${r.total} ${r.total===1?'producto':'productos'}`);$('siteProducts').innerHTML=items.map(card).join('')||'<div class="empty-catalogue"><h3>No encontramos productos.</h3><p>Prueba con otro término o elimina los filtros.</p></div>';text('siteStatus','');$('sitePager').innerHTML=r.total>r.limit?`<button class="button outline" data-page="-1" ${offset===0?'disabled':''}>Anterior</button><span>${Math.floor(offset/r.limit)+1} / ${Math.ceil(r.total/r.limit)}</span><button class="button outline" data-page="1" ${offset+r.limit>=r.total?'disabled':''}>Siguiente</button>`:'';await hydratePhotos()}catch(e){if(seq===generation)text('siteStatus',friendly(e))}}
function minimum(p){const m=Number(p.order_minimum)||0,s=Number(p.order_multiple)||0;return s>0?Math.round(Math.ceil(Math.max(m,s)/s)*s*1000)/1000:Math.max(m,1)}
function validQty(p,q){p=p||{};const step=Number(p.order_multiple)||0;return Number.isFinite(q)&&q>=minimum(p)&&q<=100000&&Math.abs(q*1000-Math.round(q*1000))<1e-6&&(!step||Math.abs(q/step-Math.round(q/step))<1e-6)}
function saveCart(){try{sessionStorage.setItem('gama.public.selection',JSON.stringify(cart))}catch(_){}text('cartCount',cart.length)}
function add(id,qty){const p=products.get(id);if(!p||!cfg.enable_quotes)return;const line=cart.find(x=>x.id===id),q=qty??minimum(p);if(line){const next=Math.round((line.qty+q)*1000)/1000;if(!validQty(p,next))return;line.qty=next}else{if(cart.length>=30){text('siteStatus','Puedes seleccionar hasta 30 productos.');return}cart.push({id,qty:q})}saveCart();text('siteStatus',`${p.name} añadido a tu cotización.`);if($('cartDialog').open)renderCart()}
async function detail(id,push=true){const seq=++detailGeneration;try{const r=await api('product',{id});if(seq!==detailGeneration)return;const p=r.item;products.set(p.id,p);$('productDetail').innerHTML=`<div class="detail-grid"><div class="detail-photo">${imageHTML(p.id,p.name)}</div><div class="detail-copy"><span class="eyebrow">${E(p.category_title)}</span><h2 id="productTitle">${E(p.name)}</h2><p class="product-reference">${E(p.reference)}${p.brand?' · '+E(p.brand):''}</p><div class="product-price">${priceHTML(p)}</div><p class="description">${E(p.description||'Consulta con nuestro equipo por este producto.')}</p>${cfg.enable_quotes?`<form id="detailForm"><label class="detail-quantity">Cantidad<input name="quantity" type="number" value="${minimum(p)}" min="${minimum(p)}" max="100000" step="${Number(p.order_multiple)||'0.001'}" required></label><small>${Number(p.order_minimum)>0?'Mínimo: '+E(p.order_minimum)+'. ':''}${Number(p.order_multiple)>0?'Múltiplos de '+E(p.order_multiple)+'.':''}</small><p id="detailStatus" role="status"></p><button type="submit" class="button primary wide">Añadir a mi cotización +</button></form>`:''}</div></div>`;if(!$('productDialog').open)$('productDialog').showModal();if(push){const u=new URL(location.href);u.searchParams.set('product',id);history.pushState({},'',u)}if($('detailForm'))$('detailForm').onsubmit=e=>{e.preventDefault();const q=Number(e.target.elements.quantity.value);if(!validQty(p,q)){text('detailStatus','Revisa la cantidad mínima y los múltiplos.');return}add(id,q);text('detailStatus','Producto añadido a tu selección.')};await hydratePhotos()}catch(e){text('siteStatus',friendly(e))}}
function lineAmount(p,q){const net=round(Number(p.unit_price)*q);return cfg.price_display==='without_tax'?net:net+round(net*Number(p.tax_rate||0)/100)}
function renderCart(){let total=0,unknown=false;$('cartLines').innerHTML=cart.map(l=>{const p=products.get(l.id);if(!p){unknown=true;return `<article class="cart-line"><p>Producto por actualizar</p><button data-remove="${E(l.id)}" class="text-link">Eliminar</button></article>`}const v=price(p);if(v==null)unknown=true;else total+=lineAmount(p,l.qty);return `<article class="cart-line"><div class="cart-photo">${imageHTML(p.id,p.name)}</div><div><strong>${E(p.name)}</strong><small>${E(p.reference)}</small><button class="text-link" data-remove="${E(l.id)}" type="button">Eliminar</button></div><label>Cantidad<input data-quantity="${E(l.id)}" aria-label="Cantidad de ${E(p.name)}" type="number" value="${l.qty}" min="${minimum(p)}" max="100000" step="${Number(p.order_multiple)||'0.001'}"></label><b>${v==null?'Consultar':E(money(lineAmount(p,l.qty)))}</b></article>`}).join('')||'<p class="empty-cart">Tu selección está vacía. Explora el catálogo y añade productos.</p>';text('cartTotal',cfg.show_prices?`${unknown?'Importe parcial indicativo':'Importe indicativo'}: ${money(total)}${unknown?' · Hay precios por confirmar':''}`:'Precios a confirmar con nuestro equipo.');$('quoteSend').disabled=sending||!cart.length||cart.some(l=>!products.has(l.id))||!cfg.enable_quotes;hydratePhotos()}
async function openCart(){if(!cfg.enable_quotes)return;if(!$('cartDialog').open)$('cartDialog').showModal();renderCart();text('quoteStatus','Actualizando tu selección…');const original=cart.map(x=>x.id);const results=await Promise.allSettled(original.map(id=>api('product',{id})));let missing=false;results.forEach((r,i)=>{if(r.status==='fulfilled')products.set(original[i],r.value.item);else if(r.reason?.message==='WEBSITE_PRODUCT_NOT_FOUND'){cart=cart.filter(l=>l.id!==original[i]);missing=true}});saveCart();renderCart();text('quoteStatus',missing?'Un producto ya no está disponible y fue retirado de la selección.':'')}
async function submit(e){e.preventDefault();if(sending||!cart.length)return;const form=e.currentTarget;for(const l of cart)if(!validQty(products.get(l.id)||{},l.qty)){text('quoteStatus','Revisa las cantidades antes de enviar.');return}const payload={...Object.fromEntries(new FormData(form)),consent:form.elements.consent.checked,lines:cart.map(l=>({product_id:l.id,quantity:l.qty}))};const signature=JSON.stringify(payload);if(signature!==retryPayload){retryPayload=signature;requestKey=crypto.randomUUID()}sending=true;renderCart();text('quoteStatus','Enviando solicitud…');try{const r=await api('submit',{...payload,request_key:requestKey});cart=[];saveCart();form.reset();renderCart();text('quoteStatus',`Solicitud ${r.reference} recibida. Nuestro equipo confirmará los precios y las condiciones contigo.`);retryPayload='';requestKey=''}catch(err){text('quoteStatus',friendly(err))}finally{sending=false;renderCart()}}
function paused(c){cfg=c||{};document.querySelectorAll('main > section').forEach(s=>s.hidden=s.id!=='unavailable');$('cartOpen').hidden=true;$('unavailableContact').innerHTML=contactHTML(cfg);$('siteProducts').replaceChildren();products.clear();photos.clear()}
async function start(){try{const initial=JSON.parse($('initial-data').textContent||'null');boot=initial||await api('bootstrap');$('initial-data').textContent='null';if(boot.paused){paused(boot.settings);return}cfg=boot.settings;currency=boot.currency||'USD';configure();for(const c of boot.categories||[])if(c.photo_id)products.set(c.photo_id,{id:c.photo_id,name:c.title,has_photo:true});const featured=boot.featured||[];$('featuredSection').hidden=!cfg.show_featured||!featured.length;$('featuredProducts').innerHTML=featured.map(card).join('');if(!cfg.hero_image)document.querySelectorAll('[data-hero]').forEach((n,i)=>{const p=featured[i];n.hidden=!p;if(p)n.innerHTML=imageHTML(p.id,p.name)+`<small>${E(p.name)}</small>`});filters();saveCart();await catalogue();const id=new URL(location.href).searchParams.get('product');if(uuid(id))detail(id,false)}catch(e){paused();$('unavailable').querySelector('p').textContent='No podemos conectar con el catálogo. Vuelve a intentarlo en un momento.'}}
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;if(b.dataset.product)detail(b.dataset.product);if(b.dataset.add)add(b.dataset.add);if(b.dataset.category!=null){category=b.dataset.category;offset=0;filters();catalogue();$('catalogo').scrollIntoView({behavior:'smooth'})}if(b.dataset.page){offset=Math.max(0,offset+Number(b.dataset.page)*(Number(cfg.page_size)||12));catalogue();$('catalogo').scrollIntoView({behavior:'smooth'})}if(b.dataset.remove){cart=cart.filter(x=>x.id!==b.dataset.remove);saveCart();renderCart()}if(b.dataset.closeDialog){$(b.dataset.closeDialog).close()}if(b.dataset.legal){text('legalTitle',cfg[b.dataset.legal+'_title']||'Información');text('legalText',cfg[b.dataset.legal+'_text']||'');if(!$('legalDialog').open)$('legalDialog').showModal()}if(b.closest('#navigation')){$('header').classList.remove('menu-expanded');$('menuOpen').setAttribute('aria-expanded','false')}});
document.addEventListener('change',e=>{const id=e.target.dataset.quantity;if(id){const p=products.get(id),q=Number(e.target.value);if(!validQty(p,q)){text('quoteStatus','Revisa las cantidades mínimas y los múltiplos.');renderCart();return}cart.find(x=>x.id===id).qty=q;saveCart();renderCart();text('quoteStatus','')}});
window.addEventListener('popstate',()=>{const id=new URL(location.href).searchParams.get('product');if(uuid(id))detail(id,false);else{$('productDialog').close();detailGeneration++}});$('productDialog').addEventListener('close',()=>{detailGeneration++;const u=new URL(location.href);if(u.searchParams.has('product')){u.searchParams.delete('product');history.replaceState({},'',u)}});
 $('siteSearch').oninput=e=>{search=e.target.value;clearTimeout(timer);timer=setTimeout(()=>{offset=0;catalogue()},300)};$('siteSort').onchange=e=>{sort=e.target.value;offset=0;catalogue()};$('brandFilter').onchange=e=>{brand=e.target.value;offset=0;catalogue()};$('clearFilters').onclick=()=>{search=category=brand='';offset=0;$('siteSearch').value='';filters();catalogue()};$('searchOpen').onclick=()=>{$('catalogo').scrollIntoView();$('siteSearch').focus()};$('cartOpen').onclick=openCart;$('quoteForm').onsubmit=submit;$('menuOpen').onclick=()=>{const open=$('header').classList.toggle('menu-expanded');$('menuOpen').setAttribute('aria-expanded',String(open))};$('retryLoad').onclick=()=>location.reload();start();
})();
