/* Public catalogue. All prices and availability are rechecked by Coco. */
(()=>{'use strict';
const $=id=>document.getElementById(id),E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=v=>/^https:\/\/[^\s<>"']+$/.test(v||''),safeImage=v=>safeURL(v)||/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(v||''),uuid=v=>/^[0-9a-f-]{36}$/i.test(v||'');
let cfg={},currency='USD',boot=null,generation=0,detailGeneration=0,offset=0,search='',category='',brand='',sort='featured',timer,noticeTimer,sending=false,retryPayload='',requestKey='';
const customer=()=>window.GamaCustomer?.isActive()===true;let started=false,startSerial=0,customerEpoch=0,accountView='catalog';
const products=new Map(),photos=new Map(),illustrativePhotos=new Set();let cart=[];
const categoryKey=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().replace(/\s+/g,' ').toUpperCase();
try{cart=JSON.parse(sessionStorage.getItem('gama.public.selection')||'[]').filter(x=>uuid(x.id)&&Number(x.qty)>0).slice(0,30)}catch(_){cart=[]}
const friendly=e=>({WEBSITE_RATE_LIMIT:'Has enviado varias solicitudes. Espera un momento antes de volver a intentarlo.',WEBSITE_PRODUCT_NOT_FOUND:'Un producto ya no está disponible. Actualiza tu selección.',WEBSITE_PACK_QUANTITY:'Revisa las cantidades mínimas y los múltiplos de compra.',WEBSITE_CONNECTION_REQUIRED:'La recepción de solicitudes está temporalmente fuera de servicio. Contacta con nuestro equipo.',WEBSITE_QUOTES_DISABLED:'Las solicitudes están pausadas. Contacta con nuestro equipo.',WEBSITE_PUBLIC_PAUSED:'Estamos actualizando el catálogo.'}[e?.message]||'No hemos podido completar la operación. Vuelve a intentarlo.');
async function api(action,data={}){if(customer()&&['bootstrap','catalog','product'].includes(action))return window.GamaCustomer.storefront(action,data);const r=await fetch('/api/storefront',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({p_action:action,p_data:data}),signal:AbortSignal.timeout(18000)});let out;try{out=await r.json()}catch(_){throw Error('NETWORK_ERROR')}if(!r.ok||out.error)throw Error(out.error||'NETWORK_ERROR');return out}
const prose=v=>{const s=String(v??'');return s!==s.toLocaleLowerCase('es')&&s===s.toLocaleUpperCase('es')?s.toLocaleLowerCase('es'):s};
const catalogLabel=v=>prose(v).replace(/\p{L}/u,c=>c.toLocaleUpperCase('es'));
function text(id,v){$(id).textContent=prose(v)}
const photoPlaceholder=()=>`<span class="photo-placeholder">${icon('box')}<span>Foto por confirmar</span></span>`;
const photoNotice=()=>'<span class="photo-caption" title="La imagen es representativa. Confirma la marca, el modelo y la presentación con nuestro equipo.">Foto ilustrativa</span>';
function imageHTML(id,alt,notice=true){return `<span data-photo="${E(id)}" data-photo-notice="${notice}">${photos.has(id)?`<img src="${E(photos.get(id))}" alt="${E(catalogLabel(alt))}${illustrativePhotos.has(id)?' · Foto ilustrativa':''}" loading="lazy">${notice&&illustrativePhotos.has(id)?photoNotice():''}`:photoPlaceholder()}</span>`}
function categoryImage(c){return c.photo_id?imageHTML(c.photo_id,c.title,false).replace('<span ','<span class="category-visual" '):`<span class="category-visual category-symbol" aria-hidden="true">${icon('box')}</span>`}
async function hydratePhotos(){const ids=[...new Set([...document.querySelectorAll('[data-photo]')].map(n=>n.dataset.photo))].filter(id=>!photos.has(id)&&products.get(id)?.has_photo);for(let i=0;i<ids.length;i+=24){try{const rows=await api('photos',{ids:ids.slice(i,i+24)});for(const p of rows)if(safeImage(p.photo_data)){photos.set(p.id,p.photo_data);if(p.photo_is_illustrative===true)illustrativePhotos.add(p.id);else illustrativePhotos.delete(p.id)}}catch(_){/* Photos do not block the catalogue. */}}document.querySelectorAll('[data-photo]').forEach(n=>{const url=photos.get(n.dataset.photo);if(url){const img=document.createElement('img');img.src=url;img.alt=catalogLabel(products.get(n.dataset.photo)?.name||'')+(illustrativePhotos.has(n.dataset.photo)?' · Foto ilustrativa':'');img.loading='lazy';n.replaceChildren(img);if(n.dataset.photoNotice==='true'&&illustrativePhotos.has(n.dataset.photo)){const note=document.createElement('span');note.className='photo-caption';note.textContent='Foto ilustrativa';note.title='La imagen es representativa. Confirma la marca, el modelo y la presentación con nuestro equipo.';n.append(note)}}});if(photos.size>150){const visible=new Set([...document.querySelectorAll('[data-photo]')].map(n=>n.dataset.photo));for(const id of photos.keys())if(!visible.has(id)&&photos.size>100){photos.delete(id);illustrativePhotos.delete(id)}}}
const round=v=>Math.round((Number(v)+Number.EPSILON)*100)/100;
const money=v=>new Intl.NumberFormat('es-EC',{style:'currency',currency}).format(v);
function price(p){if((!cfg.show_prices&&!customer())||p.unit_price==null||Number(p.unit_price)<=0)return null;return cfg.price_display==='without_tax'?Number(p.unit_price):round(Number(p.unit_price)*(1+Number(p.tax_rate||0)/100))}
function priceHTML(p){const v=price(p);return v==null?'<strong data-gi=86016c201b92>Consultar</strong><small>Precio a confirmar</small>':`<strong>${E(money(v))}</strong><small>${customer()?'Tu precio · ':''}${cfg.price_display==='without_tax'?'Sin impuestos':'Incluye impuestos'}</small>`}
function icon(name){const paths={cart:'<path d="M6 8h13l-1.3 9H7.4L5 4H2"/><circle cx="9" cy="21" r="1"/><circle cx="17" cy="21" r="1"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>',box:'<path d="m3 7 9-4 9 4v10l-9 4-9-4ZM3 7l9 4 9-4M12 11v10M7.5 5l9 4"/>',headset:'<path d="M4 13v-2a8 8 0 0 1 16 0v2M4 12H2v6h4v-6ZM20 12h2v6h-4v-6ZM20 18c0 3-4 3-7 3"/>',truck:'<path d="M2 5h12v12H2ZM14 10h4l4 4v3h-8"/><circle cx="6" cy="19" r="2"/><circle cx="18" cy="19" r="2"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6ZM8 12l3 3 5-6"/>'};return `<svg viewBox="0 0 24 24" aria-hidden="true">${paths[name]||paths.box}</svg>`}
function favoriteHTML(p){return customer()?`<button type="button" class="catalog-favorite" data-customer-favorite="${E(p.id)}" aria-pressed="${window.GamaCustomer.isFavorite(p.id)}" aria-label="Guardar ${E(catalogLabel(p.name))} en mis compras habituales"><span aria-hidden="true">${window.GamaCustomer.isFavorite(p.id)?'♥':'♡'}</span> Favorito</button>`:''}
function card(p){products.set(p.id,p);return `<article class="product-card"><button class="product-image" type="button" data-product="${E(p.id)}" aria-label="Ver ${E(catalogLabel(p.name))}">${imageHTML(p.id,p.name)}${p.badge?`<span class="product-badge">${E(prose(p.badge))}</span>`:''}</button><div class="product-info">${favoriteHTML(p)}<span class="product-category">${E(catalogLabel(p.category_title))}</span><button class="product-name" type="button" data-product="${E(p.id)}">${E(catalogLabel(p.name))}</button><span class="product-reference">${p.brand?E(prose(p.brand))+' · ':''}${E(p.reference)}</span>${p.description?`<p class="product-summary">${E(prose(p.description))}</p>`:''}<button class="product-details-link" type="button" data-product="${E(p.id)}">${icon('info')}<span>Ver descripción y especificaciones</span></button><div class="product-facts"><span>${icon('box')}Disponibilidad por confirmar</span><span>${icon('truck')}Entrega coordinada con nuestro equipo</span></div><div class="product-bottom"><div class="product-price">${priceHTML(p)}</div>${((cfg.enable_quotes||customer())&&(!customer()||p.orderable!==false))?`<div class="quick-order"><input type="number" data-card-quantity aria-label="Cantidad para ${E(catalogLabel(p.name))}" value="${initialQuantity(p)}" min="${minimum(p)}" max="100000" step="${Number(p.order_multiple)||'0.001'}"><button class="add-button" type="button" data-add="${E(p.id)}" aria-label="Añadir ${E(catalogLabel(p.name))} a la cotización">${icon('cart')}<span data-gi=7542a5e800f9>Añadir</span></button></div>`:''}</div></div></article>`}
function contactHTML(c){return [[c.phone,c.phone?'tel:'+c.phone.replace(/[^+\d]/g,''):''],[c.email,c.email?'mailto:'+c.email:''],[c.address,safeURL(c.map_url)?c.map_url:''],[c.opening_hours,'']].filter(x=>x[0]).map(([label,href])=>href?`<a href="${E(href)}">${E(label)}</a>`:`<p>${E(label)}</p>`).join('')}
function configure(){document.querySelectorAll('main > section:not(#customerArea,#unavailable)').forEach(n=>{n.hidden=false;delete n.dataset.customerHidden});$('unavailable').hidden=true;$('menuOpen').disabled=false;$('siteSearch').disabled=false;$('searchOpen').disabled=false;document.querySelectorAll('[data-brand]').forEach(n=>n.textContent=cfg.brand_name);for(const [id,key]of Object.entries({announcement:'announcement',tagline:'tagline',heroLabel:'hero_label',heroTitle:'hero_title',heroAccent:'hero_accent',heroIntro:'hero_intro',catalogueTitle:'catalog_title',catalogueIntro:'catalog_intro',categoriesTitle:'categories_title',featuredTitle:'featured_title',aboutTitle:'about_title',aboutText:'about_text',contactTitle:'contact_title',contactIntro:'contact_intro',footerNote:'footer_note',quoteLabel:'quote_label'}))text(id,cfg[key]);
 for(const [key,v]of Object.entries({primary:cfg.primary_color,accent:cfg.accent_color,background:cfg.background_color}))if(/^#[0-9a-f]{6}$/i.test(v))document.documentElement.style.setProperty('--'+key,v);
 document.documentElement.style.setProperty('--radius',cfg.corner_style==='square'?'0px':'12px');document.title=cfg.seo_title||cfg.brand_name;document.querySelector('meta[name=description]').content=cfg.seo_description||'';
 for(const id of ['brandLogo','footerLogo'])if(safeImage(cfg.logo_url))$(id).src=cfg.logo_url;
 const navigation=(cfg.navigation||[]).filter(n=>(safeURL(n.href)||/^#[a-z][a-z0-9_-]*$/i.test(n.href))&&!(n.href==='#nosotros'&&!cfg.show_about)&&!(n.href==='#contacto'&&!cfg.show_contact)).map(n=>`<a href="${E(n.href)}">${E(prose(n.label))}</a>`).join('');$('navigation').innerHTML=navigation;$('menuLinks').innerHTML=navigation;$('headerContact').hidden=!cfg.show_contact;document.querySelector('meta[name=theme-color]').content=getComputedStyle(document.documentElement).getPropertyValue('--primary').trim();document.querySelector('meta[property="og:title"]').content=cfg.seo_title||cfg.brand_name;document.querySelector('meta[property="og:description"]').content=cfg.seo_description||'';
 if(cfg.phone){$('topPhone').hidden=false;$('topPhone').textContent=cfg.phone;$('topPhone').href='tel:'+cfg.phone.replace(/[^+\d]/g,'')}
 $('heroButton').innerHTML=E(prose(cfg.hero_button))+' <span aria-hidden="true">↗</span>';$('heroButton').href='#'+(cfg.hero_button_target==='contacto'?'contacto':'catalogo');
 if(safeImage(cfg.hero_image))$('heroArt').innerHTML=`<img class="hero-cover" src="${E(cfg.hero_image)}" alt="${E(cfg.brand_name)}">`;
 if(safeImage(cfg.about_image))$('aboutArt').innerHTML=`<img class="about-cover" src="${E(cfg.about_image)}" alt="${E(prose(cfg.about_title))}">`;
 $('benefits').hidden=!cfg.show_benefits;$('benefits').innerHTML=(cfg.benefits||[]).map(b=>`<article class="benefit"><span class="benefit-icon" aria-hidden="true">${icon(b.icon)}</span><div><strong>${E(prose(b.title))}</strong><p>${E(prose(b.text))}</p></div></article>`).join('');
 $('nosotros').hidden=!cfg.show_about;$('contacto').hidden=!cfg.show_contact;$('contactDetails').innerHTML=contactHTML(cfg);$('unavailableContact').innerHTML=contactHTML(cfg);
 if(/^\d{7,15}$/.test((cfg.whatsapp||'').replace(/\D/g,''))){$('whatsappLink').hidden=false;$('whatsappLink').href='https://wa.me/'+cfg.whatsapp.replace(/\D/g,'')}else $('whatsappLink').hidden=true;
 $('socialLinks').innerHTML=['facebook','instagram','linkedin'].filter(k=>safeURL(cfg[k+'_url'])).map(k=>`<a href="${E(cfg[k+'_url'])}" target="_blank" rel="noopener">${E(k[0].toUpperCase()+k.slice(1))} ↗</a>`).join('');
 $('brandsSection').hidden=!(cfg.brands||[]).length;$('brands').innerHTML=(cfg.brands||[]).map(b=>safeURL(b.image)?`<img src="${E(b.image)}" alt="${E(b.name)}" loading="lazy">`:`<span>${E(b.name)}</span>`).join('');
 $('faqSection').hidden=!cfg.show_faq||!(cfg.faq||[]).length;$('faq').innerHTML=(cfg.faq||[]).map(f=>`<details><summary>${E(prose(f.question))}</summary><p>${E(prose(f.answer))}</p></details>`).join('');
 text('copyright',`© ${new Date().getFullYear()} ${cfg.brand_name}.`);$('cartOpen').hidden=!cfg.enable_quotes&&!customer();text('quoteLabel',customer()?'Mi selección':cfg.quote_label);$('b2bAccess').querySelector('span').textContent=customer()?'Mi cuenta':'Mi empresa';$('b2bAccess').setAttribute('aria-label',customer()?'Abrir mi cuenta':'Iniciar sesión en Mi empresa');sort=cfg.default_sort||'featured';$('siteSort').value=sort;
}
function categoryPriority(c){const k=categoryKey(c.category);return k.includes('SUMINISTROS DE OFICINA')?0:k.includes('SUMINISTROS ESCOLARES')?1:k.includes('COMPUTACI')?2:k.includes('EQUIPOS DE OFICINA')?3:4}
function filters(){const cats=[...(boot.categories||[])].sort((a,b)=>categoryPriority(a)-categoryPriority(b)),all=[{category:'',title:'Todos los productos',count:boot.total},...cats];$('categoryFilters').className='category-filters';$('categoryFilters').innerHTML=all.map(c=>`<button type="button" class="category-filter ${category===c.category?'active':''}" aria-pressed="${category===c.category}" data-category="${E(c.category)}"><span>${E(catalogLabel(c.title))}</span><small>${E(c.count)}</small></button>`).join('');$('menuCategories').innerHTML=all.map(c=>`<button type="button" class="menu-category ${category===c.category?'active':''}" aria-pressed="${category===c.category}" data-category="${E(c.category)}"><span>${E(catalogLabel(c.title))}</span><small>${E(c.count)}</small></button>`).join('');$('categoriesSection').hidden=!cfg.show_categories||!cats.length;$('categories').innerHTML=cats.map(c=>`<button type="button" class="category-card ${category===c.category?'active':''}" aria-pressed="${category===c.category}" data-category="${E(c.category)}">${categoryImage(c)}<span class="category-copy"><strong>${E(catalogLabel(c.title))}</strong><small>${E(c.count)} ${c.count===1?'producto':'productos'}</small></span></button>`).join('');const brands=boot.brands||[];$('brandFilterWrap').hidden=!brands.length;$('brandFilter').innerHTML='<option value="">Todas las marcas</option>'+brands.map(b=>`<option value="${E(b)}">${E(prose(b))}</option>`).join('');$('brandFilter').value=brand}
async function catalogue(){const seq=++generation;text('activeCategory',search?`Resultados para «${search}»`:catalogLabel((boot.categories||[]).find(c=>c.category===category)?.title||'Todos los productos'));text('siteStatus','Cargando productos…');$('siteProducts').setAttribute('aria-busy','true');try{const r=await api('catalog',{search,category,brand,sort,offset,limit:Number(cfg.page_size)||12});if(seq!==generation)return;const items=r.items||[];text('productCount',`${r.total} ${r.total===1?'producto':'productos'}`);$('siteProducts').innerHTML=items.map(card).join('')||'<div class="empty-catalogue"><h3>No encontramos productos.</h3><p>Prueba con otro término o elimina los filtros.</p></div>';text('siteStatus','');$('sitePager').innerHTML=r.total>r.limit?`<button class="button outline" data-page="-1" ${offset===0?'disabled':''} data-gi=e4ce7c09d51e>Anterior</button><span>${Math.floor(offset/r.limit)+1} / ${Math.ceil(r.total/r.limit)}</span><button class="button outline" data-page="1" ${offset+r.limit>=r.total?'disabled':''}>Siguiente</button>`:'';await hydratePhotos()}catch(e){if(seq===generation)text('siteStatus',friendly(e))}finally{if(seq===generation)$('siteProducts').setAttribute('aria-busy','false')}}
function minimum(p){const m=Number(p.order_minimum)||0,s=Number(p.order_multiple)||0;return s>0?Math.round(Math.ceil(Math.max(m,s)/s)*s*1000)/1000:Math.max(m,1)}
function initialQuantity(p){const s=Number(p.order_multiple)||0,q=Math.max(1,minimum(p));return s>0?Math.round(Math.ceil(q/s-1e-9)*s*1000)/1000:q}
function validQty(p,q){p=p||{};const step=Number(p.order_multiple)||0;return Number.isFinite(q)&&q>=minimum(p)&&q<=100000&&Math.abs(q*1000-Math.round(q*1000))<1e-6&&(!step||Math.abs(q/step-Math.round(q/step))<1e-6)}
function saveCart(){if(customer()){text('cartCount',window.GamaCustomer.cartCount());return}try{sessionStorage.setItem('gama.public.selection',JSON.stringify(cart))}catch(_){}text('cartCount',cart.length)}
function notice(message){text('cartNotice',message);$('cartNotice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>{$('cartNotice').hidden=true},4500)}
function add(id,qty){const p=products.get(id);if(!p||(!cfg.enable_quotes&&!customer()))return false;if(customer()){if(p.orderable===false){notice('Contacta con GAMA para solicitar este servicio.');return false}try{window.GamaCustomer.add(p,qty??initialQuantity(p));notice(`${catalogLabel(p.name)} añadido a tu selección.`);return true}catch(e){notice(window.GamaCustomer.error(e));return false}}const line=cart.find(x=>x.id===id),q=qty??initialQuantity(p);if(!validQty(p,q)){notice('Revisa la cantidad mínima y los múltiplos de compra.');return false}if(line){const next=Math.round((line.qty+q)*1000)/1000;if(!validQty(p,next)){notice('La cantidad total supera el máximo permitido.');return false}line.qty=next}else{if(cart.length>=30){notice('Puedes seleccionar hasta 30 productos.');return false}cart.push({id,qty:q})}saveCart();notice(`${catalogLabel(p.name)} añadido a tu cotización.`);if($('cartDialog').open)renderCart();return true}
async function detail(id,push=true){
 const seq=++detailGeneration;$('productDetail').innerHTML='<h2 id="productTitle">Detalle del producto</h2><p role="status">Cargando información…</p>';if(!$('productDialog').open)$('productDialog').showModal();
 try{const r=await api('product',{id});if(seq!==detailGeneration)return;const p=r.item;products.set(p.id,p);
 const related=(boot.featured||[]).filter(x=>x.id!==p.id).sort((a,b)=>Number(b.category===p.category)-Number(a.category===p.category)).slice(0,2);
 $('productDetail').innerHTML=`<div class="detail-grid"><div class="detail-photo">${imageHTML(p.id,p.name)}</div><div class="detail-copy"><span class="eyebrow">${E(catalogLabel(p.category_title))}</span><h2 id="productTitle">${E(catalogLabel(p.name))}</h2><p class="product-reference"><span data-gi=b23cae5865d0>Referencia: </span>${E(p.reference)}</p><div class="product-price">${priceHTML(p)}</div>${favoriteHTML(p)}<p class="description">${E(prose(p.description||'Consulta con nuestro equipo por este producto.'))}</p><dl class="specifications">${price(p)!=null?`<dt>Precio sin impuestos</dt><dd>${E(money(p.unit_price))}</dd><dt>Impuesto</dt><dd>${E(Number(p.tax_rate)||0)} %</dd>`:''}<dt data-gi=558bb20a82ed>Categoría</dt><dd>${E(catalogLabel(p.category_title))}</dd>${p.brand?`<dt data-gi=8e2ca9b0cc8a>Marca</dt><dd>${E(prose(p.brand))}</dd>`:''}${Number(p.order_minimum)>0?`<dt>Compra mínima</dt><dd>${E(p.order_minimum)} unidades</dd>`:''}${Number(p.order_multiple)>0?`<dt data-gi=6bbcd2f13499>Presentación</dt><dd>Múltiplos de ${E(p.order_multiple)} unidades</dd>`:''}</dl><div class="detail-help">${icon('truck')}<span>Confirmamos disponibilidad, precios finales y entrega al preparar tu cotización.</span></div>${((cfg.enable_quotes||customer())&&(!customer()||p.orderable!==false))?`<form id="detailForm"><div class="detail-order"><label class="detail-quantity" data-gi=8930e00fcc39>Cantidad<input name="quantity" type="number" value="${initialQuantity(p)}" min="${minimum(p)}" max="100000" step="${Number(p.order_multiple)||'0.001'}" required></label><button type="submit" class="button primary">${icon('cart')}Añadir a mi cotización</button></div><small>${Number(p.order_minimum)>0?'Mínimo: '+E(p.order_minimum)+'. ':''}${Number(p.order_multiple)>0?'Múltiplos de '+E(p.order_multiple)+'.':''}</small><p id="detailStatus" role="status"></p></form>`:''}</div></div>${related.length?`<section class="related-products"><h3>También te puede interesar</h3><div class="product-grid">${related.map(card).join('')}</div></section>`:''}`;
 if(push){const u=new URL(location.href);u.searchParams.set('product',id);history.pushState({},'',u)}
 if($('detailForm'))$('detailForm').onsubmit=e=>{e.preventDefault();const q=Number(e.target.elements.quantity.value);if(!validQty(p,q)){text('detailStatus','Revisa la cantidad mínima y los múltiplos.');return}if(add(id,q))text('detailStatus','Producto añadido a tu selección.');else text('detailStatus','No se pudo añadir. Revisa tu selección y las cantidades.')};await hydratePhotos();
 }catch(e){if(seq===detailGeneration)$('productDetail').innerHTML=`<h2 id="productTitle">Producto no disponible</h2><p role="status">${E(friendly(e))}</p>`}
}
function lineAmount(p,q){const net=round(Number(p.unit_price)*q);return cfg.price_display==='without_tax'?net:net+round(net*Number(p.tax_rate||0)/100)}
function renderCart(){let total=0,unknown=false;$('cartLines').innerHTML=cart.map(l=>{const p=products.get(l.id);if(!p){unknown=true;return `<article class="cart-line"><p>Producto por actualizar</p><button data-remove="${E(l.id)}" class="text-link" data-gi=c9894cf002f9>Eliminar</button></article>`}const v=price(p);if(v==null)unknown=true;else total+=lineAmount(p,l.qty);return `<article class="cart-line"><div class="cart-photo">${imageHTML(p.id,p.name,false)}</div><div><strong>${E(catalogLabel(p.name))}</strong><small>${E(p.reference)}</small><button class="text-link" data-remove="${E(l.id)}" type="button" data-gi=c9894cf002f9>Eliminar</button></div><label data-gi=8930e00fcc39>Cantidad<input data-quantity="${E(l.id)}" aria-label="Cantidad de ${E(catalogLabel(p.name))}" type="number" value="${l.qty}" min="${minimum(p)}" max="100000" step="${Number(p.order_multiple)||'0.001'}"></label><b>${v==null?'Consultar':E(money(lineAmount(p,l.qty)))}</b></article>`}).join('')||'<p class="empty-cart">Tu selección está vacía. Explora el catálogo y añade productos.</p>';text('cartTotal',cfg.show_prices?`${unknown?'Importe parcial indicativo':'Importe indicativo'}: ${money(total)}${unknown?' · Hay precios por confirmar':''}`:'Precios a confirmar con nuestro equipo.');$('quoteSend').disabled=sending||!cart.length||cart.some(l=>!products.has(l.id))||!cfg.enable_quotes;hydratePhotos()}
async function openCart(){if(customer()){window.GamaCustomer.open('cart');return}if(!cfg.enable_quotes)return;if(!$('cartDialog').open)$('cartDialog').showModal();renderCart();text('quoteStatus','Actualizando tu selección…');const original=cart.map(x=>x.id);const results=await Promise.allSettled(original.map(id=>api('product',{id})));let missing=false;results.forEach((r,i)=>{if(r.status==='fulfilled')products.set(original[i],r.value.item);else if(r.reason?.message==='WEBSITE_PRODUCT_NOT_FOUND'){cart=cart.filter(l=>l.id!==original[i]);missing=true}});saveCart();renderCart();text('quoteStatus',missing?'Un producto ya no está disponible y fue retirado de la selección.':'')}
async function submit(e){e.preventDefault();if(customer()){window.GamaCustomer.open('cart');return}if(sending||!cart.length)return;const form=e.currentTarget;for(const l of cart)if(!validQty(products.get(l.id)||{},l.qty)){text('quoteStatus','Revisa las cantidades antes de enviar.');return}const payload={...Object.fromEntries(new FormData(form)),consent:form.elements.consent.checked,lines:cart.map(l=>({product_id:l.id,quantity:l.qty}))};const signature=JSON.stringify(payload);if(signature!==retryPayload){retryPayload=signature;requestKey=crypto.randomUUID()}sending=true;renderCart();text('quoteStatus','Enviando solicitud…');try{const r=await api('submit',{...payload,request_key:requestKey});cart=[];saveCart();form.reset();renderCart();text('quoteStatus',`Solicitud ${r.reference} recibida. Nuestro equipo confirmará los precios y las condiciones contigo.`);retryPayload='';requestKey=''}catch(err){text('quoteStatus',friendly(err))}finally{sending=false;renderCart()}}
function paused(c){cfg=c||{};document.querySelectorAll('main > section:not(#customerArea)').forEach(s=>s.hidden=s.id!=='unavailable');$('cartOpen').hidden=true;$('menuOpen').disabled=true;$('siteSearch').disabled=true;$('searchOpen').disabled=true;$('unavailableContact').innerHTML=contactHTML(cfg);$('siteProducts').replaceChildren();products.clear();photos.clear()}
async function start(){const serial=++startSerial;try{await window.GamaCustomer?.ready;const initial=JSON.parse($('initial-data').textContent||'null');const next=(!customer()&&initial)||await api('bootstrap');if(serial!==startSerial)return;boot=next;$('initial-data').textContent='null';if(boot.paused){paused(boot.settings);return}cfg=boot.settings;currency=boot.currency||'USD';configure();for(const c of boot.categories||[])if(c.photo_id)products.set(c.photo_id,{id:c.photo_id,name:c.title,has_photo:true});const featured=boot.featured||[];$('featuredSection').hidden=!cfg.show_featured||!featured.length;$('featuredProducts').innerHTML=featured.map(card).join('');if(!cfg.hero_image)document.querySelectorAll('[data-hero]').forEach((n,i)=>{const p=featured[i];n.hidden=!p;if(p)n.innerHTML=imageHTML(p.id,p.name,false)+`<small>${E(catalogLabel(p.name))}</small>`});filters();saveCart();if(customer()&&accountView!=='catalog')customerView(accountView);await catalogue();if(serial!==startSerial)return;const id=new URL(location.href).searchParams.get('product');if(uuid(id))detail(id,false)}catch(e){if(serial!==startSerial)return;paused();$('unavailable').querySelector('p').textContent='No podemos conectar con el catálogo. Vuelve a intentarlo en un momento.'}}
function showLegal(kind){
 const identity=[cfg.legal_name||cfg.brand_name,/^\d{13}$/.test(cfg.legal_tax_id||'')?'RUC: '+cfg.legal_tax_id:'',cfg.address,cfg.phone,cfg.privacy_email||cfg.email].filter(Boolean).join('\n');
 const defaults={notice:['Información legal',identity+'\n\nEste sitio presenta el catálogo de GAMA y permite solicitar cotizaciones. El envío de una solicitud no constituye una compra ni una reserva. Puedes contactar con nosotros a través de los datos indicados.'],delivery:['Entregas, cambios y garantías','La disponibilidad, los plazos, el costo de envío y las condiciones de pago se confirman por escrito antes de aceptar un pedido. Para entregas, cambios, garantías o devoluciones, contacta con nuestro equipo. Se respetan los derechos del consumidor previstos en la legislación ecuatoriana.'],storage:['Cookies y almacenamiento','El catálogo conserva los identificadores y cantidades de la selección en el almacenamiento de sesión de esta pestaña. No guarda allí los datos personales del formulario. Mi empresa utiliza una sesión de autenticación. No se incorporan herramientas publicitarias ni analítica de comportamiento en el catálogo.']};
 const fallback=defaults[kind];text('legalTitle',cfg[kind+'_title']||fallback?.[0]||'Información');
 let body=cfg[kind+'_text']||fallback?.[1]||'';
 if(kind==='notice'&&cfg.notice_text)body=identity+'\n\n'+body;
 if(kind==='privacy')body=identity+'\n\n'+body;
 text('legalText',body);if(!$('legalDialog').open)$('legalDialog').showModal();
}
document.addEventListener('error',e=>{const img=e.target;if(img instanceof HTMLImageElement&&img.parentElement?.matches('[data-photo]')){photos.delete(img.parentElement.dataset.photo);img.parentElement.innerHTML=photoPlaceholder()}},true);
function catalogVisible(){if(customer())window.GamaCustomer.open('catalog')}
function closeMenu(){if($('menuDialog').open)$('menuDialog').close()}
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b||b.closest('#customerArea,#customerLogin,#mfaDialog'))return;if(b.id==='b2bAccess'||(b.matches('a')&&/\/(?:gama-)?b2b(?:\.html)?(?:[?#]|$)/.test(b.getAttribute('href')||''))){e.preventDefault();closeMenu();window.GamaCustomer?.open();return}if(['#catalogo','#contacto','#nosotros'].includes(b.getAttribute('href')))catalogVisible();if(b.dataset.customerFavorite){e.preventDefault();const id=b.dataset.customerFavorite,saved=b.getAttribute('aria-pressed')!=='true';b.disabled=true;window.GamaCustomer.setFavorite(id,saved).then(()=>{document.querySelectorAll('[data-customer-favorite]').forEach(n=>{if(n.dataset.customerFavorite===id){n.setAttribute('aria-pressed',String(saved));n.querySelector('span').textContent=saved?'♥':'♡'}});notice(saved?'Producto guardado en mis compras habituales.':'Producto retirado de mis compras habituales.')}).catch(e=>notice(window.GamaCustomer.error(e))).finally(()=>{b.disabled=false});return}if(b.dataset.product)detail(b.dataset.product);if(b.dataset.add){const input=b.closest('.product-card')?.querySelector('[data-card-quantity]');if(input&&!input.checkValidity()){input.setAttribute('aria-invalid','true');notice('Revisa la cantidad mínima y los múltiplos de compra.');input.focus({preventScroll:true})}else add(b.dataset.add,input?Number(input.value):undefined)}if(b.dataset.category!=null){catalogVisible();category=b.dataset.category;offset=0;closeMenu();filters();catalogue();$('catalogo').scrollIntoView({behavior:'smooth'})}if(b.dataset.page){offset=Math.max(0,offset+Number(b.dataset.page)*(Number(cfg.page_size)||12));catalogue();$('catalogo').scrollIntoView({behavior:'smooth'})}if(b.dataset.view){$('siteProducts').className=b.dataset.view==='grid'?'product-grid':'product-list';document.querySelectorAll('[data-view]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)))}if(b.dataset.remove){cart=cart.filter(x=>x.id!==b.dataset.remove);saveCart();renderCart()}if(b.dataset.closeDialog){$(b.dataset.closeDialog).close()}if(b.dataset.legal)showLegal(b.dataset.legal);if(b.closest('#menuLinks'))closeMenu()});
document.addEventListener('change',e=>{const id=e.target.dataset.quantity;if(id){const p=products.get(id),q=Number(e.target.value);if(!validQty(p,q)){text('quoteStatus','Revisa las cantidades mínimas y los múltiplos.');renderCart();return}cart.find(x=>x.id===id).qty=q;saveCart();renderCart();text('quoteStatus','')}});
window.addEventListener('popstate',()=>{const id=new URL(location.href).searchParams.get('product');if(uuid(id))detail(id,false);else{$('productDialog').close();detailGeneration++}});$('productDialog').addEventListener('close',()=>{detailGeneration++;const u=new URL(location.href);if(u.searchParams.has('product')){u.searchParams.delete('product');history.replaceState({},'',u)}});
function runSearch(){catalogVisible();clearTimeout(timer);search=$('siteSearch').value.trim();offset=0;catalogue();$('catalogo').scrollIntoView({behavior:'smooth'})}
$('siteSearch').oninput=()=>{clearTimeout(timer);timer=setTimeout(runSearch,300)};$('searchForm').onsubmit=e=>{e.preventDefault();runSearch()};$('siteSort').onchange=e=>{sort=e.target.value;offset=0;catalogue()};$('brandFilter').onchange=e=>{brand=e.target.value;offset=0;catalogue()};$('clearFilters').onclick=()=>{clearTimeout(timer);search=category=brand='';offset=0;$('siteSearch').value='';filters();catalogue()};$('cartOpen').onclick=openCart;$('quoteForm').onsubmit=submit;
$('menuOpen').onclick=()=>{if($('menuDialog').open){closeMenu();return}$('menuDialog').showModal();document.body.classList.add('menu-open');$('menuOpen').setAttribute('aria-expanded','true')};$('menuClose').onclick=closeMenu;$('menuDialog').addEventListener('close',()=>{document.body.classList.remove('menu-open');$('menuOpen').setAttribute('aria-expanded','false')});$('menuDialog').addEventListener('click',e=>{if(e.target!==$('menuDialog'))return;const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeMenu()});$('retryLoad').onclick=()=>location.reload();
function customerView(tab){accountView=tab;const browsing=tab==='catalog';document.querySelectorAll('main > section:not(#customerArea)').forEach(n=>{if(!browsing){if(!n.hasAttribute('data-customer-hidden'))n.dataset.customerHidden=String(n.hidden);n.hidden=true}else if(n.hasAttribute('data-customer-hidden')){n.hidden=n.dataset.customerHidden==='true';delete n.dataset.customerHidden}})}
function sessionChanged(){generation++;detailGeneration++;startSerial++;const transfer=customer()?cart.slice():[],transferSerial=++customerEpoch;if(transfer.length){cart=[];try{sessionStorage.removeItem('gama.public.selection')}catch(_){}Promise.allSettled(transfer.map(async l=>{const r=await window.GamaCustomer.storefront('product',{id:l.id});if(customer()&&customerEpoch===transferSerial&&r.item.orderable!==false)window.GamaCustomer.add(r.item,l.qty)})).then(results=>{if(customer()&&customerEpoch===transferSerial&&results.some(r=>r.status==='rejected'))notice('Algunos productos necesitan una revisión. Comprueba tu selección.')})}products.clear();$('siteProducts').replaceChildren();$('featuredProducts').replaceChildren();$('productDetail').replaceChildren();$('productDialog').close();$('cartDialog').close();$('cartLines').replaceChildren();$('cartTotal').textContent='';$('cartNotice').hidden=true;customerView('catalog');if(started)start()}
document.addEventListener('gama:customer-session',sessionChanged);
document.addEventListener('gama:customer-view',e=>customerView(e.detail.tab));
document.addEventListener('gama:customer-cart',e=>{if(customer())text('cartCount',e.detail.count)});
(window.GamaCustomer?.ready||Promise.resolve()).then(()=>{started=true;start()});
})();
