(function(){'use strict';
const host=document.getElementById('survey'),F=window.CocoSurveyForm,token=location.hash.slice(1),lang=['es','fr','en'].includes(navigator.language.slice(0,2))?navigator.language.slice(0,2):'es';
const messages={unavailable:['Esta encuesta no está disponible o ya está cerrada.','Ce sondage est indisponible ou déjà fermé.','This survey is unavailable or already closed.'],answered:['Ya se ha registrado una respuesta con este enlace.','Une réponse a déjà été enregistrée avec ce lien.','A response has already been recorded with this link.'],error:['No se pudo enviar. Tus respuestas se conservan; inténtalo de nuevo.','L’envoi a échoué. Vos réponses sont conservées ; réessayez.','Could not submit. Your answers are retained; please retry.'],rate:['Demasiados envíos. Inténtalo más tarde.','Trop d’envois. Réessayez plus tard.','Too many submissions. Please try again later.'],invalid:['Revisa las respuestas obligatorias y los valores introducidos.','Vérifiez les réponses obligatoires et les valeurs saisies.','Check required answers and entered values.'],retry:['Reintentar','Réessayer','Retry']};
const T=(k,l=lang)=>messages[k][({es:0,fr:1,en:2}[l]??0)];
async function rpc(a,d={}){const r=await fetch('/api/surveys',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({p_action:a,p_data:{token,...d}})});const b=await r.json();if(!r.ok)throw Error(b.error);return b}
async function load(){try{if(!/^[a-f0-9-]{36}$/i.test(token))throw Error('SURVEY_UNAVAILABLE');const s=await rpc('get');document.documentElement.lang=s.language;document.title=s.title+' · GAMA';if(s.answered){host.innerHTML=`<div class="svQuestionnaire svEmpty"><h1>${F.esc(s.title)}</h1><p>${F.esc(T('answered',s.language))}</p></div>`;return}host.innerHTML=F.render(s);const form=host.querySelector('form');let requestKey=crypto.randomUUID(),lastPayload=null;
 form.onsubmit=async e=>{e.preventDefault();const btn=form.querySelector('[type=submit]'),status=form.querySelector('[role=status]');if(btn.disabled)return;try{const d=F.read(form,s),encoded=JSON.stringify(d);if(lastPayload!==null&&lastPayload!==encoded)requestKey=crypto.randomUUID();lastPayload=encoded;btn.disabled=true;const r=await rpc('submit',{...d,request_key:requestKey});host.innerHTML=`<div class="svQuestionnaire svEmpty"><p class="svEyebrow">GAMA · COCO</p><h1>${F.esc(F.t('thanks',s.language))}</h1><p class="svIntro">${F.esc(r.thanks)}</p>${r.maximum>0?`<p class="svStat">${r.score} / ${r.maximum}</p><p>${F.esc(F.t(r.passed?'passed':'failed',s.language))}</p>`:''}</div>`;host.setAttribute('tabindex','-1');host.focus()}catch(e){const m=String(e.message);status.textContent=m==='SURVEY_UNAVAILABLE'?T('unavailable',s.language):m==='SURVEY_ALREADY_ANSWERED'?T('answered',s.language):m==='SURVEY_RATE_LIMIT'?T('rate',s.language):m.includes('INVALID')||m.includes('REQUIRED')?T('invalid',s.language):Object.values(messages).some(a=>a.includes(m))?m:m===F.t('missing',s.language)?m:T('error',s.language);btn.disabled=false}};
 }catch(e){host.innerHTML=`<div class="svQuestionnaire svEmpty"><h1>GAMA · COCO</h1><p role="status">${F.esc(T('unavailable'))}</p><button class="svButton">${F.esc(T('retry'))}</button></div>`;host.querySelector('button').onclick=load}}
load();
})();
