(function(){'use strict';
const U=window.ArcUI,E=U.esc,T=s=>window.GamaI18n?.t?.(s)||s,money=v=>window.GamaCurrency.format(v),rpc=(customer=null,data={})=>window.ArcData.rpc('gama_customer_aging',{p_customer:customer,p_data:data});
let epoch=0;
const toast=e=>window.gamaToast?.(window.ArcErrors.message(e));
async function credit(customer,order,host){if(!host)return;const token=epoch,data=await window.ArcData.rpc('gama_customer_credit_status',{p_customer:customer,p_order:order||null});if(token!==epoch||!host.isConnected)return;
 U.render(host,`<div class="arcPanel"><span class="arcStatusBadge" data-state="${data.blocked?'error':'confirmed'}">${E(T(data.blocked?'Crédito bloqueado · solicita aprobación':'Crédito disponible'))}</span><p>${E(T('Exposición total'))}: <b>${E(money(data.exposure))}</b> · ${E(T('Límite de crédito'))}: ${data.credit_limit===null?'—':E(money(data.credit_limit))}</p><p>${E(T('Facturas pendientes'))}: ${E(money(data.receivable))} · ${E(T('Pedidos sin facturar'))}: ${E(money(data.commitment))}</p>${data.hold_reason?`<p>${E(data.hold_reason)}</p>`:''}${data.overdue.length?`<p>${E(T('Facturas vencidas'))}: ${data.overdue.slice(0,5).map(r=>E(r.number)+' · '+E(money(r.balance))).join(' / ')}</p>`:''}</div>`);return data;
}
async function aging(){const token=epoch;let offset=0,search='',revision=0;const dlg=U.dialog({title:T('Balance por antigüedad'),saveLabel:T('Cerrar'),body:`<div class="arcToolbar"><input name="search" type="search" placeholder="${E(T('Buscar cliente'))}"><button type="button" data-search class="arcButton primary">${E(T('Buscar'))}</button></div><div data-aging></div><div class="arcToolbar"><button type="button" data-prev class="arcButton secondary">${E(T('Anterior'))}</button><span data-count></span><button type="button" data-next class="arcButton secondary">${E(T('Siguiente'))}</button></div>`,onSave:async()=>{}});dlg.dataset.collections='';
 const load=async()=>{const request=++revision,data=await rpc(null,{offset,search});if(request!==revision||token!==epoch||!dlg.isConnected)return;U.render(dlg.querySelector('[data-aging]'),`<p>${E(T('Saldo pendiente'))}: <b>${E(money(data.balance))}</b> · ${E(T('Importe vencido'))}: <b>${E(money(data.overdue))}</b></p>`+U.table({columns:[{key:'name',label:T('Cliente')},...Object.entries({current:'Sin vencer',days_0_30:'0–30 días',days_31_60:'31–60 días',days_61_90:'61–90 días',days_over_90:'Más de 90 días',missing_due:'Sin vencimiento'}).map(([key,label])=>({key,label:T(label),value:r=>money(r[key]||0)})),{label:T('Acciones'),actions:true,html:r=>`<button type="button" class="arcButton secondary" data-statement="${E(r.id)}">${E(T('Estado de cuenta y recordatorio'))}</button>`}],items:data.rows}));dlg.querySelector('[data-prev]').disabled=offset===0;dlg.querySelector('[data-next]').disabled=offset+30>=data.total;dlg.querySelector('[data-count]').textContent=`${data.total?offset+1:0}–${Math.min(offset+30,data.total)} / ${data.total}`;dlg.querySelectorAll('[data-statement]').forEach(b=>b.onclick=()=>statement(b.dataset.statement).catch(toast));};
 dlg.querySelector('[data-search]').onclick=()=>{search=dlg.querySelector('[name=search]').value;offset=0;load().catch(toast)};dlg.querySelector('[data-prev]').onclick=()=>{offset=Math.max(0,offset-30);load().catch(toast)};dlg.querySelector('[data-next]').onclick=()=>{offset+=30;load().catch(toast)};await load();return dlg;
}
async function statementPdf(data){await window.ArcLoadScript('gama-pdf.js');await window.GamaPdf.ready();await window.ArcLoadScript('gama-pdf-template.js');
 const pdf=window.GamaPdfTemplate.layout({title:T('Estado de cuenta'),reference:data.customer.identification,date:data.today,company:{...window.GamaCompany?.get(),...data.company,configured:true}}),doc=pdf.doc;
 pdf.text(data.customer.name,12,true);pdf.text(T('Saldo pendiente')+': '+money(data.total)+' · '+T('Importe vencido')+': '+money(data.overdue),10,true);
 const widths=[76,32,32,42],xs=[14,90,122,154];const header=()=>{doc.setFont('helvetica','bold');doc.setFontSize(9);[T('Factura'),T('Fecha'),T('Vencimiento'),T('Saldo')].forEach((v,i)=>doc.text(v,xs[i]+2,pdf.y));pdf.y+=7;doc.setFont('helvetica','normal')};header();
 for(const row of data.rows){const cells=[row.number,row.issue_date,row.due_date||T('Sin vencimiento'),money(row.balance)],wrapped=cells.map((v,i)=>doc.splitTextToSize(String(v),widths[i]-4)),height=Math.max(1,...wrapped.map(a=>a.length))*4+4;if(pdf.y+height>269){pdf.next();header()}doc.setFont('helvetica','normal');doc.setFontSize(9);wrapped.forEach((v,i)=>doc.text(v,xs[i]+2,pdf.y));pdf.y+=height;}
 pdf.finish(T('Los saldos incluyen pagos, notas de crédito, retenciones y ajustes registrados.'));return doc.output('blob');
}
function reminder(data){const c=data.customer;return {email:c.email||'',subject:T('Recordatorio de pago')+' · '+c.name,body:T('Estimado/a')+' '+c.name+',\n\n'+T('Adjuntamos su estado de cuenta actualizado.')+'\n'+T('Saldo pendiente')+': '+money(data.total)+'\n'+T('Importe vencido')+': '+money(data.overdue)+'\n'+T('Fecha de corte')+': '+data.today+'\n\n'+T('Le agradeceríamos confirmar la fecha prevista de pago. Si ya pagó, envíenos el comprobante para actualizar el saldo.')+'\n\n'+(data.company.legal_name||'GAMA')};}
async function statement(customer){const token=epoch,data=await rpc(customer,{export:true});if(token!==epoch)return;const filename='Estado-de-cuenta-'+data.today+'-'+data.customer.name.replace(/[^a-zA-Z0-9-]/g,'-').slice(0,80)+'.pdf',draft=reminder(data);
 const dlg=U.dialog({title:T('Estado de cuenta y recordatorio'),saveLabel:T('Cerrar'),body:`<p><b>${E(data.customer.name)}</b> · ${E(data.today)}</p><p>${E(T('Saldo pendiente'))}: ${E(money(data.total))} · ${E(T('Importe vencido'))}: ${E(money(data.overdue))}</p><textarea data-reminder rows="10" aria-label="${E(T('Mensaje'))}">${E(draft.body)}</textarea><div class="arcToolbar"><button type="button" class="arcButton secondary" data-pdf>${E(T('Descargar estado de cuenta PDF'))}</button><button type="button" class="arcButton primary" data-email ${data.customer.email?'':'disabled'}>${E(T('Preparar correo con estado de cuenta'))}</button><button type="button" class="arcButton secondary" data-whatsapp ${data.customer.phone?'':'disabled'}>${E(T('Preparar WhatsApp'))}</button></div><p>${E(T('Revisa el mensaje antes de enviar y adjunta el PDF descargado.'))}</p>`,onSave:async()=>{}});dlg.dataset.collections='';
 let blob;const pdf=async()=>{blob=blob||await statementPdf(data);if(token!==epoch)throw Error('AUTH_CHANGED');return blob};
 const run=(b,fn)=>async()=>{b.disabled=true;try{await fn()}catch(e){toast(e)}finally{b.disabled=false}};
 const p=dlg.querySelector('[data-pdf]');p.onclick=run(p,async()=>window.GamaPdf.save(await pdf(),filename));
 const e=dlg.querySelector('[data-email]');e.onclick=run(e,async()=>{await window.ArcLoadScript('gama-quote-pdf.js');await window.GamaQuotePdf.sendDocument({blob:await pdf(),filename,...draft,body:dlg.querySelector('[data-reminder]').value})});
 const w=dlg.querySelector('[data-whatsapp]');w.onclick=run(w,async()=>{const phone=data.customer.phone.replace(/[^0-9]/g,'');if(phone.length<8||(!data.customer.phone.trim().startsWith('+')&&!phone.startsWith('593')))throw Error(T('Completa el teléfono con el código de país.'));window.GamaPdf.save(await pdf(),filename);window.open('https://wa.me/'+phone+'?text='+encodeURIComponent(dlg.querySelector('[data-reminder]').value),'_blank','noopener')});return dlg;
}
window.GamaCollections={aging,statement,statementPdf,reminder,credit};window.addEventListener('gama:auth-change',e=>{if(e.detail?.event==='TOKEN_REFRESHED')return;epoch++;document.querySelectorAll('[data-collections]').forEach(d=>d.close())});
})();
