"""Compile reviewed local translations and mark static UI text at its source.
No business-data substitution, machine translation API, or build dependency.
Run after editing locales/catalog.tsv; safe to run repeatedly.
"""
import hashlib, html, json, pathlib, re
ROOT = pathlib.Path(__file__).resolve().parent.parent
rows = {}
for n, line in enumerate((ROOT/'locales/catalog.tsv').read_text().splitlines(), 1):
    if not line or line.startswith('#'): continue
    parts = line.split('\t')
    if len(parts) != 3 or any(not x for x in parts): raise ValueError(f'Invalid translation row {n}')
    es, fr, en = parts
    if es in rows and rows[es] != [es, fr, en]: raise ValueError(f'Duplicate {es}')
    rows[es] = [es, fr, en]

def variant(text):
    text = ' '.join(html.unescape(text).split())
    if text in rows: return rows[text]
    # Preserve icons, punctuation and required-field stars outside the label.
    m = re.fullmatch(r'([^\wÀ-ÿ]*)(.*?)([\s:·*….!?—]*)', text)
    if not m: return None
    pre, core, post = m.groups()
    if core+post in rows: return [text, pre+rows[core+post][1], pre+rows[core+post][2]]
    if core in rows: return [text, pre+rows[core][1]+post, pre+rows[core][2]+post]
    return None

def key(row):
    ident = hashlib.sha256(row[0].encode()).hexdigest()[:12]
    catalog[ident] = row
    return ident
catalog = {}
for row in rows.values(): key(row)
VOID = {'area','base','br','col','embed','hr','img','input','link','meta','source','track','wbr'}
count = 0
for path in [ROOT/'index.html', *sorted(ROOT.glob('gama-*.js'))]:
    if path.name.startswith('gama-i18n'): continue
    source = path.read_text()
    def mark(m):
        global count
        opening, tag, text = m.groups()
        if tag in VOID:
            # Text after <br> or <input> belongs to the parent: mark it in its own span
            # (and drop the id an earlier pass put on the empty tag).
            row = variant(text)
            if not row: return m[0]
            count += 1
            return re.sub(r' data-gi=[a-f0-9]+>$', '>', opening)+'<span data-gi='+key(row)+'>'+text+'</span>'
        if tag in ('script','style','svg','path','textarea','title') or 'data-gi=' in opening: return m[0]
        row = variant(text)
        if not row: return m[0]
        count += 1
        return opening[:-1]+' data-gi='+key(row)+'>'+text
    source = re.sub(r'(<([a-z][\w-]*)\b[^<>]*>)([^<>]+)(?=<)', mark, source)
    def attribute(m):
        name, quote, text = m.groups()
        row = variant(text)
        if not row: return m[0]
        return f'data-gi-{name}={key(row)} '+m[0]
    # Do not add a second annotation on subsequent builds.
    source = re.sub(r'<[a-z][\w-]*\b[^<>]*>', lambda tag: re.sub(r'(?<!\S)(placeholder|aria-label|title)=("|\x27)([^<>\n]*?)\2', attribute, tag[0]), source)
    source = re.sub(r'(data-gi-(?:placeholder|aria-label|title)=[a-f0-9]+ )\1+', r'\1', source)
    # Isolate literal prefixes from interpolated business values (e.g. Fecha: ${date}).
    def prefix(m):
        opening, tag, literal = m.groups()
        if tag in ('option','script','style','textarea','title','svg','path') or 'data-gi=' in opening: return m[0]
        row=variant(literal)
        if not row: return m[0]
        return opening+'<span data-gi='+key(row)+'>'+literal+'</span>'
    source=re.sub(r'(<([a-z][\w-]*)\b[^<>]*>)([^<>$`{}]+)(?=\$\{)',prefix,source)
    if path.read_text() != source: path.write_text(source)
# Retain keys referenced by previous annotation passes (including icon variants).
for path in [ROOT/'index.html', *sorted(ROOT.glob('gama-*.js'))]:
    if path.name.startswith('gama-i18n'): continue
    for m in re.finditer(r'data-gi=([a-f0-9]+)>([^<>]+)(?=<)',path.read_text()):
        row=variant(m[2])
        if row: key(row)
# Some server functions answer in English: each message maps to its Spanish
# source text, which catalog.tsv then translates like any other label.
server = {}
server_path = ROOT/'locales/server-messages.tsv'
if server_path.exists():
    for n, line in enumerate(server_path.read_text().splitlines(), 1):
        if not line or line.startswith('#'): continue
        parts = line.split('\t')
        if len(parts) != 2 or any(not x for x in parts): raise ValueError(f'Invalid server message row {n}')
        if parts[1] not in rows: raise ValueError(f'Server message without catalogue row: {parts[1]}')
        server[parts[0]] = parts[1]
(ROOT/'gama-i18n-catalog.js').write_text('/* Generated by scripts/build-i18n.py from reviewed local translations. */\nwindow.GamaI18nCatalog='+json.dumps(catalog,ensure_ascii=False,sort_keys=True,separators=(',',':'))+';\nwindow.GamaI18nServer='+json.dumps(server,ensure_ascii=False,sort_keys=True,separators=(',',':'))+';\n')
print(f'{len(rows)} source entries, {len(catalog)} keys, {count} new static annotations')
