-- Execute inside BEGIN/ROLLBACK, optionally after the migration in the same transaction.
do $$
declare a uuid;q uuid;c uuid;o uuid;t uuid;s uuid;i uuid;p jsonb;key uuid:=gen_random_uuid();d date:=(now() at time zone 'America/Guayaquil')::date;v record;blocked boolean;other_user uuid;res jsonb;
begin
 select id into a from public.profiles where role='administrador' and active limit 1;
 perform set_config('request.jwt.claim.sub',a::text,true);
 insert into public.customers(name,identification,email,payment_terms_days) values('PAYMENT QA',gen_random_uuid()::text,'qa@example.invalid',30) returning id into c;
 insert into public.invoices(customer_id,user_id,quote_state,subtotal,tax,quote_details) values(c,a,'accepted',100,15,'{}') returning id into q;
 insert into public.sales_orders(request_key,customer_id,customer_name,status,created_by) values(gen_random_uuid(),c,'PAYMENT QA','confirmed',a) returning id into o;
 insert into public.tms_deliveries(customer,address,status,delivered_at,delivery_date) values('PAYMENT QA','Quito','Entregada',(d-22)::timestamp at time zone 'America/Guayaquil',d-40) returning id into t;
 insert into public.tms_proofs(delivery_id,signature) values(t,'data:image/png;base64,QA');
 insert into public.external_invoices(request_key,order_id,number,issuer_ruc,software,issue_date,subtotal,tax,fiscal_status,created_by,document_kind,source_quote_id,document_snapshot)
 values(gen_random_uuid(),o,'PAY-QA-'||gen_random_uuid(),'1234567890001','QA',d,100,15,'unverified',a,'internal',q,'{}') returning id into i;
 select * into v from private.gama_receivables where id=i;
 assert v.payment_status='awaiting_delivery' and v.due_date is null,'UNLINKED_DELIVERY_MUST_NOT_START_CLOCK';
 insert into public.sales_deliveries(order_id,request_key,tms_delivery_id,created_by,departed_at,departed_by) values(o,gen_random_uuid(),t,a,(d-22)::timestamp at time zone 'America/Guayaquil',a) returning id into s;
 perform public.gama_commercial_action('link_invoice_delivery',jsonb_build_object('invoice_id',i,'delivery_ids',jsonb_build_array(s)));
 select * into v from private.gama_receivables where id=i;
 assert v.due_date=d+8 and v.payment_delivery_date=d-22 and v.payment_status='pending','USE_ACTUAL_DELIVERY_NOT_PLANNED_OR_ISSUE_DATE';
 assert not exists(select 1 from private.gama_live_alerts where target_id=i),'NO_ALERT_AT_DAY_MINUS_8';
 update public.tms_deliveries set delivered_at=(d-23)::timestamp at time zone 'America/Guayaquil' where id=t;
 assert exists(select 1 from private.gama_live_alerts where target_id=i and kind='due_soon_invoice' and priority=2),'ORANGE_AT_DAY_MINUS_7';
 update public.tms_deliveries set delivered_at=(d-30)::timestamp at time zone 'America/Guayaquil' where id=t;
 assert exists(select 1 from private.gama_live_alerts where target_id=i and kind='due_soon_invoice'),'ORANGE_ON_DUE_DATE';
 update public.tms_deliveries set delivered_at=(d-31)::timestamp at time zone 'America/Guayaquil' where id=t;
 assert exists(select 1 from private.gama_live_alerts where target_id=i and kind='overdue_invoice' and priority=3),'RED_DAY_AFTER';
 assert (select count(*) from private.gama_live_alerts where target_id=i)=1,'NO_DUPLICATE_ALERT';
 execute 'set local role authenticated';
 res:=public.gama_payment_action('list',jsonb_build_object('order_id',o,'status','all'));
 assert res#>>'{rows,0,number}' like 'FAC-%' and res#>>'{rows,0,order_number}' like 'PED-%','CANONICAL_DOSSIER_REFERENCES';
 assert (res->>'total')::integer=1 and jsonb_array_length(res->'rows')=1,'LIST_FILTER_PAGINATION';
 res:=public.gama_payment_action('list',jsonb_build_object('order_id',o,'search','not-a-matching-invoice'));
 assert (res->>'total')::integer=0 and jsonb_array_length(res->'rows')=0,'EMPTY_LIST';
 res:=public.gama_payment_action('reminder',jsonb_build_object('invoice_id',i));
 assert res->>'email'='qa@example.invalid' and (res->>'balance')::numeric=115,'REMINDER_MATCHES_INVOICE_CUSTOMER';
 p:=public.gama_payment_action('payment',jsonb_build_object('invoice_id',i,'request_key',key,'amount',40,'method','transfer','paid_at',d));
 perform public.gama_payment_action('payment',jsonb_build_object('invoice_id',i,'request_key',key,'amount',40,'method','transfer','paid_at',d));
 res:=public.gama_payment_action('detail',jsonb_build_object('invoice_id',i));
 assert (res->>'balance')::numeric=75 and jsonb_array_length(res->'payments')=1,'PARTIAL_AND_IDEMPOTENT';
 blocked:=false;begin perform public.gama_payment_action('payment',jsonb_build_object('invoice_id',i,'request_key',gen_random_uuid(),'amount',76,'method','cash'));exception when others then if sqlerrm='PAYMENT_EXCEEDS_BALANCE' then blocked:=true;else raise;end if;end;
 assert blocked,'OVERPAYMENT_BLOCKED';
 perform public.gama_payment_action('payment',jsonb_build_object('invoice_id',i,'request_key',gen_random_uuid(),'amount',75,'method','cash','paid_at',d));
 res:=public.gama_payment_action('detail',jsonb_build_object('invoice_id',i));
 assert res->>'payment_status'='paid','FULLY_PAID';
 blocked:=false;begin perform public.gama_payment_action('reminder',jsonb_build_object('invoice_id',i));exception when others then if sqlerrm='REMINDER_NOT_DUE' then blocked:=true;else raise;end if;end;
 assert blocked,'STALE_REMINDER_BLOCKED';
 execute 'reset role';
 assert not exists(select 1 from private.gama_live_alerts where target_id=i),'PAID_ALERT_REMOVED';
 update public.customers set payment_terms_days=60 where id=c;
 assert (select payment_terms_days=30 from public.external_invoices where id=i),'PAID_TERMS_PRESERVED';
 perform public.gama_payment_action('cancel_payment',jsonb_build_object('invoice_id',i,'payment_id',p->>'id','reason','QA correction'));
 assert exists(select 1 from private.gama_live_alerts where target_id=i and priority=3),'VOID_REOPENS_ALERT';
 update public.customers set payment_terms_days=31 where id=c;
 assert (select due_date=d from public.external_invoices where id=i),'CUSTOMER_TERM_CHANGE_UPDATES_OPEN_INVOICES';
 update public.customers set payment_terms_days=null where id=c;
 assert (select payment_status='missing_terms' and due_date is null from private.gama_receivables where id=i),'MISSING_TERMS_NO_INVENTED_DEADLINE';
 update public.customers set payment_terms_days=0 where id=c;
 assert (select due_date=payment_delivery_date from public.external_invoices where id=i),'ZERO_DAY_TERM';
 for v in select id from public.external_invoice_payments where invoice_id=i and status='confirmed' loop
  perform public.gama_payment_action('cancel_payment',jsonb_build_object('invoice_id',i,'payment_id',v.id,'reason','QA cancellation'));
 end loop;
 update public.external_invoices set fiscal_status='cancelled' where id=i;
 assert not exists(select 1 from private.gama_live_alerts where target_id=i),'CANCELLED_INVOICE_NO_ALERT';
 select id into other_user from public.profiles where role='almacenero' and active limit 1;
 assert other_user is not null,'WAREHOUSE_PROFILE_FIXTURE_REQUIRED';
 perform set_config('request.jwt.claim.sub',other_user::text,true);
 blocked:=false;begin perform public.gama_payment_action('list','{}');exception when others then if sqlerrm='ROLE_NOT_ALLOWED' then blocked:=true;else raise;end if;end;
 assert blocked,'WAREHOUSE_CANNOT_READ_PAYMENTS';
 perform set_config('request.jwt.claim.sub','',true);
 blocked:=false;begin perform public.gama_payment_action('list','{}');exception when others then if sqlerrm='AUTH_REQUIRED' then blocked:=true;else raise;end if;end;
 assert blocked,'ANONYMOUS_CANNOT_READ_PAYMENTS';
end $$;
select 'payment_tracking_checks_passed' result;
