-- Run within BEGIN/ROLLBACK; scans and Auth fixtures are never kept.
do $$
#variable_conflict use_column
<<loading_test>>
declare
 admin_id uuid; operator_id uuid:=gen_random_uuid(); client_user uuid:=gen_random_uuid(); cid uuid; pid uuid; pid2 uuid; loc uuid; loc2 uuid; wh uuid;
 oid uuid; lid uuid; lid2 uuid; sid uuid; tid uuid; driver uuid; route_id uuid;
 code text:='SCAN-'||gen_random_uuid(); code2 text:='SCAN-'||gen_random_uuid();
 r jsonb; key_id uuid:=gen_random_uuid(); payload jsonb; rejected boolean; scan_id uuid; v integer; movement_count integer; qty_before numeric;
begin
 select id into admin_id from public.profiles where role='administrador' and active limit 1;
 select id,warehouse_id into loc,wh from public.warehouse_locations where active order by id limit 1;
 insert into public.warehouse_locations(warehouse_id,code,name) values(wh,'LOAD-'||gen_random_uuid(),'Loading test rollback') returning id into loc2;
 insert into auth.users(id,email,email_confirmed_at) values(operator_id,operator_id||'@gama-test.invalid',now()),(client_user,client_user||'@gama-test.invalid',now());
 insert into public.profiles(id,role,active,full_name) values(operator_id,'almacenero',true,'Test loader'),(client_user,'cliente',true,'Test client') on conflict(id) do update set role=excluded.role,active=true;
 insert into public.customers(name,address) values('Loading test rollback','Quito') returning id into cid;
 insert into public.products(name,barcode,reference,sale_price,stock) values('Loading A '||gen_random_uuid(),code,gen_random_uuid()::text,10,4) returning id into pid;
 insert into public.products(name,barcode,reference,sale_price,stock) values('Loading B '||gen_random_uuid(),code2,gen_random_uuid()::text,10,1) returning id into pid2;
 insert into public.stock_quants(product_id,location_id,quantity,reserved_quantity) values(pid,loc,2,0),(pid,loc2,2,0),(pid2,loc,1,0);
 insert into public.tms_drivers(name,vehicle,enabled) values('Loading test driver','TEST-TRUCK',true) returning id into driver;
 perform set_config('request.jwt.claim.sub',admin_id::text,true);execute 'set local role authenticated';
 r:=public.gama_sales_action('create',jsonb_build_object('request_key',gen_random_uuid(),'customer_id',cid,'delivery_address','Quito','lines',jsonb_build_array(jsonb_build_object('product_id',pid,'quantity',4,'unit_price',10,'tax_rate',0),jsonb_build_object('product_id',pid2,'quantity',1,'unit_price',10,'tax_rate',0))));oid:=(r->>'id')::uuid;
 perform public.gama_sales_action('confirm',jsonb_build_object('order_id',oid));
 select id into lid from public.sales_order_lines where order_id=oid and product_id=pid;
 select id into lid2 from public.sales_order_lines where order_id=oid and product_id=pid2;
 perform set_config('request.jwt.claim.sub',operator_id::text,true);
 r:=public.gama_sales_action('ship',jsonb_build_object('order_id',oid,'request_key',gen_random_uuid(),'delivery_date',current_date+1,'lines',jsonb_build_array(jsonb_build_object('line_id',lid,'location_id',loc,'quantity',2),jsonb_build_object('line_id',lid,'location_id',loc2,'quantity',2),jsonb_build_object('line_id',lid2,'location_id',loc,'quantity',1))));sid:=(r->>'id')::uuid;
 select tms_delivery_id into tid from public.sales_deliveries where id=sid;
 if tid is null then raise exception 'FAIL_AUTOMATIC_TMS'; end if;
 r:=public.gama_loading_action('manifest',jsonb_build_object('delivery_id',tid));
 if jsonb_array_length(r->'lines')<>3 or (r->>'complete')::boolean then raise exception 'FAIL_MANIFEST'; end if;
 if not exists(select 1 from jsonb_array_elements(public.gama_loading_action('list','{}')) a where a->>'id'=tid::text) then raise exception 'FAIL_FUTURE_DELIVERY_MISSING'; end if;
 rejected:=false;begin perform public.gama_loading_action('depart',jsonb_build_object('delivery_id',tid,'driver_id',driver,'version',0));exception when others then if sqlerrm='LOADING_INCOMPLETE' then rejected:=true;else raise;end if;end;
 if not rejected then raise exception 'FAIL_EMPTY_DEPART'; end if;
 rejected:=false;begin update public.tms_deliveries set status='En tránsito' where id=tid;exception when others then if sqlerrm='LOADING_INCOMPLETE' then rejected:=true;else raise;end if;end;
 if not rejected then raise exception 'FAIL_RAW_DEPART'; end if;
 rejected:=false;begin insert into public.tms_proofs(delivery_id,photo) values(tid,'data:image/png;base64,AAAA');exception when others then if sqlerrm='LOADING_INCOMPLETE' then rejected:=true;else raise;end if;end;
 if not rejected then raise exception 'FAIL_PROOF_BEFORE_LOADING'; end if;
 insert into public.tms_routes(route_date,driver_id,driver_name,vehicle,stops,status) values(current_date,driver,'Test','TEST-TRUCK',jsonb_build_array(tid),'Planificada') returning id into route_id;
 update public.tms_deliveries set route_id=loading_test.route_id where id=tid;
 rejected:=false;begin update public.tms_routes set status='En ruta' where id=route_id;exception when others then if sqlerrm='LOADING_INCOMPLETE' then rejected:=true;else raise;end if;end;
 if not rejected then raise exception 'FAIL_ROUTE_BYPASS'; end if;
 rejected:=false;begin perform public.gama_loading_action('scan',jsonb_build_object('delivery_id',tid,'request_key',gen_random_uuid(),'barcode','WRONG','quantity',1));exception when others then if sqlerrm='WRONG_PRODUCT' then rejected:=true;else raise;end if;end;
 if not rejected then raise exception 'FAIL_WRONG_CODE'; end if;
 payload:=jsonb_build_object('delivery_id',tid,'request_key',key_id,'barcode',code,'quantity',3);
 perform public.gama_loading_action('scan',payload);perform public.gama_loading_action('scan',payload);
 if (select count(*) from public.tms_loading_scans where delivery_id=sid)<>1 then raise exception 'FAIL_RETRY_DUPLICATES'; end if;
 if (select sum(a.quantity) from public.tms_loading_allocations a join public.tms_loading_scans sc on sc.id=a.scan_id where sc.delivery_id=sid)<>3 then raise exception 'FAIL_SPLIT_ALLOCATION'; end if;
 rejected:=false;begin perform public.gama_loading_action('scan',payload||jsonb_build_object('request_key',gen_random_uuid(),'quantity',2));exception when others then if sqlerrm='EXCEEDS_CARGO_QUANTITY' then rejected:=true;else raise;end if;end;
 if not rejected then raise exception 'FAIL_OVERSCAN'; end if;
 r:=public.gama_loading_action('scan',payload||jsonb_build_object('request_key',gen_random_uuid(),'quantity',1));
 if (r->>'complete')::boolean then raise exception 'FAIL_SECOND_PRODUCT_NOT_CHECKED'; end if;
 r:=public.gama_loading_action('scan',payload||jsonb_build_object('request_key',gen_random_uuid(),'barcode',code2,'quantity',1));
 if not (r->>'complete')::boolean then raise exception 'FAIL_COMPLETE'; end if;
 select id into scan_id from public.tms_loading_scans where request_key=key_id;
 r:=public.gama_loading_action('void_scan',jsonb_build_object('delivery_id',tid,'scan_id',scan_id,'reason','Three units removed from truck'));
 if (r->>'complete')::boolean then raise exception 'FAIL_VOID_NOT_REOPENED'; end if;
 r:=public.gama_loading_action('scan',payload||jsonb_build_object('request_key',gen_random_uuid()));v:=(r->'shipment'->>'version')::int;
 rejected:=false;begin update public.tms_deliveries set status='En tránsito' where id=tid;exception when others then if sqlerrm='DEPARTURE_REQUIRED' then rejected:=true;else raise;end if;end;
 if not rejected then raise exception 'FAIL_NO_EXPLICIT_DEPARTURE'; end if;
 rejected:=false;begin perform public.gama_loading_action('depart',jsonb_build_object('delivery_id',tid,'driver_id',driver,'version',v-1));exception when others then if sqlerrm='LOADING_CHANGED' then rejected:=true;else raise;end if;end;
 if not rejected then raise exception 'FAIL_STALE_DEPARTURE'; end if;
 select count(*) into movement_count from public.stock_movements where product_id in (pid,pid2);
 select sum(quantity) into qty_before from public.stock_quants where product_id in (pid,pid2);
 r:=public.gama_loading_action('depart',jsonb_build_object('delivery_id',tid,'driver_id',driver,'version',v));
 if r->'shipment'->>'departed_at' is null or r->'delivery'->>'status'<>'En tránsito' then raise exception 'FAIL_DEPARTURE'; end if;
 perform public.gama_loading_action('depart',jsonb_build_object('delivery_id',tid,'driver_id',driver,'version',v));
 if (select count(*) from public.tms_events where delivery_id=tid and type='SALIDA_VALIDADA')<>1 then raise exception 'FAIL_DOUBLE_DEPARTURE'; end if;
 if (select sum(quantity) from public.stock_quants where product_id in (pid,pid2))<>qty_before or (select count(*) from public.stock_movements where product_id in (pid,pid2))<>movement_count then raise exception 'FAIL_DOUBLE_STOCK_ISSUE'; end if;
 rejected:=false;begin perform public.gama_loading_action('void_scan',jsonb_build_object('delivery_id',tid,'scan_id',scan_id,'reason','Attempt after departure'));exception when others then if sqlerrm='LOADING_CLOSED' then rejected:=true;else raise;end if;end;
 if not rejected then raise exception 'FAIL_CHANGE_AFTER_DEPARTURE'; end if;
 rejected:=false;begin update public.tms_deliveries set status='Planificada' where id=tid;exception when others then if sqlerrm='LOADING_CLOSED' then rejected:=true;else raise;end if;end;
 if not rejected then raise exception 'FAIL_REPLAN_AFTER_DEPARTURE'; end if;
 update public.tms_routes set status='En ruta' where id=route_id;
 rejected:=false;begin delete from public.tms_routes where id=route_id;exception when others then if sqlerrm='ROUTE_STARTED' then rejected:=true;else raise;end if;end;
 if not rejected then raise exception 'FAIL_DELETE_STARTED_ROUTE'; end if;
 insert into public.tms_proofs(delivery_id,photo) values(tid,'data:image/png;base64,AAAA');
 update public.tms_deliveries set status='Entregada',delivered_at=now() where id=tid;
 rejected:=false;begin update public.tms_loading_scans set quantity=99 where delivery_id=sid;exception when insufficient_privilege then rejected:=true;end;
 if not rejected then raise exception 'FAIL_DIRECT_SCAN_WRITE'; end if;
 perform set_config('request.jwt.claim.sub',client_user::text,true);
 if exists(select 1 from public.tms_loading_scans where delivery_id=sid) then raise exception 'FAIL_CLIENT_READ'; end if;
 rejected:=false;begin perform public.gama_loading_action('manifest',jsonb_build_object('delivery_id',tid));exception when others then if sqlerrm='ROLE_NOT_ALLOWED' then rejected:=true;else raise;end if;end;
 if not rejected then raise exception 'FAIL_CLIENT_RPC'; end if;
 perform set_config('request.jwt.claim.sub','',true);
 rejected:=false;begin perform public.gama_loading_action('list','{}');exception when others then if sqlerrm='AUTH_REQUIRED' then rejected:=true;else raise;end if;end;
 if not rejected then raise exception 'FAIL_ANONYMOUS_RPC'; end if;
 execute 'reset role';
end $$;
