import * as ui from './ui/components.js';
import {icons} from './ui/icons.js';
import {escapeHtml,format,normalizeError,errorMessage} from './domain/format.js';
import * as data from './data/service.js';
import * as entities from './domain/entities.js';
import {registry,groups,roles,aliases,roleAliases,tabsOf} from './app/registry.js';
import {router,startRouter} from './app/router.js';
import {directory} from './modules/directories.js';
import {installLazyModules,loadModule} from './app/loader.js';
window.ArcUI={...ui,icons,esc:escapeHtml};
window.ArcFormat=format;
window.ArcErrors={normalize:normalizeError,message:errorMessage};
window.ArcData=data;
window.ArcEntities={...entities};
window.ArcModules={registry,groups,roles,aliases,roleAliases,tabsOf,get:id=>registry.find(m=>m.id===(aliases[id]||id))};
window.ArcRouter=router;
window.ArcDirectories={directory};
window.ArcLoad=loadModule;
installLazyModules();
data.startDataEvents();startRouter();

import {startPerformance} from './app/performance.js';
startPerformance();
