-- Dashboard cash uses actual receipts, without counting allocation a second time.
do $$declare src text;anchor text;begin
 select pg_get_functiondef('public.gama_company_dashboard(date,date)'::regprocedure) into src;
 anchor:=$a$cash as (select p.paid_at,p.amount from public.external_invoice_payments p join invoices i on i.id=p.invoice_id where p.status='confirmed')$a$;
 if strpos(src,anchor)=0 then raise exception 'DASHBOARD_CASH_ANCHOR';end if;
 src:=replace(src,anchor,$b$cash as (select p.paid_at,p.amount from public.external_invoice_payments p join invoices i on i.id=p.invoice_id where p.status='confirmed' and p.receipt_id is null union all select paid_at,amount from public.customer_receipts where status='confirmed')$b$);
 anchor:=$a$select sum(p.amount) from public.external_invoice_payments p where p.financial_account_id=f.id and p.status='confirmed' and p.paid_at<=today$a$;
 if strpos(src,anchor)=0 then raise exception 'DASHBOARD_ACCOUNT_CASH_ANCHOR';end if;
 src:=replace(src,anchor,$b$select sum(p.amount) from (select amount,financial_account_id,status,paid_at from public.external_invoice_payments where receipt_id is null union all select amount,financial_account_id,status,paid_at from public.customer_receipts)p where p.financial_account_id=f.id and p.status='confirmed' and p.paid_at<=today$b$);
 src:=replace(src,'sum(greatest(l.quantity-coalesce(s.quantity,0),0)) remaining',$b$sum(greatest(l.quantity-case when l.product_kind='service' then coalesce((select sum(c.quantity) from public.sales_service_completions c where c.order_line_id=l.id and c.cancelled_at is null),0) else coalesce(s.quantity,0) end,0)) remaining$b$);
 src:=replace(src,'where p.active;','where p.active and p.product_kind=''goods'';');
 src:=replace(src,'''weighted'',coalesce(sum(o.amount*o.probability/100),0),',$b$'weighted',coalesce(sum(o.amount*o.probability/100),0),
 'won',(select coalesce(sum(w.amount),0) from public.crm_opportunities w where w.active and (w.won_at at time zone private.erp_timezone())::date between first_day and last_day),
 'invoiced',case when private.dashboard_access('payments') then (select coalesce(sum(i.subtotal),0) from public.external_invoices i join public.sales_orders so on so.id=i.order_id where so.source_opportunity_id is not null and i.fiscal_status not in ('cancelled','rejected') and i.issue_date between first_day and last_day) end,$b$);execute src;
end $$;
-- RLS-preserving drilldowns use the same dates and monetary definitions as KPIs.
create function public.gama_dashboard_details(p_module text,p_metric text,p_from date,p_to date,p_offset integer default 0) returns jsonb language plpgsql stable security invoker set search_path='' as $$
declare today date:=(now() at time zone private.erp_timezone())::date;q text;result jsonb;begin
 if not private.dashboard_access('dashboard') or not private.dashboard_access(p_module) then raise exception 'DASHBOARD_ACCESS_DENIED';end if;
 if p_from is null or p_to is null or p_from>p_to or p_to>today or p_to-p_from>730 then raise exception 'DASHBOARD_INVALID_PERIOD';end if;
 if p_module='payments' and p_metric='net' then q:=$q$select i.id,i.order_id,i.number label,o.customer_name customer,i.issue_date date,i.subtotal amount,'invoice'::text kind from public.external_invoices i join public.sales_orders o on o.id=i.order_id where i.fiscal_status not in ('cancelled','rejected') and i.issue_date between $1 and $2$q$;
 elsif p_module='payments' and p_metric='collected' then q:=$q$select p.id,i.order_id,coalesce(nullif(p.reference,''),i.number) label,o.customer_name customer,p.paid_at date,p.amount,'payment'::text kind from public.external_invoice_payments p join public.external_invoices i on i.id=p.invoice_id join public.sales_orders o on o.id=i.order_id where p.status='confirmed' and p.receipt_id is null and i.fiscal_status not in ('cancelled','rejected') and p.paid_at between $1 and $2 union all select r.id,null::uuid,r.reference,c.name,r.paid_at,r.amount,'receipt' from public.customer_receipts r join public.customers c on c.id=r.customer_id where r.status='confirmed' and r.paid_at between $1 and $2$q$;
 elsif p_module='payments' and p_metric='receivable' then q:=$q$select * from (select i.id,i.order_id,i.number label,o.customer_name customer,i.issue_date date,greatest(0,i.total-coalesce((select sum(amount) from public.external_invoice_payments p where p.invoice_id=i.id and status='confirmed' and paid_at<=$3),0)-coalesce((select sum(amount) from public.return_credits c where c.invoice_id=i.id and issued_on<=$3),0)) amount,'invoice'::text kind from public.external_invoices i join public.sales_orders o on o.id=i.order_id where i.fiscal_status not in ('cancelled','rejected') and i.issue_date<=$3) r where amount>0$q$;
 elsif p_module='sales-orders' and p_metric in ('orders','to_ship') then q:=$q$select o.id,o.id order_id,o.number label,o.customer_name customer,(o.created_at at time zone private.erp_timezone())::date date,1::numeric amount,'order'::text kind from public.sales_orders o where o.status='confirmed'$q$||case when p_metric='orders' then $q$ and (o.created_at at time zone private.erp_timezone())::date between $1 and $2$q$ else $q$ and exists(select 1 from public.sales_order_lines l where l.order_id=o.id and l.quantity>case when l.product_kind='service' then coalesce((select sum(quantity) from public.sales_service_completions c where c.order_line_id=l.id and c.cancelled_at is null),0) else coalesce((select sum(quantity) from public.sales_delivery_lines dl where dl.order_line_id=l.id),0) end)$q$ end;
 elsif p_module='warehouses' and p_metric='out' then q:=$q$select p.id,null::uuid order_id,coalesce(p.reference,p.barcode) label,p.name customer,null::date date,1::numeric amount,'product'::text kind from public.products p where p.active and p.product_kind='goods' and coalesce((select sum(quantity-reserved_quantity) from public.stock_quants q where q.product_id=p.id),0)<=0$q$;
 elsif p_module='tms' and p_metric='delivered' then q:=$q$select d.id,(select order_id from public.sales_deliveries s where s.tms_delivery_id=d.id limit 1) order_id,d.id::text label,d.customer customer,(d.delivered_at at time zone private.erp_timezone())::date date,1::numeric amount,'delivery'::text kind from public.tms_deliveries d where d.status='Entregada' and (d.delivered_at at time zone private.erp_timezone())::date between $1 and $2$q$;
 elsif p_module='crm' and p_metric in ('weighted','won') then q:=$q$select o.id,null::uuid order_id,o.title label,''::text customer,(o.won_at at time zone private.erp_timezone())::date date,$q$||case when p_metric='weighted' then 'o.amount*o.probability/100' else 'o.amount' end||$q$ amount,'opportunity'::text kind from public.crm_opportunities o join public.crm_pipeline_stages s on s.id=o.stage_id where o.active$q$||case when p_metric='weighted' then ' and not s.is_won and not s.is_lost' else $q$ and (o.won_at at time zone private.erp_timezone())::date between $1 and $2$q$ end;
 else raise exception 'METRIC_NOT_SUPPORTED';end if;
 execute 'with rows as ('||q||') select jsonb_build_object(''generated_at'',now(),''count'',(select count(*) from rows),''total'',(select coalesce(sum(amount),0) from rows),''rows'',(select coalesce(jsonb_agg(to_jsonb(r)),''[]'') from (select * from rows order by date desc nulls last,id limit 100 offset $4)r))' into result using p_from,p_to,today,greatest(0,coalesce(p_offset,0));return result;
end $$;
revoke all on function public.gama_dashboard_details(text,text,date,date,integer) from public,anon;grant execute on function public.gama_dashboard_details(text,text,date,date,integer) to authenticated;
