/* Ecuador payroll and employee receipts. Loaded only in the payroll tab. */
(function(){'use strict';
const U=window.ArcUI,E=U.esc,T=s=>window.GamaI18n?.t?.(s)||s,M=n=>window.GamaCurrency.format(n);
const L=s=>`<span data-gi-live>${E(s)}</span>`;
let epoch=0,context={},state={},host;const F=(label,body)=>`<label><span>${L(label)}</span>${body}</label>`,I=(name,value=0,extra='')=>`<input name="${name}" value="${E(value??'')}" ${extra}>`,B=(name,label,primary=false)=>`<button type="button" class="arcButton ${primary?'primary':'secondary'}" data-ec="${name}">${L(label)}</button>`,S=(name,values,selected,translate=true)=>`<select name="${name}">${values.map(([v,l])=>`<option value="${E(v)}" ${v===selected?'selected':''} ${translate?'data-gi-live':''}>${E(l)}</option>`).join('')}</select>`;
const ERR={PAYROLL_CHOICE_DATE_REVIEW_REQUIRED:'Solicita a RRHH la revisión de una elección fuera del plazo o del mes actual.',PAYROLL_MINIMUM_SALARY_REQUIRED:'El sueldo contractual es inferior al mínimo vigente proporcional a la jornada.',PAYROLL_PARAMETERS_REVIEW_REQUIRED:'Confirma los parámetros del año antes de calcular.',EC_COMPANY_REQUIRED:'Configura la empresa en Ecuador y en USD.',PAYROLL_CONTRACT_REQUIRED:'Completa el sueldo y las fechas del contrato en la ficha del empleado.',PAYROLL_EMPLOYEE_CHOICES_REQUIRED:'Registra las opciones del empleado y su solicitud escrita.',PAYROLL_WORKED_DAYS_INVALID:'Revisa los días trabajados dentro del contrato.',PAYROLL_INVALID_AMOUNT:'Revisa los importes. No se admiten valores negativos ni descuentos superiores al ingreso.',PAYROLL_RESERVE_DAYS_REVIEW_REQUIRED:'Indica los días con derecho a fondos de reserva en el mes de aniversario.',PAYROLL_RESERVE_DAYS_INVALID:'Los días de reserva superan los días trabajados con derecho.',PAYROLL_RECALCULATE_REQUIRED:'Los datos cambiaron. Calcula y revisa otra vez antes de validar.',PAYROLL_ALREADY_VALIDATED:'La nómina validada conserva sus importes. Abre el rol registrado.',PAYROLL_UTILITIES_WORKFORCE_REVIEW_REQUIRED:'Revisa la plantilla completa, incluidos los exempleados del ejercicio.',PAYROLL_UTILITIES_ZERO_FAMILY_REVIEW_REQUIRED:'No hay cargas acreditadas. Confirma con Contabilidad el criterio de reparto del 5%.',PAYROLL_UTILITIES_DECLARATION_REQUIRED:'La provisión definitiva requiere el ejercicio cerrado y la declaración de renta revisada.',PAYROLL_BANK_DETAILS_REQUIRED:'Completa y revisa los datos bancarios de todos los beneficiarios.',PAYROLL_ACCRUAL_MONTHS_REQUIRED:'Faltan nóminas validadas en el periodo de acumulación.',PAYROLL_ACCRUAL_PERIOD_OPEN:'El periodo de acumulación sigue abierto.',PAYROLL_ACCRUAL_EXTERNAL_REVIEW_REQUIRED:'Revisa los décimos de las nóminas externas antes de liquidar.',PAYROLL_ACCRUAL_EMPTY:'No hay décimos acumulados pendientes en este periodo.',PAYROLL_ACCRUAL_ALREADY_RELEASED:'La nómina financia un décimo ya liquidado. Revisa el beneficio antes de anular.',PAYROLL_NOT_FOUND:'El rol no está disponible para esta cuenta.',SIGNATURE_REQUIRED:'Firma dentro del recuadro antes de confirmar.',PAYROLL_EMPLOYEE_SIGNATURE_REQUIRED:'Sólo el empleado puede firmar su rol validado.'};
function message(e){const s=String(e?.message||e);return T(Object.entries(ERR).find(([k])=>s.includes(k))?.[1]||window.ArcErrors.message(e));}
const toast=e=>window.gamaToast?.(message(e));
async function rpc(action,data){return window.ArcData.rpc('gama_hr_ec_action',{p_action:action,p_data:data||{}});}
function values(form){const d={};form.querySelectorAll('[name]').forEach(el=>d[el.name]=el.type==='checkbox'?el.checked:el.value);return d;}
function bind(root,key,fn){const b=root.querySelector(`[data-ec="${key}"]`);if(!b)return;b.onclick=async()=>{const token=epoch;b.disabled=true;try{await fn();}catch(e){if(token===epoch)toast(e)}finally{if(b.isConnected)b.disabled=false}};}
const people=()=>state.employees||[],names=id=>people().find(e=>e.employee_id===id)?.name||'—';
function choose(name='employee_id'){return S(name,people().map(e=>[e.employee_id,e.name]),context.selected,false);}
const modes=[['monthly','Mensualizado'],['accrued','Acumulado']];
const rateLabels={sbu:'Salario básico unificado',iess_personal_rate:'Aporte personal IESS (%)',iess_employer_rate:'Aporte patronal IESS (%)',iess_health_min_rate:'Prima mínima de salud parcial (%)',reserve_rate:'Fondos de reserva (%)',additional_employer_rate:'Otros aportes patronales (%)',util_work_rate:'Utilidades por tiempo (%)',util_family_rate:'Utilidades por cargas (%)'};
const calculations={salary:'Sueldo proporcional',gross:'Bruto',personal_iess:'Aporte personal IESS',employer_iess:'Aporte patronal IESS',health_complement:'Complemento de salud por jornada parcial',additional_employer:'Otros aportes patronales',decimo13:'Décimo tercero',decimo14:'Décimo cuarto',reserve:'Fondos de reserva',income_tax:'IR revisado',other_deductions:'Otros descuentos',net:'Neto a pagar',employer_cost:'Coste empleador'};
function amounts(calc){return U.table({columns:[{key:'label',label:T('Concepto')},{key:'amount',label:T('Importe'),value:r=>M(r.amount)}],items:Object.entries(calculations).map(([k,label])=>({label:T(label),amount:calc[k]}))});}
function panel(title,body){return `<div class="arcPanel hpBox"><h3>${L(title)}</h3>${body}</div>`;}
function render(){const adm=context.admin,params=state.parameters,year=Number(context.period.slice(0,4));
 const config=adm?`<details><summary>${L('Parámetros de nómina')} · ${year}</summary><form data-parameters>${F('Ejercicio',I('year',year,'type="number" min="2020" max="2100" required'))}<p>${L('Verifica el SBU, los aportes y las reglas aplicables. Cada confirmación conserva una versión.')}</p><div class="gaGrid">${Object.entries(rateLabels).map(([k,label])=>F(label,I(k,params?.parameters?.[k]??'','type="number" min="0" step="0.0001" required'))).join('')}${F('Fuente y revisión',I('evidence','','required minlength="10" maxlength="2000"'))}</div>${B('parameters','Confirmar parámetros',true)}</form></details>`:'';
 const calc=adm?`<form data-calculate><div class="gaGrid">${F('Empleado',choose())}${F('Días remunerados (máx. 30)',I('worked_days',30,'type="number" min="0.5" max="30" step="0.5" required'))}${F('Ingresos remunerativos adicionales',I('bonus',0,'type="number" min="0" step="0.01"'))}${F('IR calculado por el responsable',I('income_tax',0,'type="number" min="0" step="0.01"'))}${F('Otros descuentos autorizados',I('other_deductions',0,'type="number" min="0" step="0.01"'))}${F('Días con derecho a reserva (opcional)',I('reserve_days','','type="number" min="0" max="30" step="0.5"'))}${F('Centro de coste',I('cost_center','','maxlength="200"'))}</div><p class="hpNote">${L('El sueldo contractual procede de la ficha. Los décimos acumulados y la reserva depositada al IESS forman obligaciones; no se suman al neto.')}</p>${B('preview','Calcular y revisar',true)}<div data-calculation></div></form>`:'';
 U.render(host,panel('Nómina calculada para Ecuador',`${adm&&!params?.confirmed_at?`<p class="hpNotice">${L('Confirma los parámetros del año antes de calcular.')}</p>`:''}${config}${calc}<div class="gaGrid">${B('terms','Opciones y banco del empleado')}${adm?B('export','Exportar nómina para depósito bancario'):''}</div>`)+(adm?panel('Décimos y utilidades',`${B('utilities','Calcular provisión de utilidades')}${B('accrued','Liquidar décimos acumulados')}<p class="hpNote">${L('Las utilidades se calculan sobre el beneficio anual declarado. Los trabajadores y exempleados se revisan por días, jornada y cargas acreditadas.')}</p>`):'')+benefitsUI());
 bind(host,'parameters',async()=>{const form=host.querySelector('[data-parameters]');if(!form.reportValidity())return;const d=values(form);await rpc('parameters_save',{year:Number(d.year),parameters:Object.fromEntries(Object.keys(rateLabels).map(k=>[k,Number(d[k])])),evidence:d.evidence});await mount(context)});
 bind(host,'terms',termsForm);bind(host,'export',exportBank);bind(host,'utilities',utilitiesForm);bind(host,'accrued',accruedForm);
 const form=host.querySelector('[data-calculate]');let preview,stamp;const payload=()=>{const d=values(form);return {employee_id:d.employee_id,period:context.period+'-01',cost_center:d.cost_center,inputs:Object.fromEntries(['worked_days','bonus','income_tax','other_deductions','reserve_days'].filter(k=>d[k]!=='').map(k=>[k,Number(d[k])]))}};
 if(form){form.oninput=()=>{preview=null;stamp=null;form.querySelector('[data-calculation]').replaceChildren()};bind(host,'preview',async()=>{if(!form.reportValidity())return;const token=epoch,d=payload(),key=JSON.stringify(d),c=await rpc('preview',d);if(token!==epoch||!form.isConnected||JSON.stringify(payload())!==key)return;preview=c;stamp=key;U.render(form.querySelector('[data-calculation]'),amounts(c)+B('calculate','Guardar nómina calculada',true));bind(form,'calculate',async()=>{if(!preview||stamp!==JSON.stringify(payload()))return;await rpc('calculate',{...payload(),expected_calculation:preview});await context.reload?.();})});}
 host.querySelectorAll('[data-benefit-pay]').forEach(b=>b.onclick=()=>benefitPayment(b.dataset.benefitPay).catch(toast));
}
function benefitsUI(){const rows=state.benefits||[];if(!rows.length)return '';return panel('Beneficios liquidados',U.table({columns:[{key:'employee_id',label:T('Empleado'),value:r=>names(r.employee_id)},{key:'kind',label:T('Concepto'),value:r=>T({decimo13:'Décimo tercero',decimo14:'Décimo cuarto',utilidades:'Utilidades'}[r.kind])},{key:'to_date',label:T('Hasta')},{key:'amount',label:T('Importe'),value:r=>M(r.amount)},{key:'paid',label:T('Pagado'),value:r=>M(r.paid)},{label:T('Acciones'),actions:true,html:r=>context.admin&&Number(r.amount)>Number(r.paid)?`<button type="button" class="arcButton secondary" data-benefit-pay="${E(r.id)}">${L('Registrar pago')}</button>`:''}],items:rows}));}
async function mount(c){context=c;host=document.getElementById('hpEcPayroll');if(!host)return;const token=++epoch;U.render(host,`<p>${L('Cargando nómina ecuatoriana…')}</p>`);try{const d=await rpc('list',{period:c.period+'-01'});if(token!==epoch||!host.isConnected)return;state=d;render();}catch(e){if(token===epoch&&host.isConnected){U.render(host,`<p role="alert">${E(message(e))}</p>${B('retry','Reintentar')}`);bind(host,'retry',()=>mount(c));}}
 const section=document.getElementById('hr');section?.querySelectorAll('[data-ec-slip]').forEach(b=>b.onclick=()=>slip(b.dataset.ecSlip).catch(toast));section?.querySelectorAll('[data-ec-edit]').forEach(b=>b.onclick=()=>{const p=c.payroll.find(p=>p.id===b.dataset.ecEdit),f=host.querySelector('[data-calculate]');if(!p||!f)return;const d={...p.ec_calculation.inputs,employee_id:p.employee_id,cost_center:p.cost_center};for(const [k,v]of Object.entries(d))if(f.elements[k])f.elements[k].value=v;f.dispatchEvent(new Event('input'));f.scrollIntoView({block:'center'})});
}
async function termsForm(){const own=!context.admin;const body=`<div class="gaGrid">${F('Empleado',choose())}${F('Décimo tercero',S('decimo13_mode',modes,'monthly'))}${F('Décimo cuarto',S('decimo14_mode',modes,'monthly'))}${context.admin?F('Reserva',S('reserve_mode',[['direct','Pago directo'],['iess','Depósito al IESS']],'direct'))+F('Región del décimo cuarto',S('region',[['costa','Costa e Insular'],['sierra','Sierra y Amazonía']],'costa'))+F('Jornada / jornada completa',I('work_ratio',1,'type="number" min="0.0001" max="1" step="0.0001" required'))+F('Mínimo sectorial mensual (0 = SBU)',I('sectoral_minimum',0,'type="number" min="0" step="0.01"'))+`<label><input name="other_fulltime" type="checkbox"> ${L('Afiliación a jornada completa con otro empleador acreditada')}</label>`+F('Banco',I('bank_name','','maxlength="120"'))+F('Número de cuenta',I('bank_number','','inputmode="numeric" pattern="[0-9]{0,30}" maxlength="30"'))+F('Tipo de cuenta',S('bank_kind',[['savings','Ahorros'],['checking','Corriente']],'savings'))+F('Identificación del beneficiario',I('beneficiary_id','','maxlength="30"')):''}${F('Solicitud escrita y revisión',I('evidence','','required minlength="10" maxlength="2000"'))}</div><p>${L('La elección se guarda para este mes y los siguientes. El sueldo es el mensual contractual, también en jornada parcial.')}</p>`;
 const dlg=U.dialog({title:T('Opciones y banco del empleado'),body,saveLabel:T('Guardar'),onSave:async el=>{await rpc('terms_save',{...values(el),work_ratio:Number(values(el).work_ratio||1),sectoral_minimum:Number(values(el).sectoral_minimum||0),period:context.period+'-01'});await mount(context)}});dlg.dataset.hrEc='';
 const fill=()=>{const t=people().find(p=>p.employee_id===values(dlg).employee_id)?.terms;for(const [k,v]of Object.entries(t||{})){const n=dlg.querySelector(`[name="${k}"]`);if(n){if(n.type==='checkbox')n.checked=!!v;else n.value=v;}}};dlg.querySelector('[name=employee_id]').onchange=fill;fill();if(own)dlg.querySelector('[name=employee_id]').disabled=true;
}
function csv(data){const cell=v=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};return '\uFEFF'+[['nombre','identificacion','banco','tipo_cuenta','numero_cuenta','importe_usd','referencia'],...data.rows.map(r=>[r.name,r.identification,r.bank,r.account_kind,r.account,Number(r.amount).toFixed(2),r.reference])].map(r=>r.map(cell).join(';')).join('\r\n');}
async function exportBank(){const token=epoch,dlg=U.dialog({title:T('Exportar nómina para depósito bancario'),body:`<p>${L('Se exportan sólo importes validados pendientes de pago. El CSV se revisa y adapta al formato del banco; descargarlo no registra ni envía una transferencia.')}</p><label><input name="include_benefits" type="checkbox"> ${L('Incluir beneficios liquidados pendientes')}</label>`,saveLabel:T('Descargar CSV'),onSave:async el=>{const d=await rpc('bank_export',{period:context.period+'-01',include_benefits:values(el).include_benefits});if(token!==epoch)return;const link=document.createElement('a'),url=URL.createObjectURL(new Blob([csv(d)],{type:'text/csv;charset=utf-8'}));link.href=url;link.download='NOMINA-'+context.period+'.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}});dlg.dataset.hrEc='';}
async function slipPdf(data){await window.ArcLoadScript('gama-pdf.js');await window.GamaPdf.ready();await window.ArcLoadScript('gama-pdf-template.js');const p=data.payroll,c=p.ec_calculation,pdf=window.GamaPdfTemplate.layout({title:T('Rol de pagos'),reference:p.erp_reference||'—',date:p.period,company:{...window.GamaCompany?.get(),...data.company,configured:true}}),doc=pdf.doc;
 pdf.text(data.employee.name,12,true);pdf.text(T('Identificación')+': '+(data.employee.identification||'—'));pdf.text(T('Periodo')+': '+p.period.slice(0,7)+' · '+T('Estado')+': '+T({draft:'Borrador',validated:'Validada',cancelled:'Cancelada'}[p.status]));
 if(c){for(const [key,label]of Object.entries(calculations))pdf.text(T(label)+': '+M(c[key]),10,['gross','net','employer_cost'].includes(key));pdf.text(T('Décimo tercero')+': '+T(c.terms.decimo13_mode==='monthly'?'Mensualizado':'Acumulado')+' · '+T('Décimo cuarto')+': '+T(c.terms.decimo14_mode==='monthly'?'Mensualizado':'Acumulado'));pdf.text(T('Días remunerados')+': '+c.inputs.worked_days+' · '+T('Días de reserva')+': '+c.inputs.reserve_days);}
 else for(const [label,value]of [[T('Bruto'),p.gross],[T('Neto'),p.net],[T('Coste empleador'),p.employer_cost]])pdf.text(label+': '+M(value),11,true);
 pdf.text(T('Pagado')+': '+M(data.paid)+' · '+T('Pendiente de pago')+': '+M(Math.max(0,Number(p.net)-Number(data.paid))));
 if(pdf.y>222)pdf.next();if(data.signature){pdf.text(T('Acuse de recibo del empleado'),10,true);doc.addImage(data.signature.signature_png,'PNG',14,pdf.y,64,20);pdf.y+=25;pdf.text(T('Firmado el')+': '+data.signature.signed_at,9);pdf.text(T('Huella del rol')+': '+data.signature.snapshot_hash,8);}else pdf.text(T('Firma del empleado pendiente'),10);
 pdf.finish(T('Los importes proceden del rol registrado y sus pagos. La firma acredita la recepción del documento.'));return doc.output('blob');}
async function slip(id){const token=epoch,data=await rpc('slip',{payroll_id:id});if(token!==epoch)return;const dlg=U.dialog({title:T('Rol de pagos'),saveLabel:T('Cerrar'),body:`<p><b>${E(data.employee.name)}</b> · ${E(data.payroll.period.slice(0,7))}</p><p>${L('Neto a pagar')}: ${E(M(data.payroll.net))}</p>${B('pdf','Descargar rol PDF',true)}${data.can_sign?B('signature','Firmar recepción del rol'):''}${data.signature?`<p>${L('Firmado el')}: ${E(data.signature.signed_at)}</p>`:''}`,onSave:async()=>{}});dlg.dataset.hrEc='';bind(dlg,'pdf',async()=>{const blob=await slipPdf(data);if(token===epoch)window.GamaPdf.save(blob,'ROL-'+(data.payroll.erp_reference||data.payroll.period.slice(0,7))+'.pdf')});bind(dlg,'signature',()=>signatureForm(id));return dlg;}
function signatureForm(id){let ink=false;const token=epoch;const dlg=U.dialog({title:T('Firmar recepción del rol'),saveLabel:T('Confirmar firma'),body:`<p>${L('Firma con el dedo o el ratón. Se registra tu cuenta y la hora del servidor.')}</p><canvas data-sign width="620" height="180" style="width:100%;height:180px;border:1px solid var(--arc-line);border-radius:8px;touch-action:none" aria-label="${E(T('Firma del empleado'))}"></canvas>${B('clear','Borrar firma')}<label><input name="ack" type="checkbox" required> ${L('Confirmo que recibí y revisé este rol de pagos.')}</label>`,onSave:async el=>{if(!ink||!el.querySelector('[name=ack]').checked)throw Error(T('Firma dentro del recuadro antes de confirmar.'));await rpc('sign',{payroll_id:id,signature_png:el.querySelector('canvas').toDataURL('image/png')});if(token===epoch){document.querySelectorAll('[data-hr-ec]').forEach(d=>d.close());await slip(id);}}});dlg.dataset.hrEc='';const canvas=dlg.querySelector('canvas'),ctx=canvas.getContext('2d');ctx.strokeStyle='#173341';ctx.lineWidth=3;ctx.lineCap='round';let drawing=false;const point=e=>{const r=canvas.getBoundingClientRect();return [(e.clientX-r.left)*canvas.width/r.width,(e.clientY-r.top)*canvas.height/r.height]};canvas.onpointerdown=e=>{e.preventDefault();drawing=true;canvas.setPointerCapture(e.pointerId);ctx.beginPath();ctx.moveTo(...point(e))};canvas.onpointermove=e=>{if(!drawing)return;ctx.lineTo(...point(e));ctx.stroke();ink=true};canvas.onpointerup=canvas.onpointercancel=()=>drawing=false;bind(dlg,'clear',()=>{ctx.clearRect(0,0,canvas.width,canvas.height);ink=false});}
function workforce(year){const from=year+'-01-01',to=year+'-12-31';return people().filter(e=>e.hire_date&&e.hire_date<=to&&(!e.end_date||e.end_date>=from)).map(e=>{const a=(e.hire_date>from?e.hire_date:from).split('-').map(Number),b=(e.end_date&&e.end_date<to?e.end_date:to).split('-').map(Number),last=new Date(Date.UTC(b[0],b[1],0)).getUTCDate(),days=(b[0]-a[0])*360+(b[1]-a[1])*30+(b[2]===last?30:Math.min(30,b[2]))-Math.min(30,a[2])+1;return {...e,days,ratio:e.terms?.work_ratio??1}});}
async function utilitiesForm(){let preview,stamp;const token=epoch,key=crypto.randomUUID(),dlg=U.dialog({title:T('Calcular provisión de utilidades'),saveLabel:T('Confirmar provisión revisada'),body:`<div class="gaGrid">${F('Ejercicio',I('year',Number(context.period.slice(0,4))-1,'type="number" min="2020" max="2100" required'))}${F('Beneficio líquido declarado',I('net_profit',0,'type="number" step="0.01" required'))}${F('Declaración y revisión anual',I('evidence','','required minlength="10" maxlength="2000"'))}</div><div data-workforce></div><label><input name="reviewed" type="checkbox" required> ${L('Revisé los días, la jornada y las cargas de toda la plantilla, incluidos los exempleados.')}</label>${F('Sin cargas acreditadas',S('zero_family_policy',[['review','Revisión necesaria'],['by_days_reviewed','Reparto por días confirmado por Contabilidad']],'review'))}${B('utility-preview','Calcular y revisar',true)}<div data-utility-preview></div>`,onSave:async el=>{const d=payload();if(!preview||JSON.stringify(d)!==stamp||!values(el).reviewed)throw Error(T('Calcula y revisa los importes antes de confirmar.'));await rpc('utilities_confirm',{...d,request_key:key});if(token===epoch)await context.reload?.();}});dlg.dataset.hrEc='';
 const fill=()=>{preview=null;dlg.querySelector('[data-utility-preview]').replaceChildren();const rows=workforce(Number(values(dlg).year));U.render(dlg.querySelector('[data-workforce]'),U.table({columns:[{key:'name',label:T('Empleado')},{label:T('Días remunerados'),html:r=>I('days_'+r.employee_id,r.days,'type="number" min="0" max="360" step="0.5" required')},{label:T('Jornada'),html:r=>I('ratio_'+r.employee_id,r.ratio,'type="number" min="0.0001" max="1" step="0.0001" required')},{label:T('Cargas acreditadas'),html:r=>I('family_'+r.employee_id,0,'type="number" min="0" max="30" step="1" required')}],items:rows}));};fill();dlg.querySelector('[name=year]').onchange=fill;
 const payload=()=>{const d=values(dlg);return {year:Number(d.year),net_profit:Number(d.net_profit),evidence:d.evidence,zero_family_policy:d.zero_family_policy,people:workforce(Number(d.year)).map(e=>({employee_id:e.employee_id,worked_days:Number(d['days_'+e.employee_id]),work_ratio:Number(d['ratio_'+e.employee_id]),dependents:Number(d['family_'+e.employee_id]),evidence:d.evidence}))}};
 bind(dlg,'utility-preview',async()=>{if(!dlg.querySelector('form')?.reportValidity?.()&&[...dlg.querySelectorAll('[required]')].some(e=>!e.reportValidity()))return;const d=payload(),s=JSON.stringify(d),c=await rpc('utilities_preview',d);if(token!==epoch||!dlg.isConnected||JSON.stringify(payload())!==s)return;preview=c;stamp=s;U.render(dlg.querySelector('[data-utility-preview]'),`<p>${L('Provisión total')}: <b>${E(M(c.total))}</b></p>`+U.table({columns:[{key:'name',label:T('Empleado')},{key:'work_amount',label:T('Por tiempo'),value:r=>M(r.work_amount)},{key:'family_amount',label:T('Por cargas'),value:r=>M(r.family_amount)},{key:'amount',label:T('Total'),value:r=>M(r.amount)}],items:c.people}));});}
async function accruedForm(){const dlg=U.dialog({title:T('Liquidar décimos acumulados'),saveLabel:T('Liquidar'),body:`<div class="gaGrid">${F('Empleado',choose())}${F('Año de pago',I('year',context.period.slice(0,4),'type="number" min="2020" max="2100" required'))}${F('Concepto',S('kind',[['decimo13','Décimo tercero'],['decimo14','Décimo cuarto']],'decimo13'))}${F('Revisión del periodo',I('evidence','','required minlength="10"'))}</div><p>${L('Se suman sólo nóminas validadas acumuladas. Se conserva el coste ya provisionado y se reconoce el beneficio a pagar.')}</p>`,onSave:async el=>{const d=values(el);await rpc('accrued_release',{...d,year:Number(d.year)});await context.reload?.();}});dlg.dataset.hrEc='';}
async function benefitPayment(id){const b=state.benefits.find(b=>b.id===id),key=crypto.randomUUID();if(!b)return;const dlg=U.dialog({title:T('Registrar pago de beneficio'),saveLabel:T('Registrar pago'),body:`<p>${E(names(b.employee_id))} · ${L('Pendiente de pago')}: ${E(M(Number(b.amount)-Number(b.paid)))}</p><div class="gaGrid">${F('Importe',I('amount',Number(b.amount)-Number(b.paid),'type="number" min="0.01" step="0.01" required'))}${F('Fecha',I('paid_on',new Intl.DateTimeFormat('en-CA',{timeZone:window.GamaCompany?.get()?.timezone||'America/Guayaquil'}).format(new Date()),'type="date" required'))}${F('Cuenta',S('financial_account_id',(state.accounts||[]).map(a=>[a.id,a.name]),null,false))}${F('Referencia',I('reference','','required maxlength="180"'))}</div>`,onSave:async el=>{const d=values(el);await rpc('benefit_payment',{...d,amount:Number(d.amount),benefit_id:id,request_key:key});await context.reload?.();}});dlg.dataset.hrEc='';}
window.GamaHrEc={mount,slip,slipPdf,csv};window.addEventListener('gama:auth-change',e=>{if(e.detail?.event==='TOKEN_REFRESHED')return;epoch++;state={};document.querySelectorAll('[data-hr-ec]').forEach(d=>d.close())});
})();
